### ISSUE TITLE
Add travis.yml to repo

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#1]
Please create travis.yml and add the right configuration.

**Comment by betterclever** [comment]
travis.yml is added in #5 . Should I make changes in travis to post notifications to loklak gitter channel?

**Comment by mariobehling** [comment]
yes, post it to the loklak channel for now. It is sufficient. Thank you.

**Comment by the-dagger** [comment]
Closing this as travis.yml is added to the repo

**Comment by betterclever** [comment]
@the-dagger Notification system is still not working properly. I'm not able to figure out. Basically, I used the webhook url used in other loklak services. Can you look into that?

**Comment by the-dagger** [comment]
Ok sure, let me take a look.
