### ISSUE TITLE
Implement Material Design in the App

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#10]
The App currently uses old Halo Theme instead of new Material Theme. Material design can be implemented in the app for better looks.

**Comment by jig08** [comment]
@betterclever Feel free to work on this and submit a PR.

**Comment by Orbiter** [comment]
+1

**Comment by code-crusher** [comment]
@betterclever are you working on this as i would like to work on it? 🙂

**Comment by betterclever** [comment]
@code-crusher Yes I'm working on this. You may work on #11 , that would be a little difficult for me.

**Comment by betterclever** [comment]
![screenshot_20160926-090319](https://cloud.githubusercontent.com/assets/16309034/18822044/503439f8-83c9-11e6-8b67-3a068b7454dd.png)
![screenshot_20160926-090338](https://cloud.githubusercontent.com/assets/16309034/18822045/5037cf96-83c9-11e6-8aca-19d552a3e424.png)

@jig08 @code-crusher @Orbiter  Please have a look and suggest whether something else should be changed/added?

**Comment by daminisatya** [comment]
@betterclever Can I know from where the ```error: No value for answers``` coming from?

**Comment by daminisatya** [comment]
Please open a pull request and we can have a proper review :) Please attach the same screenshots there!

**Comment by betterclever** [comment]
@daminisatya  Actually, when app is not able to fetch the answers due to unavailability of internet, that error is displayed. There was some issue of internet here at time of screenshots.

**Comment by betterclever** [comment]
As far as the pull request is concerned, I'm delaying it till #13 gets merged, so I can resolve any merge conflicts beforehand.

**Comment by code-crusher** [comment]
@betterclever you can go ahead and send a PR. What ever conflicts will be there I'll solve them before merging my PR.

**Comment by betterclever** [comment]
Solved in #14, hence closing.
