### ISSUE TITLE
Hotword detection toast keeps on popping up more than once

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/susi_android#1005]
**Actual Behaviour**

In my device(emulator), hotword detection toast is coming, each time when redirecting to the ChatActivity, though user is running the app.

**Expected Behaviour**

Toast should only come once, only when the user open-up the app 

**Steps to reproduce it**

In an emulator device, run the app, redirect to any other activity, and when you come back to ChatActivity, toast will be shown again.

**Screenshots of the issue**

![giphy](https://user-images.githubusercontent.com/21143936/31056439-2cc7e2f4-a6ef-11e7-8d94-bda2a12c3fd1.gif)

**Would you like to work on the issue?**

Yes, 
@chiragw15 @iamareebjamal is this a valid issue?

**Comment by yashLadha** [comment]
Are you using an emulator or a device. Check the microphone settings for the app. @aditya98ak

**Comment by yashLadha** [comment]
Oh sorry my bad..In emulator microphone is not detected automatically. It is not using your laptop microphone. So you have to alter settings of emulator to use a microphone or use a virtual microphone.

**Comment by aditya98ak** [comment]
@yashLadha But don't you think it is a valid issue, though it is not using microphone but toast message should not be shown so many times? What do you say? or should I close this issue?

**Comment by yashLadha** [comment]
See it is because whenever activity comes it calls on create method and in that there is a function call `initializeMethod` which takes places and produces the toast icon. Instead of every time producing the toast we can generate it once but due to some error the microphone is disconnected for some time and them get connected so the user should also get notified about it too. We can take this discussion on gitter for getting views of everyone.

**Comment by aditya98ak** [comment]
@yashLadha Yes, sure :+1:

**Comment by chiragw15** [comment]
We could show two different toasts, one can be displayed if hotword detection is not supported by phone, other can be if some error occurred during hotword detection like microphone disconnected or something like that. What say @yashLadha @aditya98ak ?

**Comment by aditya98ak** [comment]
I agree with you @chiragw15 and also a toast if microphone gets connected again, as @yashLadha said.

**Comment by yashLadha** [comment]
Yes, it would be great @chiragw15

**Comment by aditya98ak** [comment]
Toast for hotword detection like microphone disconnected is ok, but for showing toast I am stuck
Acc to me we can do two things here.
1. Show a toast("Hotword detection is not supported") only for once per lifetime, till the data is not cleared.
2. For this point please have a look at this link.
https://stackoverflow.com/questions/7360846/how-can-i-execute-something-just-once-per-application-start
@chiragw15 @yashLadha What are your views?

**Comment by collinx** [comment]
@aditya98ak We are already using shared preferences, so it would be great if you implement using that to trigger first-time toast. 😄

**Comment by aditya98ak** [comment]
@collinx I was just confirming, Okay then, sending the PR soon :smile:
