### ISSUE TITLE
Skills info and examples are not loading

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#1008]
Clicking on the sample skills button shows that skills are no longer loading.

![screenshot_2017-10-02-21-15-58](https://user-images.githubusercontent.com/1583873/31095419-123d8aea-a7b9-11e7-8c31-89a38e7795a1.png)

**Comment by RaiVaibhav** [comment]
@mariobehling its works fine when i opened in my phone
![screenshot_2017-10-03-12-10-43-137_org fossasia susi ai](https://user-images.githubusercontent.com/22278438/31113761-51263110-a838-11e7-8933-5a72e1884406.png)

**Comment by chiragw15** [comment]
Works for me too. Can be due to internet connection issue.

**Comment by knight-shade** [comment]
Maybe a snack bar can added to notify the user of internet connectivity issue as an improvement?
And automatic fetching of data once internet is connected if the user is still in the sample skills or a swipe to refresh?

**Comment by saitejach1998** [comment]
can i work on this issue?

**Comment by aniket-agarwal1999** [comment]
![susi](https://user-images.githubusercontent.com/30111752/37227343-008e1ab4-2403-11e8-9a0e-7101a9d10f12.gif)
@chiragw15 As you can see the app is still showing some error while showing the skills as it just shows Network problem and the problem doesn't seem to go even when the page is refreshed. I can even add a snack bar when the network connection problem is genuine. So can I please claim this issue?

**Comment by aniket-agarwal1999** [comment]
@mariobehling @chiragw15 Can you please guide me a bit on how to solve this error, when I viewed the logcat for the issue, the problem seemed to be the result of Null Pointer exception.

**Comment by ShubhamKushwah** [comment]
@mariobehling @chiragw15 
Hey, I can solve this one... We can store it locally the first time.
And still, there would be the reload option.
Assign it to me.

**Comment by batbrain7** [comment]
@mariobehling skills are now shown properly in the skills activity
