### ISSUE TITLE
Showing Colour of ratings based on their value

### ISSUE THREAD

**Issue by yashLadha** [fossasia/susi_android#1009]
Currently the rating is just shown as simple text, it would be more attractive if it shown on a card or a coloured text box and the colour depends on the value of rating.

**Would you like to work on the issue?**

Yes. @chiragw15 views??

**Comment by yashLadha** [comment]
@mariobehling can you add label of hacktoberfest??? :sweat_smile:

**Comment by chiragw15** [comment]
@yashLadha please go ahead and do add a screenshot for reviewing

**Comment by yashLadha** [comment]
Sure :+1:

**Comment by anandwana001** [comment]
@yashLadha Nice idea, could we take 5-stars rating system or else showing red color as a positive rating in your screenshot is not a good option so we can interchange red and blue color.
![extreme](https://user-images.githubusercontent.com/25057618/31272183-b19df8ae-aaa7-11e7-81be-8c4691174539.png)
