### ISSUE TITLE
Fix flaky UI tests

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#1015]
```
java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong. Selected Root:
```

There are flaky UI tests in the app, either these should be fixed or removed (replaced by RoboElectric unit tests) since they fail the build on occasional basis making it hard to validate the status of repository

**Comment by collinx** [comment]
@iamareebjamal I tested the app, all the UI tests are working fine. No such error is popping up. Could you give more details about the error??

**Comment by iamareebjamal** [comment]
@collinx Please check circle CI logs

**Comment by collinx** [comment]
@iamareebjamal I looked into the CI logs and UI test needs to be fixed. I would like to work on it.

**Comment by iamareebjamal** [comment]
Sure please go ahead @collinx
