### ISSUE TITLE
Search functionality not working properly

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#102]
You can see it in below pic .
![screenshot_2016-10-08-15-11-46](https://cloud.githubusercontent.com/assets/14003244/19212206/85aa41e0-8d6a-11e6-9fbf-5bdd834c7bab.png)
![screenshot_2016-10-08-15-14-36](https://cloud.githubusercontent.com/assets/14003244/19212208/8fa406b8-8d6a-11e6-841e-4bf94dc252fb.png)

**Comment by daminisatya** [comment]
Can we make the UI a little better?

**Comment by jig08** [comment]
@daminisatya +1.

**Comment by gogeta95** [comment]
I'd like to work on search UI @daminisatya , will be something new for me.

**Comment by amitiwary999** [comment]
@gogeta95 I already started working on it but you can also try.

**Comment by daminisatya** [comment]
@gogeta95 yes you can also try. @gogeta95 @amitiwary999 please open a separate issue. Lets track it separately!

**Comment by viveksb007** [comment]
@amitiwary999 after changing query you need to click search button again
i tried same scenario as you did and its working fine

![screenshot_2016-10-08-20-15-37-754_org fossasia susi ai](https://cloud.githubusercontent.com/assets/12713808/19213891/31b34bb6-8d94-11e6-9595-eaec3add9395.png)
![screenshot_2016-10-08-20-15-49-895_org fossasia susi ai](https://cloud.githubusercontent.com/assets/12713808/19213892/31b7a6ac-8d94-11e6-8dce-abf6f268372e.png)

**Comment by amitiwary999** [comment]
@viveksb007 
![screenshot_2016-10-08-20-36-51](https://cloud.githubusercontent.com/assets/14003244/19214008/63a46d32-8d97-11e6-8983-f9ad105358ba.png)
![screenshot_2016-10-08-20-37-26](https://cloud.githubusercontent.com/assets/14003244/19214010/71bcc25c-8d97-11e6-9222-70bb8fa485bb.png)

**Comment by viveksb007** [comment]
@amitiwary999 uninstall previous app and install fresh.
i fixed this, it was due to change in ids and position. previously ids started from 1 and recycler position started from 0. 
i changed ids starting from 0.

**Comment by gogeta95** [comment]
@daminisatya  created #105 .
