### ISSUE TITLE
Welcome description overlapping on screen less than 5"

### ISSUE THREAD

**Issue by anandwana001** [fossasia/susi_android#1022]
**Actual Behaviour / Screenshots**
![screenshot_2017-10-09-16-13-08](https://user-images.githubusercontent.com/25057618/31337307-57e2aeea-ad18-11e7-9e73-c6a093509a4d.png)

**Currently happening**
Less than 5" Screen, Welcome screen description text overlapping TabLayout

**Expected Behaviour / Screenshots**
![screenshot_2017-10-09-18-39-07](https://user-images.githubusercontent.com/25057618/31339664-375c2eb8-ad21-11e7-9d56-27f14c2dc2dd.png)

**Would you like to work on the issue?**
Yes, Let's discuss if anyone having any other idea for this design else please allow me to make PR for this issue.

**Comment by Arshilgenius** [comment]
@anandwana001   actually it look's better below the screen, can you try something which will make the description not overlap the screen?

**Comment by anandwana001** [comment]
@Arshilgenius ok, let's have some more comments if anyone can suggest on the basis of UI/UX or we can alter the textSize or layout for screens less than 5"!!

**Comment by Arshilgenius** [comment]
@anandwana001  yeah sure.

**Comment by anandwana001** [comment]
@chiragw15 could you give some helpful comments!!

**Comment by chiragw15** [comment]
@anandwana001 keep the the description below the mobile image only and bottom align it. Change the mobile image size according to the screen size.

**Comment by anandwana001** [comment]
@chiragw15 @Arshilgenius Ok, now it's look good on small screen,
@chiragw15 can I make PR now for this?
![screenshot_2017-10-09-22-03-57](https://user-images.githubusercontent.com/25057618/31348623-e24b887a-ad3d-11e7-88a0-933ee5a0a30b.png)
![screenshot_2017-10-09-22-03-52](https://user-images.githubusercontent.com/25057618/31348624-e296d79e-ad3d-11e7-8a69-d355f2ad912f.png)

**Comment by chiragw15** [comment]
@anandwana001 yes sure.

**Comment by anandwana001** [comment]
@chiragw15 If you could please review the PR #1023  !!
