### ISSUE TITLE
susi message layout not similar to user message layout

### ISSUE THREAD

**Issue by anandwana001** [fossasia/susi_android#1024]
#**Actual Behaviour / Screenshot**
![screenshot_2017-10-10-08-38-18](https://user-images.githubusercontent.com/25057618/31368114-4b4632ca-ad99-11e7-912c-e23e3263df74.png)

**Expected Behaviour / Screenshot**
![screenshot_2017-10-10-09-20-10](https://user-images.githubusercontent.com/25057618/31368582-483e13f6-ad9c-11e7-969c-e474d56b6ec8.png)

Timestamp of susi message is below the text and timestamp of user message is not!! I had made the timestamp of user message below the text which makes both the message layout similar.
May I make PR for this issue?

**Would you like to work on the issue?**
Yes

**Comment by collinx** [comment]
@anandwana001 Go ahead, work on it. 😄
