### ISSUE TITLE
Adding delete and copy feature in susi app

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#103]
I would like to add delete and copy features in the susi app , so that we can delete and copy individual messages..

**Comment by gogeta95** [comment]
Copy of #16.

**Comment by jig08** [comment]
@mayank408 duplicate feature. Closing this.

**Comment by mayank408** [comment]
This feature has not been implemented that's why I created the issue.  I did not know that its already in the issue.

**Comment by gogeta95** [comment]
No worries, you can continue discussion in #16 and discuss with others if you want to help with issue.

**Comment by mayank408** [comment]
@gogeta95 ya sure
