### ISSUE TITLE
A searchview in susi.ai skills 

### ISSUE THREAD

**Issue by akashagra** [fossasia/susi_android#1035]
**Actual Behaviour**

Now,the skills are displayed in a list and one cant do live search on them

**Expected Behavior
It would be great if a live search option is added, so that one can search the skills

**Would you like to work on the issue?**
Yes,I would like to work on it

**Comment by akashagra** [comment]
What say @chiragw15 ?

**Comment by chiragw15** [comment]
Yes, we can add it. No harm in adding a searchview. @akashagra Please proceed.

**Comment by akashagra** [comment]
@chiragw15  i need a suggestion ,i am thinking of creatinga different recycler adapter as a results of the searchview. Like when the user searches then grouping would be not there ,so should i do it or do something else

**Comment by chiragw15** [comment]
@akashagra Display the results group wise only. For example, suppose I searched for skills starting with c, display the skills starting with c in first group in horizontal list, then display the skills starting with c in second group in horizontal list and so on.

**Comment by batbrain7** [comment]
@chiragw15 please close this issue
