### ISSUE TITLE
Add @string resource for enter url in activity_forgot_password and in many other places as well

### ISSUE THREAD

**Issue by akashagra** [fossasia/susi_android#1042]
Currently hardcoded string is present and it would be better if @string resource is added.
I would like to work on the issue

**Comment by collinx** [comment]
@akashagra Go ahead. 👍  Also, add the translational strings for each string you add for forgot password activity.

**Comment by akashagra** [comment]
@collinx Ya i have done for all strings in the entire project.
Actually i had earlier made a pull request regarding some different issue and now commited the changes regarding to strings ,so that pull request shows two commits. Can you please help what can be done?

**Comment by collinx** [comment]
@akashagra Actually, you have been doing work and committing changes from the development branch, hence, each time you push commits, they are getting pushed to the same PR. Try to make a new branch for individual issues.

**Comment by akashagra** [comment]
So it would work this time or do i need to close this one and then create two seperate pull requests for two different commits ?
@collinx

**Comment by collinx** [comment]
@akashagra creating different PR for the two different issues would be fine. 😄

**Comment by akashagra** [comment]
Done @collinx 
Thanks
