### ISSUE TITLE
App closes while asking for permission

### ISSUE THREAD

**Issue by hardik124** [fossasia/susi_android#1049]
**Actual Behaviour**

App closes while asking for permission

**Expected Behaviour**
App should pause while user grants permission
**Steps to reproduce it**
Disable permission and open app.

**LogCat for the issue**

N/A

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
Yes
Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by dabbler011** [comment]
@hardik124 I think it is only because textToSpeech is accessed before its initialisation in onPause(). Should I open a PR fixing that?

**Comment by batbrain7** [comment]
@dabbler011 @hardik124 the app closes without asking for permissions now, if there anything other than this on the issu
