### ISSUE TITLE
Improve Search UI.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#105]
improve search UI while searching messages in conversation

**Comment by iit2014086** [comment]
how about using spannable string??

![screenshot_2016-10-09-03-11-49-787_org fossasia susi ai](https://cloud.githubusercontent.com/assets/12937069/19216172/9708609c-8dcf-11e6-89ea-f275c356bb6c.png)

![screenshot_2016-10-09-03-12-13-488_org fossasia susi ai](https://cloud.githubusercontent.com/assets/12937069/19216173/a997ce46-8dcf-11e6-85d7-b3ada0dd3fbd.png)

**Comment by daminisatya** [comment]
Yes, this is the required output.

**Comment by iit2014086** [comment]
okay, I will create a PR.
