### ISSUE TITLE
Change downvote color to red (#d1462f)

### ISSUE THREAD

**Issue by DipanshKhandelwal** [fossasia/susi_android#1057]
**Actual Behaviour**

Shows blue color in thumbs up and down both.

**Expected Behaviour**

![screenshot_2017-11-28-15-29-48-717_ai susi](https://user-images.githubusercontent.com/24923974/33313680-61fa8686-d451-11e7-85bf-707d663e8985.png)

**Steps to reproduce it**

Click on thumbs down in current app to see blue color.

**Would you like to work on the issue?**

Yes

**Comment by jay006** [comment]
I would like to work on this. @DipanshKhandelwal
