### ISSUE TITLE
Reporting time

### ISSUE THREAD

**Issue by namanbakhru** [fossasia/susi_android#1063]
**Actual Behaviour**

The app when asked for time reports me in CET time zone, when it clearly recognises my location.

**Expected Behaviour**

Should report time in native (Indian Time Zone in my case).

**Steps to reproduce it**

Just ask time from different locations.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/18362779/33518319-eec8db8e-d7b8-11e7-907b-09e5e744c37e.png)
.

**Would you like to work on the issue?**

Yes, I would like to try to work on the issue after getting familiar with the app and code.

**Comment by abishekvashok** [comment]
@namanbakhru this should go with the server's response, I guess

**Comment by chiragw15** [comment]
@namanbakhru The app only displays the response that it gets from the server. The app sends the location of user to the server as an API parameter. Please use that to create a skill to get the time based on user's location.

**Comment by chiragw15** [comment]
Need to be fixed on server. Thus closing it from here.
