### ISSUE TITLE
Change ContributionHelp file in docs to ContributionHelp.md 

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#1068]
1. Change ContributionHelp file in docs to ContributionHelp.md 

2. Add following in main readme file
```
For first time Contributors

First time contributors can read [ContributionHelp.md](docs/ContributionHelp.md) file for help regarding creating issues and sending pull requests.
```

**Comment by vchrombie** [comment]
Hello,
I am new to Open Source and I am interested to work on this project.
Can I take this issue and work on it?

**Comment by chiragw15** [comment]
@vchrombie sure. Go ahead. :+1:

**Comment by vchrombie** [comment]
Can you tell me where should I add that text in the readme file exactly?

Can I do it under  [Join the development](https://github.com/vchrombie/susi_android/blob/development/README.md#join-the-development) ?

**Comment by chiragw15** [comment]
Below https://github.com/fossasia/susi_android#contributions-best-practices
