### ISSUE TITLE
no response when there is no internet

### ISSUE THREAD

**Issue by iit2014086** [fossasia/susi_android#107]
if a user sends a message when there is no internet then he should get relevant answers once he is connected to internet

**Comment by amitiwary999** [comment]
@iit2014086 From now onward if you want to work on an issue assigned to someone then inform him also because it waste time and energy.(I already started working on #102(#102 and #105 both are same).

**Comment by yasharmaster** [comment]
I want to work on this issue.

**Comment by iit2014086** [comment]
@amitiwary999  yeah i will from now on...  @yasharmaster  you can work on it...

**Comment by jig08** [comment]
@nikimullick Follow up: 
- https://github.com/fossasia/susi_android/issues/123#issue-181915909
- https://github.com/fossasia/susi_android/issues/123#issuecomment-252583933

**Comment by nikimullick** [comment]
@jig08  I'm sorry I'm confused now..Should I go ahead with my implementation or stop?

**Comment by nikimullick** [comment]
@yasharmaster have you worked on this already?

**Comment by jig08** [comment]
@yasharmaster  Are you working on this issue ? If not, we can assign @nikimullick .

**Comment by yasharmaster** [comment]
I am working on this issue @jig08 .

**Comment by jig08** [comment]
@nikimullick Kindly look for some other issue to fix, or open an issue for a new feature. Cheers 😃

**Comment by nikimullick** [comment]
I have already implemented the toast message showing the connection error.

**Comment by nikimullick** [comment]
okay cool @jig08 . 
@yasharmaster you work on this if you want.

**Comment by yasharmaster** [comment]
@jig08 should we keep a variable isDelivered for every chat message from user and then when internet connection is available then fetch responses of all undelivered messages and add them to the chat?

**Comment by jig08** [comment]
@yasharmaster seems fine to me.

@Orbiter @mariobehling  Your feedback required.

>should we keep a variable isDelivered for every chat message from the user and then when the internet connection is available then fetch responses of all the undelivered messages and add them to the chat?

**Comment by mariobehling** [comment]
@jig08 How does whatsapp deal with this? Please implement in the same way.

**Comment by jig08** [comment]
@mariobehling WhatsApp does send all the messages at a later stage when the internet connection is available, instead of discarding them off.

We can follow suit, @yasharmaster I think we should associate a `isDelivered` variable with each message, check accordingly and fetch responses of all the undelivered messages.

**Comment by abhi007tyagi** [comment]
please use job scheduler... it will handle background sync when network is not there. you can implement the other features using callback methods

**Comment by yasharmaster** [comment]
I would not be able to work on this issue anymore. Anyone else can take up this issue if they want. @jig08

**Comment by iit2014086** [comment]
if no one is working on this..i can take up this issue @daminisatya
