### ISSUE TITLE
Allow users to add custom background in the ChatActivity

### ISSUE THREAD

**Issue by srv-twry** [fossasia/susi_android#1074]
**Actual Behaviour**

The background in the ```ChatActivity``` is just blank white space.

**Expected Behaviour**

Allow users to add custom background in order to make the UI better as well as add personal touch.

**Steps to reproduce it**

Open the chat window.

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes
@chiragw15 views ?

**Comment by chiragw15** [comment]
@srv-twry this feature also existed before and after discussing with @mariobehling we removed this because we wanted to keep UI as simple as possible and more close to the Google Assistant. Thus that feature was an overkill

**Comment by srv-twry** [comment]
Thank you @chiragw15 .
