### ISSUE TITLE
Add option to delete the chat history in ChatActivity

### ISSUE THREAD

**Issue by srv-twry** [fossasia/susi_android#1075]
**Actual Behaviour**

There is no option to delete the previous chat messages.

**Expected Behaviour**

There should be an option to clear the chat messages.

**Steps to reproduce it**

Open the ```ChatActivity```

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes.

@chiragw15 Views ?

**Comment by brijeshshah13** [comment]
@srv-twry Have you started implementing this? If not, can I?

**Comment by srv-twry** [comment]
@brijeshshah13 no I haven't started yet but I intend to work on it. I am just waiting for @chiragw15 to approve it.

**Comment by srv-twry** [comment]
As discussed in #1081 , in case the functionality is implemented on the server , it will be reopened. 
Closing it for now.
