### ISSUE TITLE
Add option to change chat wallpaper 

### ISSUE THREAD

**Issue by Nirvan101** [fossasia/susi_android#1077]
**Actual Behaviour**
The wallpaper in the chat activity is currently a fixed blank screen.

**Expected Behaviour**
There should be an option allowing the user to set the wallpaper to whatever picture he/she wants. This is similar to the wallpaper option in whatsApp.

**Would you like to work on the issue?**
Yes

**Comment by brijeshshah13** [comment]
Duplicate #1074.
