### ISSUE TITLE
Pressing back button after Settings->Login closes the app 

### ISSUE THREAD

**Issue by Nirvan101** [fossasia/susi_android#1080]
**Actual Behaviour**
If the user is not logged in , going to Settings->Login opens the Login page. Here if the user presses the back button, the app closes instead of going back to the settings page. 
 
**Expected Behaviour**
The app closes on pressing the back button in LoginActivity. This should not happen if the user has come to the Login page from Settings->Login.
    If the user has come to LoginActivity from Settings->Login, pressing the back button should take the user back to Settings page.

**Steps to reproduce it**
Open the app without logging in. Go to Settings and press Login. The Login page opens. Press back button. The app will close instead of going back to the Login page.

**Would you like to work on the issue?**
Yes

**Comment by ribhav-pahuja** [comment]
@Nirvan101 are you still working on this?

**Comment by Nirvan101** [comment]
No. Feel free to take it up!

**Comment by anipmehta** [comment]
@Nirvan101 I just submitted a PR for this issue and if you think this is not able to solve the issue then you can reopen this.

**Comment by ShubhamAvasthi** [comment]
I would like to work on this issue.

**Comment by Nirvan101** [comment]
Sure, though I must warn you. It seems like a number of people have tried and failed on this quest before you. I remember it being a pretty difficult problem and I couldn't see any straightforward way to do this with the existing design.

**Comment by ShubhamAvasthi** [comment]
> 
> 
> @ShubhamAvasthi Sure, though I must warn you. It seems like a number of people have tried and failed on this quest before you XD. I remember it being a pretty difficult problem and I couldn't see any straightforward way to do this with the existing design.

I understand and will atleast try. What was the issue in this pull request #1116 ?

**Comment by atm1504** [comment]
@mariobehling @iamareebjamal please close this issue. This issue has already been resolved.
