### ISSUE TITLE
Use Predefined PrefManager rather than creating new SharedPref's

### ISSUE THREAD

**Issue by anandwana001** [fossasia/susi_android#1083]
**Actual Behaviour**

we are creating new SharedPref's in `WelcomeActivity` class.

**Expected Behaviour**

We can use our predefined `PrefManager` class to perform that task

**Steps to reproduce it**

Use `PrefManager` class

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/25057618/34319668-056b2828-e80e-11e7-95a9-0b01a32baf3d.png)

**Would you like to work on the issue?**

Yes

**Comment by knight-shade** [comment]
#1090 Fixes this issue.

**Comment by mamakancha** [comment]
I am working on this one.
