### ISSUE TITLE
Enable auto capitalisation of the first letter of a sentence

### ISSUE THREAD

**Issue by nikit19** [fossasia/susi_android#1085]
**Actual Behaviour**

Currently first letter of a sentence does not get automatically capitalised in the EditText of the Chat Activity.

**Expected Behaviour**

It should get capitalised automatically

**Steps to reproduce it**

Open ChatActivity.
Type a sentence.
Notice how it didn't get capitalised

**Screenshots of the issue**

![screenshot_20180102-191326](https://user-images.githubusercontent.com/20878145/34485554-46aebf30-eff1-11e7-8c3a-04153d9b475e.png)

**Would you like to work on the issue?**

Yes

**Comment by yashLadha** [comment]
Why there is a need for this? May be a user can also type phrase. can you explain a bit more about the need of the functionality.

**Comment by nikit19** [comment]
Almost all apps I use, I have seen them having this feature be it WhatsApp or Messenger. The message looks more readable be it a sentence or a phrase. Moreover this feature will only work if user has enabled auto capitalisation in his keyboard settings.So for users who have enabled this feature in their keyboard settings they should get automatically capitalised letters just like they are getting in all other apps they are using.

**Comment by yashLadha** [comment]
Have you seen that feature in Google search or any recommendation app which reformatted the text and does query. I think messaging has this feature because it makes text more meaningful as you rightly said but do you think such functionality needs to be there in these apps.

**Comment by yashLadha** [comment]
Have you seen that feature in Google search or any recommendation app which reformatted the text and does query. I think messaging has this feature because it makes text more meaningful as you rightly said but do you think such functionality needs to be there in these apps.

**Comment by nikit19** [comment]
I have seen this feature in recommendation apps which reformatted the text and does query.(Just used Swiggy and saw them capitalising the first letter of every word in search)
Moreover, what harm can a text which is nicely formatted do?
Susi's interface is  pretty similar to a messaging app so I guess it makes sense to have this feature

**Comment by yashLadha** [comment]
Will that only be for the representation purpose or also for the query part
as well.

**Comment by nikit19** [comment]
For both the purposes.
I have sent a pull request you can see [here](https://github.com/fossasia/susi_android/pull/1086) how it is implemented
