### ISSUE TITLE
Handle orientation change during welcome screen

### ISSUE THREAD

**Issue by knight-shade** [fossasia/susi_android#1090]
**Actual Behaviour**

When the app is opened for the first time, it shows the introduction screen. If there is a orientation change happens, from portrait to landscape mode or vice -versa it closes the introduction part and automatically goes to the login screen.

**Expected Behaviour**

Even after orientation change, the introduction screen should show the same screen as in portrait mode. 

**Steps to reproduce it**

1. Open the app first time, (can clear the app storage so that introduction screen starts)
2. Then change the orientation from portrait to landscape if it is in portrait mode and vice versa.

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by batbrain7** [comment]
@codedsun this issue?

**Comment by codedsun** [comment]
Yes

**Comment by codedsun** [comment]
@batbrain7 Close this issue, it has been fixed earlier.
