### ISSUE TITLE
Upgrade Kotlin Runtime Version to 1.1.51

### ISSUE THREAD

**Issue by S2606** [fossasia/susi_android#1094]
**Actual Behaviour**

Current Kotlin runtime version is 1.1.3

**Expected Behaviour**

Upgrade it to 1.1.51

**Would you like to work on the issue?**

Yes

**Comment by S2606** [comment]
@chiragw15 What do you think?

**Comment by saitejach1998** [comment]
is the issue still open?

**Comment by S2606** [comment]
@saitejach1998 I am working on it..
