### ISSUE TITLE
App crashes on clicking "skip" on signup/login activity 

### ISSUE THREAD

**Issue by madhurgupta10** [fossasia/susi_android#1097]
**Actual Behaviour**

App crashes on clicking "skip" on signup/login activity

**Expected Behaviour**

App should not crashes on clicking "skip" on signup/login activity and open the chat activity.

**Steps to reproduce it**

Clear the cache and data > Open App > Skip the launcher > click on "skip" on login activity.

**Device Information**

Tested on Xiaomi Mi A1 running 8.0.0 Oreo.

**Comment by saitejach1998** [comment]
Fixing the Kotlin runtime solved the issue for me...
Just check if it works for you too..
https://github.com/saitejach1998/susi_android

**Comment by madhurgupta10** [comment]
Hi, @saitejach1998 I tested the play store version.

**Comment by saitejach1998** [comment]
@madhurgupta10  can you the version in my repo?
i don't have that problem anymore
Tested on Nexus 5x API 27

**Comment by madhurgupta10** [comment]
@saitejach1998 same issue, see [screenshot](https://imgur.com/YOX1q2s)

**Comment by saitejach1998** [comment]
@madhurgupta10  how can i share the apk with you?
I've tested it on 3 devices again
7.1.2
8.0
8.1
it works perfectly on all of them..

**Comment by saitejach1998** [comment]
here...
https://drive.google.com/open?id=17TSB41vXWAprnc7IZwDEtme2cyKgZ5Rw

**Comment by madhurgupta10** [comment]
@saitejach1998 worked on my device as well as on AVD.

**Comment by saitejach1998** [comment]
@madhurgupta10  the problem still exists in the main repo

**Comment by madhurgupta10** [comment]
@saitejach1998 please open the PR.
