### ISSUE TITLE
Add message resend option

### ISSUE THREAD

**Issue by harshitbansal05** [fossasia/susi_android#1098]
**Actual Behaviour**

Currently there is no option to resend a message.

**Expected Behaviour**

User may be able to resend a message.

**Steps to reproduce it**

Long clicking the message must initiate a contextual action bar with one option for re-sending the message.

**Would you like to work on the issue?**

Yes

**Comment by harshitbansal05** [comment]
@chiragw15 should l work on it?

**Comment by NithinThomasJoji** [comment]
Hey can I be assigned to fix this bug?

**Comment by NithinThomasJoji** [comment]
Hey can I be assigned to fix this?

**Comment by harshitbansal05** [comment]
@chiragw15 ^^

**Comment by arundhati24** [comment]
@harshitbansal05 In what situation do you wnat the user to be able to resend a message?

**Comment by aniket-agarwal1999** [comment]
@harshitbansal05 The idea is great but the copy option already exists in the app for every message. So I don't think it would be of much use.
