### ISSUE TITLE
Link in message content opening in same chrome tab

### ISSUE THREAD

**Issue by harshitbansal05** [fossasia/susi_android#1099]
**Actual Behaviour**

Clicking a link in the content of a susi message opens the link in the same tab of chrome. 

**Expected Behaviour**

Like the link preview title in **item_susi_link_preview .xml**, the link in message content(if any) should also open in a new chrome tab. 

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
Sorry, I didn't get the issue exactly. So, clicking on a link opens that link in a single tab and you want that all links that you click open in a new tab?

**Comment by harshitbansal05** [comment]
yaa, that is the issue @chiragw15

**Comment by chiragw15** [comment]
I don't get why is this an issue?

**Comment by harshitbansal05** [comment]
I thought the user may wish to see the website he opened before @chiragw15..
