### ISSUE TITLE
Store Messages in a local database

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#11]
The app currently starts a new chat session every time you start it , old messages are not shown. Old messages must be stored and displayed too.

**Comment by amitiwary999** [comment]
Are you working on this ?

**Comment by betterclever** [comment]
Not started yet. Do you wish to wish to work on this?

**Comment by code-crusher** [comment]
@betterclever I would like to work on it :)

**Comment by betterclever** [comment]
@code-crusher Sure!! Please carry on the work.

@the-dagger @daminisatya You may assign the issue.

**Comment by code-crusher** [comment]
@betterclever @the-dagger Great. Will start working on it :)

**Comment by gogeta95** [comment]
@the-dagger please close this as it has been done.
