### ISSUE TITLE
Adding a Share floating button 

### ISSUE THREAD

**Issue by Ananthusubramanian** [fossasia/susi_android#1101]
In the skills activity there is a need of sharing floating button so that the users can have the feature to share this app .This feature is very useful for sharing of app across social networks

![screenshot_2018-01-25-17-41-06-198_ai susi](https://user-images.githubusercontent.com/22250995/35387862-8113097a-01f7-11e8-8d12-5342f1d90178.png)

**Comment by gakarod** [comment]
can I work on this ?

**Comment by rishabchirania** [comment]
@chiragw15 hey i would really like to work on this issue...should i work on this?

**Comment by ShubhamKushwah** [comment]
@chiragw15 Please assign this task to me, I would also add a floating popup like this below:
[tbn:ANd9GcQzqjt2kewnayp6KOkePjyekBCjsEqBsLJFxhTqpcN_8XW3WWh_fQp0yqYR](Image link)

**Comment by arundhati24** [comment]
@ShubhamKushwah  IMHO there's no need of this floating button as the app already allows the user to share this app using Share SUSI option from settings menu.

**Comment by ShubhamKushwah** [comment]
@arundhati24 It's better to have a FAB for it, since it is more attractive, and user will have a more chance of sharing the app.
