### ISSUE TITLE
Providing Social Logins such as Facebook, Google

### ISSUE THREAD

**Issue by apoorvinfo** [fossasia/susi_android#1103]
**Actual Behaviour**

Login Behavior of the app is simple and non-friendly as compared to the common login trends.

**Expected Behaviour**

In the Login Window User should use Facebook or Google Login

**Steps to reproduce it**

Provides the User SignUp using Facebook and Gmail for the first time, and then the login token is used for the regular usage of the app.

**Would you like to work on the issue?**
 Yes, I want to add this feature to the app. 
 Please review @Orbiter

**Comment by rishabchirania** [comment]
@chiragw15 i would love to work on this issue

**Comment by apoorvinfo** [comment]
@rishabchirania I hope, I have already asked to work on this feature!

**Comment by aniket-agarwal1999** [comment]
@apoorvinfo @chiragw15 As the issue has been stagnant for quite some time now, can I please work on this.

**Comment by batbrain7** [comment]
@aniket-agarwal1999 this has to be implemented on the server first, so closing it for now
