### ISSUE TITLE
App crashes on refreshing skill listing activity

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1110]
**Actual Behaviour**

Currently, the app crashes on refreshing the skills listing activity. 

Logcat : 

![app_crash_logcat](https://user-images.githubusercontent.com/30979369/36241665-bea52c04-123d-11e8-8e02-94b71a834e86.png)

**Expected Behaviour**

The app should not crash on refreshing this activity. It should display the default skill groups.

**Steps to reproduce it**

[Device used : Xiaomi Redmi Note 4]

* Open the skills listing activity in the app
* The default skill groups would be displayed
* Now, try searching for a skill (e.g. music as in the screenshot)
* The skill fetch error message appears 
* Now try refreshing the page once or twice using swipe to refresh
* The app crashes, the logcat of which is above

![crash_1](https://user-images.githubusercontent.com/30979369/36241799-6f2dc7ac-123e-11e8-94ab-c3b5c2f44af2.jpg)

**Would you like to work on the issue?**
Yes

**Comment by anipmehta** [comment]
@arundhati24 : Thanks for finding this bug. I was able to solve it and submitted a PR and if you think there is still an issue then you can open this issue again.
