### ISSUE TITLE
Dialog issue in the reset password activity.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/susi_android#1129]
**Actual Behaviour**

After entering the email id and clicking on the reset password button to change the password a dialog pops up stating that the recovery email to change the password is sent to the user's email id, now on clicking the back navigation button or on tapping on the screen the dialog does not dismiss. 

**Expected Behaviour**

On pressing the back navigation button or on single tapping the screen, the dialog should be dismissed.

**Steps to reproduce it**

Go to the reset password page, try resetting the password.

**Would you like to work on the issue?**

Yes.

**Comment by aniket-agarwal1999** [comment]
@sauravvishal8797 as the issue has been stagnant for quite some time now, can I please work on this.

**Comment by aniket-agarwal1999** [comment]
@sauravvishal8797 Okay :)

**Comment by batbrain7** [comment]
@arundhati24 is this the settings fragment which is being referred to as the reset password activity?

**Comment by arundhati24** [comment]
No, actually the issue exists and is valid. It happens for both. If you try resetting password when you enter the login screen for the first time or when you try to reset it using settings. I think he meant forgot password activity.
