### ISSUE TITLE
Use Android resources and avoid concatenation using '+' in setText

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1134]
**Actual Behaviour**

Currently, there are a few strings that have been hard-coded in setText in SkillDetailsFragment.kt . Also the strings concatenated using '+' cannot be translated properly. 

**Expected Behaviour**

These string literals should be referenced by using Android resources rather than hard-coding them.

**Screenshots of the issue**
Example : 

![string_literals](https://user-images.githubusercontent.com/30979369/36634176-858266d6-19c6-11e8-9e46-c719e3e0ff16.png)

**Would you like to work on the issue?**

Yes

**Comment by aniket-agarwal1999** [comment]
@arundhati24 @chiragw15  As the issue has been stagnant for quite some time, can I please work on it?

**Comment by arundhati24** [comment]
@aniket-agarwal1999  I have already sent a PR, and i need to make the changes requested by @chiragw15 . 
I will be updating it in some time. You may please look for some other issues and work on them. :)

**Comment by aniket-agarwal1999** [comment]
@arundhati24 Okay :)
