### ISSUE TITLE
Add splash screen.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/susi_android#1137]
**Actual Behaviour**

On launching the application, the login page appears or the user is directed to the chat interface if he/she is logged in.

**Expected Behaviour**

A splash screen can be added which would be displayed for a very short period of time before the user is directed to the login page or the chat interface.

**Steps to reproduce it**

Launch the app.

**Would you like to work on the issue?**

Yes.

**Comment by ujjwalagr** [comment]
Yes, I will do it by tommorow for sure.

**Comment by sauravvishal8797** [comment]
@ujjwalagr I'm already working on this.

**Comment by ujjwalagr** [comment]
@sauravvishal8797 I already  added it, I just have to send a PR , Actually I was trying to do it yesterday but something went wrong.May you help me in sending a PR.

**Comment by sauravvishal8797** [comment]
@ujjwalagr I had clearly mentioned above(in the create issue template) that I would be working on it and had also mentioned the same thereafter. I have finished working on it and I'm about to open the PR for the issue. Since I was the one who created the issue and I mentioned very clearly that I'd be working on it, I should be the one to send the PR. Therefore please see that from next time you consult the person working on the issue whether he/she wants to give it to someone else or not, before working on the issue yourself as it will just waste your and the author's time and effort. Instead you can create new issues if you find any and can work on that.
