### ISSUE TITLE
Press 'enter' key to send not working

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1143]
**Actual Behaviour**

Currently, the user cannot send the message by pressing the enter key on the keyboard even after turning on this feature from the settings.

**Expected Behaviour**

The user should be able to send message by pressing the enter key on the keyboard if s/he chooses to do so in the app settings.

**Screenshots of the issue**

![tap_enter_to_send](https://user-images.githubusercontent.com/30979369/36854053-0b74cb8a-1d96-11e8-845c-788d58b22d48.jpg)

**Would you like to work on the issue?**

Yes

**Comment by developershivamshukla** [comment]
Yes I would like to work on this

**Comment by arundhati24** [comment]
@developershivamshukla 
I have already mentioned in the issue that I want to work on it. You can look into the app and open other issues and work on them. Please follow the best practices.
https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by batbrain7** [comment]
@arundhati24 its been a while, I would like to proceed on this issue if you are no longer following it
