### ISSUE TITLE
Add an Alert dialog to confirm before closing the app when (logging in) in the app.

### ISSUE THREAD

**Issue by ujjwalagr** [fossasia/susi_android#1149]
**Actual Behavior**

On exiting the application at the time of login, the application get close directly , may be user don't want to close it & mistakenly it get closed. 

**Expected Behavior**

A popup must appear that confirms user ,that he/she really wants to close the application or not.

**Step to reproduce**

1. Reinstall or clear the data of the app.
2. Launch the app.
3. Press the back button when the login screen appear.

**Would you like to work on the issue**?

Yes.

**Comment by developershivamshukla** [comment]
Cool
