### ISSUE TITLE
Add search in Chat activity

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1152]
**Actual Behaviour**

Currently, the user cannot search for specific chat messages in the chat activity.

**Expected Behaviour**

The user should be allowed to search for specific messages from the previous chat messages. The user might want to revisit some specific instances where s/he might have asked susi to perform some task for her/him, say, display map of some city. It would be difficult for the user to scroll through the entire chat each time and find out that message. It would be much more convenient if the user is allowed to use a search to find out what s/he is looking for.
To add this feature,  we can convert the susi FAB to an expandable FAB menu which would show two FABS - skills and search, on being pressed. The skills FAB would direct the user to the skills activity and the search FAB would display a search bar that will allow the user to search for specific messages in the chat activity.

**Would you like to work on the issue?**

Yes

**Comment by agh372** [comment]
@arundhati24  Hi, If it's okay, can I work on this issue?

**Comment by arundhati24** [comment]
@agh372 Okay. Go ahead.

**Comment by agh372** [comment]
@batbrain7  yaa , working in a different branch actually , UI implementation is done,  just searching functionality is remaining.

**Comment by sats98** [comment]
@batbrain7 i would like to work on this issue?

**Comment by iamareebjamal** [comment]
@sats98 Go ahead

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @batbrain7 can I start working in this issue. I would require a bit time to solve it. But I will surely do it.

**Comment by atm1504** [comment]
@iamareebjama sir will solving this issue be considered as an effective pr?
