### ISSUE TITLE
Enhancements in search functionality in the Skills Activity.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/susi_android#1156]
**Actual Behaviour**

After performing the search operation along with the search results other skills information are displayed too.
User has to click on the search button on the keyboard to initiate the search operation.

**Expected Behaviour**

- [ ] Only the information matching the search query should be displayed on performing the search operation. 

- [ ] Proper message should be displayed if the search results are null. 

- [ ] A listener can be added which will display the search results as the user enters the query. On destroying the search view refreshed skills info could be displayed as it was displayed before initiating the search operation.

**Steps to reproduce it**

Open the SUSI.AI skills Activity. Tryout the search option.

**Would you like to work on the issue?**

Yes.

**Comment by arundhati24** [comment]
@sauravvishal8797  It's working for me. 

![search_functionality](https://user-images.githubusercontent.com/30979369/36934610-511fc8c4-1f12-11e8-96e7-7b5b04e1a1ff.jpg)

The only problem here is that the skill fetch error message, if it occurs, overlaps the skill details group and it remains there even after refreshing the page for which I have already opened and fixed issues #1121  and #1106 .

**Comment by sauravvishal8797** [comment]
@arundhati24 I guess a couple of enhancements can be made here. First, shouldn't we only display the items matching the search query cause at the moment info about other skills are displayed too along with the ones searched for, and the user has to click on the search button on the keyboard in order to initiate the search, what can be done is a listener can be added that will keep displaying the search query matched items as the user enters the search query, and if no results matching the search query are found an appropriate message can be displayed on the screen. And on destroying the search view refreshed skills info could be displayed as it was in the beginning i.e before initiating the search operation. What do you say?

**Comment by arundhati24** [comment]
@sauravvishal8797  It sounds good to me.

**Comment by batbrain7** [comment]
@arundhati24 its not working for me

**Comment by batbrain7** [comment]
@arundhati24 lets break this into several issues and implement one at a time

**Comment by batbrain7** [comment]
@sauravvishal8797 I am fixing this issue

**Comment by arundhati24** [comment]
We have a new [API](https://github.com/fossasia/susi_server/blob/development/src/ai/susi/server/api/cms/ListSkillService.java) on the server to return the search results. #1353 shall deal with the new implementation, hence closing this issue now.
