### ISSUE TITLE
app crashing when tapping like or dislike in chat 

### ISSUE THREAD

**Issue by vivek1339** [fossasia/susi_android#1161]
**Actual Behaviour**
when  like or dislike is tapped it should be liked or disliked in chat

the app is crashing 
**Expected Behaviour**
it should be either liked or disliked

it can provide feedback for the reply
**Steps to reproduce it**
just tap  like or dislike on the chat

**LogCat for the issue**
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329] Throwing new exception 'length=209; index=3392' with unexpected pending exception: java.lang.ArrayIndexOutOfBoundsException: length=209; index=3392
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void org.fossasia.susi.ai.chat.adapters.viewholders.ChatViewHolder.rateSusiSkill(java.lang.String, java.lang.String, android.content.Context) (ChatViewHolder.java:238)
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void org.fossasia.susi.ai.chat.adapters.viewholders.ChatViewHolder.access$000(org.fossasia.susi.ai.chat.adapters.viewholders.ChatViewHolder, java.lang.String, java.lang.String, android.content.Context) (ChatViewHolder.java:51)
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void org.fossasia.susi.ai.chat.adapters.viewholders.ChatViewHolder$2.onClick(android.view.View) (ChatViewHolder.java:196)
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at boolean android.view.View.performClick() (View.java:5198)
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void android.view.View$PerformClick.run() (View.java:21147)
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:739)
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
03-08 19:19:22.738 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void android.os.Looper.loop() (Looper.java:148)
03-08 19:19:22.739 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5417)
03-08 19:19:22.739 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-08 19:19:22.739 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:726)
03-08 19:19:22.739 16320-16320/ai.susi A/art: art/runtime/thread.cc:1329]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:616)

**Screenshots of the issue**
![untitled](https://user-images.githubusercontent.com/29175007/37154495-3567c814-2306-11e8-8af9-0515801b7bfb.gif)

**Would you like to work on the issue?**
yes
actually i found that the issue is with the number of elements of the locationarray in the file ParseSusiResponseHelper.kt file i have observed that the no of elements it has is 5 where as in the subsequent lines we are calling elements until locationarray[6]

**Comment by vivek1339** [comment]
and when i print all the values in the array i am getting only 4 elements
03-08 23:08:15.900 22962-22962/ai.susi D/ContentValues: susi_server
03-08 23:08:15.900 22962-22962/ai.susi D/ContentValues: conf
03-08 23:08:15.900 22962-22962/ai.susi D/ContentValues: susi
03-08 23:08:15.900 22962-22962/ai.susi D/ContentValues: en_0700_ai_play.json
i got this in the log when i printed all values in the locationarray

**Comment by vivek1339** [comment]
the setlocation function is invoked in the databaserepository.kt when database is updated by the onretrivesuccess function in the chatpresenter.kt which sets the locationuri as "skill": "/susi_server/conf/susi/en_0700_ai_play.json".
it is seperated by the '/' character and then sent to locationarray so it has only 4 values where as we are calling 6 values which is causing the crash.
If someone could help me in what the model,skill,language,group map to in the four values i can solve the problem
Thanks

**Comment by arundhati24** [comment]
Hey @vivek1339  It works fine for me on Xiaomi Redmi Note 4, Android 7.0. Which device are you using?

**Comment by vivek1339** [comment]
i have tried on emulator pixel2 and my phone yu yunicorn 
i think it is the problem with the version of android cause both the devices run on marshmellow

**Comment by vivek1339** [comment]
i want to eliminate the compatibility issue in the app can i apply this as gsoc project
