### ISSUE TITLE
Display of wrong date and day

### ISSUE THREAD

**Issue by aniket-agarwal1999** [fossasia/susi_android#1168]
**Actual Behaviour**

The screenshot is taken on 11th March, 2018 (Suday) at around 12.40am. The assisstant clearly states the wrong day and date, that is, it is still showing the date and day of the day that has just passed.

**Expected Behaviour**

The correct date and day corresponding to the current day should have been displayed.
However, one thing to note here is that when I tested the same thing at proper day time( after around 10am) the display of date and day were correct.

**Screenshots of the issue**

![susi_error_time](https://user-images.githubusercontent.com/30111752/37246016-715fe6b8-24c7-11e8-86cf-e4aac8112d2c.png)

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
That is not an issue of the android app imo. App is just displaying the response it is getting from server. Open this issue in server repo. The app correctly displays "March 11, 2018" on the top. If that date is wrong, then it is an issue of the app. But if you ask susi "date today" and it displays wrong date as an answer, that is an issue of the server. So, closing it from here. Open it in server repo. Reopen if I am wrong.

**Comment by aniket-agarwal1999** [comment]
@chiragw15 Okay :+1:
