### ISSUE TITLE
Dialog in signup activity not retained across configuration change

### ISSUE THREAD

**Issue by harshitbansal05** [fossasia/susi_android#1171]
**Actual Behaviour**

In SignUp activity, on pressing back button without entering credentials, a dialog is shown. The dialog is not retained across device rotation.

**Expected Behaviour**

The dialog must be retained across configuration change.

**Steps to reproduce it**

Open Signup Activity. Press back button and rotate the device.

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@harshitbansal05 may I work on this?
