### ISSUE TITLE
Display of search icon still there in the top bar when the user is there in a particular skill page

### ISSUE THREAD

**Issue by aniket-agarwal1999** [fossasia/susi_android#1177]
**Actual Behaviour**

The search option is there for all the pages: skill listing, settings, specific skills page.

**Expected Behaviour**

The search option should be given to the user only in the skill listing page as the presence of search option in the other pages is of no use.

**Screenshots of the issue**

![susi_error_searchoption](https://user-images.githubusercontent.com/30111752/37308443-162c5954-2664-11e8-801e-1f59ec00eff9.png)

**Would you like to work on the issue?**

Yes

**Comment by akhil117** [comment]
I want to work on this.

**Comment by akhil117** [comment]
@aniket-agarwal1999 can I work on this?

**Comment by aniket-agarwal1999** [comment]
@akhil117 Sorry, but I have already specified that I am working on this.
