### ISSUE TITLE
Bug: in new Wallpaper feature

### ISSUE THREAD

**Issue by abhi007tyagi** [fossasia/susi_android#118]
Selecting an image from Gallery is not setting it as chat background.
I get a toast saying "Editing is not supported for this image"

Steps:
1. open top right menu.
2. select wallpaper
3. select gallery
4. choose any image
5. toast appears with no change in background

**Comment by amitiwary999** [comment]
It is working fine.I just checked it.
![screenshot_2016-10-09-19-17-31](https://cloud.githubusercontent.com/assets/14003244/19220880/5528fc32-8e55-11e6-86d5-fcd8c03a023f.png)

**Comment by abhi007tyagi** [comment]
Tested it on LG Nexus 5 (2013), v6.0.1
Not able to add any image from Gallery

![image](https://cloud.githubusercontent.com/assets/12875356/19221066/2fa6794a-8e59-11e6-9ca1-919a43f58f47.png)

**Comment by amitiwary999** [comment]
Are you testing on Emulator?

**Comment by jig08** [comment]
@rahulworld Your take pls.

**Comment by abhi007tyagi** [comment]
@amitiwary999 No, as I mentioned, I am testing it on my phone, LG Nexus 5 (2013 model), Android v6.0.1

**Comment by gogeta95** [comment]
its because of runtime permission in marshmallow and above.

**Comment by abhi007tyagi** [comment]
That needs to be handled then !!

But my studio alerts me while writing the code regarding the permission and it does not let me compile my code. It should have been handled in that case.

**Comment by rahulworld** [comment]
it works fine in my mobile (marshmall 6.0) but it gives massage when image not able to crop if there is any improvement i'll Check it.

**Comment by jig08** [comment]
@rahulworld make sure all cases are taken account into, assigning you this issue. Cheers !

**Comment by jig08** [comment]
@abhi007tyagi Thanks for pointing out this case 😃

**Comment by gogeta95** [comment]
@rahulworld whats the status of this issue?

**Comment by rahulworld** [comment]
@gogeta95  sorry for late working i had virus infection. i work on tommorow.

**Comment by rahulworld** [comment]
@gogeta95 handled this issue.
