### ISSUE TITLE
APKs in apk branch not updating

### ISSUE THREAD

**Issue by mamakancha** [fossasia/susi_android#1180]
**Actual Behaviour**

Ever since PR #1033 merge, the APKs in apk branch are not updating. 
ref All Circle CI merge builds after [this](https://circleci.com/gh/fossasia/susi_android/2262) build are failing.

**Expected Behaviour**

Currently, do not know the reason. But expected behaviour should obviously be that the APKs should update. 

**LogCat for the issue**
```
./exec/apk-gen.sh

apk    build.gradle  exec		gradlew      nohup.out
app    circle.yml    gradle		gradlew.bat  README.md
build  docs	     gradle.properties	LICENSE      settings.gradle
cp: cannot stat ‘/home/ubuntu/susi_android/app/build/outputs/apk/app-debug.apk’: No such file or directory

./exec/apk-gen.sh returned exit code 1
```

**Would you like to work on the issue?**
yes

**Comment by iamareebjamal** [comment]
@mamakancha Status?

**Comment by mamakancha** [comment]
Not working currently. If someone wants to take up this issue, go ahead.

**Comment by iamareebjamal** [comment]
@batbrain7 The apk upload is not working correctly. Please create a PR to fix this. You have to change the circle CI config again for this

Please handle this first

**Comment by batbrain7** [comment]
@iamareebjamal taking it up

**Comment by batbrain7** [comment]
@iamareebjamal there is output.json file in the apk branch could that be of any relevance?

**Comment by iamareebjamal** [comment]
No

**Comment by batbrain7** [comment]
@iamareebjamal could you please help me and assist me in what to edit in the .yml file

**Comment by iamareebjamal** [comment]
Only one of the scripts is running after the build. All three must run
