### ISSUE TITLE
Circle CI Build Failing

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#1181]
**Actual Behaviour**

Circle CI build is failing most of the time
```
java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
```

**Expected Behaviour**

Seems like the root view isn't getting focus as some other screen might be obstructing it. In short, the UI tests are failing and need to be fixed.

**Would you like to work on the issue?**
No. Comment if you want to work.

**Comment by arundhati24** [comment]
@chiragw15 I would like to work on this.

**Comment by batbrain7** [comment]
@arundhati24 if its alright with you, I would also like to proceed towards this issue

**Comment by arundhati24** [comment]
Yes sure @batbrain7  :)

**Comment by iamareebjamal** [comment]
How much of testing is done in UI tests? In my opinion, UI tests should be disabled for now. CircleCI environment is quite fragile and may sometimes kill the process even without UI tests. 

It is not fine to have failing tests for this long. This move will also shift focus towards writing more unit tests

**Comment by batbrain7** [comment]
@iamareebjamal I will send a PR for the sam i.e. disabling the UI tests

**Comment by iamareebjamal** [comment]
But before that, how much of tests are actually done in UI tests? I mean count

**Comment by batbrain7** [comment]
@iamareebjamal 
There are 4 tests for chatactivity
4 for forgotpasswordactivity
7 for loginactivity
4 for welcomeactivity
5 for signupactivity
1 for skillsactivity

so total  : 21
