### ISSUE TITLE
Unit test case - MainActivity view visibility

### ISSUE THREAD

**Issue by abhi007tyagi** [fossasia/susi_android#119]
Can I write test cases ?
I will use Espresso for writing unit test cases.
Will start from checking presence of UI views
then gradually add methods to test different UI and navigation and features of the app.

This way I will also learn writing test cases.

**Comment by gogeta95** [comment]
isn't this copy of #39 ?

**Comment by abhi007tyagi** [comment]
Can these be merged into one heading (if same) and remain open for all unit test case related PRs?

**Comment by the-dagger** [comment]
Yes we can continue this in #39.
I will close this for now.
