### ISSUE TITLE
Update dependencies in build.gradle

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1194]
**Actual Behaviour**

Currently, there are a number of outdated dependencies present in build.gradle. Also, the support libraries use different version specifications that might lead to runtime crashes.

**Expected Behaviour**

The outdated dependencies need to be updated and all support libraries should use the exact same version specification.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Please handle all updates as one PR
