### ISSUE TITLE
App Crashing when a user messages a link.

### ISSUE THREAD

**Issue by ShubhamKushwah** [fossasia/susi_android#1199]
**Actual Behaviour**
- The app is crashing whenever the user sends a link in the message.
- Showing nothing when a user types open <something>.

**Expected Behaviour**
Should open the link in-app/browser.

**Steps to reproduce it**
Create an intent to start when clicked on the link.

Intent can either:
- open the link in the in-app activity(may increase unwanted app-size).
- open the link in the default browser in the device.

**LogCat for the issue**
N/A

**Screenshots of the issue**
![ss_01_crash](https://user-images.githubusercontent.com/24874033/37536599-0dc239d6-2971-11e8-922a-805c4ca96ef1.png)

**Would you like to work on the issue?**
Yes

**Comment by ShubhamKushwah** [comment]
@chiragw15 Please review!

**Comment by batbrain7** [comment]
@ShubhamKushwah it works fine!

![screenshot_20180513-170346](https://user-images.githubusercontent.com/16780496/39966839-ecc5a66e-56cf-11e8-9d73-ee4b12a90352.png)

**Comment by batbrain7** [comment]
@chiragw15 @amitiwary999 @the-dagger please close this issue.
