### ISSUE TITLE
Two toast messages are shown when rating of a message switches

### ISSUE THREAD

**Issue by raj10071997** [fossasia/susi_android#1204]
**Actual Behaviour**

When we switch the rating of a message from thumbs down to thumbs up or thumbs up to thumbs down, the error toast message is shown twice instead of once.

**Expected Behaviour**
The error message should be shown only once.

**Steps to reproduce it**

Login in to chat activity, rate any of your message whether thumbs up or down. Now switch the rating.

**Would you like to work on the issue?**

Yes.

**Comment by batbrain7** [comment]
Not reproducible works fine
