### ISSUE TITLE
Removing Snackbar behaviour class

### ISSUE THREAD

**Issue by mamakancha** [fossasia/susi_android#1206]
**Actual Behaviour**

There is an extra class in the code which defined snackbar behavior. This class is no longer in use.

**Expected Behaviour**

Remove this class.

**Would you like to work on the issue?**
yes

**Comment by aniket-agarwal1999** [comment]
@mamakancha I think that the class should remain there only as in the future the developers may need to add a new feature to the app. SnackBar being such a common feature may be added in the near future in some part of the app.

**Comment by mamakancha** [comment]
@aniket-agarwal1999 This snackbar behavior class is very old and since then there have been many changes in the app so it's kind of useless rn. In future, if anyone wants to add a snackbar in the app the default behavior works fine and we don't specifically need a behavior class for it. That's my opinion. 
@chiragw15
