### ISSUE TITLE
Removing Android dependency from forgot password presenter

### ISSUE THREAD

**Issue by mamakancha** [fossasia/susi_android#1207]
**Actual Behaviour**

According to MVP pattern, the presenter must not have any android dependency as it makes it difficult to test the presenter later on separately.

Here we can see that there is a dependency of `android.color` in the Presenter.
https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordPresenter.kt#L3

**Expected Behaviour**

Remove this to follow proper MVP pattern.

**Would you like to work on the issue?**
yes

**Comment by iamareebjamal** [comment]
@arundhati24 @batbrain7 Take such small issues first

**Comment by anandkumarkparmar** [comment]
Hi @mamakancha @iamareebjamal, Can I take this issue?

**Comment by batbrain7** [comment]
@anandkumarkparmar okay go ahead

**Comment by anandkumarkparmar** [comment]
Hi @mamakancha / @batbrain7, Currently default branch is _development_. But there as I can see file 
https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordPresenter.kt#L3 does not contain code. And Last commit for this file is also says that this file is deleted. 

So, are these changes required? and if yes, which branch should I pick?

**Comment by batbrain7** [comment]
@anandkumarkparmar I will send a PR to delete that file

**Comment by batbrain7** [comment]
or make your own branch and a send a PR deleting the forgotpassword activity along with the package
