### ISSUE TITLE
Reset dialog box is not visible completely in landscape mode.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/susi_android#1209]
**Actual Behaviour**

When the orientation change to landscape mode, the reset dialog box is not visible completely.

**Expected Behaviour**

The dialog box should be visible completely or there should be a scrollview for scrolling down to view the complete dialog box. 

**Steps to reproduce it**

Open settings after logging in, now click on reset dialog in portrait mode. Now change the orientation to landscape the dialog box is not completely visible.

**Would you like to work on the issue?**

Yes.

**Comment by ShubhamKushwah** [comment]
@chiragw15 I would like to work on this.

**Comment by aniket-agarwal1999** [comment]
@ShubhamKushwah I think that @raj10071997 has already claimed this issue.

**Comment by batbrain7** [comment]
@raj10071997 I am taking this issue.
