### ISSUE TITLE
Unable to fetch dialog shows when the orientation changes to landscape mode in skills.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/susi_android#1210]
**Actual Behaviour**

When you scroll down in skills activity to view skills in landscape mode, Unable to fetch skill dialog is shown.

**Expected Behaviour**

The dialog should be shown on orientation changes.

**Steps to reproduce it**

See below gif to reproduce the effects.

**gif of the issue**

![1](https://user-images.githubusercontent.com/24502136/37604405-ec85547c-2bb6-11e8-9a1c-607f9f799ff3.gif)

**Would you like to work on the issue?**

Yes.

**Comment by aniket-agarwal1999** [comment]
@raj10071997 #1008 This is the same issue here also

**Comment by raj10071997** [comment]
Sorry I didn't see that. Are you still working on the issue?

**Comment by aniket-agarwal1999** [comment]
@raj10071997 Yes but I am quite stuck here, so I would be more than happy to have help from you :)

**Comment by raj10071997** [comment]
Sure..! :smiley:

**Comment by aniket-agarwal1999** [comment]
@raj10071997 Thanks :)

**Comment by ShubhamKushwah** [comment]
@raj10071997 Where are you stuck ask here, maybe I could help.

**Comment by raj10071997** [comment]
@ShubhamKushwah thanks for your help. May be you can help @aniket-agarwal1999 as he is trying to solve this issue.
