### ISSUE TITLE
Search Functionality in Skill List Fragment implemented improperly

### ISSUE THREAD

**Issue by mamakancha** [fossasia/susi_android#1211]
**Actual Behaviour**

Only first matching search is displayed rather than showing all the matching results. 

```
for (item2 in item.second.keys){
                if( query.toLowerCase() in item2){
                    skillGroups.scrollToPosition(pos)
                    return
                }
```
The above code snippet is currently in use for search a query. Firstly, complexity can be improved for efficient search and even the logic is not completely correct. This simply finds the given query in the name of the skill and scrolls to the first position it finds.

**Expected Behaviour**

To improve this, we can create a new list and find skills from the current list matching the given query and then we can transfer those skills to a new list and display that list instead of just showing the top element which matches the query.

**Would you like to work on the issue?**

Yes

**Comment by ShubhamKushwah** [comment]
@chiragw15 I can improve this by also considering the substrings as well, which will make the search a lot more efficient. Please assign this to me.

**Comment by mamakancha** [comment]
Hi. You may start working on this issue. I anyway won't be able to contribute.

**Comment by agh372** [comment]
@ShubhamKushwah Are you still working on this issue? If not, can I work on it ?
