### ISSUE TITLE
Add hint in the skill search section and remove the line under the query

### ISSUE THREAD

**Issue by mamakancha** [fossasia/susi_android#1212]
**Actual Behaviour**

The green line under the query is very redundant and also does not look good.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/19153609/37618537-92d0fec4-2bdc-11e8-8eef-009f78ae86f0.png)

**Would you like to work on this issue**
Yes

**Comment by ShubhamKushwah** [comment]
@chiragw15 I would like to work on this.

**Comment by mamakancha** [comment]
Please start working. I won't be contributing any further.

**Comment by arundhati24** [comment]
Already done.
