### ISSUE TITLE
SUSI.AI skills screen shows an error message

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1213]
**Actual Behaviour**

On SUSI.AI skills screen on scrolling down, the process automatically stops and a message is shown  : "Unable to fetch. Please try later"
**Expected Behaviour**

This should not happen if the skills are all displayed then should be present there instead of such an abrupt message.

**Steps to reproduce it**

Click on the SUSI button on the top of the chat and and then scroll down

**Screenshots of the issue**

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/16780496/37729297-9f817248-2d62-11e8-88db-f0add0231425.gif)

**Would you like to work on the issue?**

Yes.

**Comment by ShubhamKushwah** [comment]
How are you going to correct this, please elaborate!

**Comment by raj10071997** [comment]
@batbrain7 there are already issues opened regarding this problem . #1008 #1210

**Comment by batbrain7** [comment]
I didn't know @raj10071997 .
Closing this issue
