### ISSUE TITLE
Add a feature to Call users using SUSI.AI

### ISSUE THREAD

**Issue by mkmar01** [fossasia/susi_android#1214]
**Actual Behaviour**

Call making does not take place using SUSI.AI and "Internet connectivity problem" is displayed.

**Expected Behaviour**

Add a feature to call the respective user from the person's contacts.

**Steps to reproduce it**

Type or speak Call then any name.

**Screenshots of the issue**

![bb4a23a6-8ce8-481d-82ad-501d8044dbf7](https://user-images.githubusercontent.com/16780496/37730886-c641bfa6-2d66-11e8-8ee9-e2c62b0bd405.jpg)

**Would you like to work on the issue?**

Yes

**Comment by ShubhamKushwah** [comment]
I am working on it.

**Comment by batbrain7** [comment]
@ShubhamKushwah which issue are you pointing out to?

**Comment by ShubhamKushwah** [comment]
#1174 This one.

**Comment by batbrain7** [comment]
@ShubhamKushwah I think your issue is too big in itself so it might be better if different parts were implemented through each issue :)

**Comment by ShubhamKushwah** [comment]
Maybe :)

**Comment by DipanshKhandelwal** [comment]
@ShubhamKushwah Is it complete? Or are you still working on it?
