### ISSUE TITLE
No Dark theme like web

### ISSUE THREAD

**Issue by DipanshKhandelwal** [fossasia/susi_android#1216]
**Actual Behaviour**
Presently there is no dark theme for the Android app like the web has.

**Expected Behaviour**
Must have a dark theme

**Screenshots of the issue**
![dark](https://user-images.githubusercontent.com/24923974/38470957-fafd4290-3b87-11e8-8eba-cd9174b4ed5f.png)

**Would you like to work on the issue?**
Yes

**Comment by chiragw15** [comment]
@DipanshKhandelwal Where was this discussed? We do not want a dark theme for the app right now. Please work on more important issues.

**Comment by iamareebjamal** [comment]
@chiragw15 What should be done if the PR?

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 can I start working on it?

**Comment by iamareebjamal** [comment]
No, low priority
