### ISSUE TITLE
Add CardView for news in chat window.

### ISSUE THREAD

**Issue by pprathameshmore** [fossasia/susi_android#1223]
**Actual Behaviour**

When we request for News, it shows in just one news.

**Expected Behaviour**

We need to add "CardView" for news. So we can show multiple top headlines in just horizontal "RecyclerView"

**Screenshots of the issue**
![news_cardview](https://user-images.githubusercontent.com/17108186/39350366-979d3e38-4a1b-11e8-87e0-d2595c57f1ac.png)

**Would you like to work on the issue?**
I am still exploring and understanding code base. So this issue solve if anyone interested!

**Comment by codedsun** [comment]
@pprathameshmore I am taking this issue.

**Comment by pprathameshmore** [comment]
@codedsun Greate!

**Comment by batbrain7** [comment]
@codedsun you doing this?

**Comment by batbrain7** [comment]
@codedsun status ?

**Comment by codedsun** [comment]
When I hit news, on 'action' I m getting one response, while in 'data' array I m getting multiple news.Then tell me what shall be done for "news" as we are only showing the 'actions' array?

**Comment by batbrain7** [comment]
@codedsun this has been done, it was solved as part of the TableResponse handling
