### ISSUE TITLE
 Unused XML scheme declaration.

### ISSUE THREAD

**Issue by pprathameshmore** [fossasia/susi_android#1224]
**Actual Behaviour**

It is unused XML scheme declaration.

**Expected Behaviour**

We need to remove unused XML schemes declarations from code.
To style proper coding style.

**LogCat for the issue**

![error](https://user-images.githubusercontent.com/17108186/39403861-a9d2d17e-4ba3-11e8-9edd-9700353b916d.JPG)

**Screenshots of the issue**

![error](https://user-images.githubusercontent.com/17108186/39403882-efecac8e-4ba3-11e8-84d7-0328d04598e5.JPG)

**Would you like to work on the issue?**

I would like to work on this issue!
@mariobehling

**Comment by batbrain7** [comment]
@pprathameshmore are you working on this?

**Comment by iamareebjamal** [comment]
Very minor and irrelevant
