### ISSUE TITLE
On rotating the device in EmailVerification activity the process is killed

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1225]
**Actual Behaviour**

When we rotate the device in the email verification activity after clicking the reset password button, the progress bar vanishes.

**Expected Behaviour**

The progress bar should be present in the landscape mode also

**Steps to reproduce it**

Open the app, click on the forgot password, enter your email click on reset password and then rotate the device.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
How will you solve this?

**Comment by batbrain7** [comment]
Fixed in some other issue
