### ISSUE TITLE
Welcome cards not visible even when skip is not pressed

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1226]
**Actual Behaviour**
On opening the app when welcome cards are displayed, when the app is closed instantly without clicking skip on reopening the app the welcome cards are gone.

**Expected Behaviour**
Welcome cards should not be displayed only when the user presses skip.

**Steps to reproduce it**
Open the app, kill the app then reopen it.

**Would you like to work on the issue?**
Yes

**Comment by codedsun** [comment]
@batbrain CAan I work on the issue?

**Comment by batbrain7** [comment]
@codedsun I have already started working on it, I am busy with my exams but will send a PR by 11th May.

**Comment by codedsun** [comment]
@batbrain7 Thanks, no problem. Can u tag me some beginner issue of this project so that I can start contributions.
