### ISSUE TITLE
App allows to send a message even without the internet connection.

### ISSUE THREAD

**Issue by nikimullick** [fossasia/susi_android#123]
The user can send a message successfully even without an internet connection.This must not happen.It should show a retry option or an appropriate message that "the message is not sent" to avoid user to think that he is communicating even without internet.

**Comment by jig08** [comment]
@nikimullick Sounds like a must-have feature. Pls go ahead with the implementation ..

**Comment by nikimullick** [comment]
@jig08 Is it good? or shall I create retry button? Also, I'm  new to github. Could you please guide me as to how can I merge the change?A little help would be great :)
![screenshot_2016-10-10-15-55-48-361_org fossasia susi ai 1](https://cloud.githubusercontent.com/assets/20987692/19233482/5aa5e32e-8f03-11e6-8010-7ed2a4f07eec.png)

**Comment by jig08** [comment]
@nikimullick 

- Looks good !
- Show us a sample implementation or a mock-up with the `retry` button as well
- To merge your changes in the main repository: Fork the repo >> Push your changes to a new branch in a single commit referencing this issue using the naming pattern explained in README >> Open a Pull Request for the same.

Hope it helps, cheers !

**Comment by yasharmaster** [comment]
Isn't #123 same as #107 ?

**Comment by jig08** [comment]
@yasharmaster  
Relevant implementation details were missing from #107 , also the duplicity was missed.

@nikimullick Kindly post your suggestions & referIssue #107, closing this for now.
