### ISSUE TITLE
Write unit tests for Login feature

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1231]
**Actual Behaviour**

Currently, there are no unit tests for Login feature which includes the Login Contract (View and Presenter Interfaces) as well as the respective implementations as LoginActivity and LoginPresenter.

**Expected Behaviour**

There should be unit tests for Login feature so as to test it as an isolated component. This will help detect and fix flaws/bugs in this feature and will help us deal with regression in the long term.

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@arundhati24 I would like to add unit tests for the login?
I'll create separate issues for each test and will reference to this issue ?

**Comment by arundhati24** [comment]
@batbrain7 Yes sure. Please go ahead. :)

**Comment by arundhati24** [comment]
At present, this is not being worked upon. Hence, closing for now.
