### ISSUE TITLE
Write unit tests for Chat 

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1233]
**Actual Behaviour**

Currently, there are no unit tests for chat feature which includes the chat Contract (View and Presenter Interfaces) as well as the respective implementations as ChatActivity and ChatPresenter.

**Expected Behaviour**

There should be unit tests for Chat feature so as to test it as an isolated component. This will help detect and fix flaws/bugs in this feature and will help us deal with regression in the long term.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Generally, it's a good idea to create one parent issue and then keep adding child issues as you iterate on it. This keeps issue tracker free of similar placeholder issues

**Comment by arundhati24** [comment]
@iamareebjamal Sure. Will do the same.
