### ISSUE TITLE
Issue with the time stamp

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#125]
I think there is some issue with time stamp of messages . See the screenshot.

![whatsapp image 2016-10-10 at 12 14 38 pm](https://cloud.githubusercontent.com/assets/22056321/19228498/7a6762ac-8ee3-11e6-80d3-7341b1ddb755.jpeg)

**Comment by jig08** [comment]
@mayank408 Date change doesn't show up as in the case of WhatsApp ? Or is the time decreasing ?

**Comment by mayank408** [comment]
@jig08 The problem is that the time is in 12 hour format without showing am or pm.
Suggestions
1. Make the time format to be 24hr or include am or pm in the stamp.
2. Also show proper date and day for the particular messages of chat on a given day once like happens in whatsapp.

**Comment by gogeta95** [comment]
we should apply time stamp on messages according to system preferences (12/24 hr). we can use [`DateFormat.is24HourFormat()`](https://developer.android.com/reference/android/text/format/DateFormat.html#is24HourFormat(android.content.Context)) to determine system preference.

**Comment by mayank408** [comment]
@jig08 I will like to work on this..

**Comment by jig08** [comment]
@mayank408 yes pls.

**Comment by mayank408** [comment]
@jig08 Is it looking all right or any changes needed.

![whatsapp image 2016-10-10 at 7 00 06 pm](https://cloud.githubusercontent.com/assets/22056321/19237774/20a9c500-8f1c-11e6-8caf-f1990721dd0c.jpeg)

**Comment by the-dagger** [comment]
I think that we can do away with the date and display only the time.(with am/pm)
Adding date makes it a bit too cluttered.
@daminisatya @mariobehling Views?

**Comment by daminisatya** [comment]
@the-dagger agreed. Displaying time is enough. (Y)

**Comment by mayank408** [comment]
@daminisatya @the-dagger ok no problem , I will show time only.

**Comment by mayank408** [comment]
@jig08 @the-dagger @daminisatya how it would be to display date like this.


![whatsapp image 2016-10-10 at 7 49 54 pm](https://cloud.githubusercontent.com/assets/22056321/19239293/f51e08cc-8f22-11e6-939d-c1f8d0c98009.jpeg)

**Comment by the-dagger** [comment]
Looks awesome :+1:

**Comment by jig08** [comment]
@mayank408 Much better.
