### ISSUE TITLE
Connect smart speaker with SUSI Android App 

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1250]
As discussed in the meeting, we need to add the feature to connect smart speakers with our Android app using Wifi-direct. 
@batbrain7 @imjog We can discuss here.

**Comment by imjog** [comment]
Thank you @arundhati24 for creating the issue. Do you have any idea about where we are going to implement it, I mean in app where we are going to give the option to connect to the smart speaker? (from UI perspective) @batbrain7

**Comment by batbrain7** [comment]
@imjog I think we will make a separate section for Devices part as suggested by @mariobehling  just like in alexa app

**Comment by arundhati24** [comment]
sure @Akshat-Jain . 
@batbrain7 Could you please elaborate a bit on what do you mean by a separate section for Devices?

**Comment by batbrain7** [comment]
[https://arxiv.org/pdf/1609.02966.pdf](url) this is an important paper that may help in the connection of smart speaker with android device

**Comment by arundhati24** [comment]
@batbrain7 This link does not contain the resource. I get a 404 Not Found error on checking this link. Would you please look into it?

**Comment by iamareebjamal** [comment]
@arundhati24 I've updated the link

**Comment by arundhati24** [comment]
@iamareebjamal Thanks 👍
