### ISSUE TITLE
App crashes on scrolling through the Skills Activity

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1262]
**Actual Behaviour**

Currently, all the skills are not being displayed in the Skills Activity. Also, on scrolling through the skills, the app crashes.
 
**Expected Behaviour**

All the skills should be displayed and the app should not crash on scrolling.

**Steps to reproduce it**

1) Log into the app.
2) Open Skill Activity by tapping the Susi FAB on the chat activity.
3) Try scrolling through the skills

**LogCat for the issue**

![image](https://user-images.githubusercontent.com/30979369/40265976-3153a698-5b60-11e8-945a-bea80263b7ca.png)

![image](https://user-images.githubusercontent.com/30979369/40265983-4acd4aca-5b60-11e8-9e2a-a86fc909d9d5.png)

![image](https://user-images.githubusercontent.com/30979369/40265987-5e91ad8a-5b60-11e8-81ae-ce66aca41069.png)

![image](https://user-images.githubusercontent.com/30979369/40265988-75994eac-5b60-11e8-8f96-451254fae65b.png)

**Device used**
Xiaomi Redmi Note 4 (Android 7.0)

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@batbrain7 Would you please confirm this?

**Comment by batbrain7** [comment]
@arundhati24 yeah it is happening to me as well, but I would like to say there is an error in the string resource on the first line

**Comment by arundhati24** [comment]
@batbrain7 Thanks. I will fix this asap.
