### ISSUE TITLE
Display the 5-star ratings on the Skills page

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_android#1270]
**Actual Behaviour**
Currently, thumbs-up and thumbs-down rating is shown.

**Expected Behaviour**
It should display it according to this image - 
![screenshot from 2018-05-22 00-24-54](https://user-images.githubusercontent.com/12656846/40330075-676f834a-5d69-11e8-91a7-b0d96a81b79b.png)

Ref - https://developers.google.com/actions/distribute/directory

**Steps to reproduce it**
Open the skills page

**Would you like to work on the issue?**
Anyone is free to work on it.

**Comment by batbrain7** [comment]
@akshatnitd so we need a graph, a total ratings section and an average ratings section? also from where will this be fetched?

**Comment by AnupKumarPanwar** [comment]
@batbrain7 please refer to this PR https://github.com/fossasia/susi_server/pull/730

**Comment by agh372** [comment]
@batbrain7 @akshatnitd I would like to work on this issue.

**Comment by agh372** [comment]
@batbrain7 If you want to work on it, it's okay, I'll check for some other issue :)

**Comment by arundhati24** [comment]
@akshatnitd @batbrain7 @imjog @AnupKumarPanwar We also need to add a section where the user can actually provide this rating in our existing SkillDetailsFragment. This would be the rating (from the different users) that we would use to prepare and show the statistics mentioned in this issue. I would like to start with it. Please add your views.

**Comment by akshatnitd** [comment]
@arundhati24 Yes, we would eventually be working on he section, where user can provide his feedback as well as the ratings. As of now, we would like to replicate the above attached UI for **Ratings Summary** section. As, the APIs for providing the ratings/feedback are ready, we can further work on it under another issue and a separate PR can be sent for it.

**Comment by arundhati24** [comment]
Okay, so we have to remove the current rating and implement this one for now, right @akshatnitd ?

**Comment by akshatnitd** [comment]
Yes, for the skills section, the thumbs-up/down rating is to be replaced with the 5-star rating system.

**Comment by AnupKumarPanwar** [comment]
@arundhati24 I would like to work on its server side. Please let me know if you need some API for that.

**Comment by akshatnitd** [comment]
@arundhati24 The API for taking user input of ratings is already ready. Check this [link](https://github.com/fossasia/susi_server/pull/730).

The API for editing the rating added by user will be added by today. Ref - https://github.com/fossasia/susi_server/issues/741

**Comment by arundhati24** [comment]
Thanks @akshatnitd . I will recheck it once. And will also send a PR with the UI implementing the rating bar as well soon.
