### ISSUE TITLE
Remove search functionality from Settings

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1273]
**Actual Behaviour**

Currently, there is a search button provided in the action bar, which is non-functional i.e. it does not search anything in the Settings Activity.

**Expected Behaviour**

This search bar is not required in Settings. It serves no purpose here.

**Screenshot of the Settings Screen**

![settings_screen](https://user-images.githubusercontent.com/30979369/40361669-be6e85be-5de7-11e8-9e81-e4c008e4484d.jpg)

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@arundhati24 I think we need to add the functionality for the settings activity to display the item we search. :)

**Comment by arundhati24** [comment]
@batbrain7 generally none of the standard apps implement this. Search in case of Settings is only provided in the Settings app itself. Would you please have a look at some of the standard apps, including the Settings app, in your phone?. :)
