### ISSUE TITLE
Modify dialog messages to show standard messages

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1290]
**Actual Behaviour**

Currently, the messages shown in the dialog have grammatical errors.

**Expected Behaviour**

These messages should be grammatically correct and should be to the point to let the user know what message the dialog aims to convey.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 I want to work on that issue!

**Comment by arundhati24** [comment]
@codedsun Okay go ahead.

**Comment by arundhati24** [comment]
@codedsun As we need to release the new version of our app, I am fixing this for now.
