### ISSUE TITLE
Susi.ai voice is different from the Google Assistant's Voice It should be same

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1292]
**Actual Behaviour**

The SUSI.AI has voice different from that of the google assistant.

**Expected Behaviour**

It should be the same to provide the best experience to the user

**Steps to reproduce it**

Go to the chat activity and click on the voice and say something

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@batbrain7 Already opened :smile:
