### ISSUE TITLE
Modify Skills Listing Activity UI to make it more uniform 

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1294]
**Actual Behaviour**

Currently, the UI of the Skills Listing activity appears non-uniform. There is no proper criteria for the order of skills.

**Expected Behaviour**

The UI should be uniform and the Skills should be displayed according to top rating.

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
duplicate with #1467
