### ISSUE TITLE
Launch SUSI on F-Droid

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1302]
Currently susi is only on play store, we have to launch it on the F-Droid .

**Comment by batbrain7** [comment]
In the recent progress with the Fdroid issue I successfully generated the metadata file, passed all the lint tests and started the local build of fdroidserver with susi.ai added in it. Three errors were faced by me :  
![screen-shot-2018-06-19-at-9 48 59-am](https://user-images.githubusercontent.com/16780496/41736905-6ec048dc-75ab-11e8-9bd1-7bd27c7d45fd.png)

**Comment by batbrain7** [comment]
The first error is with the link preview library for which alternative can be easily found, second error is with the binary file that is put in the app so that the HotWordDetection can take place.

1. The first library can be easily found and replaced.
2. For the second and third file we need to find an alternative to provide hotword detection and replace these binary files or another approach would be download these files after the app is installed.

So as we can see above that build was successful but these errors came in way. So once these errors are fixed we can make a merge request to F-Droid

**Comment by batbrain7** [comment]
To check for Fdroid compatibility and to build the app using fdroid follow these blogs : 

1. [https://docs.google.com/document/d/1IRc4EILOb-LHXkErQCybSv2CIKKkzqC_-Sese0_i5C8/edit](https://docs.google.com/document/d/1IRc4EILOb-LHXkErQCybSv2CIKKkzqC_-Sese0_i5C8/edit)

2. [https://docs.google.com/document/d/1ItltxTNFFNgvMcN41yw176HwC7ena-pqtbwIIsgLP8g/edit](https://docs.google.com/document/d/1ItltxTNFFNgvMcN41yw176HwC7ena-pqtbwIIsgLP8g/edit)

3. [https://docs.google.com/document/d/1npSHMfZEY_ac3rOFKANPq_M7dizgA974wbNoaOOu6To/edit](https://docs.google.com/document/d/1npSHMfZEY_ac3rOFKANPq_M7dizgA974wbNoaOOu6To/edit)

**Comment by mariobehling** [comment]
> For the second and third file we need to find an alternative to provide hotword detection and replace these binary files or another approach would be download these files after the app is installed.

There are not many good options for the download. So, downloading after installation sounds good to me.

**Comment by iamareebjamal** [comment]
@batbrain7 I'm not sure if binary files can be downloaded after installation. Also, this may violate the terms of service of FDroid

Snowboy is open source, so look for how this can be integrated in the build process

**Comment by batbrain7** [comment]
1.  [https://gitlab.com/fdroid/fdroidserver/issues/504](Issue for the link preview library) since the library is open source, it should be accepted.
2. [https://forum.f-droid.org/t/androidapp-inclusion-stuck-shared-library-issue/3145](Link for the issue on fdroid-forum for the binary files)

**Comment by codedsun** [comment]
@batbrain7 @iamareebjamal These two ".so" files are created using SWIG. I tried finding out the C or C++ file that could build the .so files using NDK, but that also won't help as these shared object files will be again causing the issues. 
> What I would like to propose, is that downloading as suggested by @batbrain7 or we can go with pocketsphinx android that was used earlier (cmusphinx.github.io/wiki/tutorialandroid/)

**Comment by iamareebjamal** [comment]
How is downloading going to work? Please link to a documentation or article which provides more info into that. I may be wrong but I don't think it is possible to download and dynamically link the binary files like that

**Comment by batbrain7** [comment]
@iamareebjamal I did research it on the internet, I thought just like the obb package files we could download these files too, but I too don't think it is possible

**Comment by iamareebjamal** [comment]
Even that doesn't allow you to download what you want. It downloads stuff automatically, the resources, layouts and libs it needs

**Comment by codedsun** [comment]
@iamareebjamal One suggestion I recieved on the post is 

> The README you linked contains instructions how to build the native libraries. Put them into the build recipe.

Please guide me for the same, the instructions given are here: 
https://github.com/Kitt-AI/snowboy/blob/master/examples/Android/README.md

**Comment by codedsun** [comment]
@iamareebjamal I researched that it uses swig and compile all the native methods in two .so files, but the problem here is how can I include in the build process? so that it creates that files during the build and not before hand.

**Comment by iamareebjamal** [comment]
Can you do it in F-Droid build process and not the SUSI build?

I think they are referring to build recipe(F-Droid) and not the build process of SUSI because I don't know how that will change the matter.

In any way we can change the process is to maintain a fork of snowboy which is not recommended. Clarify please

**Comment by codedsun** [comment]
@iamareebjamal @batbrain7 

```
1 actionable task: 1 executed
INFO: Scanning source for common problems...
ERROR: Found usual suspect 'youtube.*android.*player.*api' at app/libs/YouTubeAndroidPlayerApi.jar
WARNING: Found JAR file at app/libs/YouTubeAndroidPlayerApi.jar
WARNING: Found possible binary at app/src/main/assets/snowboy/alexa_02092017.umdl
WARNING: Found possible binary at app/src/main/assets/snowboy/common.res
ERROR: Found shared library at app/src/main/jniLibs/arm64-v8a/libsnowboy-detect-android.so
ERROR: Found shared library at app/src/main/jniLibs/armeabi-v7a/libsnowboy-detect-android.so
INFO: Removing gradle-wrapper.jar at gradle/wrapper/gradle-wrapper.jar
ERROR: Could not build app ai.susi: Can't build due to 3 errors while scanning
INFO: Finished
INFO: 1 build failed
```

**Comment by iamareebjamal** [comment]
No, you should be building the play store variant and not a general build

**Comment by batbrain7** [comment]
The most recent problem that was faced is how to build a particular flavor in the fdroid build process, so I posted the issue on the forum : 
https://forum.f-droid.org/t/how-to-build-a-particular-app-flavor-on-fdroid/3346

**Comment by iamareebjamal** [comment]
Always share your metadata reference here with the build log

**Comment by batbrain7** [comment]
@iamareebjamal can I move down a version ?

**Comment by batbrain7** [comment]
```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/fdroidserver/1.0.9/libexec/bin/python3.7
  Reason: image not found
Abort trap: 6
```

on moving down to version 3.6.5 I get this error , @iamareebjamal unable to understand this

**Comment by iamareebjamal** [comment]
Your fdroid is linked to python 3.7

You have to reinstall it

**Comment by batbrain7** [comment]
how to build the app after uninstalling the brew one as the "fdroid build" command is not available now

**Comment by iamareebjamal** [comment]
Did you install using git?

**Comment by batbrain7** [comment]
I have forked the fdroid repository into my own and then cloned the forked repository

**Comment by iamareebjamal** [comment]
Yeah, so there is fdroid binary in it, you must not have added it in your path

**Comment by iamareebjamal** [comment]
@batbrain7 It's been 2 days. I am able to build SUSI on my PC since we last spoke. What's the issue?

**Comment by batbrain7** [comment]
@iamareebjamal since the PR you made now if I install the fdroidserver with brew does it work ?

**Comment by iamareebjamal** [comment]
PR is not merged yet and even if it was, brew doesn't update libraries that fast

Why are you not cloning the repo, it's literally much much easier. Ask @nikit19 if you have doubts

**Comment by batbrain7** [comment]
@iamareebjamal I have cloned the respo but I don't understand where to add it in the path

**Comment by nikit19** [comment]
@batbrain7 
I did the following to install the server
`git clone https://gitlab.com/fdroid/fdroidserver.git
`
`export PATH="$PATH:$PWD/fdroidserver"
`

credits: https://gitlab.com/fdroid/fdroiddata/blob/master/README.md#quickstart

**Comment by batbrain7** [comment]
this gives me error @nikit19 @iamareebjamal  : 
```
Traceback (most recent call last):
  File "/Users/mohitkumar/Documents/fdroidserver/fdroid", line 24, in <module>
    import fdroidserver.common
  File "/Users/mohitkumar/Documents/fdroidserver/fdroidserver/common.py", line 50, in <module>
    from pyasn1.codec.der import decoder, encoder
ModuleNotFoundError: No module named 'pyasn1'
```

**Comment by nikit19** [comment]
You have to install it

https://forum.f-droid.org/t/python-no-module-named-pyasn1-modules/2991/5

**Comment by iamareebjamal** [comment]
This is because you are using mac AFAIK

Are you using bash on it? If not, install it

https://gist.github.com/samnang/1759336

**Comment by iamareebjamal** [comment]
This is why it is requested to contributors to stay at same environment, the `declare` command is different in bash and macOS

The script won't run properly

**Comment by batbrain7** [comment]
after installing bash too, I get the same error , are the steps different after installing bash than usual?

**Comment by iamareebjamal** [comment]
bash is a shell, did you run the instructions through bash after installing it? This is basic requirements setup

**Comment by batbrain7** [comment]
@iamareebjamal even after running all the steps through the bash shell, still I get the same error

**Comment by iamareebjamal** [comment]
What did you do?

**Comment by iamareebjamal** [comment]
@batbrain7 This is taking too long, what should we do?

**Comment by batbrain7** [comment]
@iamareebjamal I installed bash on my machine :  
![screen shot 2018-07-31 at 12 41 39 am](https://user-images.githubusercontent.com/16780496/43418085-8c08e642-945a-11e8-81c8-abb11d6edfce.png)
here is how it looks after opening it, now on reinstalling the fdroid server i.e cloning the fdroidserver again and following all the steps with this I get the above error again, is this not the bash to be used ?

**Comment by iamareebjamal** [comment]
Please setup TeamViewer and share your credentials in private Gitter channel ASAP so I can take a look into the issue, have the fdroiddata and server directory open with a terminal as well

We should tackle this within this day

**Comment by batbrain7** [comment]
Okay

**Comment by batbrain7** [comment]
> @batbrain7
> I did the following to install the server
> git clone https://gitlab.com/fdroid/fdroidserver.git
> export PATH="$PATH:$PWD/fdroidserver"
> 
> credits: https://gitlab.com/fdroid/fdroiddata/blob/master/README.md#quickstart

@nikit19 @iamareebjamal I have cloned repo from the original fdroid repo and not mine the forked, how to send MR now ?

**Comment by iamareebjamal** [comment]
Change the remote to your forked version

```bash
git remote add fork https://gitlab.com/mohit/fdroiddata
git add metadata/ai.susi.yml
git commit -m "Add SUSI AI metadata"
git push fork master
```

**Comment by batbrain7** [comment]
@iamareebjamal fdroiddata or fdroidserver ?

**Comment by IzzySoft** [comment]
@batbrain7 @iamareebjamal fdroiddata. And there is an [open MR](https://gitlab.com/fdroid/fdroiddata/merge_requests/3519) hanging around for several months now waiting for an update from @batbrain7 (guess the notification got lost). Could you please check and update there? Thanks!

**Comment by iamareebjamal** [comment]
@batbrain7 Please finalize this ASAP. I was not aware that MR had not been merged

**Comment by iamareebjamal** [comment]
/remind me to check the status in 2 days

**Comment by iamareebjamal** [comment]
@liveHarshit Can please take this task up?

**Comment by liveHarshit** [comment]
> @liveHarshit Can please take this task up?

Sure.

**Comment by liveHarshit** [comment]
But I have not much idea about it. Can you please help what steps should I take?

**Comment by iamareebjamal** [comment]
Set up F-Droid on your computer and go through the setup instructions and the MR on gitlab https://gitlab.com/fdroid/fdroiddata/merge_requests/3519

Coordinate with me on gitter if you encounter any problems. I'd be happy to help

**Comment by liveHarshit** [comment]
> Coordinate with me on gitter if you encounter any problems. I'd be happy to help

Please coordinate.

**Comment by iamareebjamal** [comment]
@IzzySoft Have created a new MR

**Comment by liveHarshit** [comment]
> @IzzySoft Have created a new MR

https://gitlab.com/fdroid/fdroiddata/merge_requests/4459/

**Comment by IzzySoft** [comment]
Thanks @liveHarshit – I've already seen it and marked it for review (I'm no dev and have no dev environment, so I cannot verify if it builds etc). If the review approves it, it will be merged.

**Comment by liveHarshit** [comment]
MR is merged.

**Comment by IzzySoft** [comment]
So this can probably be closed then. Congrats!
