### ISSUE TITLE
add deep linking

### ISSUE THREAD

**Issue by iit2014086** [fossasia/susi_android#131]
if a user opens api.asksusi.com in mobile browser then we can open the susi app

**Comment by jig08** [comment]
Deep Linking sounds like a nice feature @iit2014086 .

**Comment by daminisatya** [comment]
@iit2014086  if I'm not wrong, you mean the app store?

**Comment by mariobehling** [comment]
It is too early to talk about and implemente this feature as we are not sure, how this is best used. Plese focus on other features first.

**Comment by jig08** [comment]
>@iit2014086 if I'm not wrong, you mean the app store?

@daminisatya It generally means if the app is already installed, the browser queries open in the app itself.
