### ISSUE TITLE
Fix lint warnings in XML

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1312]
**Actual Behaviour**

Currently, there are a number of warnings in XML files, like :
- Unused namespace declarations
- Use of 'dp' in place of 'sp' for text sizes
- Use of 'paddingEnd' along with 'paddingRight' etc. to better support right-to-left locale
- Padding/Margin symmetry
- Presence of hardcoded strings

**Expected Behaviour**

Removal of the above warnings for an improved code quality.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Parent #1311
