### ISSUE TITLE
Remove redundant constructs and imports

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1315]
**Actual Behaviour**

Currently, there are a number of redundant constructs are present in the code, some of which are mentioned below : 
- Explicitly given type which is redundant
- Redundant overrides
- Redundant semicolons
- Unnecessary local variables
- Unused imports

**Expected Behaviour**

All such redundant constructs should be removed as they increase the length of the codebase without serving any purpose and they often distract the user from understanding the code logic quickly.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Parent #1311
