### ISSUE TITLE
Adding swipe gesture to toggle betweem Chat Activity and Skills Activity

### ISSUE THREAD

**Issue by agh372** [fossasia/susi_android#1319]
**Actual Behaviour**

Currently, only on tapping Susi FAB, Skills activity page opens and on tapping back button, it takes us back to Chat Activity.

**Expected Behaviour**

We can add a left swipe gesture to take us to Skills Activity and right swipe gesture to take us back to Chat Activity. This feature is to improve the user experience. (This behavior can be found in Instagram app too, where a button as well as swipe gesture toggles between Feeds page and message page)

**Steps to reproduce it**

 Open the chats activity page

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@agh372 Before changing this, I suggest you to have an opinion of other members as well. @batbrain7 @chiragw15 @iamareebjamal  Please suggest if this is needed.

**Comment by batbrain7** [comment]
This will be a good addition to the app but I think there are more important issues to work on right now.

**Comment by agh372** [comment]
@batbrain7 @arundhati24 Fine 👍 will work on it later then.

**Comment by imjog** [comment]
I think it gives a very good user experience. As @agh372 mentioned, in Instagram, I personally like this feature. I was also thinking to implement in SUSI iOS. Also, It will not take much time as the method will be same as the back button.

**Comment by codedsun** [comment]
@batbrain7 @arundhati24 Can i take this issue?

**Comment by batbrain7** [comment]
@arundhati24 why was this issue closed ?

**Comment by imjog** [comment]
@batbrain7 Please refer discussion here: https://github.com/fossasia/susi_android/pull/1384
