### ISSUE TITLE
Implement accounting/login functionality

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#132]
The susi server already has accounting functionalities. Please implement account/login features and open relevant additional issues if needed.
* [ ] Add a Login Screen that allows user to Log In and Sign Up
* [ ] Handle the backend when the user logs in or signs up

**Comment by gogeta95** [comment]
I'd like to implement this, but where can I find the required docs for authentication APIs? @Orbiter @mariobehling

**Comment by mariobehling** [comment]
@gogeta95 Please have a look at the accounts apps at http://api.asksusi.com/apps/applist/index.html

* There is also an accounting blog post here: http://blog.loklak.net/under-the-hood-accounting-example/
* and about logins: http://blog.loklak.net/under-the-hood-public-key-login/
* the AAA system: http://blog.loklak.net/under-the-hood-authorization/

**Comment by gogeta95** [comment]
@mariobehling you can assign this to me will ask others if needed any help. one question, what about the login and sign up form UI?

**Comment by mariobehling** [comment]
@gogeta95 exactly, all these are implemented in the server already, but it should be possible to follow the whole process in the app as well. Please create sub-issues for different parts, if necessary. Thank you.

**Comment by mayank408** [comment]
@mariobehling @gogeta95 We can create a sub issue for handling frontend and backend . I am interested in doing the frontend (UI) of login/sign up of the app.

**Comment by the-dagger** [comment]
I have updated the initial issue to reflect the changes to be made both in the backend and frontend of the app.

**Comment by gogeta95** [comment]
so @mayank408 has the liberty of designing and implementing the UI, right? i'll get to work after UI is done.

**Comment by mayank408** [comment]
@gogeta95 U can make a dummy UI and can keep working further , later I will improve the UI. Suggestions??

**Comment by gogeta95** [comment]
Sure, we can workout the UI later.

**Comment by gogeta95** [comment]
I have done login, sign up and log out. do I need to implement forgot password and reset password too?

**Comment by the-dagger** [comment]
@gogeta95 Create sub issues for that and send individual PRs for each.

**Comment by gogeta95** [comment]
@mariobehling  also had to write a new test case with authentication system. please update the issue accordingly, thanks.

**Comment by gogeta95** [comment]
@mayank408  you can continue with the UI now.
