### ISSUE TITLE
Integrate chrome custom tabs for the links in the app

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1322]
**Actual Behaviour**

The user is directed to the phone's browser currently.

**Expected Behaviour**

Use chrome custom tabs to have the user not switch to the browser of the phone and display the web result in the app itself.

**Steps to reproduce it**

login into the app and click on any link in the chat activity or click on the links anywhere in the app.

**Would you like to work on the issue?**

Yes, but anyone is free to take it.

**Comment by codedsun** [comment]
@batbrain7 I am taking it!
