### ISSUE TITLE
Allow the user to search a skill from all the skills on the server

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1353]
**Actual Behaviour**

Currently, the user can search a skill only if it is present locally.

**Expected Behaviour**

After synchronising the data, allow the user to search a skill from the server rather than searching it locally.

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@batbrain7 @akshatnitd @AnupKumarPanwar We will need server side implementation as well. We need to discuss how this search would be implemented, how would we display the search results, say whether we will search by category or would search for every occurrence of the search item in picture. It wpuld be great if you could please add your views too. :)

**Comment by atm1504** [comment]
@iamareebjamal @mariobehling please close this. This feature has already been implemented.
