### ISSUE TITLE
Issue with back button

### ISSUE THREAD

**Issue by nikimullick** [fossasia/susi_android#136]
When back button is pressed on the splashscreen second or third time the activity doesn't finish,rather it starts. I think it should either have disabled back button on the splashscreen or the splashscreen activity needs to be finished on BACK pressed.

**Comment by the-dagger** [comment]
@nikimullick We plan to remove the splash screen altogether as it serves no meaningful purpose as of now.
Can you go ahead and do this?

**Comment by nikimullick** [comment]
As a suggestion,I would say,you could probably give a little intro about what susi does on the splashscreen. Don't you think removing it will make a user think-"What is this about? What does this chatbot supposed to do?"
Still if you say I can go ahead and remove splash screen.

**Comment by the-dagger** [comment]
No, I don't think so.
Later on we can have a user onboarding tutorial if possible.
Similar to what Hangout or Allo has.

**Comment by mayank408** [comment]
@the-dagger I already planned to remove splash screen in my next pull request.Shall i go ahead with it??

**Comment by jig08** [comment]
@the-dagger @mayank408 @nikimullick I guess we already had an issue for this case. Did we ?

**Comment by the-dagger** [comment]
Nope, there isn't an issue for this.
@mayank408 , @code-crusher is working on the same thing too, so its better to coordinate with him on this.

**Comment by mayank408** [comment]
@the-dagger ya sure

**Comment by nikimullick** [comment]
okay @the-dagger i'll remove splash screen

**Comment by jig08** [comment]
@nikimullick yes pls.

**Comment by mayank408** [comment]
@the-dagger We can close this as well as splash screen cannot be removed as of now.
