### ISSUE TITLE
Add a guide for naming conventions

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1368]
**Actual Behaviour**

Currently, there are a number of different styles for naming variables, IDs, methods, classes etc. throughout the project. Thus, there is a non-uniform coding style throughout the project.

**Expected Behaviour**

Add a guide with naming conventions to be used in this project, so that all new contributors can refer to it. Also, the modifications can be made to the existing code accordingly.

**Would you like to work on the issue?**

Yes

**Comment by Bhavnaharitsa** [comment]
@arundhati24 Are you still working on this ?

**Comment by batbrain7** [comment]
@Bhavnaharitsa go ahead

**Comment by mariobehling** [comment]
This is more general info and not needed in the Readme.
