### ISSUE TITLE
Skill Search

### ISSUE THREAD

**Issue by codedsun** [fossasia/susi_android#1371]
**Actual Behaviour**

Currently while on Skill Listing and searching it has a underline on the text and the the skill is searched only when the searched is clicked.

**Expected Behaviour**

It should be dynamic in nature, like the user types and the skill is searched.
Remove the underline from edit texr

**Steps to reproduce it**

Go to skill listing and then click on search in the toolbar and search a skill.

**LogCat for the issue**

None.

**Would you like to work on the issue?**

Yes

@arundhati24 @batbrain7

**Comment by arundhati24** [comment]
@codedsun 👍

**Comment by batbrain7** [comment]
@codedsun the line is already removed in a recent PR, and yes implement the dynamic search
