### ISSUE TITLE
Replace the pngs with vector drawables

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1381]
**Actual Behaviour**

Remove all the PNGs from the app to make drawables.

**Would you like to work on the issue?**

Yes

**Comment by NitinKumar26** [comment]
is this issue still in pending state?

**Comment by batbrain7** [comment]
yeah go ahead

**Comment by NitinKumar26** [comment]
working on this..

**Comment by yashk2000** [comment]
@batbrain7 can I work on this?

**Comment by immadisairaj** [comment]
@yashk2000
Are you still working on this??

**Comment by immadisairaj** [comment]
@yashk2000 
Are you still working on this??

**Comment by yashk2000** [comment]
@immadisairaj no. Go ahead if you want to work on it.

**Comment by immadisairaj** [comment]
@batbrain7 
The images intro_.png files after converting them into vector. The file is large as it has many colors in it. Due to the large file, the app is crashing.

I have made changes for the letter_s and baseline_star_rate
