### ISSUE TITLE
Skill Details to Skill Listing Swipe Feature

### ISSUE THREAD

**Issue by codedsun** [fossasia/susi_android#1385]
**Actual Behaviour**

There is no swipe feature available currently.

**Expected Behaviour**

There should be a feature to swipe right for navigation from skill detail to skill listing

**Steps to reproduce it**

1. Go to a skill
2. Enter the details.
3. No swipe right

**Would you like to work on the issue?**

Yes ! @batbrain7 @arundhati24 @imjog

**Comment by batbrain7** [comment]
@codedsun is this not similar to #1319

**Comment by codedsun** [comment]
@batbrain7 This is between skill listing and skill details. 1319 was different.
