### ISSUE TITLE
Improve the auth flow of the app

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1392]
**Actual Behaviour**

Currently, the app follows a non standard auth flow.

**Expected Behaviour**

Improve the auth flow to make it similar to Eventbrite, which has been mentioned as an example in the official Android developer [documentation](https://developers.google.com/identity/smartlock-passwords/android/overview).

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@akshatnitd @AnupKumarPanwar Is there an end point through which I can verify whether an email address has already been registered for SUSI or not?

**Comment by akshatnitd** [comment]
@arundhati24 The exact requirement that you are looking for, isn't yet implemented. An API for it can be created.

**Comment by arundhati24** [comment]
@akshatnitd Would you be able to do that? :)

**Comment by akshatnitd** [comment]
@arundhati24 Yes, opened an issue for it. Issue no fossasia/susi_server#826

**Comment by arundhati24** [comment]
Thanks @akshatnitd 👍

**Comment by arundhati24** [comment]
@imjog As we had discussed in the app walkthrough meetings about improvements in the auth flow, how are you planning to implement it in the iOS app? 
As we had seen the example of Eventbrite in one of our app walkthrough meetings, would you be able to modify the iOS app to follow a similar auth flow?
Also, we had a discussion about storing user credentials for a quicker login. I am planning to implement the smart lock feature in our app because that is a better and more secure way of handling user credentials in an Android app. How are you planning to implement it?
