### ISSUE TITLE
Send country name and country code in chat.json API

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_android#1394]
**Actual Behaviour**

Only latitude and longitude are send as API parameters.

**Expected Behaviour**

Country code and country name are also required to get country wise usage analytics.

**Steps to reproduce it**

Check `\susi_android\app\src\main\java\org\fossasia\susi\ai\chat\ChatPresenter.kt`

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

I think @batbrain7 and @arundhati24  can solve it.

**Comment by arundhati24** [comment]
@AnupKumarPanwar Okay I will do this 👍
