### ISSUE TITLE
Display average stars and total ratings on the Skills Home page

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_android#1401]
**Actual Behaviour**
Not present

**Expected Behaviour**
Display average stars and total ratings on the Skills cards on Home page.

**Screenshots of the issue**
![deepinscreenshot_select-area_20180615104800](https://user-images.githubusercontent.com/12656846/41451256-98a2ddd0-7089-11e8-9108-129f73c6a9ef.png)

**Would you like to work on the issue?**
Anyone can take this up.

**Comment by imjog** [comment]
@akshatnitd I don't think it would be good to add ratings here too. It is like focusing so much on ratings, the user doesn't want to see this everywhere. maybe it is good to keep on web app but not on Android and iOS. @batbrain7 @arundhati24 your view?

**Comment by batbrain7** [comment]
I agree with @imjog

**Comment by arundhati24** [comment]
@imjog @batbrain7 @akshatnitd I think it can be displayed on the skills card in iOS and Android clients as well. Alexa and Google have also displayed this rating on the skills card. The difference between the two is that Google shows a star followed by the average rating while the one that we have shown on the Skills CMS is similar to Alexa.
Also, we have to keep the UI consistent across different platforms, so keeping it on Skills CMS and not adding it to Android and iOS clients won't be a good idea. I think we can go ahead and add this.
I would like to add this to the existing skills card view.
Please add your views. :)

**Comment by akshatnitd** [comment]
Yes, I completely agree with @arundhati24. We can't really make the UI inconsistent across platforms.
I think, @arundhati24 can go ahead with it. Also @imjog , it would be great if you could please go ahead with the issue on iOS.


Note: This issue was opened after a discussion in the Analytics meeting.

**Comment by imjog** [comment]
@akshatnitd @arundhati24 Please understands that Web app and Mobile app have different guidelines, if we try to make our mobile apps looks like web app then it will look very odd and not good for UX of course. Also, I would like to say that we should stick to one of UI, Google or Alexa, not both. Mixing them is like not following guidelines at all. We can just show average rating as in google assistance, but I do not agree with showing full stars as in our web app. If everyone feels making it as the web app is good then I will send a PR. @batbrain7 @chashmeetsingh @iamareebjamal Your views?

**Comment by akshatnitd** [comment]
@mariobehling Also, we need your views.

**Comment by arundhati24** [comment]
@imjog IMHO we are not following any one particular app blindly. I believe every project or app has its own requirements. At the same time we need to follow industry standards. Hence, we refer to the standard apps, like Alexa and Google Home, available in the market for a better UI/UX. So, I think we cannot stick to one and copy it. We need to make modifications considering the requirements of our project as discussed with our mentors in the project meetings. Also, as mentioned by @akshatnitd, it had already been discussed in the analytics meeting, so maybe we can go ahead and add this.
