### ISSUE TITLE
Manage Hard Coded Strings in strings.xml

### ISSUE THREAD

**Issue by therajanmaurya** [fossasia/susi_android#141]
Everywhere, contributors are using hard coded strings because there is no rule to manage strings.ml. 
This issue for managing the strings resources  in strings.xml.

**Comment by FleetAdmiral** [comment]
I'd like to take this up!

**Comment by jig08** [comment]
@FleetAdmiral This has already been taken up, look for some other 😃

**Comment by FleetAdmiral** [comment]
@jig08 Didn't notice the assignee, sorry :/
