### ISSUE TITLE
User cannot choose the order in which the skills should be displayed

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1413]
**Actual Behaviour**

Currently, the user cannot decide the order in which the skills should be displayed in the skills listing activity, as done in Skills CMS.

**Expected Behaviour**

Allow the user to choose whether s/he wants to display skills in ascending/descending order of ratings or in the lexicographical order (A-Z or Z-A) as done on Skills CMS.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 Can I work on this issue?

**Comment by arundhati24** [comment]
@codedsun I have already fixed this. I have not sent the PR because the current API needs a modification i.e. the skill identifier is also needed inside the filteredData array. Hence, as soon as the modification is done and the PR gets merged, I will send the PR. So, this has already been fixed.

**Comment by batbrain7** [comment]
@arundhati24 I think this is done

**Comment by arundhati24** [comment]
No, this has not been done. I will do it after changing the UI flow. Because the UI flow would have new options added to the main screen. And, that would govern where to add this option. Hence, I had shown the skills in the order of top rating for time being. And, once #1467 is done, this will also be implemented.
