### ISSUE TITLE
To document the workflow of connection between Smart speaker and IOS/Android App

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_android#1419]
Actual Behaviour

No documentation present

Expected Behaviour

To add documentation

**Would you like to work on the issue?**
Anyone can be assigned this issue

**Comment by Bhavnaharitsa** [comment]
Is this still a valid issue ? @stealthanthrax 
May I work on this ? :)

**Comment by stealthanthrax** [comment]
I can only see a minimal documentation of the speaker and app workflow.
So, you may work on this issue.
