### ISSUE TITLE
Search query and messaging mismatch

### ISSUE THREAD

**Issue by piyush6348** [fossasia/susi_android#143]
While searching for messages, if we don't close the search view and start messaging then search view is
not closed automatically 
![screenshot_2016-10-11-17-53-30-752_org fossasia susi ai](https://cloud.githubusercontent.com/assets/16835832/19270347/1bbc337c-8fdd-11e6-8eb7-f22f8d66e923.png)

**Comment by amitiwary999** [comment]
@piyush6348 are you working on it? Otherwise I would like to work on this.

**Comment by piyush6348** [comment]
yes i'm @amitiwary999

**Comment by amitiwary999** [comment]
@piyush6348 you need help?

**Comment by amitiwary999** [comment]
@the-dagger I am sending PR for this.Can I?

**Comment by the-dagger** [comment]
Sure @amitiwary999
