### ISSUE TITLE
Possibility of NPE due to missing explicit null checks

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1441]
**Actual Behaviour**

Currently, the members of the stars object do not have a null check as they should never be null as expected. But Android Studio displays warnings like 'unsafe calls on a nullable receiver' though the values have already been declared as non-nullable.

**Expected Behaviour**

As per the warnings shown by Android Studio and more importantly to be on the safer side, there is a need to refactor the code to handle all possibilities for null values.

**Would you like to work on the issue?**

Yes

**Comment by atm1504** [comment]
@arundhati24 I tried to reproduce it in the skill details page but didn't find any such issues. The study of the codebase also reveals that we are already doing the null check of ratings before display.
