### ISSUE TITLE
User's feedback shown in usual order

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1453]
[Parent issue #1388 ]

**Actual Behaviour**

Currently, the user's feedback is shown in the usual order as per the time of feedback submission.

**Expected Behaviour**

Show the user's feedback on top if s/he is logged in.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 Can i work on this?

**Comment by arundhati24** [comment]
@codedsun Actually, I will be working on it next. I had been working on implementation of feedback system, but as you might be aware, we had a number of crashes in skills listing fragment due to which I had to put it on hold and work on changing the UI flow of the skills listing page. As that has been completed, I would now be resuming with a few enhancements that need to be added to the feedback system. As I have been following the changes done on Skills CMS, I feel I should complete this one. But, it would be very helpful if you could please have a look at #1513  and also if you could reopen your PR for #1530 . And, you can also take up #1351 .

**Comment by codedsun** [comment]
@arundhati24 Sure, Please repoen as I am not in susi-admin yet! 👍

**Comment by arundhati24** [comment]
@codedsun Actually your branch has been force pushed or recreated, hence it can't be reopened. You have the code changes locally. Please push the changes again.

**Comment by atm1504** [comment]
@mariobehling @iamareebjamal please close this. It has already been resolved this week.
