### ISSUE TITLE
The user cannot choose the order in which the skills are shown

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1458]
**Actual Behaviour**

Currently, the skills are seen in the descending order of top rated skills.

**Expected Behaviour**

Allow the user to choose the order in which s/he wants to see skills.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 What is likely to be done here? Can I take this up?

**Comment by arundhati24** [comment]
@codedsun It will be done along with #1467 on which I am already working and sending PRs. So, I will be doing this when existing PRs are merged and when other features that need to be added before are added.
