### ISSUE TITLE
Skills listing UI flow needs modifications

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1467]
**Actual Behaviour**

Currently, there are a number of API calls being made in the skills listing activity as a separate API call is being made for each group. Also, when it is refreshed, there are a number of API calls, due to which there are a number of issues including crashed.

**Expected Behaviour**

Modify the skills listing UI flow to make it similar to CMS so as to reduce the number of API calls.

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@arundhati24 we have to do this urgently as a stable version would not be available until then

**Comment by arundhati24** [comment]
Okay. I would be starting with it today itself then. Would put feedback on hold for sometime.

**Comment by batbrain7** [comment]
Thanks :)

**Comment by arundhati24** [comment]
This can be closed as all child issues have been completed.
