### ISSUE TITLE
Add an option in settings to disable STT

### ISSUE THREAD

**Issue by the-dagger** [fossasia/susi_android#147]
Right now, susi has an option to interact with it using voice alongside typing in the query.
We should make the Text to Speech optional so that the user can disable/enable it from the settings if he wants so.

**Comment by amitiwary999** [comment]
Can you explain it?I would like to work on this.

**Comment by piyush6348** [comment]
@the-dagger I'm also looking forward to work on this.

**Comment by the-dagger** [comment]
@amitiwary999 I meant making this button optional.
![screenshot_20161011-204828](https://cloud.githubusercontent.com/assets/6565270/19276679/c9e98938-8ff4-11e6-833b-bf795fdc0efc.png)

**Comment by amitiwary999** [comment]
I would like to work on this.

**Comment by the-dagger** [comment]
Sure.
@piyush6348 Meanwhile you can have a look at #146 , there were some problems in the PR which needed to be addressed regarding squashing the commit.

**Comment by mayank408** [comment]
@the-dagger Its already optional , you can type if u want or use speech to text . Just like other messaging apps.

**Comment by the-dagger** [comment]
@mayank408 Optional as in we want to allow the user to hide/show the mic button.

**Comment by replyashu** [comment]
taking this issue right away

**Comment by amitiwary999** [comment]
@replyashu Already solved

**Comment by mayank408** [comment]
@the-dagger Already solved. We can close this.
