### ISSUE TITLE
Crash on tapping examples on skill details screen

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1480]
**Actual Behaviour**

Currently, the app crashes sometimes on tapping examples on skill details screen due to null value for five star rating bar.

**Expected Behaviour**

The app should not crash.

**Logs**

![screenshot_2018-07-04-12-49-29-215_com miui bugreport](https://user-images.githubusercontent.com/30979369/42266809-0e620536-7f95-11e8-9d00-ab95365bb95a.png)

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@arundhati24 any progress on this ? we have to release the next version
