### ISSUE TITLE
App crashing on clicking on settings

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_android#1481]
**Actual Behaviour**

App crashes unexpectedly on clicking settings option

**Expected Behaviour**

To work without crashing (required to test with raspberry pi access point mode)

**Device Info**
Galaxy S7
Android v8.0.0

**Would you like to work on the issue?**

**Comment by codedsun** [comment]
@stealthanthrax I think this issue has been resolved and merged, kindly do pull the latest changes and then check, and if possible include the logcat.
