### ISSUE TITLE
Skills not loaded when a user has not set a language explicitly

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1485]
**Actual Behaviour**

Currently, if a user has not set a language explicitly from the settings at least once in out of the entire duration of app usage, the skills are not loaded because the response returned from the server contains default value which is not present in the client, where en is being considered as default language.

**Expected Behaviour**

Show skills in any case.

**Steps to reproduce**

Log into SUSI from an account for which you have never changed language from Settings. Then go to the skills listing page. You will not see the skills loaded. Only groups list can be seen.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 I have fixed this in language crash https://github.com/fossasia/susi_android/pull/1479
Is this still reproducible?
