### ISSUE TITLE
Replace multiple queries with query map

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1490]
**Actual Behaviour**

There are a number of query params being sent while making GET/POST requests to the server.

**Expected Behaviour**

Replace multiple query params in cases where there are more than three params, with query maps while making final reuqests and use objects at all other places.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
Can I work on this issue @arundhati24 ?

**Comment by arundhati24** [comment]
Solved in #1491
