### ISSUE TITLE
Soft keyboard get open automatically

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#15]
After opening app soft keyboard get open automatically

**Comment by nehagup** [comment]
i would like to take up this issue.

**Comment by amitiwary999** [comment]
I already started working on it

**Comment by vikiCoder** [comment]
Sorry, but I did solv and sent pull request...

**Comment by amitiwary999** [comment]
I also solved that issue but not able to send PR.It always show denied permission.

**Comment by daminisatya** [comment]
Please assign the issue. who ever wants to solve it. and then send the pull request. Inorder to avoid conflict of work. This would waste a lot of energy.

**Comment by daminisatya** [comment]
I dont see any assignees to this issue. so let's follow the best practice.

**Comment by daminisatya** [comment]
@vikiCoder Please resolve the comments which i have gave to your pull request. Thank you.
