### ISSUE TITLE
Add support for search results in susi.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#150]
here is a web search result in susi: http://api.asksusi.com/susi/chat.json?timezoneOffset=-120&q=search%20freedom

> it asks a yacy node for results. The result type is ‚rss‘. That means that you must look for the three entities as given in the columns list and render that as Title, snippet and link.
> It’s similar to a table result, but the result rendering does not come as matrix but as list.

**Comment by therajanmaurya** [comment]
I want to work in this issue.

**Comment by therajanmaurya** [comment]
@gogeta95 @Orbiter I just want to ask whenever we send a message to susi, If susi does not know the answer then we have to directly fetch websearch results and open full activity dialog to show web search result 
or
there is second way, whenever we send a message to susi and susi doesn't know then added message "@susi look the web search"(any message we wanna show) and as user click to the message then we will fetch the web search result and will show in dialog or activity etc.

What do you want.

**Comment by Orbiter** [comment]
no this is a misunderstanding. There is no requirement for an if-then-else decision. Just follow the issue text. I repeat: some queries to the back-end return table-like result sets in it's json. Try the url as given above. You will find the following actions:
```
"actions": [
      {
        "expression": "Here is a web search result for freedom",
        "type": "answer"
      },
      {
        "columns": [
          "title",
          "description",
          "link"
        ],
        "type": "rss"
      }
    ]
```
That means, the app has to perform with two result rendering:
- The first action is of type "answer". That means the app should simply print out the String given in "expression"
- the second action is of type "rss". That is a new answer type which must be shown as a set of three lines:
  * Headline (here, use the objects from key "title")
  * Description (here, use the objects from key "description")
  * Link (here, use the objects from key "link")
The Objects to be used for keys "title", "description" and "link" should be taken out of the answers.data object.

**Comment by Orbiter** [comment]
Just similar to a Siri web search result:
![siri_search_result](https://cloud.githubusercontent.com/assets/238730/19302958/eb005aa8-9066-11e6-835f-cd76b77cdd3a.jpg)

**Comment by therajanmaurya** [comment]
Thanks for great explanation. Now I understand everything. Let me implement some UI and back End logic to Susi web search result. So if the user will search by speaking something then he is able to get something awesome.

**Comment by gogeta95** [comment]
@therajanmaurya any progress?

**Comment by gogeta95** [comment]
@the-dagger, looks like there is no progress on this one, could you assign this to me?

**Comment by chiragw15** [comment]
Hi @gogeta95 , I was working on a similar issue (#338). You can also look at the idea discussed on that issue, if it helps. Also, If you are not working on this issue, can I take up this issue? Or if you are working on it, can I help ( If you need) ? Thanks :)

**Comment by gogeta95** [comment]
I have completed it, its similar to allo. but the UI is not final. we can work that out later on. see screenshot.
![image](https://cloud.githubusercontent.com/assets/8329096/20464961/d8ad5258-af78-11e6-93da-c7e519a1edd4.png)

**Comment by betterclever** [comment]
https://github.com/fossasia/susi_server/issues/100
