### ISSUE TITLE
No message displayed when there are no skills for a particular language

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1513]
**Actual Behaviour**

Currently, the skills listing activity turns blank and displays no message when there is no skill for a particular language.

**Expected Behaviour**

There should be a message to let the user know that there are no skills yet for the selected language.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 Can i take this up?

**Comment by arundhati24** [comment]
Okay @codedsun 👍

**Comment by codedsun** [comment]
@arundhati24 What I see, that this issue is already resolved and hence only the groups are fetched now and when clicking on any group, if no skills are found then it shows 'No Skill Found' . If there is something more to be done then please tell?

**Comment by arundhati24** [comment]
I think this has not been resolved. Please check it once. This issue was opened because when the  language is changed from the settings, if there are no skills for that language the screen displays no error message.

**Comment by codedsun** [comment]
@arundhati24 Checking and posting the update!

**Comment by Bhavnaharitsa** [comment]
@arundhati24 Can I take this up ?

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal @batbrain7 @arundhati24 I think the issue is solved. 
![Screenshot_20190401-141557_SUSIAI](https://user-images.githubusercontent.com/37215508/55315035-0a34dc80-5489-11e9-94ba-2e502c6542f8.jpg)


I have checked for different languages and different skills , if there's no skill then it shows " No skill found "
