### ISSUE TITLE
Add support for text to speech

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#152]
The goal is that "Susi" can talk. While it is possible to set up our own service, for the beginning it might be easiest to use Android's function to put out voice. Please propose and implement ways to output answers of Susi as speech.

**Comment by amitiwary999** [comment]
I would like to work on this(Will try my level best to implement this)

**Comment by mayank408** [comment]
@mariobehling @amitiwary999 I would also like to work on this .

**Comment by mariobehling** [comment]
@amitiwary999 @mayank408 Could you please see, if it is possible to separate the tasks of this issue and work together? Thank you.

**Comment by mayank408** [comment]
@mariobehling Do we want any button for speech or as soon as the response comes from server ,susi should start speaking at the same time and message should also be displayed on the screen.

**Comment by jig08** [comment]
@mayank408 Maybe include an option to enable/disable this is the app settings.
When enabled, SUSI should start speaking the message which is also simultaneously being displayed on the screen.

**Comment by mariobehling** [comment]
@mayank408 If user uses the speech feature, "Susi" should also reply as speech. If the user writes in the text field "Susi" should only reply as text.

**Comment by mayank408** [comment]
@mariobehling @jig08 @the-dagger 
I have a send pr for Text to speech . Please review the feature and suggest any changes require.

**Comment by Orbiter** [comment]
This is not working here. Do I need some TTS module?
