### ISSUE TITLE
Thumbs up or down cannot be changed

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_android#1526]
The feedback once given on an interaction should not be changeable, otherwise it will cause inconsistencies in the feedback logs that will be used for analysis.

**Would you like to work on the issue?**

No, anyone can assign the issue to himself/herself.

**Comment by batbrain7** [comment]
Also @AnupKumarPanwar what are the parameters to be passed in the feedback log api?

**Comment by AnupKumarPanwar** [comment]
Yes you need to call 2 APIs. The old one for submitted feedback and updating the metadata of the skill and the new one for creating the log which are only for analysis purpose. The log data is not publicly available.

**Comment by AnupKumarPanwar** [comment]
Endpoint :
/cms/feedbackLog.json

Parameters :

model
group
language
skill
feedback
user_query
susi_reply
country_name
country_code
device_type
