### ISSUE TITLE
Back-End Configuration and fail-over

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#155]
The susi api is currently hard-coded in https://github.com/fossasia/susi_android/blob/master/app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.java
We should have a system variable for this.

Furthermore, the access to the susi api should have a fail-over process. That means we should have the ability to declare a set of back-end addresses, not only one.

To do:
- declare a variable susi_service_count (default: 2)
- declare two variables:
 * susi_service_0 = api.asksusi.com
 * susi_service_1 = kaskelix.com:4000
- when the back-end service 0 is accessed but ends in a time-out, try service 1 and so on

**Comment by therajanmaurya** [comment]
There are two ways to do : the first one directly pass the Base URL to the  Client Service as Parameter "@URL" and base URL will change the new one. 

and the Second one is to initialize same retrofit object again with new Base URL and make retrofit calls as we are making same no need to change anything and no need to pass any extra argument etc. need to do things as we are doing.

**Comment by therajanmaurya** [comment]
Can I implement this?

**Comment by Orbiter** [comment]
I am not familiar with the retrofit framework, so I would left the decision to you.

I would also like to change the requirement a tiny bit:
- don't use the susi_service_count variable, instead
- declare an array susi_service = ["api.asksusi.com", "kaskelix.com:4000"].
There is anothe idea in the background: both values should be overwritable with a configuration service. I will open another issue for that as well.

**Comment by therajanmaurya** [comment]
What do you mean by configuration service, Is am right we can override these base URL from
server request.

**Comment by Orbiter** [comment]
just forget about the config service right now, I will specifiy that separately. Just consider that it's possible that the susi_service can be overwritten.

**Comment by therajanmaurya** [comment]
ok

**Comment by Orbiter** [comment]
👍
