### ISSUE TITLE
remote configuration for susi_service

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#156]
Every time the susi app starts up, it reads an internal configuration for the Susi back-end server location as defined in https://github.com/fossasia/susi_android/issues/155

This configuration should be overwritten with the values as given in
http://config.asksusi.com/config_susi.json

This should happen only one time when the susi App is started.

The purpose of this remote configuration is the ability to change the back-end scaling without the need to deploy new susi versions with new back-end configuration.

To do:
- read the JSON from http://config.asksusi.com/config_susi.json
- overwrite the susi_service array as created in https://github.com/fossasia/susi_android/issues/155 with the "susi_service" value from http://config.asksusi.com/config_susi.json

**Comment by iit2014086** [comment]
so create a static susi_service array in MainApplication class which gets it's data from config_susi.json.... is this the supposed thing to do??

**Comment by therajanmaurya** [comment]
I am working in this issue.

**Comment by therajanmaurya** [comment]
@Orbiter as you have been implementing login api, and we can fetch susi_services(http://config.asksusi.com/config_susi.json). Is we can login from any susi_services that we will fetch from http://config.asksusi.com/config_susi.json.

**Comment by Orbiter** [comment]
@therajanmaurya there is no relation to login, authentication or a login api. http://config.asksusi.com/config_susi.json is statically hosted. There is no access limit.
