### ISSUE TITLE
Examples section visible even when the examples list is empty

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1564]
**Actual Behaviour**

Currently, the example section is visible in the skills details screen even when the examples list received from the server is empty.

**Expected Behaviour**

If the examples list is empty, the examples section should be hidden.

**Screenshot of the issue**

![emptyexamples](https://user-images.githubusercontent.com/30979369/43000117-d3aa7256-8c3d-11e8-8da8-8e2e581e488c.png)

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 Can i work on this issue?

**Comment by arundhati24** [comment]
Yes sure. Go ahead @codedsun
