### ISSUE TITLE
Appropriate title should be visible on the action bar

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1567]
**Actual Behaviour**

The lablel on the group wise skills listing fragment is SUSI.AI skills.

**Expected Behaviour**

The group name should be displayed instead of SUSI.AI skills.

**Steps to reproduce it**

Open the skills listing fragment, click on any group at the bottom of the skills listing page. Check the title on the action bar.

**Screenshots of the issue**

![categoryskill](https://user-images.githubusercontent.com/30979369/43000714-4866bfe4-8c40-11e8-94f3-05e401584c5c.png)

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@arundhati24 previous two issues could be coupled into one as UI modifications in GroupWiseSkills

**Comment by arundhati24** [comment]
@batbrain7 that has already been merged. And this PR deals with changes in three fragments which are all associated with a single activity. So, I don't think there is any other issue with which I need to couple it with. I was told that I should make only one change per PR, hence I am following the same now. Also, please always mention the issue number. I don't know which issue are you referring to.

**Comment by batbrain7** [comment]
Okay if you want to work hastily go ahead :)

**Comment by arundhati24** [comment]
Thanks a lot :)
