### ISSUE TITLE
TimeStamp not shown in Messages with a Map.

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#157]
![screenshot_20161012-140728](https://cloud.githubusercontent.com/assets/16309034/19303366/0267c4aa-9086-11e6-81d5-14236f31a9c2.png)

**Comment by jig08** [comment]
@betterclever Yes, nice observation. Would you like to take this up ?

**Comment by betterclever** [comment]
Yes. 
I will address this along with #70 in my next PR.
