### ISSUE TITLE
Make call to SUSI server instead of getting data from github

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1574]
**Actual Behaviour**

Currently there are 3 API calls to github links to get the image of the skills.

**Expected Behaviour**

All the API calls should be made to the server.

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@AnupKumarPanwar @hkedia321 could you tell me about this API ?

**Comment by hkedia321** [comment]
@batbrain7 Please refer PR https://github.com/fossasia/susi_server/pull/1036. To get image for a public skill you can use the API: `https://api.susi.ai/cms/getImage.png?model=general&language=en&group=Food%20and%20Drink&image=images/cooking_guide.png`

**Comment by batbrain7** [comment]
@hkedia321 thanks !
