### ISSUE TITLE
Unused skill group adapter

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1575]
**Actual Behaviour**

The is an unused file called SkillGroupAdapter.kt present after modifications in skills listing UI flow.

**Expected Behaviour**

This file is no longer needed and can be removed now.

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
@arundhati24 I am still going to say the same thing if there is more things like these do them under one issue as they are all related to the same section rest is up to you.
