### ISSUE TITLE
Add an option for adding room for the devices

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1580]
**Feature**

There is no option to add room when we are making connection to the smart speaker. 
There should be an option to add room just like the google home app.

**Would you like to work on the issue?**

Yes

**Comment by atm1504** [comment]
@batbrain7 can you please tell me what is the aim of the issue, so that I can start working on it.

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 please close it. It has been solved
