### ISSUE TITLE
GroupWiseSkillsFragment not loaded on pressing back button

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1593]
**Actual Behaviour**

The GroupWiseSkillsFragment should be loaded when the user presses back button from the SkillDetailsFragments. (in case of group wise skills).

**Expected Behaviour**

The GroupWiseSkillsFragment should be loaded when the user presses back button. (in case of group wise skills).

**Steps to reproduce it**

Open the skills listing page. Scroll to the groups at the bottom. Click on a group. This will show all the skills belonging to a particular group. Click on any skills to load skills details. Now, press the back button. You will see the skills listing page and not the group wise skills list.

**Would you like to work on the issue?**

Yes

**Comment by NileshPranami** [comment]
@arundhati24 please review my PR
