### ISSUE TITLE
convert susiresponse pojo class to data class 

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1595]
**Actual Behaviour**

Currently the response class is a simple pojo but since we use kotlin it should be a data class.

Parent issue #1568 

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@batbrain7 Should #1568 not handle all of these files together? There is nothing unrelated in converting all these classes in the same package to data classes that a separate PR should be sent for each file.
