### ISSUE TITLE
Sound even though app is set to silent

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#1597]
Even though the volume on the phone is set to silent, the app puts out the sound. Expected is that the app respects the sound settings.

**Comment by iamareebjamal** [comment]
@mariobehling There's no control of an app developer on the device sound, if the volume settings are not consistent throughout apps, it might be a bug in the device ROM. Programmatically, an app cannot cause playback on different volume level than set on Android

**Comment by atm1504** [comment]
@iamareebjamal I think we can manually check for the silent state of the phone and if the phone is not set to silent then we can make the app make a sound. Should we do something like that or we can avoid this issue?

**Comment by iamareebjamal** [comment]
This was an invalid issue. Apps cannot make sound when media volume is 0
