### ISSUE TITLE
Copy, Delete, Forward, share option

### ISSUE THREAD

**Issue by nikhilbalyan** [fossasia/susi_android#16]
After selecting the Text Copy, Delete, Forward, share option should pop up in the status bar.

**Comment by jig08** [comment]
@nikhilbalyan Would you like to take up this issue ?

**Comment by nikhilbalyan** [comment]
Yes.

**Comment by addiittya2006** [comment]
@nikhilbalyan are we talking about selecting messages here or Results from Susi?

**Comment by amitiwary999** [comment]
@nikhilbalyan have you started working on it?

**Comment by nikhilbalyan** [comment]
@amitiwary999 i am working on it and am trying to implement it via contextual action bar. But I am facing issuse with RecyclerView. I will highly appreciate if you can help me out in implementing it.

**Comment by nikhilbalyan** [comment]
@addiittya2006 i am trying to delete the messages from application.

**Comment by mayank408** [comment]
@daminisatya I would like to work on this issue please assign me..

**Comment by amitiwary999** [comment]
@mayank408 @nikhilbalyan is trying to solve this issue.Asked him if he want to work with you on this issue.

**Comment by mayank408** [comment]
@nikhilbalyan could you please tell me how much work has been on the issue done so that i can help as well if u want to work with me..

**Comment by nikhilbalyan** [comment]
@mayank408 i am facing the same issue as i have mentioned above while integrating CAB with RecyclerView.

**Comment by nikhilbalyan** [comment]
@mayank408 you may take this issue i tried my best but i wasn't able to make it happening. In the onbindview method of chatfeedrecycleradapter class i was obtaining the position of the item clicked but after working around a lot i am stucked now with a lot of git merge conflicts. plz @jig08 assign this to @mayank408. And i am really really sorry for not being able to resolve this issue.

**Comment by jig08** [comment]
@nikhilbalyan No worries, at least you tried 😃 
Help resolving other issues or suggest new features.

@mayank408 You can go ahead with this.

**Comment by mayank408** [comment]
@jig08 ya sure

**Comment by nikhilbalyan** [comment]
thanx @jig08 looking forward to give my best :+1:

**Comment by mayank408** [comment]
@jig08 @the-dagger @mariobehling @daminisatya 

Is it looking fine or any improvement needed. As of now I dont think there is any requirement for forward and sharing option so I have not implemented that. 
The dialog message gets opened on longclick on messages.


![whatsapp image 2016-10-11 at 7 34 17 pm 1](https://cloud.githubusercontent.com/assets/22056321/19273475/47a5c16c-8fea-11e6-8424-48d69f03a989.jpeg)
![whatsapp image 2016-10-11 at 7 34 17 pm](https://cloud.githubusercontent.com/assets/22056321/19273476/48463be2-8fea-11e6-8fba-954af3665c2b.jpeg)

**Comment by the-dagger** [comment]
Looks good :+1:
Just a suggestion, can you also replace the toast messages with a Snackbar?
Since we are moving to a material design, it only makes sense to use the new material widgets as well.

**Comment by mayank408** [comment]
@the-dagger ok sure 👍

**Comment by addiittya2006** [comment]
@mayank408, Also The Color Yellow for the Date Stamp must be changed to suit better with the App. Maybe a lighter than Primary Shade.

**Comment by mayank408** [comment]
@addiittya2006 ok I will change it in next pr.

**Comment by jig08** [comment]
@mayank408 Yep, currently `copy` and `delete` seems just fine.
- As mentioned, change `toast` to `snackbar`
- Change the date color to a slightly lighter shade

Make the above changes in the same PR, in a single commit using the required naming format. Cheers !

**Comment by mayank408** [comment]
@jig08 @the-dagger @addiittya2006 
Is it fine now...


![whatsapp image 2016-10-11 at 8 49 04 pm](https://cloud.githubusercontent.com/assets/22056321/19276526/465e8c76-8ff4-11e6-9b00-55bb1408858b.jpeg)

**Comment by gogeta95** [comment]
@mayank408 use coordinator layout. snackbar should lift the layout up instead of covering it.

**Comment by the-dagger** [comment]
Agreed :+1:

**Comment by mayank408** [comment]
@gogeta95 @the-dagger 

![whatsapp image 2016-10-11 at 9 08 03 pm](https://cloud.githubusercontent.com/assets/22056321/19277386/220d8c3e-8ff7-11e6-81c3-d69032fa6f6e.jpeg)

**Comment by gogeta95** [comment]
yes.. all snackbars should lift UI up.

**Comment by mayank408** [comment]
@the-dagger @gogeta95 I am facing problem in lifting up the layout when snackbar is opened . I am using coordinate layout but its only lifting the floating action button not the whole layout. Could anyone suggest the solution or someone else would like to work on it.

**Comment by betterclever** [comment]
@mayank408 You might wish to read this. 
http://alisonhuang-blog.logdown.com/posts/290009-design-support-library-coordinator-layout-and-behavior.
I tried this earlier while using the "Internet Connection unavailable" Snackbar, but was not able to achieve that. You may try following.

**Comment by mayank408** [comment]
@the-dagger We can close this issue , as it is already fixed in issue #203 .

**Comment by mariobehling** [comment]
Good job!
