### ISSUE TITLE
Lifting up the UI on opening of snackbar.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#160]
![whatsapp image 2016-10-11 at 8 49 04 pm](https://cloud.githubusercontent.com/assets/22056321/19306897/6d87b646-9095-11e6-8174-c932412f47e2.jpeg)

**Comment by rajdeep1008** [comment]
I would like to work on this issue if no one else is already working on this.

**Comment by jig08** [comment]
@rajdeep1008 Assigned you the issue, pls go ahead.

**Comment by mejariamol** [comment]
I fixed the issue. Please guide me how to make Pull Request. I am new at this.

![device-2016-10-17-211817](https://cloud.githubusercontent.com/assets/13533840/19445603/d54f9aca-9449-11e6-9275-5203600c4b7b.gif)
