### ISSUE TITLE
Convert files in other package to data classes

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1628]
**Actual Behaviour**

In the other package of the responses, the classes are present as simple response classes.

**Expected Behaviour**

convert these classes to data classes

**Would you like to work on the issue?**

Yes

**Comment by starlord1311** [comment]
@batbrain7 can i work on this issue?

**Comment by arundhati24** [comment]
This has already been fixed in #1649 , hence closing this issue.
