### ISSUE TITLE
Old screenshots in README.md

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1630]
**Actual Behaviour**

There are old screenshots in README.md.

**Expected Behaviour**

Replace the old screenshots with the new ones showing current UI.

**Would you like to work on the issue?**

Yes

**Comment by starlord1311** [comment]
@arundhati24 can itake up this issue?

**Comment by arundhati24** [comment]
@starlord1311 I will be fixing this later after adding some more enhancements to the UI.
