### ISSUE TITLE
Use circular image view for skill image in group wise skills card

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1633]
**Actual Behaviour**

Currently, original images are displayed in the group wise skills card.

**Expected Behaviour**

Display all images in a circular image view.

**Would you like to work on the issue?**

Yes

**Comment by starlord1311** [comment]
@arundhati24 can i take up this issue?

**Comment by arundhati24** [comment]
@starlord1311 I will be working on this. Please have a look at some other issues or may be try testing the app and look for more issues that need to be worked upon.
