### ISSUE TITLE
Really bad practices in DeviceConnectFragment

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#1635]
I don't know if I was sleeping during the merge of the PR related to this fragment, but really sorry to let it be merged

@batbrain7 The code looks in the fragment looks like someone was playing with it locally and just pushed the changes and got it merged. Please send a PR to fix these issues ASAP

## Single letter variables

Let's keep `a=2,b=3` to the college assignments

```Kotlin
private var b = false
```

What's b? 

```kotlin
val b = dialogBuilder.create()
b.show()
```

```kotlin
val wi = mainWifi.connectionInfo
```

**Comment by batbrain7** [comment]
I'll work on this
