### ISSUE TITLE
App crashes if user doesn't allow any of the permissions

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/susi_android#1650]
**Actual Behaviour**

If user is not allowing any of the three permissions - location, voice and storage, app crashes on opening it again.

**Expected Behaviour**

User must allow all the permission at start.

**Steps to reproduce it**
If the user is not allowing the permission then alert the user why these permissions are necessary and you must allow them or need to add some condition where the process is happening.

**LogCat for the issue**

`java.lang.RuntimeException: Unable to start activity ConnponentInfo{conn.google.android.packageinstaller/ com.android.packageinstaller.permission.ui.GrantP ermissionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean`

**Would you like to work on the issue?**

Yes, I want to work on this issue.

**Comment by hrprt96** [comment]
Yes, I want to work on this issue.

**Comment by codedsun** [comment]
@liveHarshit Please check once again as this issue is not reproducible on my device and pull the latest changes from the dev branch and try the above steps again.

**Comment by liveHarshit** [comment]
@codedsun Yes, when I pull the latest changes, the issue is not anymore.
