### ISSUE TITLE
repeated code

### ISSUE THREAD

**Issue by iit2014086** [fossasia/susi_android#167]
in chatFeedRecyclerAdapter the same OnLongClick method is implemented repeatedly...there will be many different types of holders and need to be implemented many times...so instead make the Recycleradapter implement OnLongClickListener and for every chatMessageview set onlongclicklistener as class itself instead of creating new listener.

**Comment by piyush6348** [comment]
I would like to work on this issue if someone hasn't started yet.

**Comment by piyush6348** [comment]
I would like to work on this issue if some-one hasn't started yet.

**Comment by iit2014086** [comment]
@piyush6348  i think no one is working on this....you can proceed

**Comment by mayank408** [comment]
@the-dagger We can close this issue.
