### ISSUE TITLE
Improve UI of the Login screen

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1671]
**Actual Behaviour**

There are different types of fonts used for same context, spacing issues and so on, that need to be fixed.

**Expected Behaviour**

Improve the UI of the login screen and use the same color scheme as for the entire project.

**Would you like to work on the issue?**

Yes

**Comment by aleronarjun** [comment]
Hello @arundhati24 , I would like to work on this issue if its still open.

**Comment by arundhati24** [comment]
@aleronarjun Yes sure, please go ahead. But, please note that we don't need any major color changes etc. All we need is to use similar fonts and colors that have been used throughout the app.

**Comment by aleronarjun** [comment]
@arundhati24 yes, of course. Should I intimidate you here before creating a PR? I could post a screenshot maybe of the final login screen? Thanks.

**Comment by arundhati24** [comment]
You can go ahead and send a PR and yes of course add screenshots before and after the changes. I will add my reviews and suggestions there.

**Comment by iamareebjamal** [comment]
You definitely look intimidating @aleronarjun

**Comment by mariobehling** [comment]
The only change we need at the moment is to change the colors to reflect the same colors after login. Apart from that please keep the different areas similar to Facebook. 

![tumblr_nxuh7v6auj1ul8y65o1_1280-1](https://user-images.githubusercontent.com/1583873/45915768-34af3880-be5b-11e8-8946-93b828ce687b.png)

**Comment by mani87** [comment]
@arundhati24 @iamareebjamal @mariobehling  i want to work on this issue if its till open. Can i?
Thanks. :)

**Comment by aleronarjun** [comment]
@mani87 PR already exists for this issue.

**Comment by mani87** [comment]
It's been 20+ days since no commit on this issue thats why i asked. Can i work on this issue of no one is working on the same?
@aleronarjun

**Comment by aleronarjun** [comment]
@mani87 Hi. Last commit was about a week ago on the PR. All necessary changes were made, waiting for someone to finalise the review on that. Thanks.

**Comment by aleronarjun** [comment]
@iamareebjamal Please review the PR for this issue. I have addressed all changes you requested.
