### ISSUE TITLE
Improve the skill details view for landscape orientation

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1673]
There is a need to check the UI of the skill details screen on changing the screen orientation.

**Screenshots of the issue**

![img_20180819_123004_970](https://user-images.githubusercontent.com/30979369/44306448-a1429d80-a3ac-11e8-9d2d-c8c8fbc92409.jpg)

![img_20180819_122924_104](https://user-images.githubusercontent.com/30979369/44306450-a869ab80-a3ac-11e8-9f1f-e82ca94e345e.jpg)

**Would you like to work on the issue?**

Yes

**Comment by aleronarjun** [comment]
@arundhati24 I would like to solve this issue, if it is still open. Thanks.

**Comment by arundhati24** [comment]
@aleronarjun Yes sure, please go ahead.
