### ISSUE TITLE
Improve the UI of the Settings fragment

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1674]
Settings has a very different color scheme and font. There is a need to improve the UI of settings screen.

**Would you like to work on the issue?**

Yes

**Comment by hrprt96** [comment]
Hi @arundhati24 , I would like to work on this. Can I take it up?

**Comment by arundhati24** [comment]
Okay @hrprt96 , go ahead.

**Comment by mani87** [comment]
Hello @arundhati24 , I would like to work on this issue. Since its been long and there's not PR from anyone. So can i take this up?

**Comment by Bhavnaharitsa** [comment]
May I work on this ?

**Comment by arundhati24** [comment]
@Bhavnaharitsa Yes please go ahead. 👍

**Comment by Bhavnaharitsa** [comment]
@arundhati24 The settings seems quite matching with other activities . Could you pleas tell me what are the expected modifications ? :)

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 I am taking up this issue.
