### ISSUE TITLE
Accent color.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#169]
we need to decide an accent color for the app. currently its white and causing UI problems with Login functionality.
see below:
![image](https://cloud.githubusercontent.com/assets/8329096/19321743/d52568f0-90d3-11e6-84a5-0aac6b95c3e5.png)

please decide the accent color and I'll include it in #132 to resolve UI problems. thanks

**Comment by piyush6348** [comment]
how about this #5C6BC0- it might go with the theme of the app

**Comment by mayank408** [comment]
@the-dagger UI already updated. So we can close this.
