### ISSUE TITLE
App's Language Select not Changing app's default language

### ISSUE THREAD

**Issue by muarachmann** [fossasia/susi_android#1699]
**Language not being read from string files dynamically**
When you go to settings and click on Language tab, it prompts you the various languages. Upon selection of one, it opens the skills activity but not still in the language selected 

**Expected Behaviour**
I know this might take quite some time to implement. The app is to display the basic apps laguages in the selected language from the tab setting like setting - parametres , about - apropos (in french). Similar stuff should be done for other languages. From what i see, the string.xml files are quite explicit. using these will be great

**Steps to reproduce it**
Go to settings > Language
Select a language

![img_20180919_015059_071](https://user-images.githubusercontent.com/16350814/45724641-21fbe180-bb85-11e8-9a0f-7b2287f4879b.jpg)
Here language is in french but app still shows default language (englsih)

![screenshot_20180919-014926](https://user-images.githubusercontent.com/16350814/45724690-5a9bbb00-bb85-11e8-8359-0dbc081532e1.png)
same here

**Would you like to work on the issue?**
Yes i would like to work on this

**Comment by atm1504** [comment]
Please close it.
