### ISSUE TITLE
"Devices" in Settings doesn't respond

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_android#1700]
**Actual Behaviour**

I tab to "Devices" in Settings, but nothing shows up.

**Expected Behaviour**

Something open (not sure what is it, because it doesn't appear yet).

**Steps to reproduce it**

Grab the APK here: https://github.com/fossasia/susi_android/commit/2e2d6c4506d83918f1b359c4c3be84808d951221 (Released on 19 Sept).

Go to Settings > Devices, tap to "No connected device".

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2018-09-20-10-18-50-590_ai susi](https://user-images.githubusercontent.com/314607/45794379-97200180-bcc0-11e8-9165-7dd53e66b33c.png)

**Would you like to work on the issue?**

No

**Comment by immadisairaj** [comment]
@batbrain7 @iamareebjamal 
Is there any action required for the click?
