### ISSUE TITLE
Add signin / signup option in the menu 

### ISSUE THREAD

**Issue by Princejhabak** [fossasia/susi_android#1703]
**Actual Behaviour**

User is not able to sign in / sign up later if he skips the sign in /sign up process when the app starts for the first time

**Expected Behaviour**

User must be able to sign in / sign up anytime he wants

**Steps to reproduce it**

Option for sign in / sign up can be added to  the menu  which will take the user to sign in page

**Would you like to work on the issue?**

Yes , I would like to work on this issue

**Comment by atm1504** [comment]
@arundhati24 @batbrain7 @iamareebjamal as there is no response in this issue for a long time, can I take this issue?

**Comment by iamareebjamal** [comment]
Go ahead
