### ISSUE TITLE
App crashes on selecting different categories from 'Categories' section

### ISSUE THREAD

**Issue by shikhart98** [fossasia/susi_android#1705]
**Actual Behaviour**

App crashes on selecting different categories from 'Categories' section

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

1. Click on the SUSI logo after login. 
2. Go to Categories section and open any category.
3. Selecting anything from the list will crash the application

**LogCat for the issue**

**Would you like to work on the issue?**

Yes

**Comment by immadisairaj** [comment]
I am not able to reproduce this issue
@batbrain7 .?

**Comment by immadisairaj** [comment]
@iamareebjamal 
I am not able to reproduce this issue
