### ISSUE TITLE
Improve UI of VoiceInput Fragment

### ISSUE THREAD

**Issue by kartik-karz** [fossasia/susi_android#1715]
**Actual Behaviour**

Looks quite bland and feels detached.
**Screenshots of the issue**

![voice fragment](https://user-images.githubusercontent.com/21131443/46146319-147ae180-c280-11e8-9488-0d8fb25b0fd6.jpg)]
**Would you like to work on the issue?**

Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 can I work in this issue?

**Comment by kartik-karz** [comment]
Oh! I had assumed that this was merged already! Thanks, @atm1504  I would have forgotten about it altogether...  I think there are just some conflicting files which I'll look at it today sorry you might have to look at another issue

**Comment by atm1504** [comment]
@iamareebjamal please close it, the ui has changed a lot now.
