### ISSUE TITLE
map invocation shows blank card view

### ISSUE THREAD

**Issue by kartik-karz** [fossasia/susi_android#1718]
**Actual Behaviour**

Shows blank card view if we call anything which requires maps
eg. where is India

**Expected Behaviour**

Should show the map properly instead

**Steps to reproduce it**

Ask susi
Where is Singapore

**Screenshots of the issue**
![map_error](https://user-images.githubusercontent.com/21131443/46256110-e8e83900-c4c3-11e8-8c71-29a01d7e0cd8.png)

**Would you like to work on the issue?**
Yes

**Comment by kartik-karz** [comment]
@iamareebjamal @arundhati24 The mapview fails due to the openstreetmaps checking the header which is included with the picasso request and it returns a default image if it concludes that it's a robot (here picasso) which is displayed sometimes 
![2018-10-03 22-53-08 screenshot](https://user-images.githubusercontent.com/21131443/46427552-59f74d00-c75f-11e8-985d-c468599b10d1.jpg)

The best way to solve this would be to use the openstreet api to get a static map (cap at 15000 req per month) though it seems enough now it might be costly if the app widely adopted what are your opinions? should be use the api or maybe think of another work around all together?
Note: api requires key, so should I create one in the name of FOSSASIA or will someone else create one and give it to me if it's required

**Comment by kartik-karz** [comment]
An example using my private key
![map_resolve](https://user-images.githubusercontent.com/21131443/46428100-bad35500-c760-11e8-9232-ad27695454a3.png)

**Comment by kartik-karz** [comment]
I just tested it out by changing the url but I we can use it in gradle properties or build gradle, btw should we just display the API key in the repo? wouldn't people just misuse it? I saw the youtube api key in the project, but map view seems to be an integral part of susi_android so what's your opinion on this?

**Comment by iamareebjamal** [comment]
> btw should we just display the API key in the repo? wouldn't people just misuse it?

>  we'll add an API key in the build process

**Comment by atm1504** [comment]
@iamareebjamal can you please make some arrangement to add a sample key, at least for now.

**Comment by iamareebjamal** [comment]
As said, I'll add it in the build process, tell me the key name

**Comment by atm1504** [comment]
I need to get it. As soon as I get it, I will inform u.
