### ISSUE TITLE
UI and UX enhancement for the authentication system 

### ISSUE THREAD

**Issue by daminisatya** [fossasia/susi_android#172]
* The ```susi``` logo must be properly placed in the middle

Feel free to mention more enhacements which you would like to add.

**Comment by chashmeetsingh** [comment]
@daminisatya 

- Less focus on the timestamp
- Timestamp should be shown below

<img width="531" alt="screen shot 2016-10-13 at 12 18 04 pm" src="https://cloud.githubusercontent.com/assets/8962264/19339143/310ffcbe-913f-11e6-8ff9-7eb16130352c.png">

**Comment by daminisatya** [comment]
Awesome. This is one of the valid enhancements

**Comment by chashmeetsingh** [comment]
should I send a PR?

**Comment by daminisatya** [comment]
Yes

**Comment by chashmeetsingh** [comment]
Using "SUSI" as title with a specific font instead of the image?
