### ISSUE TITLE
Unnecessary color primary in colors.xml

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1727]
**Actual Behaviour**

Color primary and color primary dark have been assigned the same color code.

**Expected Behaviour**

Remove color primary dark as this is not required.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
We should have a dark color as per material design guidelines

**Comment by arundhati24** [comment]
Okay @iamareebjamal 👍
