### ISSUE TITLE
improve UX in readme file by adding a mobile frame to screenshots

### ISSUE THREAD

**Issue by prudhvir3ddy** [fossasia/susi_android#1731]
**this is the kind of screenshots we are using  currently**

![login](https://user-images.githubusercontent.com/20471162/46295800-93d91f80-c5b6-11e8-92fa-71715237ae31.png)

**readme will look a lot better if we use this kind of screenshots**

![download](https://user-images.githubusercontent.com/20471162/46295995-fc280100-c5b6-11e8-819e-bd9ff886f830.png)

**if you want to see how this looks**
you can check it [here](https://github.com/prudhvir3ddy/susi_android) 

**Would you like to work on the issue?**
yes

please assign the issue to me

**Comment by iamareebjamal** [comment]
It's actually hard to maintain such screenshots. Like if there's a new UI or layout, we'll have to regenerate everything back to this form

**Comment by prudhvir3ddy** [comment]
@iamareebjamal  this is not custom generated by me . it is by [theapplaunchpad](https://theapplaunchpad.com/) we can generate in just seconds upload screenshots and get it 

the way they look worth it i think 
i have seen google doing it for their app screenshots in [playstore](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en_IN) checkout once will be great even if we want to add some description

**Comment by iamareebjamal** [comment]
That's the thing. Instead of just putting screenshots, we have to manually put them through this process of generating images. This adds an extra step to the relatively straightforward process

**Comment by prudhvir3ddy** [comment]
@iamareebjamal  my idea is to make the documentation look more beautiful . looks like we have enough contributors to take an extra step 

if the idea looks beautiful and worth to take an extra step we can implement it .

i agree with what you have said about future devs taking an extra step to write documentation . yes

**Comment by iamareebjamal** [comment]
The point is that after you'll be gone and we'll have to quickly update the screenshots, we'll have to use an external service manually for that. Instead of just adding those screenshots in the repo. What if the service shuts down, or something else?

Then we'll have inconsistent screenshots and will have to find original screenshots from the frames. IMO, it is not worth it. This can be done for the Play Store screenshots but not the repo ones

**Comment by prudhvir3ddy** [comment]
@iamareebjamal yeah agreed, thanks for the reply i am closing the issue
