### ISSUE TITLE
Login Screen font fix

### ISSUE THREAD

**Issue by codedsun** [fossasia/susi_android#1733]
**Actual Behaviour**

The login screen 'sign up for susi' has another font

**Expected Behaviour**

It should have same font and font size as others.

**Steps to reproduce it**

Open the login screen and check the 'SignUp for SUSI'

**Screenshots of the issue**
![screenshot-1538992981119](https://user-images.githubusercontent.com/20026440/46603030-7d2f4d00-cb0f-11e8-88d0-2124118fef82.jpg)

**Would you like to work on the issue?**

Yes!

**Comment by yashk2000** [comment]
@codedsun can I fix this issue?

**Comment by codedsun** [comment]
@yashk2000 Yes go on!
