### ISSUE TITLE
Change font family of the application

### ISSUE THREAD

**Issue by mani87** [fossasia/susi_android#1736]
**Actual Behaviour**

Present font family is very basic and doesn't go with the color of the app.

**Expected Behaviour**

Some other font family that'll look good with the present color of the app, and make it more appealing. (In the whole application)

**Would you like to work on the issue?**

Yes, i would like to work on the issue.

**Comment by mani87** [comment]
@mariobehling @arundhati24 @iamareebjamal can you suggest some font styles that will look good with the current color we are using in or app?
Thanks.

**Comment by iamareebjamal** [comment]
I think the default one is fine. I don't see the reason of surprising users with another font than the default system one. Also, I don't understand how a font goes with or against a color scheme. We are following Material Design, which consists of all colors in its palette and only uses one font - Roboto

**Comment by mani87** [comment]
Okay, If this font is fine. @iamareebjamal thanks for responding. :)
