### ISSUE TITLE
Margins, Paddings and TextSizes are not according to material guidelines

### ISSUE THREAD

**Issue by mani87** [fossasia/susi_android#1737]
**Actual Behaviour**

Margins, Paddings and textsizes wherever used in the app do not  follow material guidelines.

**Expected Behaviour**

Margins, Paddings and textsizes wherever used in the app must follow material guidelines to look good and standardized.

**Screenshots of the issue**
![screenshot_2018-10-13-10-47-08-071_ai susi](https://user-images.githubusercontent.com/30254676/46901677-8e90a480-ced5-11e8-9029-01651bde6534.png)
![screenshot_2018-10-12-21-14-07-991_ai susi](https://user-images.githubusercontent.com/30254676/46901681-92242b80-ced5-11e8-8fc6-ca16adf26ef1.png)

**Would you like to work on the issue?**

Yes, i would like to work on this issue.

**Comment by sats98** [comment]
Yes, I would like to work on  this issue.

**Comment by Bhavnaharitsa** [comment]
May I work on this issue ?

**Comment by iamareebjamal** [comment]
Low priority. Current layout is fine
