### ISSUE TITLE
Unused and unoptimised imports

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1741]
**Actual Behaviour**

Currently, there are a number of unused and unoptimised imports present throughout the project.

**Expected Behaviour**

The unused imports should be removed and the others should be optimised. Although there is no effect on performance due to this, this would improve code readability and will slightly improve the compile time of the code.

**Would you like to work on the issue?**

Yes

**Comment by IgorWilbert** [comment]
Hello @arundhati24 ! Can I work on this issue?

**Comment by arundhati24** [comment]
@IgorWilbert Okay. Please go ahead. 👍

**Comment by arundhati24** [comment]
@IgorWilbert Are you still working on this?

**Comment by IgorWilbert** [comment]
@arundhati24 I'm sorry, I had a few issues here with other activities and the little I did isn't enough to create a PR. If you want to work on it, please go ahead.

**Comment by anujji1999** [comment]
Hello @arundhati24 ! Can i work on this issue?

**Comment by anujji1999** [comment]
I'm not able to clone the project.
![tempp](https://user-images.githubusercontent.com/33349650/48312026-b0617200-e5ce-11e8-9325-bafd2018d991.PNG)
can anyone help.
@arundhati24 @iamareebjamal

**Comment by iamareebjamal** [comment]
I'm sorry, but we don't provide Windows support and definitely recommend you to use git CLI. This error itself is related to GitHub Desktop client on electron framework, and not related to this project

**Comment by anujji1999** [comment]
ok, i will use git CLI.

**Comment by anujji1999** [comment]
ok, i will use git CLI.

**Comment by NitinKumar26** [comment]
can i work on this?

**Comment by arundhati24** [comment]
@NitinKumar26 This issue has already been claimed by @anujji1999 . I suggest you to please check out other issues or maybe find one yourself to work upon.

**Comment by iamareebjamal** [comment]
@NitinKumar26 We need help in testing #1765. As soon as it gets finalized, we'll create new issues for contributors
