### ISSUE TITLE
Sort SUSI skills in 'All' category

### ISSUE THREAD

**Issue by IgorWilbert** [fossasia/susi_android#1744]
**Actual Behaviour**

SUSI skills in 'All' category are randomly sorted.

**Expected Behaviour**

SUSI skills should be sorted according to rating, so that users could find what they want with minimum scroll.

**Would you like to work on the issue?**

Yes, but I need some help to know where do I begin.

**Comment by amey-ghate** [comment]
Hello IgorWilbert,

Analyzed the code to check the result returned. The list of skills are sorted on average rating. This sorting happens in two stages, all the skills with 10 or more reviews are sorted first and listed. This is followed by sorting of remaining skills. This would be reason where one can feel that the listing is not sorted.

Thus this issue can be closed

**Comment by IgorWilbert** [comment]
@amey-ghate I checked the code, and indeed you are right. Thank you!
