### ISSUE TITLE
Only generate apks for merged branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#1747]
The apks for master and development branch currently get generated on each merged PR of the dev branch. 

Expected: The APKs for master branch should only be updated (overwritten) once master branch is updated. The development branch APKs should be updated when the dev branch is updated.

![screenshot from 2018-10-26 10-31-09](https://user-images.githubusercontent.com/1583873/47554798-7b84c800-d90a-11e8-8f7b-f8cda2429f92.png)

**Comment by iamareebjamal** [comment]
`pslab-android` is now **450 MB** in size(without any reason), whereas the development branch is only 11 MB. Just because they haven't set up the apk branch using orphan method
