### ISSUE TITLE
not very helpful

### ISSUE THREAD

**Issue by smileayu** [fossasia/susi_android#1749]
**Actual Behaviour**  it is not providing direct answers to the questions. 

 I asked it about top indian celebrities and it had no knowladge about that topic. 

**Expected Behaviour** it would help to give better solutions

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by iamareebjamal** [comment]
This is not a problem of Android Client
