### ISSUE TITLE
Problem with Web search results

### ISSUE THREAD

**Issue by ArshiaP** [fossasia/susi_android#1751]
**Actual Behaviour**

When asked to do a search, a web result is not displayed, even though the question was under the skills of Susi .

**Expected Behaviour**

Susi should have returned  with a link of the information asked.  

**Screenshots of the issue**

![screenshot_2018-10-29-21-55-20-163_ai susi](https://user-images.githubusercontent.com/44582484/47721783-df92ed80-dc76-11e8-9af2-5923698aa952.png)

**Comment by batbrain7** [comment]
@ArshiaP this response is controlled from the server side, you may open up an issue on the server repository, this is not an issue for the clients
