### ISSUE TITLE
Build failing 

### ISSUE THREAD

**Issue by knightcube** [fossasia/susi_android#1755]
**Actual Behaviour**
When I deploy the project in my local machine gradle does not build successfully. I am not being able to deploy it in my android device also hence.

**Expected Behaviour**
Build should happen successfully without errors

**LogCat for the issue**
```
Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

```
The above url shows 404 error.

**Comment by iamareebjamal** [comment]
It's a gradle issue. Try after some time.

**Comment by iamareebjamal** [comment]
Travis is able to build the project. So, there is no issue in project. Please share more logs. This is not a reproducible error
