### ISSUE TITLE
Thumbs up/down icons disappear even when the skill has not been rated

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1756]
**Actual Behaviour**

The thumbs up/down icons disappear when the skill is not rated due to some network issue.

**Expected Behaviour**

The icons should disappear only when the skill has actually been rated.

**Steps to reproduce it**

1) Open the chat activity.
2) Type a message, say, "Hello"
3) Turn off the mobile data or Wi-Fi.
4) Try rating the SUSI response.
Observation: A toast pops up with the error message - "Unable to rate skill. Please try again later."
The skill has not been rated, yet the thumbs up/down icons disappear.

**Would you like to work on the issue?**

Yes

**Comment by balaji-ramavathu** [comment]
@arundhati24 Hello! 
Can I work on this issue?

**Comment by arundhati24** [comment]
@balaji-ramavathu Yes please go ahead. 👍

**Comment by vkk2018** [comment]
@arundhati24 HI!
I want to work on this..

**Comment by balaji-ramavathu** [comment]
I am not working on this issue since I cannot reproduce it. I think the issue is solved somehow. Are you able to reproduce it @vkk2018 ?

**Comment by balaji-ramavathu** [comment]
okay then go ahead.

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @batbrain7 can I work in this issue?

**Comment by iamareebjamal** [comment]
Is it reproducible?

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @batbrain7 after studying the codebase, I realised that when we click on thumbs up or thumbs down icon, it is just updated in our local database. It is actually not stored in the server. If we logout and login again, we will see that we can rate it again, this is because it is stored locally.

**Comment by arundhati24** [comment]
I cannot see this happening now. Would you please confirm this once @atm1504 ?

**Comment by atm1504** [comment]
@arundhati24 its not happening with me also. I think this can be closed.
