### ISSUE TITLE
No link to websearch result

### ISSUE THREAD

**Issue by jakubpawlina** [fossasia/susi_android#1758]
**Actual Behaviour**

There is no link to visit (or anything) below text "Here is a websearch result:".

**Expected Behaviour**

There should be a link to visit or other field showing results.

**Steps to reproduce it**

\-

**LogCat for the issue**

none

**Screenshots of the issue**

![screenshot_20181103-164907](https://user-images.githubusercontent.com/29257057/47954346-b1b8ec00-df89-11e8-8baf-15c4426480f6.png)

**Would you like to work on the issue?**

I would like to help but I am afraid I cannot fix it on my own.

**Comment by ShubhamAvasthi** [comment]
I am not able to reproduce this issue.
![screenshot_20181214-100333](https://user-images.githubusercontent.com/26148398/50001463-f1c8b100-ffc2-11e8-9d29-e877306cc6c5.png)

**Comment by jakubpawlina** [comment]
I see it is working now. But try to type 'Search what is c++'

**Comment by vaibhavg152** [comment]
i want to work on this issue

**Comment by NileshPranami** [comment]
@vaibhavg152 are you still working on this?

**Comment by vaibhavg152** [comment]
@NileshPranami Yes. It's almost done
