### ISSUE TITLE
Asked a question 'what is glass made up of?'

### ISSUE THREAD

**Issue by Vishkrish108** [fossasia/susi_android#1761]
**Response to Question is not being provided via a URL Link**

Received a response which states "Here is a websearch result:

**Received a response which states "Here is a websearch result (ALONG WITH URL FOR ANSWER)**

The User should be able to simply CLICK on the URL Link for the question that he has asked

ADD THE URL LINK TO THE RESPONSE

**LogCat for the issue**
Test via Questions

**Screenshots of the issue**
![whatsapp image 2018-11-06 at 10 50 51 pm](https://user-images.githubusercontent.com/44814102/48081747-c2ca5d00-e216-11e8-8f59-ecb2581ad379.jpeg)

**Would you like to work on the issue?**
NO - Would like to further test this application and suggest further improvements.

**Comment by iamareebjamal** [comment]
A lot of previous issues (closed) have been of same nature. This is a duplicate and not relevant to the Android Client, hence closing
