### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by anujji1999** [fossasia/susi_android#1762]
**Actual Behaviour**
lint-gradle-api.jar file is missing

![image](https://user-images.githubusercontent.com/33349650/48313832-ccbdd880-e5e7-11e8-8ba8-d21634215b91.png)

**Expected Behaviour**

Project should sync properly

**Would you like to work on the issue?**
Open for all

**Comment by anujji1999** [comment]
@batbrain7 @iamareebjamal @arundhati24

**Comment by iamareebjamal** [comment]
This is JCenter issue. Try again after some time. Not related to project. 

Re-Open if you are still unable to build after a few hours

**Comment by anujji1999** [comment]
Tried 3-4 times.
Also tried reopening android studio.

**Comment by iamareebjamal** [comment]
Duplicate of #1755

**Comment by iamareebjamal** [comment]
Try now after fetching
