### ISSUE TITLE
Add Koin for dependency management

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#1764]
- [ ] Move all instantiation of Retrofit in Dependency Graph

More tasks to be added

**Comment by pallav12** [comment]
@iamareebjamal though this is already assigned... can I work on this when more tasks are added??

**Comment by iamareebjamal** [comment]
Yes

**Comment by pallav12** [comment]
@iamareebjamal should I continue adding classes to module??? why this issue is closed?
