### ISSUE TITLE
Small Application Icon Bad look

### ISSUE THREAD

**Issue by subhahu123** [fossasia/susi_android#1768]
Application icon of android app is very small
Icon should cover whole space 
Present icon does not look nice and also not recognisable while searching for..
![screenshot_2018-11-13-22-30-31-477_com miui home](https://user-images.githubusercontent.com/34541684/48429991-2e0bb600-e766-11e8-9ace-c1c16d02399f.png)

**Comment by iamareebjamal** [comment]
Provide screenshot for how it looks on your device

**Comment by iamareebjamal** [comment]
/remind me to close the issue in 2 days

**Comment by subhahu123** [comment]
@iamareebjamal  updated

**Comment by subhahu123** [comment]
XML editor for icon for editting file 
which shows preview also .....
@iamareebjamal

**Comment by subhahu123** [comment]
i have the icon_launcher it's fine but when 
it is very small when run on application icon display 
![screenshot from 2018-11-15 00-23-10](https://user-images.githubusercontent.com/34541684/48505388-f89dc000-e86c-11e8-9b15-0a9299d037bf.png)

- 

- 

- @iamareebjamal

**Comment by subhahu123** [comment]
![screenshot from 2018-11-15 14-09-06](https://user-images.githubusercontent.com/34541684/48540603-89fa4a00-e8e0-11e8-8564-1470eccd6362.png)

**Comment by naman653** [comment]
@iamareebjamal I don't think the issue exists anymore. Please review it.
