### ISSUE TITLE
UI issue with the timestamps

### ISSUE THREAD

**Issue by daminisatya** [fossasia/susi_android#177]
![7f21071a-9165-11e6-8086-5320e30f7a9f](https://cloud.githubusercontent.com/assets/6227784/19347330/e63d4152-9165-11e6-8182-288b030f64b2.png)

**Comment by daminisatya** [comment]
Since the chat bubbles are small, the time stamps are getting transferred to new lines.

**Comment by daminisatya** [comment]
The possible work around is to place the time stamp near the text , but reducing it's font size.

**Comment by mariobehling** [comment]
Please keep the font size the same. Simply define a minimum width of bubbles, please, that ensures the time stamps show up correctly.

**Comment by amitiwary999** [comment]
I would like to work on this

**Comment by daminisatya** [comment]
@amitiwary999 We want a quick fix for this.

**Comment by jig08** [comment]
@mariobehling Yes, that's the work around most of the chat applications use.

**Comment by amitiwary999** [comment]
@daminisatya If anyone else want to work on this then I have no problem(I am quite busy ).

**Comment by betterclever** [comment]
@jig08 @daminisatya I want to work on this.
