### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by subhahu123** [fossasia/susi_android#1770]
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

@iamareebjamal 
![20181114_034048](https://user-images.githubusercontent.com/34541684/48446496-4d6c0880-e791-11e8-94c2-630d6ace6f9d.gif)
![20181114_022017](https://user-images.githubusercontent.com/34541684/48446549-6e345e00-e791-11e8-9c72-2220354f87fc.gif)
 If u  want to say this default android classes
Then there is a implementation or designing error
But thing which is definite is tere is error
Whether u admit or not

**Comment by subhahu123** [comment]
@rctay @johnjohndoe @Orbiter @hongquan 
I dont know u re not seeing error 
I raising this issue second time first tme it was clossed by @iamareebjamal

**Comment by iamareebjamal** [comment]
> We have not written any special code to make the box highlight. We are using standard Android Menu Items.
> However, if you do want to solve this issue, you are free to send a PR, however from our side, it's a wontfix

You did not follow the issue templste, you did not tell if you wanted to solve the issue and seemingly derailed the issue thread to this:

> I dont why u r not seeing

> If u think there is no error then u must ask others to have a look on this.......................

This is considered off topic. If you want to solve this issue, please send a PR and avoid further discussion. Off Topic disussions will lead to closing of issue. Please read the Code of Conduct and Best Practices at FOSSASIA

**Comment by iamareebjamal** [comment]
Please list the "errors" properly in the issue description and follow issue template

**Comment by iamareebjamal** [comment]
Since there is no update from author for extended period of time, I'm closing the issue
