### ISSUE TITLE
App's Package Installer Stops After First Time Use

### ISSUE THREAD

**Issue by karox693** [fossasia/susi_android#1786]
**Actual Behaviour**
After starting a skill on the application, the app crashes immediately after and shows a message of '' Package Installer keeps stopping'' and runs in the background and doesn't allow the user to further operate the app whilst showing the same aforementioned message everytime the user tries to start the application.

**Expected Behaviour**
The app must re-stabilise and fix the crash after it is ended or kept in the background, thereby allowing the user to operate the app after opening it again. It must allow the user to operate it and must perform the skill asked for by the user.

**Steps to reproduce it**
The package installer code or function must be looked into and resolved so as to not stop while the app runs.

**LogCat for the issue**
-
**Screenshots of the issue**
The skill trying to be run by the user-
![screenshot_20181124-133623 1](https://user-images.githubusercontent.com/45307161/48966162-c705c100-eff1-11e8-9ead-323e423319cc.png)
The problem occuring after the user tries to run the 'skill'-
![screenshot_20181124-133650 1](https://user-images.githubusercontent.com/45307161/48966143-4941b580-eff1-11e8-8337-63fbcc76fc72.png)

**Would you like to work on the issue?**
The app developer/s should work on making the application user friendly and unsusceptible to bug crashes and the package installer must be made functional so as to not stop.

**Comment by Bhavnaharitsa** [comment]
May I work on this ?
