### ISSUE TITLE
Can't Sign Up in login

### ISSUE THREAD

**Issue by ScriptKiddies1** [fossasia/susi_android#1791]
**Actual Behaviour**
Cannot Signup for new users

**Expected Behaviour**
should be able to log in here

**Steps to reproduce it**

1. Go To Apps
2. Click Sign Up For Susi

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2018-12-05-20-30-46](https://user-images.githubusercontent.com/34539125/49516891-45edda00-f8cd-11e8-842a-b9277959b156.png)

**Would you like to work on the issue?**

**Comment by iamareebjamal** [comment]
@ScriptKiddies1 Would you like to work on this issue?

**Comment by vkk2018** [comment]
I am interested to work on this issue

**Comment by vkk2018** [comment]
I am not able to reproduce this error in my device
