### ISSUE TITLE
please fix this

### ISSUE THREAD

**Issue by jakaya123** [fossasia/susi_android#1792]
**Screenshots of the issue**

**I have tried to get maps of that countries like this**
![screenshot_20181205-235329](https://user-images.githubusercontent.com/34449936/49535517-65dfc680-f8ea-11e8-8553-cea256801330.png)
![screenshot_20181205-235329](https://user-images.githubusercontent.com/34449936/49535521-69734d80-f8ea-11e8-8657-aabcb640775c.png)

**and**

**I tried to convert meters to different other distance measuring units.But it isn't working.
Please insert units converting feature to this AI.

**Comment by iamareebjamal** [comment]
Not an issue with client, this is an issue with the server
