### ISSUE TITLE
App Crashes When Pressing Back Button During Voice

### ISSUE THREAD

**Issue by Ryan10145** [fossasia/susi_android#1794]
**Actual Behaviour**

App crashes upon hitting the phone's back button during voice search.

**Expected Behaviour**

The app shouldn't crash and instead go back to the main chat.

**Steps to reproduce it**

1. Go to the main chat page.
2. Press the microphone
3. Hit the back button on the phone

**LogCat for the issue**

https://pastebin.com/UMWPVx7Q

Using Android 4.4.2

**Screenshots of the issue**

![screenshot_2018-12-05-23-11-43](https://user-images.githubusercontent.com/8119928/49561068-47c29800-f8e3-11e8-9d25-81d5aca07dfa.png)

**Would you like to work on the issue?**

Open To All

**Comment by trancenoid** [comment]
Cannot reproduce the error [Nougat]

**Comment by vkk2018** [comment]
I think the error is showing in your platform ....It's not on Nougat and above...
