### ISSUE TITLE
Logo isn't being displayed

### ISSUE THREAD

**Issue by janvikumari** [fossasia/susi_android#1795]
**Actual Behaviour**

The logo of the app doesn't display.

**Expected Behaviour**

There should be a logo of the app.

**Steps to reproduce it**

It isn't needed.

**Screenshots of the issue**
![5231452768916233045](https://user-images.githubusercontent.com/45655693/49591197-0925ef80-f96e-11e8-8162-3d0ffb0ba1ad.png)

**Would you like to work on the issue?**

Yes

**Comment by sats98** [comment]
Hi ma`am. I would like to work on this issue.

**Comment by batbrain7** [comment]
go ahead @sats98

**Comment by SAITARUN55** [comment]
@batbrain7 I would like to work on this issue

**Comment by naman653** [comment]
@iamareebjamal @batbrain7 I think the issue is resolved.
