### ISSUE TITLE
Voice input starts automatically

### ISSUE THREAD

**Issue by STS30** [fossasia/susi_android#1797]
**Actual Behaviour**

Whenever tapping sound is made near the phone while the app is ON, the Voice Input starts automatically

**Expected Behaviour**

Voice Input must start only when It is called using its name.
For Example: "Hey Susi"
**Steps to reproduce it**

Try making a tapping sound near the device while the app is open & idle

**Comment by Bhavnaharitsa** [comment]
May I contribute to this ?

**Comment by batbrain7** [comment]
go ahead @Bhavnaharitsa

**Comment by STS30** [comment]
Yeah, go ahead @Bhavnaharitsa

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Could you give me a hint to solve this bug ?
I've understood it completely but no hint of solution
