### ISSUE TITLE
Make all commits to the dev branch

### ISSUE THREAD

**Issue by the-dagger** [fossasia/susi_android#18]
All the commits should be made to the development branch of the repo and it should be merged with master on a weekly basis, similar to what we are doing on the opev repo.
Thoughts @mariobehling ?

**Comment by mariobehling** [comment]
Yes, we will move to this model in a few weeks, when there is substantial code that justifies a more advanced process. Right now commit directly to master. Added info about this here: https://github.com/fossasia/susi_android/blob/master/README.md#branch-policy
