### ISSUE TITLE
Not show skill search result

### ISSUE THREAD

**Issue by JulioRahman** [fossasia/susi_android#1800]
**Actual Behaviour**

Toast "No skill found yet" appears, and nothing change

**Expected Behaviour**

The results of that have been entered appear

**Steps to reproduce it**

After the search button has been touched, then types the query, appears toast "No skill found yet"

**LogCat for the issue**

None

**Screenshots of the issue**

![screenshot_susi ai_20181209-151830](https://user-images.githubusercontent.com/32903387/49695075-bfd0dc80-fbc7-11e8-9f69-1ef8992c2182.png)

**Would you like to work on the issue?**

Sorry, no

**Comment by liveHarshit** [comment]
@ShridharGoel Science there is no PR, are you still working on it?
I want to work on this issue.

**Comment by ShridharGoel** [comment]
@liveHarshit You can work on it.

**Comment by gaganag50** [comment]
@ShridharGoel  are you working on it? As there is no pull request on this matter I want to work on it. If you are not currently working on it please let me work on it I have almost figured out how to do it.

**Comment by liveHarshit** [comment]
@gaganag50 Go ahead.

**Comment by gaganag50** [comment]
Thank you very much.

**Comment by ShridharGoel** [comment]
@gaganag50 Yeah, go ahead.

**Comment by immadisairaj** [comment]
@iamareebjamal I think this issue can be closed as it is already fixed in #2095
