### ISSUE TITLE
Application crashes sometimes

### ISSUE THREAD

**Issue by Flinston123** [fossasia/susi_android#1804]
**Actual Behaviour**

 Application crashes when asking for weather

**Expected Behaviour**

 feature should tell me what is the weather in a given city

**Steps to reproduce it**

 -------

**LogCat for the issue**

 no logs

**Screenshots of the issue**

 https://imgur.com/bWhiaNQ

**Would you like to work on the issue?**

 I don't know how to solve this problem and I don't know who can solve it.

**Comment by trancenoid** [comment]
I cannot reproduce the error, can you please specify what command you gave ?
