### ISSUE TITLE
Doesn't showing the Websearch Results

### ISSUE THREAD

**Issue by ztrstn** [fossasia/susi_android#1805]
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by ztrstn** [comment]
Sorry my mistake 🙏

**Comment by iamareebjamal** [comment]
Duplicate. Please check previous issues before creating new one
