### ISSUE TITLE
UI is obsolete on New Registration screen

### ISSUE THREAD

**Issue by khush3211** [fossasia/susi_android#1808]
**Actual Behaviour**
Old and basic UI is present.

**Expected Behaviour**
Modern design patterns should be followed.

**Screenshots of the issue**
![whatsapp image 2018-12-10 at 10 37 47 pm 2](https://user-images.githubusercontent.com/34205476/49749153-9306ed00-fccd-11e8-8f23-e4f68b0d7af2.jpeg)

**Comment by iamareebjamal** [comment]
A design pattern is of software architecture, not UI. Besides what "modern" design can be applied, and what is old design here?

**Comment by sanyamdogra** [comment]
I can imporve the sign up UI through flutter, should i go ahead?

**Comment by iamareebjamal** [comment]
No, this is not a f;utter project
