### ISSUE TITLE
Shows Internet Connectivity Problem even when Internet is working

### ISSUE THREAD

**Issue by khush3211** [fossasia/susi_android#1809]
**Actual Behaviour**
For first message sent, error of no internt connection occurs. Afterwards, it starts working.

**Expected Behaviour**
Proper Internet Connectivity Check should be done.

**Steps to reproduce it**
Try using 2G or 3G instead of 4G or WiFi

**Screenshots of the issue**
![whatsapp image 2018-12-10 at 10 37 47 pm 3](https://user-images.githubusercontent.com/34205476/49749266-d2353e00-fccd-11e8-8678-5c4ad5c341c1.jpeg)

**Comment by 02zchen** [comment]
I had the exact same error. It worked out the second time I ran the command.

**Comment by 02zchen** [comment]
![screenshot_20181210-160554](https://user-images.githubusercontent.com/33395887/49761722-d8a7c380-fc95-11e8-8dea-ef482ad36bee.png)

**Comment by bbtdev** [comment]
Same problem for me!

**Comment by Bhavnaharitsa** [comment]
Is anybody working on this issue ?

**Comment by batbrain7** [comment]
This is a server problem, there is no problem in the app regarding this
