### ISSUE TITLE
UI issue with Login Form

### ISSUE THREAD

**Issue by aakashkhatter1296** [fossasia/susi_android#181]
### Expected Behaviour
The keyboard should not hide the Login and SignUp button. The entire form should move upwards when any of the text fields is in focus.
### Actual Behaviour
When the text field is in focus, the keyboard hides the Login and Signup button.
### Screenshots of the issue
![screenshot_20161014-001402](https://cloud.githubusercontent.com/assets/10905662/19362321/f5f3501c-91a3-11e6-8bba-7d89f682841b.jpg)

I would like to work on this issue.

**Comment by aakashkhatter1296** [comment]
Same issue is the with the SignUp form as well.

**Comment by gogeta95** [comment]
@mayank408 are you working on these UI issues or not? because we can assign someone else.

**Comment by aakashkhatter1296** [comment]
@gogeta95 I have managed to fix it. Should I submit a PR ?

**Comment by mayank408** [comment]
@gogeta95 @aakashkhatter1296 
I am currently working on two issues within limited time.
1. Using text to speech as output.
2. Deleting messages from database.

So for now @aakashkhatter1296 can take up the UI improvement issue.

**Comment by mayank408** [comment]
@the-dagger Issue is already addressed , So we can close this.
