### ISSUE TITLE
Title is not changing in skills activity

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/susi_android#1812]
**Actual Behaviour**
App bar title of SkillsActivity is not changing when getting back from setting or about us.

**Expected Behaviour**
The title should change back to SUSI.AI Skills

**Steps to reproduce it**

- Open the app
- Go to Skills 
- Open setting or about for the first time
- Go back
- See title is not changing

**Screenshots of the issue**

<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/50008447-37dd3f00-ffda-11e8-80eb-e7f745d72f98.png" height = "480" width="270"> 
<img src="https://user-images.githubusercontent.com/27783786/50008448-3875d580-ffda-11e8-924b-5cffb53974b9.png" height = "480" width="270"> 

**Would you like to work on the issue?**
Yes

**Comment by Maimoi** [comment]
Its working fine on android Oreo . Which version are you using ?

**Comment by liveHarshit** [comment]
> Its working fine on android Oreo . Which version are you using ?

Nougat 7.1, `onResume()` is not called for the fragment when open first time. After opening again, it works fine.

**Comment by vkk2018** [comment]
It's working fine..
![screenshot_20190109-192816](https://user-images.githubusercontent.com/43517972/50903990-2eae8900-1445-11e9-8bf6-fa5b36705cf4.png)
![screenshot_20190109-192845](https://user-images.githubusercontent.com/43517972/50903999-31a97980-1445-11e9-9394-41a81c1afa58.png)
![screenshot_20190109-192852](https://user-images.githubusercontent.com/43517972/50904004-33733d00-1445-11e9-987a-591e164bc47f.png)

**Comment by liveHarshit** [comment]
Not on my device when I go back for the first time. I have tested `onResume()` is not called.
