### ISSUE TITLE
SignUp screen after sign up is sucessfull 

### ISSUE THREAD

**Issue by nimit95** [fossasia/susi_android#182]
### Expected Behaviour

After the successful sign up the activity should go back on the log in page
### Actual Behaviour

It only shows a successful signup toast and user has to press back to get to login page 
### Would you like to work on the issue?

Yes I would like to solve this issue. 
I will work on it.

**Comment by mayank408** [comment]
@nimit95 Instead of toast bar pls use the snackbar .

**Comment by jig08** [comment]
@nimit95 yes pls, use `snackbar` instead.

**Comment by nimit95** [comment]
okay I will implement snackbar as well
