### ISSUE TITLE
Words in about us page are missing

### ISSUE THREAD

**Issue by 091karan** [fossasia/susi_android#1825]
**Actual Behaviour**

Some words are missing in the about us page

**Expected Behaviour**

Missing words should be displayed

**Screenshots of the issue**

![screenshot_1546955453](https://user-images.githubusercontent.com/29620528/50834762-e460d580-137a-11e9-89c3-372d3b981a94.png)

**Would you like to work on the issue?**

Yes

**Comment by vkk2018** [comment]
I am not able to reproduce the error @091karan .It might be showing on ur platform.
![screenshot_20190109-192318](https://user-images.githubusercontent.com/43517972/50903563-243fbf80-1444-11e9-87bc-5e87edfaba5e.png)

**Comment by 091karan** [comment]
@vkk2018 Possible. I am using android emulator, and tried on various emulators.

**Comment by batbrain7** [comment]
is this issue observed in devices ?
