### ISSUE TITLE
Sudden apperance of toast message on search activity

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#1827]
**Actual Behaviour**

On performing a search in SUSI.AI skills just after writing a toast appear stating "No skills found yet"

**Expected Behaviour**

Search option should properly search for it.

**Steps to reproduce it**

Update the search option with required changes.
**LogCat for the issue**

**Would you like to work on the issue?**
YES

**Comment by immadisairaj** [comment]
@iamareebjamal I think this issue can be closed as it is already fixed in #2095
