### ISSUE TITLE
App crashes sometimes if speed and pitch of SUSI voice is changed

### ISSUE THREAD

**Issue by vkk2018** [fossasia/susi_android#1829]
**Actual Behaviour**

Sometimes the app crashes if the speed and pitch of the sound is altered 
**Expected Behaviour**

It should automatically adjust for all combinations.

**Steps to reproduce it**

It can be reproduced by altering the speed and pitch of the sound and then using skills like Farming,Weather information
**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes
![screenshot_20190109-201955](https://user-images.githubusercontent.com/43517972/50907331-17739980-144d-11e9-8794-bdc4938f7c2e.png)

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @batbrain7 I tried to reproduce the issue, but I didn't get any search error. @vkk2018 can you please check and tell if you are still facing the issue, as I didn't face it.
