### ISSUE TITLE
Back button on SignUp Screen

### ISSUE THREAD

**Issue by aakashkhatter1296** [fossasia/susi_android#183]
### Expected Behaviour
There should be a back button on the SignUp screen to go back to the login screen

### Would you like to work on the issue?
I would like to work on this issue

**Comment by replyashu** [comment]
Taking up this issue

**Comment by mariobehling** [comment]
Actually the usual behaviour in Android is to use the standard Android back button on the phone. Please ensure this is working.

**Comment by the-dagger** [comment]
My bad, I forgot to close this issue, it's already fixed in #214
