### ISSUE TITLE
Search menu is displayed in skill details fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/susi_android#1835]
**Actual Behaviour**

Search menu is displayed in skill details fragment.

**Expected Behaviour**

Menu item should not be displayed.

**Screenshots of the issue**

<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/51046855-314be280-15ed-11e9-9683-d8e7282c4506.png" height = "480" width="270"> 
</p>

**Would you like to work on the issue?**

Yes

**Comment by liveHarshit** [comment]
@iamareebjamal Is it a bug or not? I'm a little bit confused. Because currently, search is not working for both fragments.

**Comment by iamareebjamal** [comment]
@arundhati24 @batbrain7 Please clarify

**Comment by batbrain7** [comment]
The search icon must not be present in the skillsdetails fragment

**Comment by liveHarshit** [comment]
@batbrain7 Currently the menu options are used in SkillListing fragment only. Can I shift the menu in the respective fragment? So there is no need to hide the menu items in other fragments.
