### ISSUE TITLE
App doesn't run from beginning 

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#1848]
Description Of Issue:
As soon as I run the application again after closing Android Studio and emulator, the application doesn't run from the start,rather it shows the previous state from which I closed.
![untitled](https://user-images.githubusercontent.com/37215508/51296346-d2012e80-1a41-11e9-8c21-6876523066da.png)

**What I want to do?**
I want to fix the bug and make sure the app starts from first 

**Would you like to work on the issue?**
Yes !

**Comment by liveHarshit** [comment]
I think Android emulator save instant state by default. Try it with a device.

**Comment by batbrain7** [comment]
@Bhavnaharitsa u have to clear the app resources from settings
