### ISSUE TITLE
Add shimmer effect

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/susi_android#1850]
**Describe the feature you'd like**

Remove progress bar in favor of shimmer effect layout in skill listing fragment.

**Would you like to work on the issue?**

yes

**Comment by batbrain7** [comment]
@liveHarshit I think progress bar was deliberately kept there because the app style is made consistent according to the standard apps like for skills section if there is shimmer effect in Alexa or google assistant skills then same should be implemented in SUSI else it should not be implemented

**Comment by liveHarshit** [comment]
Okay. I'm sorry. I was not aware of the standard apps which you are following,
