### ISSUE TITLE
skill variable not initialized

### ISSUE THREAD

**Issue by Nimagna123** [fossasia/susi_android#1855]
**Describe the bug**
skills variable is only declared but is not assigned any value in SkillsActivity.kt & SkillListingFragment.kt

**Expected Behaviour**
skills variable should be initialized from database

**Steps To Reproduce it**
Try to print the size of skill variable. You will find it to be zero.

**Would you like to work on the issue?**
Yes

**Comment by Nimagna123** [comment]
https://github.com/fossasia/susi_android/pull/1859/commits/7c19331d66b7b772fb5fc24e188cd5b1ee421165

**Comment by batbrain7** [comment]
@Nimagna123 why do we need to initialize the variable?

**Comment by Nimagna123** [comment]
refer to issue #1782
