### ISSUE TITLE
Need of Writing Hint

### ISSUE THREAD

**Issue by manisoni28** [fossasia/susi_android#186]
1.There should be a writing hint while Susi is typing something as it feels unrealistic when someone ask any ques and with no time Susi replies back.It is inappropiate and Susi will give a feel that there is other person typing..In response to time taken by us to write something,same time should be shown of Susi.

**Comment by the-dagger** [comment]
Not an urgent issue imo.
Still you can take this up if you want.

**Comment by mejariamol** [comment]
I want to work on this issue.

**Comment by the-dagger** [comment]
Cool, go ahead @mejariamol

**Comment by mejariamol** [comment]
Fixed. PR created
![2016_10_18_15_57_22_1_](https://cloud.githubusercontent.com/assets/13533840/19474831/42df5700-94e6-11e6-82e0-7eedecf4cccc.gif)
