### ISSUE TITLE
In Landscape mode,after composing a message and hitting send button ,conversation screen is not opening.

### ISSUE THREAD

**Issue by mustaqmustu** [fossasia/susi_android#1870]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43813438/51534228-34f02c80-1e6b-11e9-9c33-33250928e626.gif)

In Landscape mode,after composing a message and hitting send button ,conversation screen is not opening.

do u want to work on it?
yes

**Comment by naman653** [comment]
Can you please be specific because I'm not having any issue
