### ISSUE TITLE
App crashes when language changed to Deutsche

### ISSUE THREAD

**Issue by nandhinibalaji311** [fossasia/susi_android#1879]
**Describe the feature you'd like**

The application should not crash when the language is changed to Deutsche.

**Additional context**
The application should not crash when that language is chosen.

**GIF**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44377726/51754697-fcf31e80-20e2-11e9-8944-d22b785a9544.gif)

**Would you like to work on the issue?**

yes

**Comment by nandhinibalaji311** [comment]
Logcat for this issue is available [here](https://gist.github.com/nandhinibalaji311/be7a3b298f16d0ddddc5702bfa9b10b5)

**Comment by Bhavnaharitsa** [comment]
Are you still working on this issue ?
@nandhinibalaji311

**Comment by immadisairaj** [comment]
I think now it's working so this can be closed...
