### ISSUE TITLE
App shows " Dumping memory app will freeze " error

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#1884]
**Describe the bug**

The app always shows " Dumping memory , app will freeze brr " as soon as I click any skill.

**Expected Behaviour**

The app should show me the desired skill.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/37215508/51790453-8a09a680-21bb-11e9-8e9b-4289ad96a5d7.png)
  

Couldn't get the image of the error cause it was a toast.

**Would you like to work on the issue?**

I sure would!

**Comment by iamareebjamal** [comment]
This is leak canary reporting memory leaks

**Comment by Bhavnaharitsa** [comment]
Yes,it is ! but isn't that a issue ?
Like,isn't that supposed to be fixed ?

**Comment by batbrain7** [comment]
@Bhavnaharitsa leak canary helps us report the memory leaks, the issue is to fix the memory leaks not remove this warning

**Comment by Bhavnaharitsa** [comment]
Oh,got it !
