### ISSUE TITLE
Add 'Press again to close SUSI.AI'

### ISSUE THREAD

**Issue by imrrahul** [fossasia/susi_android#1901]
**Describe the feature you'd like**

In the latest SUSI.AI version pressing back button only ones exits the application. The user might end up hitting the Back button by mistake which would cause an unintentional exit from the app. It will be best to add this feature of 'Press (Back button )again to exit' .

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
It was deliberately removed from FOSSASIA apps as it is a non-standard practice and annoyance to some users

**Comment by imrrahul** [comment]
@iamareebjamal Thank you, but it is still followed by some other fossasia project such as phimp.me and eventyay application. The user might end up hitting the Back button by mistake which would cause an unintentional exit from the app and will prevent the user from repeatedly entering the application again and again.

**Comment by iamareebjamal** [comment]
Please create an issue in eventyay to remove it. Thanks

I also liked the feature and voted to keep it, but a non-standard thing is non-standard

I never unintentionally hit back and if I do, then I'm right back in one or two clicks. Unless there's a pending work happening in the app, we should not block user actions which are meant to close an app. Give me example of one standard app which implements this

**Comment by imrrahul** [comment]
@iamareebjamal thank you, I will create the issues.
Thank you
P.S.- Flipkart and Paytm

**Comment by iamareebjamal** [comment]
Not standard apps. None of them even follow Google's design guidelines
