### ISSUE TITLE
Searching is not working in SUSI.AI

### ISSUE THREAD

**Issue by alphamuth** [fossasia/susi_android#1902]
**Describe the bug**

'Search' a SUSI.AI skills option is not working in application. Whenever I press a button on keypad to search any skill a toast message appears says `No skill found yet `, which may be annoying to user and on searching it is not showing any result ,i.e, search button is not working.
**Expected Behaviour**
It should search the skill for which keyword is typed in the search bar and give the relevant output.It should not show the toast message while typing as may be annoying to the user.

**Screenshots of the issue**

![screenshot_20190202-143330](https://user-images.githubusercontent.com/37583853/52162331-4dc4d180-26f8-11e9-8b4f-fcf97a6f6271.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Would you like to work on the issue?**

Yes

**Comment by gaganag50** [comment]
@imrrahul are you still working on it because I want to work on this issue

**Comment by imrrahul** [comment]
@gaganag50 if you want you can work on it
