### ISSUE TITLE
Remember me option for passwords in sign up page 

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#1905]
**Describe the feature you'd like**

No " remember me "option in sign up page 

**Additional context**

Remember me checkbox option would help users remember their password and not have to type everytime.

**Would you like to work on the issue?**

Yes

**Comment by immadisairaj** [comment]
@Bhavnaharitsa 
"remember me" option if there should be in sign in page not in the signup page.

**Comment by chanmol1999** [comment]
Are you working on this?

**Comment by chanmol1999** [comment]
I am working on this @iamareebjamal

**Comment by Bhavnaharitsa** [comment]
@chanmol1999 Hello!
I'm still working on it.I'll let you know if it goes in vain :)

**Comment by immadisairaj** [comment]
@Bhavnaharitsa 
I think this is a duplicate issue of #1301 ?

**Comment by Bhavnaharitsa** [comment]
Yes ,it is ! But I guess the methodology is diff that's the reason I opened it

**Comment by immadisairaj** [comment]
> Yes ,it is ! But I guess the methodology is diff that's the reason I opened it

@Bhavnaharitsa 
I think it is the same.
What will be done here is the same as there.
That is adding a checkbox to remember the user password.
