### ISSUE TITLE
Implement forgot password

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#192]
### Expected Behaviour

we need to implement forgot password function.
### Would you like to work on the issue?

yes

**Comment by gogeta95** [comment]
waiting for fossasia/susi_server#11 to be fixed before this.

**Comment by YashishDua** [comment]
@gogeta95 If Server problem is fixed , Can I take up this issue ?

**Comment by gogeta95** [comment]
No it's not. I'm waiting too.

**Comment by Orbiter** [comment]
I believe the server problem is fixed!

**Comment by samsruti** [comment]
@gogeta95 are you still working on this? I would like to work on this issue.

**Comment by gogeta95** [comment]
Sorry, been caught up with work, you can work on it if you want to :)

On 07-Dec-2016 4:05 PM, "Samsruti Dash" <notifications@github.com> wrote:

@gogeta95 <https://github.com/gogeta95> are you still working on this? I
would like to work on this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/susi_android/issues/192#issuecomment-265413235>,
or mute the thread

**Comment by mayank408** [comment]
@the-dagger Already merged can be closed now.

**Comment by samsruti** [comment]
Yeah thanks @mayank408 for bringing this :)
