### ISSUE TITLE
Swipe to go to susi-skills

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#1924]
**Describe the feature you'd like**

Swipe left in order to go to susi-skills and vice versa to come back. 
The user need not always go and touch the susi icon in order to go to the susi skills.
rather he can swipe left .

**Would you like to work on the issue?**

yes

**Comment by atm1504** [comment]
@iamareebjamal can I work in it?

**Comment by Bhavnaharitsa** [comment]
@batbrain7 @iamareebjamal  Could we use ViewPager in order to implement swipe feature ?

**Comment by iamareebjamal** [comment]
No

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Are there any possible options ?

**Comment by atm1504** [comment]
@iamareebjamal I am fixing the things you said. I would make the commits within 1 or 2 days.

@Bhavnaharitsa you can see in my pr #2007 I have used gesture detector. There is a certain calculation based, if a condition is satisfied, then it passes the intent to open the activity. This is the most common technique in gesture detection.
