### ISSUE TITLE
Use correct spell for dimension 

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#1950]
**Describe the bug**

Error in the spelling of dimensions.

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Would you like to work on the issue?**
yes

**Comment by iamareebjamal** [comment]
It's not a variable. Correct both issue and PR description and title
