### ISSUE TITLE
Whole text working as hyperlink

### ISSUE THREAD

**Issue by ravi-kishan** [fossasia/susi_android#1955]
**Describe the bug**
In AboutUs fragment hyperlinks are highlighted in blue colour but link opens on clicking non highlighted text also

**Expected Behaviour**
Link should open only on clicking highlighted text

**Steps to reproduce it**
1.Open AboutUs fragment
2.Click on any text

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[ Moto G4 Plus]|
|Android Version| [Nougat 7.0]    |

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
Can I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead
