### ISSUE TITLE
Disabled settings options seem to be working

### ISSUE THREAD

**Issue by ravi-kishan** [fossasia/susi_android#1956]
**Describe the bug**
In Settings fragment some options work only if user is logged in.
But the UI controls work.

**Expected Behaviour**
User should not be allowed to change options in UI which are disabled in code

**Steps to reproduce it**
1.Open Settings fragment without logging in
2.Try to change speech options

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[ Moto G4 Plus] |
|Android Version| [ Nougat 7.0] |

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 I am taking this issue.
