### ISSUE TITLE
Wrong description of setting fragment

### ISSUE THREAD

**Issue by ravi-kishan** [fossasia/susi_android#1957]
**Describe the bug**
In string resource file setting fragment is wrongly described as settings activity

**Expected Behaviour**
It should be described as settings fragment

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@batbrain7 as the user is not active, Can I work on it?

**Comment by iamareebjamal** [comment]
Very low priority. Not worthy enough to fix
