### ISSUE TITLE
Issue on pressing back button in setting.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#196]
### Expected Behaviour
The app on pressing back button should go to main activity.
### Actual Behaviour
App is crashing on pressing back button in settings.

### Would you like to work on the issue?
Yes

**Comment by amitiwary999** [comment]
@mayank408 can you explain this issue?

**Comment by mayank408** [comment]
@amitiwary999 Go to settings then press back button of your mobile . After which the app crashes.

**Comment by amitiwary999** [comment]
@mayank408 But in my phone it is working fine.

**Comment by mayank408** [comment]
@amitiwary999  no problem , it should be working on all the phones. I just rectified it.

**Comment by gogeta95** [comment]
@mayank408 please mention your device details if this issue is device specific. like android verison , CPU etc.

**Comment by mayank408** [comment]
@gogeta95 The problem is rectified on explictily calling onBackPressed() method on settings activity and passing the intent for main activity.

**Comment by gogeta95** [comment]
I didn't ask how to rectify, I asked the cause. Pls post the log of the crash along your device info as its device specific, and starting new activity in on back pressed is a dirty hack. Don't do that. It breaks the lifecycle and increases memory.
We need to look into the cause before solving it.

**Comment by the-dagger** [comment]
@mayank408 Always provide logcat for crashed.
I have edited the issue template to include this information.

**Comment by mayank408** [comment]
@gogeta95 @the-dagger The issue is resolved . It is due to the null point exception due to which the app was crashing , and its not device specific , I tested it on three devices . The problem is resolved by just simply using an if statement.

**Comment by the-dagger** [comment]
@mayank408 which pr adds that if statement?

**Comment by mayank408** [comment]
@the-dagger I have not sent the pr yet because my previous pr is still to be merged.

**Comment by amitiwary999** [comment]
@mayank408 give logcat showing crash error.

**Comment by the-dagger** [comment]
@mayank408 can you provide logs for the crash?
