### ISSUE TITLE
Display profile photo in settings

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#1961]
**Describe the feature you'd like**

Profile photo of the user should also be displayed above login email option in settings activity.
**Would you like to work on the issue?**
Yes

**Comment by Bhavnaharitsa** [comment]
Are you still working on this ?

**Comment by chanmol1999** [comment]
No currently i am not you can go ahead.

**Comment by atm1504** [comment]
@iamareebjamal I think this should also be closed, as we cannot have it until the profile section is implemented
