### ISSUE TITLE
list missing in the answer message

### ISSUE THREAD

**Issue by vaibhavg152** [fossasia/susi_android#1962]
**Describe the bug**

When asked a question, it says 'here is a list of ... ' with no list.

**Expected Behaviour**
It should display the list.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**
![screenshot_20190120-202457](https://user-images.githubusercontent.com/33133409/52803407-02bb9e80-30a8-11e9-80e2-24f3816d8806.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 6.1|
|Android Version| 9.0 pie    |

**Would you like to work on the issue?**
Yes

**Comment by vaibhavg152** [comment]
@iamareebjamal 
I need some help on this, I'm not being able to locate the list in the result returned by the API.

**Comment by arundhati24** [comment]
This is not an issue with the app. The response itself has no list. Hence, closing.
