### ISSUE TITLE
Fix CircleCI build

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#1964]
Circle CI is not working. Change the config to 2.0

**Comment by naman653** [comment]
I would like to work on the issue. Just help me on how should I approach to solve the issue.

**Comment by iamareebjamal** [comment]
Read on how to migrate CircleCI 1 to 2

**Comment by naman653** [comment]
Why don't we create another branch so that the workflow of the project is not affected by this issue and continue circleci build on version 1.0 until this issue is resolved?

**Comment by iamareebjamal** [comment]
Circle CI 1.0 is not working. It's discontinued. Making a new branch will not solve anything. Even if it was working, it wouldn't help. Why would we maintain 2 branches, we'd merge the changes from the working 2.0 PR and call it a day

**Comment by immadisairaj** [comment]
I would like to work on this Issue

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal 
Sir,
Since there is no config.yml file in our project I'm assuming that Circle CI is discontinued.
Does the solution involve starting from scratch connecting CircleCI to app ?
If so, I can take up the issue ?


Thanks!

**Comment by iamareebjamal** [comment]
There is a config YML in our project. Without it, we wouldn't be building on circle ci

**Comment by Bhavnaharitsa** [comment]
Okay!
When I searched for it, it didn't appear .So,I inferred it isn't there.
I shall check it

**Comment by Bhavnaharitsa** [comment]
Oh,yeah!
It is named Circle.YML
