### ISSUE TITLE
Unfortunately,Package installer has stopped.

### ISSUE THREAD

**Issue by Ashish-cse38** [fossasia/susi_android#1968]
**Describe the bug**

After not giving it any of the three permissions it asks for, when you reopen app a message "Unfortunately,Package Installer has stopped." appears and it closes. Also another application opens in background.

**Expected Behaviour**

It should run and if user is doing something related to that required permission then it should ask user again for that.

**Steps to reproduce it**

1.Download the app.
2.Login or skip.
3.Don't give any one or more permissions.
4.Reopen the app.

**LogCat for the issue**

**Screenshots of the issue**

![error](https://user-images.githubusercontent.com/33326109/52918754-ab743300-3320-11e9-9507-aefa72657e40.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nubia z11 mini|
|Android Version|6.0.1  |

**Would you like to work on the issue?**

Yes.

**Comment by iamareebjamal** [comment]
Duplicate
