### ISSUE TITLE
Skills Page Not Loading

### ISSUE THREAD

**Issue by autofreak** [fossasia/susi_android#1969]
I saw URL to skills, I clicked on skills.susi.ai but it does not open any page. Kindly work on this or remove URL if page is not available.

**Comment by naman653** [comment]
can you tell me at which activity of the page, it is happening?

**Comment by Bhavnaharitsa** [comment]
@autofreak Could you tell me which activity and screen shot if possible ?

**Comment by iamareebjamal** [comment]
No response from OP. Hence, closing
