### ISSUE TITLE
UI improvement for sign up and login screen.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#197]
### Would you like to work on the issue?
Yes

**Comment by mariobehling** [comment]
Thank you. Please post ideas/screenshots/proposals on GitHub here in issues.

For the beginning let's follow and get inspired by existing apps chat apps like Whatsapp, Google Hangout etc. 
* [ ] Please keep the colors light.
* [ ] Keep the design simple (We will define design guidelines once we have more features)
* [ ] Keep background colors light - white and gray preferably
