### ISSUE TITLE
Map is not shown in chat activity

### ISSUE THREAD

**Issue by naman653** [fossasia/susi_android#1971]
**Describe the bug**

In susi chat activity, if asked for a map, no map is shown. A template of the map is shown with a working intent to start google maps.

**Expected Behaviour**

It should show the map also in the activity.

**Screenshots of the issue**

![screenshot_2019-02-20-23-16-24](https://user-images.githubusercontent.com/31595908/53113856-8540d400-3568-11e9-8a5b-33e214b3b235.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Intex Cloud Flash |
|Android Version|Lollipop 5.1|

**Would you like to work on the issue?**

**Comment by vaibhavg152** [comment]
I want to work on this

**Comment by naman653** [comment]
Well currently I'm working on this, but if you come up with the solution you're welcome to solve the issue.

**Comment by vaibhavg152** [comment]
I tried to debug it. The source of the error is that the server is denying the request to load the map.

**Comment by atm1504** [comment]
@iamareebjamal this is similar to #1718. So it can be closed
