### ISSUE TITLE
Add the feature of Exporting Chat

### ISSUE THREAD

**Issue by nandhinibalaji311** [fossasia/susi_android#1977]
**Describe the feature you'd like**
I would like to add the feature of exporting chats via mail.

**Additional context**
As of now individual messages can be copied or shared via mail,hangouts etc.

**Would you like to work on the issue?**
Yes

**Comment by nandhinibalaji311** [comment]
Can I work on implementing on this feature?

**Comment by iamareebjamal** [comment]
This should be raised on SUSI server

**Comment by nandhinibalaji311** [comment]
OK.I will raise it on SUSI server.
