### ISSUE TITLE
Change background colour of chat window

### ISSUE THREAD

**Issue by nandhinibalaji311** [fossasia/susi_android#1981]
**Describe the feature you'd like**
The colour of the chat window should be changed from white to lime

**Additional context**
Currently, it is white in colour

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Why?

**Comment by nandhinibalaji311** [comment]
As most of the other applications have a different colour for the background of their chat window, I thought of implementing it for this application too.

**Comment by iamareebjamal** [comment]
This is not required
