### ISSUE TITLE
TOS/privacy policy on server signup screen

### ISSUE THREAD

**Issue by haverholm** [fossasia/susi_android#1985]
It would be best practice to supply links to the terms and conditions of the susi.ai server. Personally I'm not too keen on signing up for any service without knowing how my data is being handled, or even shared... I'm sure everything us above board, but it should be easy for new users to ascertain that.

**Comment by atm1504** [comment]
@iamareebjamal can I work on this?

**Comment by iamareebjamal** [comment]
Go ahead
