### ISSUE TITLE
Display a Toast on deleting message

### ISSUE THREAD

**Issue by GetSetAbhi** [fossasia/susi_android#199]
### Expected Behaviour
Toast should be displayed on deleting message like in all messaging apps

### Actual Behaviour
No such activity on deleting message

### Would you like to work on the issue?
Yes please

**Comment by mayank408** [comment]
@GetSetAbhi  We are not using toast bars instead we are using snackbar .

**Comment by GetSetAbhi** [comment]
@mayank408 Yeah I noticed that database problem.
Anyway that database deletion problem is a backend problem and will be fixed so why not fix that Snackbar which is a frontend problem and can be fixed without much effort ?
Sooner or later someone has to work on it right ?

**Comment by gogeta95** [comment]
deletion is not a backend problem, message needs to be deleted locally, like whatsapp.

**Comment by piyush6348** [comment]
The only task here is to implement a snackbar??

**Comment by mayank408** [comment]
@piyush6348 Implement snackbar and make sure that the UI lifts up on opening of snackbar.

**Comment by piyush6348** [comment]
I think there was one more issue regarding lifting up of UI on opening of snackbar.

**Comment by GetSetAbhi** [comment]
@piyush6348 Would you mind If I take up this issue ?
I was trying the deletion issue but 2 results get deleted instead of one. You can work on that if you want .

**Comment by YashishDua** [comment]
Can I take up this Issue ?

**Comment by jig08** [comment]
@piyush6348 Updates on this please ?

@YashishDua Try taking up issues which are unassigned currently or open up cases for faulty or new features. Cheers !

**Comment by piyush6348** [comment]
@GetSetAbhi  sorry for being so late, if you want you can work on this issue. @jig08  i was unable to get start on this issue as i'm quite occupied from last couple of days.

**Comment by jig08** [comment]
@piyush6348 Thanks.
@GetSetAbhi Would you like to take this up, else I assign this to @YashishDua  ?

**Comment by betterclever** [comment]
@jig08 this is an old issue. We already implemented Snackbar for it and it is also present in new version of copy/delete in PR #261. This can be closed.
