### ISSUE TITLE
User's message should be ticked before SUSI's reply

### ISSUE THREAD

**Issue by balaji-ramavathu** [fossasia/susi_android#1990]
**Describe the feature you'd like**

Right now, the user's message is getting a tick mark after the reply of SUSI. This doesn't seem natural since the reply should come after the message is sent.

**Screenshots**

![susi-tick](https://user-images.githubusercontent.com/26673203/53680864-118c8d00-3d07-11e9-9cca-d2d8c9a7791e.gif)

**Would you like to work on the issue?**

Yes

**Comment by atm1504** [comment]
@iamareebjamal please code it, it is not possible to implement until it is implemented in the server
