### ISSUE TITLE
Padding missing in fragment skill listing

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#1999]
**Describe the feature you'd like**

To improve the ui of skill listing fragment the recycler view used in this should have a padding .

**Screenshots**

![Screenshot_20190309_203533](https://user-images.githubusercontent.com/42909612/54073317-abc27700-42ab-11e9-9fb0-a11399a37063.jpg)

**Would you like to work on the issue?**

Yes

**Comment by atm1504** [comment]
@iamareebjamal I think this issue can be closed.
