### ISSUE TITLE
Display user name in settings page

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2003]
**Describe the feature you'd like**
Display the name of the user in the setting page along with the user email id.

**Screenshots**
![settings](https://user-images.githubusercontent.com/43731599/54090996-9d09bc00-43a0-11e9-930e-d19c386a296d.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal can I start working in this issue?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by atm1504** [comment]
@iamareebjamal I hope it is not possible to work on this issue. Susi doesn't ask for user name during registration nor even it sends data back that contains username. 
I am attaching the json send and received.
<img width="1680" alt="Screenshot 2019-03-12 at 12 05 05 AM" src="https://user-images.githubusercontent.com/43731599/54148618-83c54600-445a-11e9-8ecb-ce2faa14d509.png">
