### ISSUE TITLE
Add help option in the skills Activity menu

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2004]
**Describe the feature you'd like**
Help option should be available in the menu bar. This would redirect to help Activity. This will provide guide to the user, whenever they want help.

**Additional context**
It will increase the ease to use the app for the user.

**Screenshots**

![help](https://user-images.githubusercontent.com/43731599/54091117-21a90a00-43a2-11e9-952f-61dc0ccbe76e.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal can I start working in this feautre

**Comment by iamareebjamal** [comment]
And what will "Help" contain?

**Comment by atm1504** [comment]
The help will contain the complete guide how to use the app.
 It will contain basic instructions like:
* How to change password?
* How to raise an issue?
* How to use susi voice?
* How to login if you have opened susi without logging in?
* How to signup in susi?
* Describe the features present in the app

**Comment by iamareebjamal** [comment]
If you have time to write the guide, then go ahead

**Comment by atm1504** [comment]
Okk, I will work on it this week

**Comment by arundhati24** [comment]
Would be a good option to add! 👍
