### ISSUE TITLE
Offer option to sign out

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#201]
Please propose and implement a sign out option in the app.

This is a follow up to: https://github.com/fossasia/susi_android/issues/194

**Comment by gogeta95** [comment]
its already there.
![image](https://cloud.githubusercontent.com/assets/8329096/19407829/2601b87a-92cb-11e6-9e36-a0743b88f007.png)

**Comment by the-dagger** [comment]
Closing this.
