### ISSUE TITLE
Add feature to speak out details of About page

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2019]
**Describe the feature you'd like**
I would like to place a pic of speaker in the AboutUs page. Clicking on this will read aloud the details written in the about us page.

**Additional context**
This will make the user more attractive to listen to the contents of the page.

**Screenshots**
![aboutUs](https://user-images.githubusercontent.com/43731599/54490488-2b6bc980-48dc-11e9-8115-1aab46d5cea9.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24  can we have this feature?

**Comment by iamareebjamal** [comment]
Unneeded
