### ISSUE TITLE
Add nickname to the user

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2026]
**Describe the feature you'd like**
Give user the chance to add nickname. The nickname can be added manually from the settings page. The name will also be displayed in the settings page along with email. It totally depends on the user wether to add nickname or not.

**Additional context**
As Susi does not ask for user name during registration, we can have this feature to display the name of the user, This will make the app look cool.

**Screenshots**
![nickname](https://user-images.githubusercontent.com/43731599/54507711-8e0aa700-4968-11e9-95f6-f144292e07f1.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24  I hope we can have this. This will help to implement #2003 .

**Comment by iamareebjamal** [comment]
Not needed unless it's on server
