### ISSUE TITLE
Add back button in review page

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2029]
**Describe the feature you'd like**
Add a back button in the page that shows all the feedbacks of the skills

**Additional context**
This will make the app more handy to use

**Screenshots**
![back](https://user-images.githubusercontent.com/43731599/54627875-4a17bf00-4a9a-11e9-8333-bafbc4ce63dd.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by chanmol1999** [comment]
@atm1504  hello
Already this issue exist #1952 :)
