### ISSUE TITLE
Message deletion is broken.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#203]
**Actual Behaviour**

message deletion just deletes the mesage temporarily, it comes back on restarting app.

**Expected Behaviour**

message should be deleted permanently from database.

**Steps to reproduce it**

delete a message > close app > open app again.

**Screenshot**
![peek 2016-10-15 12-33](https://cloud.githubusercontent.com/assets/8329096/19408142/cf5c2cae-92d3-11e6-8967-440555b654d1.gif)

**Would you like to work on the issue?**

yes

**Comment by GetSetAbhi** [comment]
@gogeta95 I fixed that issue :/

**Comment by gogeta95** [comment]
You can go ahead and send a PR. No issues if you have already done that,
but please open an issue before you start working so everyone will know.

On Oct 15, 2016 2:06 PM, "Abhishek Raina" <notifications@github.com> wrote:

@gogeta95 <https://github.com/gogeta95> I fixed that issue :/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/susi_android/issues/203#issuecomment-253971000>,
or mute the thread

**Comment by GetSetAbhi** [comment]
I was just just tinkering with the app trying to understand the code before I saw the issue here.
And solved the error doing that.

**Comment by GetSetAbhi** [comment]
Are there any rules to follow before sending a PR ?

**Comment by gogeta95** [comment]
@GetSetAbhi are you sending PR?

**Comment by GetSetAbhi** [comment]
@gogeta95 I tested the code and found that 2 messages are deleted in the recyclerview instead of one.
however in the database only the selected entry is deleted.

**Comment by gogeta95** [comment]
ok, i'll take this up then.

**Comment by GetSetAbhi** [comment]
I wrote this code
![github](https://cloud.githubusercontent.com/assets/5512947/19410312/719f2bec-9306-11e6-83f5-f3911bbbf278.png)
And thats the result I get.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5512947/19410304/3d5ac6c0-9306-11e6-96ab-dde583be5263.gif)

**Comment by gogeta95** [comment]
first of all, you shouldn't be using equalto() twice let me try once.

**Comment by GetSetAbhi** [comment]
Do let me know if you fix it. I need to know what went wrong :(

**Comment by gogeta95** [comment]
it turns out to be more complec than i thought. we need to use https://github.com/realm/realm-android-adapters

**Comment by GetSetAbhi** [comment]
@gogeta95 okay i'm on it then. Will let you know if I get it.

**Comment by gogeta95** [comment]
its done :p
