### ISSUE TITLE
Increase margin between feedback cards

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2030]
**Describe the feature you'd like**
Increase the margin between the feedbacks card in the the page that shows all the feedbacks

**Additional context**
We can also increase the padding. It will make the app look more descent.

**Screenshots**
![back](https://user-images.githubusercontent.com/43731599/54628008-99f68600-4a9a-11e9-8693-ee4cf6b6aea6.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Not needed
