### ISSUE TITLE
Move from feedback to login instead of signup.

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#2034]
**Describe the feature you'd like**
Inspite of moving to signup page user should be driven to login page for making app more handy for users.

**Additional context**
As it is clearly mentioned **Please login to post feedback** in skill detail therefore clicking on it should direct the user straight to login page instead of signup page.

**Screenshots**
![Screenrecording_20190320_200541](https://user-images.githubusercontent.com/42909612/54693400-94597880-4b4c-11e9-9536-8c04aaef3708.gif)

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@chanmol1999 those who have account they would prefer to Login first before opening the app. Only those who don't have account prefer skip. So thinking about that situation I gave the option to move to signup instead of Login page.

**Comment by iamareebjamal** [comment]
Login should be used instead
