### ISSUE TITLE
Add 'Know About Us'  button in Login and sign up page. 

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2036]
**Describe the feature you'd like**
Add the option 'Know About us' in the login and sign up page. The page would redirect to about us fragment. This 

**Additional context**
This feature targets the New SUSI users. New users have the urge to know what the app do. Implementing this feature would help such users and make it more handy. 

**Screenshots**
![Screenshot_2019-03-20-20-28-30-645_ai susi](https://user-images.githubusercontent.com/43731599/54695161-76d9de00-4b4f-11e9-8d42-6b966b599ad1.png)

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Not needed
