### ISSUE TITLE
Add signup button in settings fragment

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2049]
**Describe the feature you'd like**
Add signup button in settings fragment. Place it below the login option

**Additional context**
It's the usual conception of having both signup and login option together. But here there is no option to directly signup.

**Screenshots**
![signup](https://user-images.githubusercontent.com/43731599/54782584-43797b00-4c45-11e9-9b48-0a212ad1fbd3.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Unneeded
