### ISSUE TITLE
Settings page malfunctions on moving back from about us

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#2055]
**Describe the bug**
Settings page shows malfunctioning on moving back from about us to settings .Many features including login/logout do not work properly.

**Expected Behaviour**

Settings page should work  as normal as it was working previously.

**Steps to reproduce it**
change in chat setttings fragment

**LogCat for the issue**

**Screenshots of the issue**
![Screenrecording_20190322_030236 (1)](https://user-images.githubusercontent.com/42909612/54786765-c1db1a80-4c4f-11e9-9b48-34d0f27a3732.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Vivo 1802|
|Android Version|8.1.0    |

**Would you like to work on the issue?**
yes

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @batbrain7 I am taking up this issue
