### ISSUE TITLE
"Malayalam" language is not displayed in the ListPrefernce list of Languages

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2061]
**Describe the bug**
"Malyalam" language is not displayed in the list of ListPreference of settings page. Though the app support the malyalam translation.

**Expected Behaviour**
As the app supports malayalam language translation, user should be given the chance to select this language from the option. 

**Steps to reproduce it**
Add "Malyalam" in the array file along with its code.

**Screenshots of the issue**
![multi](https://user-images.githubusercontent.com/43731599/54847401-3ec7cc00-4d04-11e9-819c-930e0a362328.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 5 Pro |
|Android Version| Oreo 8.1    |

**Would you like to work on the issue?**
Yes

**Comment by immadisairaj** [comment]
@atm1504 I think this is a duplicate issue of #1941

**Comment by atm1504** [comment]
@immadisairaj I didn't saw that. Moreover there was no activeness in that issue for over a month.
