### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2068]
**Describe the bug**
there are certain memory leaks in skills call back

**Expected Behaviour**

All the memory leaks should be fixed

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/37215508/54874620-f21fe600-4e14-11e9-9c9d-80ac9cc09629.png)

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
Duplicate issue for #1351 . Hence, closing. Please always have a look at the already open issues to avoid duplicate issues.
