### ISSUE TITLE
UX improvement

### ISSUE THREAD

**Issue by viveksb007** [fossasia/susi_android#208]
**Actual Behaviour**

Title and numbers on AlertDialog that pops up on long press is not required.

![1](https://cloud.githubusercontent.com/assets/12713808/19411298/a539ec92-931c-11e6-85f6-845f49950591.png)

**Expected Behaviour**

Should be like this

![2](https://cloud.githubusercontent.com/assets/12713808/19411299/aed25a00-931c-11e6-8655-ecd33a0f1282.png)

**Steps to reproduce it**

Long press any chat message

**Would you like to work on the issue?**

yes

**Comment by jig08** [comment]
@viveksb007 yep, sounds better.

**Comment by jig08** [comment]
@viveksb007 yep, sounds better.
