### ISSUE TITLE
No content in see all reviews activity

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#2084]
**Describe the bug**
Currently no review is displayed on pressing see all reviews in a particular skill.

**Expected Behaviour**
All reviews must be shown on pressing see all reviews activity.

**Steps to reproduce it**
Open see all reviews for any skill .

**LogCat for the issue**

**Screenshots of the issue**
![Screenshot_20190326_234753](https://user-images.githubusercontent.com/42909612/55022930-b60da080-5021-11e9-9495-5e65749ba146.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Vivo 1802|
|Android Version| 8.1.0  |

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 I am taking up this issue.
