### ISSUE TITLE
Add shimmer until skill listing is shown

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2090]
**Describe the feature you'd like**

Show progress to the user by adding a shimmer effect 

**Additional context**

Shimmer effect is a popular feature in most apps and it will help the user to know that the skills are being loaded.

**Would you like to work on the issue?**

Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24  I am taking up this issue.
