### ISSUE TITLE
Open other apps on voice search 

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2099]
**Describe the feature you'd like**
Now the Susi-skills can only display results which is under it's skills

**Additional context**
On voice search like " Okay Susi,open gallery " or "Okay Susi,open WhatsApp "
It should be able to open those apps as well like in google assistant and alexa.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Currently out of scope, but yes, that is the plan.
