### ISSUE TITLE
Create Profile page

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2101]
**Describe the feature you'd like**
Create a profile section in settings page. Clicking on this will open Profile fragment.
The page will have datas like:
* Email ID
* Name to be added by user
* Photo of the user: To be added by the user
* Option to Logout
* Display at the bottom of the page showing "I <name> accept the terms and conditions that susi posses"

**Use of this page**
* Use the name that user enters to make susi welcome user by that name. It is similar to that of Cortana and Siri.
* Feature request to susi server:
** Take the user name from profile page and add it in the server.

**Additional context**
This will make susi more appropriate to be as a personal assistant of the user. It will be very helpful for siri to communicate with the user. Use of this feature can be further extended when we successfully train hot-word detection. 

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
This needs to be implemented on server first.
