### ISSUE TITLE
Make susi able to read email when users ask for it

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2103]
**Describe the feature you'd like**
Susi should be capable to read out recent emails that the users receive. 

**Additional context**
This is an addition of the skills that susi posses.

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
??? Emails from where?

**Comment by iamareebjamal** [comment]
How do you plan on doing it?

**Comment by atm1504** [comment]
Sir, I was going through few codes online and I found that this feature can be implemented, if you take permission in manifest file. The app would get access to those emails. After this we would be able to read out emails.

**Comment by iamareebjamal** [comment]
Bad idea
