### ISSUE TITLE
Talk to the user by the name of the user

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2104]
**Describe the feature you'd like**
Susi should be able to communicate with the user, by his/her name. This is similar to that of cortana/siri/google assistant.

**Additional context**
This feature will make the app more lively.

This issue should be solved only after #2101 #2087 #2086 
We should be able to use username only when the user accepts the terms and condition of susi.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
This is related to the server and not the app.
