### ISSUE TITLE
Add strings of different languages in privacy fragment

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2105]
**Describe the feature you'd like**
Currently,the privacy fragment does not have translations of diff apps
**Additional context**
It should be in different languages as the diverse users should know about the privacy terms

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
It do has.

**Comment by Bhavnaharitsa** [comment]
I  checked it by converting it into Hindi and Tamil...oops..it doesn't!
![Screenshot_20190329-183549_SUSIAI](https://user-images.githubusercontent.com/37215508/55234627-91980b00-5251-11e9-9653-1c2d21093b45.jpg)

**Comment by atm1504** [comment]
Multilanguage feature of the app doesn't work properly. I have already made that issue #2001. That's the reason you could not see the translation.

**Comment by Bhavnaharitsa** [comment]
Fine
