### ISSUE TITLE
Time is not properly displayed 

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2106]
**Describe the bug **
When asked susi for time right now,  it shows correct  and date but time is not appropriate. 
** Expected behaviour **
The time is currently 18.39 according to 24 hour clock but it shows 2.03 pm
**Screenshots of the issue**
![Screenshot_20190329-183721_SUSIAI](https://user-images.githubusercontent.com/37215508/55234934-3dd9f180-5252-11e9-98a5-6df8974e1a2f.jpg)
**Would you like to work on the issue?**
Yes

**Comment by immadisairaj** [comment]
@Bhavnaharitsa It is because the time zone is Central European Time(CET) which the skill is giving.

**Comment by iamareebjamal** [comment]
App should convert it to the timezone of the client

**Comment by Bhavnaharitsa** [comment]
![Screenshot_20190411-175850_SUSIAI](https://user-images.githubusercontent.com/37215508/55957398-e3925500-5c83-11e9-8e41-b6a91741a744.jpg)

Actually, when asked specifically " What is the time in India? " or " What is the time in the US? " the app shows the correct time. But if I simply ask " What is the time? " it is unable to produce correct results.
I have tried checking if my phone location is on ( if that matters here in this issue ) but still it is unable to produce results. 
Could you please tell me which part of the code is the issue? @iamareebjamal @arundhati24 @batbrain7 @immadisairaj any help is highly appreciated

**Comment by immadisairaj** [comment]
@iamareebjamal It is the same case with susi web client also. Even if logged in and set the timezone still the timezone(CET) comes.

**Comment by iamareebjamal** [comment]
It will obviously come from a different timezone, you have to change it to correct timezone in code

**Comment by atm1504** [comment]
@iamareebjamal what I think is that if we get any query stating what is the time or what is the time now we can simply display the time by taking it from the local mobile system, instead of displaying the query result. Please provide your views.

**Comment by iamareebjamal** [comment]
No

**Comment by atm1504** [comment]
@iamareebjamal I checked out the google assistant app. It displays the time from the server. The server tells the time by getting info about the current location of the app. So, I don't think it would be a good idea to convert the time in the app manually. The server should send the response according to the queried location. Every query does have location access to the device.
This is what I felt after going through the google assistant app. Please provide your views.

**Comment by iamareebjamal** [comment]
You get the time from server in UTC, just convert the time locally to correct timezone. If you don't get the time in required format, it is issue of the server

**Comment by atm1504** [comment]
@iamareebjamal please close this issue. I have already discussed this in the meeting. It is due to the skill that is responding to the query.
