### ISSUE TITLE
Prompt alert box in login page if users press skip

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2107]
**Describe the feature you'd like**
An alert box should be prompted if users press skip in login page. The alertbox should ask the user if he/she confirms to skip the login page.

**Additional context**
This feature is similar to the alert box that appears in the signup page if user presses back. It is the feature that is present in all professional apps.

**Screenshots**
![alertbox](https://user-images.githubusercontent.com/43731599/55255248-244f9e80-5280-11e9-8137-8e1154cf6a1f.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Low priority
