### ISSUE TITLE
Link preview reloads after its brought back in view

### ISSUE THREAD

**Issue by viveksb007** [fossasia/susi_android#211]
**Actual Behaviour**

Link preview reloads.

**Expected Behaviour**

Link preview should be cached atleast till app is destroyed.

**Steps to reproduce it**

send a link from your side, a preview would be shown.
scroll a bit up such that link message is out of view, then go to link message it reloads.

**Would you like to work on the issue?**

Yes

**Comment by saketkumar95** [comment]
@mariobehling @jig08 i would like to work on this.

**Comment by mayank408** [comment]
@saketkumar95 Any progress in this issue.

**Comment by saketkumar95** [comment]
Yes. Working on this now. I was a bit busy in semester exam. Will give the update soon.

**Comment by betterclever** [comment]
@mayank408 I have solved the issue already, can I send a PR?

**Comment by mayank408** [comment]
@betterclever Ya no problem you can send , I am bit busy . Cheers :)
