### ISSUE TITLE
Login page from menu bar closes the app after pressing back

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2136]
**Describe the bug**
If the user hasn't logged in, he clicks the login page under menu in SkillsActivity and it directs to the login page . But for some reasons if he doesn't want to login and clicks back button,the app closes down. 

**Expected Behaviour**
On clicking back button, it should go back to menu bar in SkillsAcitivity so that s/he can continue using the app.
The same can be implemented for signup page as well.

**Would you like to work on the issue?**
Yes

**Comment by immadisairaj** [comment]
@Bhavnaharitsa Why two PR's are open?

**Comment by immadisairaj** [comment]
@Bhavnaharitsa this is a similar issue of #1080 
Both the issues will be solved simultaneously.

**Comment by Bhavnaharitsa** [comment]
@immadisairaj  No actually the menu bar has two items 1.login 2.signup
that's why theres no prs

**Comment by immadisairaj** [comment]
@Bhavnaharitsa you could have sent both in the same PR.
