### ISSUE TITLE
Ascending order of Lists

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2147]
**Describe the bug**
Currently, under All categories, the skills are not ordered. they are abrupt and the user will a tough time if he wants to search for a skill.

**Expected Behaviour**
There should be a chronological order( alphabetical order ) so that the user can traverse through skills.
**Screen shot**
![Screenshot_20190407-170241_SUSIAI](https://user-images.githubusercontent.com/37215508/55683408-10312e80-595d-11e9-8e1f-52a4fd2f90d8.jpg)

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal I am taking up this issue

**Comment by iamareebjamal** [comment]
Not needed. Impossible task to do on client side if the list is big
