### ISSUE TITLE
Transfer Privacy, Help and About us to Settings

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2152]
**Describe the feature you'd like**
Currently, the app has privacy, help and about us fragments in menu bar which is not required. Menu bar is filled with items . We can only constraint the menu bar with login,signup(which disables after login) and settings. and tranfer the privacy, help and about us to settings because in any legit app, the user would go to the settings in order to find these docs

**Screenshots**

![image](https://user-images.githubusercontent.com/37215508/55797790-f6bded00-5aea-11e9-8fea-ac09b822cd8e.png)

@iamareebjamal Please opine on this 

**Would you like to work on the issue?**
Yes

**Comment by Bhavnaharitsa** [comment]
@arundhati24 what is your opinion on this?
I created this because there are too many items in menu bar which kind of makes it clumsy. I guess constraining the menu with only items that relates to.the functionalities as in signup,login,logout(islf he has logged in) and since these are ( privacy,help,aboutus) simple docs which are not used on regular basis can be shoved into the settings...because eventually the user has to go to.settings for further changes and he can find all.these in settings..

**Comment by iamareebjamal** [comment]
Go ahead. Do it in one PR
