### ISSUE TITLE
Implement tap targets for chat activity buttons

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#2166]
**Describe the feature you'd like**
Currently user is not able to judge the use of the floating action buttons in the chat activity.Therefore we can use tap targets for these buttons to help user.These tap targets will only be shown at first installation of the app. 

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal sir, is this feature needed?

**Comment by mariobehling** [comment]
Out of scope.
