### ISSUE TITLE
Implement notification feature 

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2174]
**Actual Behaviour**
Currently, no method has been established which allows to send notification in the app.

**Expected Behaviour**
There should be a method to send notification in the app. This will allow to send important information to the user. Like we can inform the user about new skills of susi, greet the user during some special festivals. 

**Steps to reproduce it**
Can be established with the use of firebase cloud notification service.

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal sir I think we should have this in the app. Because most of the apps have the ability to make push notification. Please provide your views sir.

**Comment by iamareebjamal** [comment]
Server issue. Not ready for app

**Comment by atm1504** [comment]
@iamareebjamal can I use firebase to implement this feature?

**Comment by iamareebjamal** [comment]
Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 for notification in JSON data format, the minimum required  SDK version is 16 and target version 26. So I need to upgrade it.

**Comment by atm1504** [comment]
I have established a system to send notification using Advanced Rest Client. Currently, it loads data and creates a notification channel and displays it.

**Comment by mariobehling** [comment]
Currently out of scope.
