### ISSUE TITLE
Sign in with google

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2175]
**Describe the feature you'd like**
Now, the user can only login using the email id. 
Being able to login or sign up with Google and saving the credentials would be a nice feature.

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Open the issue on server

**Comment by Bhavnaharitsa** [comment]
Sure, but can't we implement it with firebase?

**Comment by iamareebjamal** [comment]
How can you implement it with firebase when it is not implemented on server. Please try

**Comment by atm1504** [comment]
Sir, I think she wanted to say to shift the sign in and signup process to firebase. And then redirect the user to use the skills in the current susi server.

**Comment by immadisairaj** [comment]
@atm1504 I think that won't be good practice to shift sign in process to firebase. We are connected to the server and will be good to continue. If we implement firebase then this will be separated from the server right.

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal @immadisairaj I meant google sign in is possible with firebase only. If we want to implement that feature, we shall have to lean on firebase. Should we first implement the feature in server and then access from server like we have been doing?

**Comment by iamareebjamal** [comment]
Firebase is used by people who don't have a backend. If you use firebase by bypassing the SUSI server, it'll make no sense. Why do we have authentication on SUSI server then? There'll be no account/profile linking. First understand te scope of the feature. If you want to use Google SignIn, doesn't matter if it is through Firebase or Auth0, it is to be implemented on server first.

**Comment by Bhavnaharitsa** [comment]
Sure, thanks!
