### ISSUE TITLE
Upgrade the minSdk from kitkat to lollipop

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2176]
**Describe the chore**
the minSDk version is 15, upgrading it to lollipop(21) 

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Why?

**Comment by Bhavnaharitsa** [comment]
to improve stability and many other features require sdk with a minimum version of 21.

**Comment by iamareebjamal** [comment]
What stability will be improved and what other features which we need to use require Lollipop?

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Sorry for the late reply. My work was piled up. I honestly think upgrading the minSdk to 21 will provide a lot of features. To name a few,
The material theme
View shadows
The RecyclerView widget - We need that to implement an infinite view of skills
Drawable animation and styling effects
Material design animation and activity transition effects
Animators for view properties based on the state of the view
Customizable UI widgets and app bars with color palettes that you control
Animated and non-animated drawables based on XML vector graphics

https://developer.android.com/about/versions/android-5.0(referred)

Only 0.7% of users use minSdk 15 and hence I thought we need an upgrade. I am not skyrocketing to 28 or so but rather a slight bump to 21. I have noticed that it reduces the apk size as well( well not that much). I understand that services unused is services wasted but I think we can make use of it in mere future. I don't think it will hinder the deployment of the app. 
This is my answer or let's say suggestions to the issue I opened. In case you feel it's not needed, you can close the issue. I shall come up with better ones :) 

Thank you.

**Comment by iamareebjamal** [comment]
All things you mentioned are already in the app
