### ISSUE TITLE
Gesture detector is not working

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2182]
**Describe the bug**
The gesture is not working, as in I cannot go to Skills activity by swiping left from Chat Activity.

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@Bhavnaharitsa it is working in my device.

**Comment by Bhavnaharitsa** [comment]
@atm1504 I'm not able to reproduce it. I checked it on Samsung, Redmi and One plus.

**Comment by atm1504** [comment]
@Bhavnaharitsa then u might be using mild gestures. It won't work for mild gesture. I have restricted use of mild gestures, as stated by Areeb sir. Try to swap over chat input bar and the region above it.

**Comment by atm1504** [comment]
@arundhati24 @batbrain7 this issue can be closed as the gesture detector is working. It works for hard gestures, not mild ones.
