### ISSUE TITLE
Gesture detector to swipe from skills to chat activity

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2185]
**Describe the feature you'd like**
Swipe feature is there to swipe from chat to skills but not from skills to chat. It should be vice versa

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal I tried to implement this using a sample app. But I am continuously facing a problem. I am failing to override the onTouchEvent function. Though I have implemented all the other functions using inner class. Without this function, the fragment won't be able to detect the gestures and call the respective functions of the inner class. Can you please provide some help.

**Comment by iamareebjamal** [comment]
Why are you failing to override it?

**Comment by atm1504** [comment]
@iamareebjamal I have found a different way to implement gestures in the fragment. I will implement it and make the pr.

**Comment by atm1504** [comment]
@iamareebjamal sir the prototype app that I made is working properly. But when I am implementing it in USI, I am not getting any response.
Code for prototype app is:
<img width="1680" alt="Screenshot 2019-05-11 at 7 58 55 PM" src="https://user-images.githubusercontent.com/43731599/57571100-3dbf3b00-7427-11e9-9ba4-e802e2694519.png">

The code in SUSI: 
<img width="1680" alt="Screenshot 2019-05-11 at 7 59 26 PM" src="https://user-images.githubusercontent.com/43731599/57571107-562f5580-7427-11e9-9ccf-a651dd35280a.png">

Sir, please provide some suggestions.

**Comment by atm1504** [comment]
@iamareebjamal after doing few searches I found that its an issue due to the presence of scroll view in the respective fragments. Scrollview has its own set of gestures. I need to overcome this problem. I think this can be done. Please give me some time to do research on it.
Link: https://github.com/uptechteam/MotionViews-Android/issues/14

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 after searching a lot on the internet and understanding the circumstances I found out a way to handle gestures inside scrollView. But still, now I am failing to integrate it inside skillListing Fragment, where refreshLayout is being used. I hope I will find out a solution to this problem also very soon

**Comment by atm1504** [comment]
@iamareebjamal I think this issue is also not required now. It can be closed.
