### ISSUE TITLE
Add archive chat feature

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2189]
**Describe the feature you'd like**
User should be allowed to archive previous messages of chat. This messages won't be deleted but it would just be hidden. User can view this old messages whenever he want, but unarchiving it.

**Additional context**
This will reduce the abundance of messages in chat activity. Also users don't need to delete important chats.

**Server Change**
Archive feature needs to be implemented in the server. This could be achieved by adding another parameter to each chat messages.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Out of scope.
