### ISSUE TITLE
Change Susi Voice should be done from the app

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2205]
**Describe the feature you'd like**
Currently, clicking on change Susi Voice in settings fragment redirects to the voice settings of the android system. But it should not do so. Instead, there should be an option inside the app to change the voice settings like pitch, speed of tts engine for the app only. Now, it changes for the system as a whole. This is not a preferable option to have.

**Additional context**
We should be able to change voice settings for the susi app only. It should not affect the settings of the user. This is because the user might prefer other voice settings on other apps.

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 please provide your views on this issue. As, I think we should have this. It's necessary. Because I myself use different voice settings in different apps depending on my need. And it would be ridiculous to change the settings everytime.

**Comment by iamareebjamal** [comment]
Not a priority
