### ISSUE TITLE
Change minimum requirement to Android v.6

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#2209]
The app is currently only requiring Android 4.x. It is often a pain to get things working with old phones and Android versions. We only have a small team and we are not focusing on old devices. We have seen ratings going down on other apps, because people say it does not work on their old phones. We don't need it to work on old phones. Therefore please change the requirement to minimum Android 6, please.

**Comment by iamareebjamal** [comment]
v5 will be enough @mariobehling. There is no new API after Lollipop which makes it difficult to develop for previous versions

**Comment by atm1504** [comment]
@mariobehling @iamareebjamal so what version shall I upgrade it to v5.0 or v.60?

**Comment by iamareebjamal** [comment]
v5.0
