### ISSUE TITLE
Cookies in Login Form

### ISSUE THREAD

**Issue by rahulworld** [fossasia/susi_android#221]
**Actual Behaviour**

when we already signed up then go to again login form not showing cookies .

**Expected Behaviour**

Shows list of cookies in login form

**Steps to reproduce it**

*LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

**Comment by mariobehling** [comment]
@rahulworld Why do we need to see cookies in the login form? Which app has this feature? Could you provide a example and use case, please?

**Comment by rahulworld** [comment]
like facebook messenger we can add more account in one app.

**Comment by mariobehling** [comment]
@rahulworld Currently, we have not tested one account in real-world cases. Before we add this feature, we need to consolidate the basic features of the app. Sorry, but this is out of scope at the moment. 

I am sorry, but we do not have a list of the basic features yet. We also want to see what the community comes up with, but this is pretty clearly out of scope now.

Closing it therefore. Thank you.
