### ISSUE TITLE
Categorise old chats in groups

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2222]
**Describe the feature you'd like**
Chat activity usually contains chats of various categories like image, links, videos. We should be able to separate into different categories and show them to the user if they want.

**Additional context**
This feature is similar to that present in WhatsApp, where the user gets to see links, documents, and images.

**Screenshots**
![WhatsApp Image 2019-05-19 at 1 05 21 AM](https://user-images.githubusercontent.com/43731599/57974216-55239880-79d2-11e9-87e5-2252e2ecbbe7.jpeg)

## Categories to be implemented
- [x] Chat Category
- [x] Media Category
- [x]  Map Category
- [ ]  UI Polishing

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@mariobehling sir was not this feature useful. I found the need for it because, when we have a lot of chats, it becomes clumsy enough to find some old results. If we have, the option to categorize and see them, it really helps a lot, to find it out. Sir, please provide your views.

**Comment by mariobehling** [comment]
This kind of feature is out of scope at the moment.
