### ISSUE TITLE
Error in setting up SUSI Smart Speaker

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_android#2225]
**Describe the bug**
- The app downloaded from play store shows up the speaker in the add device section but doesn't respond further.
- The latest APK in releases hangs on "Connecting to device.." if the mobile phone was already connected to a wifi network during the setup procedure.

**Expected Behaviour**
- Update the app on play store.
- The speaker setup should work even if the device is already connected to a wifi network

**Steps to reproduce it**
- download the app from playstore
- flash a clean susibian image on the smart speaker and power it on.
- attempt to set up the speaker using the app

**Screenshots of the issue**
- The app in the play store: Clicking on setup is unresposive
![image](https://user-images.githubusercontent.com/14289201/58274503-a8219500-7db0-11e9-936b-151a9f964ab8.png)

- The App downloaded from releases 
![image](https://user-images.githubusercontent.com/14289201/58274587-cedfcb80-7db0-11e9-960d-e8960de081a3.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Sumsung Galaxy J6|
|Android Version| Android 9 Pie    |

**Would you like to work on the issue?**
no

**Comment by atm1504** [comment]
@alok760 I will surely look into it.
