### ISSUE TITLE
How do you deal with user privacy.

### ISSUE THREAD

**Issue by HarryHeights** [fossasia/susi_android#2238]
Privacy policies are vital documents necessary for every kind of app or project. Yours included. I was wondering how you handle user privacy when the app is utilized. I was expecting to accept terms and conditions after I launched the app for the first time but it wasn't there. I've scoured the repository and didn't a privacy doc. 

It'd be great to have a privacy policy. Irrespective of whether user information is collected or not.
If there's no privacy policy, I could help draft one.

**Comment by atm1504** [comment]
@HarryHeights we have a fragment devoted to the Privacy. You can read it by going to settings and then privacy(last option in settings page).

**Comment by HarryHeights** [comment]
My bad. I just saw it now. Btw I'm experiencing a reoccurring crash.

**Comment by atm1504** [comment]
Can you please mention where did you experience that?

**Comment by HarryHeights** [comment]
Is it okay if I open a more detailed issue of the bug?

**Comment by atm1504** [comment]
Yah. You can create the issue for the bug you found. Also, do provide a detail description of the bug.

**Comment by atm1504** [comment]
@HarryHeights can you please close the issue, as privacy is already present in the app
