### ISSUE TITLE
(BUG)[susi_android Version 1.0.14 ] The application crashes when I click the try it button

### ISSUE THREAD

**Issue by XAMIR555** [fossasia/susi_android#2244]
#### Project Information
* Repository--------------:[Here](https://github.com/fossasia/susi_android)
* Project Name----------:  [ SUSI.AI](https://play.google.com/store/apps/details?id=ai.susi&ah=dWLy7rQKg16yxp3OLlfGsqjnp8c)
* Publisher---------------:  [FOSSASIA ](https://github.com/fossasia)
* My GitHub account-----:  [Here](https://github.com/XAMIR555)

#### Expected behavior
The app should not crash when I click on the try button, all the applications should appear in the try it button 

#### Actual behavior
The application crashes when I click the try button

#### How to reproduce
* open the application
* At the top right click the Blue icon 
* click on  GCI option 
* click on the try it button
* Note the Bug

* Browser/App version-: 1.2.0
* Operating system----: 8.1.0

#### Recording Of The Bug
![20190603_163552](https://user-images.githubusercontent.com/49812927/58799300-d590ee80-85b9-11e9-8383-17102fa89551.gif)

# Logcat

<pre><code>06-03 16:30:54.041 27289 27289 E AndroidRuntime: FATAL EXCEPTION: main
06-03 16:30:54.041 27289 27289 E AndroidRuntime: Process: ai.susi, PID: 27289
06-03 16:30:54.041 27289 27289 E AndroidRuntime: java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{53c6c1a position=9 id=-1, oldPos=-1, pLpos:-1 not recyclable(0) no parent} android.support.v7.widget.RecyclerView{4674119 VFED.V... .F....ID 0,0-720,1268 #7f0900f1 app:id/rv_chat_feed}, adapter:org.fossasia.susi.ai.chat.adapters.recycleradapters.ChatFeedRecyclerAdapter@82285de, layout:android.support.v7.widget.LinearLayoutManager@330d3bf, context:org.fossasia.susi.ai.chat.ChatActivity@94d2d01
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:915)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8317)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8282)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1571)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:597)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1858)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:847)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:771)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1027)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:809)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7555)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
06-03 16:30:54.041 27289 27289 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: FATAL EXCEPTION: main
06-03 16:31:11.640 27478 27478 E AndroidRuntime: Process: ai.susi, PID: 27478
06-03 16:31:11.640 27478 27478 E AndroidRuntime: java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{541201e position=11 id=-1, oldPos=-1, pLpos:-1 not recyclable(0) no parent} android.support.v7.widget.RecyclerView{905f5bb VFED.V... .F....ID 0,0-720,1268 #7f0900f1 app:id/rv_chat_feed}, adapter:org.fossasia.susi.ai.chat.adapters.recycleradapters.ChatFeedRecyclerAdapter@20acad8, layout:android.support.v7.widget.LinearLayoutManager@3765e31, context:org.fossasia.susi.ai.chat.ChatActivity@5c887d5
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:915)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8317)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8282)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1571)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:597)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1858)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:847)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:771)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1027)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:809)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7555)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
06-03 16:31:11.640 27478 27478 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
</code></pre>

**Comment by atm1504** [comment]
@XAMIR555 thank you for reporting the bug. I will surely look into it.

**Comment by XAMIR555** [comment]
Welcome sir

**Comment by atm1504** [comment]
Yah I was able to reproduce the bug in the way u said. I will be looking for it tonight.
