### ISSUE TITLE
Issue with text to speech

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#225]
**Actual Behaviour**

Each time user scroll up chat message and then scroll to last message text to speech service wake up.
**Expected Behaviour**
text to speech service should not wake up Each time user scroll up chat message and then scroll to last message.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

_LogCat for the issue_*

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
Yes I would like to work on this.

**Comment by betterclever** [comment]
Same is happening when someone reopens the app.
