### ISSUE TITLE
Incorrect toast messages on rating SUSI response

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#2254]
**Describe the bug**

Three toast messages appear on rating SUSI response when the internet connection is off.

**Expected Behaviour**

When the internet connection is off and the user tries to rate a response, there should be only one toast/snackbar (preferred) message that should be displayed informing the user about no internet connection or error in rating skill.

**Steps to reproduce it**

Open SUSI Android app.
Open the chat activity.
Chat with SUSI.
Turn off the internet connection.
Try rating a response.

There would be three toast messages appearing in sequence. First two with the message "Thank you for responding". The third one "Unable to rate skill...."

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Xiaomi Redmi Note 4 |
|Android Version| Android 7.0 (API 24) |

**Would you like to work on the issue?**

No, anybody who wishes to work may claim the issue by commenting below.

**Comment by sonusourav** [comment]
Can I work on this?

**Comment by atm1504** [comment]
@sonusourav as mentioned in today's scrum, I have already started working in this issue. Please find some other issues. Thank you :)

**Comment by sonusourav** [comment]
Cool, best of luck 👍
