### ISSUE TITLE
Propose and implement language handling of Susi

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#226]
Currently the app only offers English. How should we deal with languages?

Users have defined their language already in their mobile phone settings, but we also have use cases where a user could communicate in Susi in another language, e.g. a German user speaks English with Susi.

**Expected Behaviour**

Please propose ways to handle languages and UI design.

**Comment by gogeta95** [comment]
we can just detect the language of every message and send response accordingly? 
The flow would be 
1. use https://detectlanguage.com/ to detect language of message in server 
2. translate it back to english(IF server supports english only right now), generate response
3. then use google translator api to send response translated into detected language in step 1.

**Comment by mariobehling** [comment]
Closing this issue in favor of https://github.com/fossasia/susi_android/issues/350
