### ISSUE TITLE
Add resend message option in chat messages

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2260]
**Describe the feature you'd like**
There are many situations where a user wants to query an already queried message. He might re-query questions like what is the time, or he needs to query again if there were some internet connectivity issues. In such cases the users need to write the complete message again. There should be a small icon which when clicked should automatically query the question(put the message) and the user should be able to get the response.

**Additional context**
Some of my friends suggested me to have such kind of feature. IT would be very helpful if we have so. I personally will also like to have similar features.

**Screenshots**
<img width="406" alt="Screenshot 2019-06-11 at 11 45 24 PM" src="https://user-images.githubusercontent.com/43731599/59296907-a870ca00-8ca4-11e9-99e5-a77c1d9fb40e.png">

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
@iamareebjamal @mariobehling @batbrain7 @arundhati24 please put your views on it.

**Comment by mariobehling** [comment]
Please demonstrate if Google or Alexa have this feature. If not this is out of scope.

**Comment by atm1504** [comment]
@mariobehling Yes, a similar feature is present in google assistant app but implemented in a different way. What happens there is that if we just click the message sent by us, it automatically gets added to the query box. So, the user can resend the message now, without rewriting it again.

**Comment by atm1504** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43731599/59334730-bc561380-8d18-11e9-9619-69db9c8e35c6.gif)
