### ISSUE TITLE
Communication to ipinfo.io is not permitted by network policy

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2268]
**Describe the bug**
Currently, there exist some network connection errors, while connecting to ipinfo.io. These errors are shown in the log.

**Expected Behaviour**
Such errors should not exist.

**Steps to reproduce it**
Open logcat at the android studio, now open the app.

**LogCat and Screenshot for the issue**
<img width="1680" alt="Screenshot 2019-06-17 at 11 29 05 AM" src="https://user-images.githubusercontent.com/43731599/59581888-031a8380-90f4-11e9-83ac-a292a6948b4d.png">

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 5 Pro |
|Android Version| Pi 9.0  |

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
This issue has been resolved in #2263

**Comment by iamareebjamal** [comment]
Change http to https
