### ISSUE TITLE
Cursor not visible in SendMessage Layout

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#227]
**Actual Behaviour**

Cursor is not visible in SendMessage Layout possibly because it is white due to colorAccent being white.

**Expected Behaviour**

It must be visible.

**Steps to reproduce it**

Open Susi App MainActivity and notice the invisibility of cursor in sendMessageLayout

*LogCat for the issue**

Not Required

**Screenshots of the issue**

![screenshot_20161017-070732](https://cloud.githubusercontent.com/assets/16309034/19423001/7d161e98-9439-11e6-85c0-cc9ca33ccabb.png)

See that cursor is not visible even though layout is open.

PS: Timing of screenshot is not the reason.

**Would you like to work on the issue?**

Sure.

**Comment by betterclever** [comment]
@jig08 I wish to solve 3 issues in my one commit in my next PR, what should I name it according to current code practices?

**Comment by shealini** [comment]
I wanna take up this issue

**Comment by daminisatya** [comment]
@betterclever Please make three separate PRs. It's the suggested practice.
