### ISSUE TITLE
Communication to api.duckduckgo.com is not permitted by network policy

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2272]
**Describe the bug**
Currently, there exist some network connection errors, while connecting to ipinfo.io. These errors are shown in the log.

**Expected Behaviour**
Such errors should not exist.

**Steps to reproduce it**
Open logcat at the android studio, now open the app. Type the search message " Search something in web"

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 5 Pro |
|Android Version| Pi 9.0  |

**Would you like to work on the issue?**
Yes

#### The issue is similar to #2268 #1743 . So it would be solved in #2263

**Comment by iamareebjamal** [comment]
No, as I told. Replace http with https. ClearText is not the solution
