### ISSUE TITLE
Connecting smart speaker to app when device already connected to another wifi

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2278]
**Describe the bug**
In some cases, the app is failing to connect to the smart speaker, when my device is connected
to the wifi. It's not happening in all cases. But sometimes its happening.

**Expected Behaviour**
The app should be able to connect to the smart speaker in all cases. Though a part of it was solved in #2252 , but more such cases should be handled.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | RedMI Note 5 Pro|
|Android Version| Pi 9.0    |

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
The problem is arising because of auto connect to wifi feature of Android. What's happening is that I am able to connect to the susi.ai hotspot. But if my device is already connected to another wifi, what the android system is doing is that after some time of successful connection to the speaker, it is automatically getting disconnected from the susi.ai hotspot and connecting itself to other networks. The probable reason behind it is that the susi.ai hotspot doesn't provide internet. So, wifi assistant is connecting the wifi to another network.
If the wifi assistant is disabled, then the app works properly even if my device is connected to any network.

@iamareebjamal @batbrain7 @mariobehling @arundhati24 this is the main problem. I don't think we can control the flow of wifi assistant programatically.

**Comment by atm1504** [comment]
@batbrain7 most of the wifi manager components have been deprecated from API level 28. So, we are facing this issue. Now to add a network or disable or to prevent auto connect we need to use NetworkSPecifier and WifiNetworkSpecifier. I searched about it on google but no proper documentation is available as of now. Can you please in implementing it?

Links for documentation that I got:
* https://developer.android.com/reference/android/net/wifi/WifiNetworkSpecifier.Builder.html#build()
* https://developer.android.com/reference/android/net/NetworkSpecifier
* https://developer.android.com/reference/android/net/wifi/WifiNetworkSpecifier

**Comment by batbrain7** [comment]
@atm1504 check this out here in this [link](https://developer.android.com/reference/android/net/wifi/WifiManager
): 
![Screenshot 2019-07-02 at 12 17 45 AM](https://user-images.githubusercontent.com/16780496/60459491-f7d06780-9c5e-11e9-9be1-e583f50ac6e4.png)

try using these functions which are written as an alternative for the deprecated `disableNetwork(int) `function

**Comment by atm1504** [comment]
@batbrain7 tried to implement it. But no proper documentation is available on how to use this functions. I googled a lot, but didn't get any solution.

**Comment by atm1504** [comment]
@iamareebjamal please close. It has been resolved. We don't use this method any more.
