### ISSUE TITLE
Text To Speech not working in LinkPreviews and PieChart

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#228]
**Actual Behaviour**

The TTS is not functional in LinkPreview and PieChart Message Types.

**Expected Behaviour**

It must be working.

**Steps to reproduce it**

Not required.

*LogCat for the issue**

Not Applicable.

**Screenshots of the issue**

Not Applicable.

**Would you like to work on the issue?**

Sure.

**Comment by YashishDua** [comment]
Can I take up this Issue ?

**Comment by betterclever** [comment]
Solved. Hence closing.
