### ISSUE TITLE
Sometime the app fails to add the device to the server.

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2290]
**Describe the bug**
Sometimes the app is failing to add the device to the server when I have the device setup. The reason behind failure is internet connectivity.
*  What we should do is that we should implement a delay of about 2 seconds before trying to make a request to the server. By this time our phone will get disconnected to the smart speaker hotspot.  

**Would you like to work on the issue?**
Yes

**Comment by atm1504** [comment]
**The main problem:**
A request to add the device to the server is made only after the successful verification of the password during the device setup. But, immediately after succesfull password verification, the susi hotspot goes off and there is a switching between network occurs. Also, we don't have any access to the internet during the setup process of the device. The reason behind this is that the susi hotspot does not provide any internet.

Now, because of this switching of the internet sometimes the retrofit client is failing to send the request to the server. And we are failing to add the device to the server.

**Probable solution:**
It would best if the request to add the device to the server is made from the smart speaker after password verification is successful. All the required data like ```room name, location, macid, speaker name ``` can be sent to the smart speaker from the android app. It would be able to do so because it has an internet connection for itself. Probably this is the solution that is used in google home to overcome this problem.

**Comment by atm1504** [comment]
@iamareebjamal what do u think we should do. 
Mainly two options:
* Send a request from the smart speaker(by getting the relevant data from the app) to the server
**or**
* Use a database in the app and save the query in it. Try to resend the request to the server until it is successful, and clear the query from the database after success.

I personally think the 1st option would be better.

**Comment by iamareebjamal** [comment]
Which is easier?

**Comment by atm1504** [comment]
1st option is much easier and would be more efficient. Because, in 2nd option, there might be excess memory usage or memory leaks.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by atm1504** [comment]
I am closing this issue, as we have shifted the plan to add the device from the hardware itself, instead of doing that from the app.
