### ISSUE TITLE
Add Copy, Delete and Share Options in the Appbar / ActionBar

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#230]
**Actual Behaviour**

Currently, copy and delete option are available by long pressing the views. 

**Expected Behaviour**

It can be implemented in the ActionBar itself such that on long press on any message, its color changes and options are displayed there. It will also enable us to enable muliple deletion.

**Steps to reproduce it**

Not Required

*LogCat for the issue**

Not Applicable.

**Screenshots of the issue**

Not Required

**Would you like to work on the issue?**

Sure.

**Comment by replyashu** [comment]
I want to take up this issue

**Comment by betterclever** [comment]
It has been already assigned to me currently and I have started working on it. You may look for other issues or raise your own.

**Comment by betterclever** [comment]
@daminisatya @jig08 @the-dagger Have a look!!

Multi-Delete
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/16309034/19518821/c36d6e02-9626-11e6-80ff-3f93dbcf741d.gif)

Multi-Copy
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/16309034/19518979/6f618590-9627-11e6-93b0-dcb6967f2f30.gif)

Multi Share is also working fine.

**Comment by the-dagger** [comment]
Looks good @betterclever
