### ISSUE TITLE
Add changes to fdroid metadata

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#2301]
Latest changes are not compatible with fdroid build server, please add these to the fdroid metadata

https://gitlab.com/fdroid/fdroiddata/merge_requests/5053/diffs

https://gitlab.com/fdroid/fdroiddata/merge_requests/5055/diffs

**Comment by atm1504** [comment]
@iamareebjamal I have made the suggested here : https://gitlab.com/fdroid/fdroiddata/merge_requests/5084

Please review it

**Comment by atm1504** [comment]
@iamareebjamal please close it. The pr in gitlab has already been merged
