### ISSUE TITLE
Back button missing in Chat Search Activity

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2355]
**Describe the bug**
The back button is missing in chat search activity. Add a back button in the action bar. Also, show the searched query in the action bar if possible.

**Steps to reproduce it**
* Search for some keywords in the chat page
* The search results appear in an activity that has no back button.

**Screenshots of the issue**
![Screenshot_2019-08-20-19-36-46-716_ai susi](https://user-images.githubusercontent.com/43731599/63427564-09e6af00-c433-11e9-9d0e-5cb4c6d26a5a.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | RedMi Note 5 Pro|
|Android Version| Pi 9.0   |

**Would you like to work on the issue?**
Yes

**Comment by rajput2122** [comment]
Can I work on this?

**Comment by atm1504** [comment]
> Can I work on this?

I have already made a pr for this issue. It's open for review. You can work on issue https://github.com/fossasia/susi_android/issues/2364
