### ISSUE TITLE
Update the readme file

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2364]
**Describe the chore**
Update the latest information, features of the app, screenshots in the readme file. Mention about susi smart speaker configuration feature. 

**Would you like to work on the issue?**
No. Anybody can grab it.

**Comment by Zyro9922** [comment]
Yes, I want to work on it.

**Comment by Zyro9922** [comment]
Where do I have to update it? In this Readme https://github.com/fossasia/susi_android/blob/development/README.md ?

<blockquote><img src="https://avatars1.githubusercontent.com/u/6295529?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/fossasia/susi_android">fossasia/susi_android</a></strong></div><div>SUSI.AI Android App https://play.google.com/apps/testing/ai.susi - fossasia/susi_android</div></blockquote>

**Comment by liveHarshit** [comment]
> Where do I have to update it? In this Readme https://github.com/fossasia/susi_android/blob/development/README.md ?
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/6295529?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[fossasia/susi_android](https://github.com/fossasia/susi_android)**SUSI.AI Android App https://play.google.com/apps/testing/ai.susi - fossasia/susi_android

What will you update?


> Update the latest information, features of the app, screenshots in the readme file. Mention about susi smart speaker configuration feature.

@atm1504 I think new contributors are not aware of it. Either you should provide the details or update the README.

<blockquote><img src="https://avatars1.githubusercontent.com/u/6295529?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/fossasia/susi_android">fossasia/susi_android</a></strong></div><div>SUSI.AI Android App https://play.google.com/apps/testing/ai.susi - fossasia/susi_android</div></blockquote>
<blockquote><div><strong><a href="https://play.google.com/apps/testing/ai.susi">Sign in - Google Accounts</a></strong></div></blockquote>

**Comment by atm1504** [comment]
@liveHarshit @Zyro9922 I will write a comment explaining about the details that one need to update and also some of the screenshots of device setup page.

**Comment by atm1504** [comment]
Details to be updated in the readme file: 
* Update the screenshots, I will attach few at the end of the comment, update them accordingly in the readme file
* Under ```Roadmaps``` add a point about ```Susi Smart Speaker Configuration and Control```
* Under ```Libraries used and their documentation``` section add the following:  
* * Play services authentication (Smart Lock for Passwords on Android) - https://developers.google.com/identity/smartlock-passwords/android/store-credentials

![Screenshot_2019-08-20-19-33-45-054_ai susi](https://user-images.githubusercontent.com/43731599/63771922-b45c4780-c8f5-11e9-8422-5859510e8e52.png)
![Screenshot_2019-08-20-19-33-57-977_ai susi](https://user-images.githubusercontent.com/43731599/63771923-b4f4de00-c8f5-11e9-85ab-aa97db4c8285.png)
![Screenshot_2019-08-20-20-38-40-632_ai susi](https://user-images.githubusercontent.com/43731599/63771924-b4f4de00-c8f5-11e9-94ff-785afcfb7ba3.png)
![Screenshot_2019-08-20-20-39-01-160_ai susi](https://user-images.githubusercontent.com/43731599/63771925-b4f4de00-c8f5-11e9-8cbb-874b1df9f114.png)
![Screenshot_2019-08-25-20-34-01-762_ai susi](https://user-images.githubusercontent.com/43731599/63771926-b58d7480-c8f5-11e9-8b8b-98361438ea7e.png)



<blockquote><img src="https://developers.google.com/_static/965372ada8/images/share/devsite-google-green.png" width="48" align="right"><div>Google Developers</div><div><strong><a href="https://developers.google.com/identity/smartlock-passwords/android/store-credentials">Store a user's credentials  |  Smart Lock for Passwords on Android
       |  Google Developers</a></strong></div></blockquote>
