### ISSUE TITLE
Fix margin and paddings in Manage Device page

### ISSUE THREAD

**Issue by atm1504** [fossasia/susi_android#2366]
**Describe the feature you'd like**
Proper padding and margins are not present in the manage device page. Please update the uniform padding margin there.

**Screenshots**
![Screenshot_2019-08-28-11-24-15-409_ai susi](https://user-images.githubusercontent.com/43731599/63830163-187c1b80-c989-11e9-8d19-7504f6049f39.png)

**Would you like to work on the issue?**
No. Anyone can grab it

**Comment by rajput2122** [comment]
Can I work on this issue?

**Comment by atm1504** [comment]
> Can I work on this issue?

Yes. Go ahead

**Comment by rajput2122** [comment]
I am testing on my phone. There is no any Manage device option appear so that I check the layout. Can you please help me with how to navigate to manage device activity?. Actually there is a managedevice preference in chatsettingfragment but in XML file there is no preference created for manage device.
![Screenshot_20190828-170327_SUSIAI](https://user-images.githubusercontent.com/43101744/63852241-7c1c3e00-c9b5-11e9-9265-010da2a8d060.jpg)

**Comment by rajput2122** [comment]
Even if i created preference screen for manage device now also option is not showing when i run app in my device and also device setup section is not showing up.Can you please help?
![susi](https://user-images.githubusercontent.com/43101744/63854232-56ddfe80-c9ba-11e9-82c6-213497e1d4da.png)

**Comment by atm1504** [comment]
You need to be logged in, to get access to this portion of the code in the app. So, login into your app. This portion of the setting will appear then.

**Comment by rajput2122** [comment]
okk sir

**Comment by rajput2122** [comment]
if i am signing up with new id it is showing that email is already exist but i have not registered with that email even once can you please help sir . i want to fix this issue today

**Comment by liveHarshit** [comment]
> if i am signing up with new id it is showing that email is already exist but i have not registered with that email even once can you please help sir . i want to fix this issue today

Open an issue with proper logs from logcat. 
@atm1504 Is [Stetho](https://github.com/facebook/stetho) library added to the app?

**Comment by rajput2122** [comment]
No sir Stetho library is not added in build.gradel app level file

**Comment by atm1504** [comment]
> Open an issue with proper logs from logcat.
> @atm1504 Is [Stetho](https://github.com/facebook/stetho) library added to the app?

No. We need to add it. WIll look into it.

**Comment by rajput2122** [comment]
@atm1504  Sir, Can you please guide me what to do now?

**Comment by atm1504** [comment]
> @atm1504 Sir, Can you please guide me what to do now?

Show the logcat. Whats the error coming.

**Comment by rob729** [comment]
@rajput2122 Are you working on this issue?

**Comment by rajput2122** [comment]
Yaa

**Comment by iamareebjamal** [comment]
It's been 12 days now. Let someone else take the issue

**Comment by rob729** [comment]
@iamareebjamal Can I work on this issue?

**Comment by atm1504** [comment]
@rob729 go ahead.

**Comment by rajput2122** [comment]
Actually sir i have done this but i had mentioned that there was problem
when sign up to app with new mail id even i am signing up with new device
showing email was already registered

**Comment by iamareebjamal** [comment]
You were asked to explain the error. You gave no response. We expect the contributor to follow up with queries ASAP. You can't stay silent for 2 weeks and stop others from working on the issue.

**Comment by rajput2122** [comment]
Sorry for the late reply

**Comment by rob729** [comment]
<img src="https://user-images.githubusercontent.com/31350501/64635016-46973c00-d41c-11e9-83f8-37edb7abe0f6.jpg" alt="drawing" width="250"/>
@atm1504 I am not able to get the "Manage Devices" option even after I logged in the app.
Can you tell how to access the manage the device?

**Comment by atm1504** [comment]
@rob729 open ChatSettingsFragment, there you will find a condition check, to display menu actions. Go through that portion of the code, you will understand it.

**Comment by rob729** [comment]
@atm1504 Can you please specify the view in which I have to change the padding?

**Comment by atm1504** [comment]
This is the file for Settings Preference: https://github.com/fossasia/susi_android/blob/development/app/src/main/res/xml/pref_settings.xml

For Manage Device: https://github.com/fossasia/susi_android/blob/development/app/src/main/res/layout/fragment_music_servers.xml


<blockquote><img src="https://avatars1.githubusercontent.com/u/6295529?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/fossasia/susi_android">fossasia/susi_android</a></strong></div><div>SUSI.AI Android App https://play.google.com/apps/testing/ai.susi - fossasia/susi_android</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/6295529?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/fossasia/susi_android">fossasia/susi_android</a></strong></div><div>SUSI.AI Android App https://play.google.com/apps/testing/ai.susi - fossasia/susi_android</div></blockquote>

**Comment by rob729** [comment]
@atm1504 I am asking whether to change the padding of cardview containing Spotify or something else?

**Comment by rob729** [comment]
@atm1504 Can you specify the view in fragments_music_server.xml where padding has to be changed?

**Comment by atm1504** [comment]
@rob729 I hope I have stated the bug properly also have attached a screenshot. Its on your part what are you going to change to fix it up.

**Comment by Zyro9922** [comment]
@atm1504 Can I work on this?

**Comment by rob729** [comment]
@Zyro9922 I am already working on it.
