### ISSUE TITLE
Add Stetho debug bridge

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/susi_android#2368]
Docs: https://github.com/facebook/stetho

**Would you like to work on the issue?**

Good first issue

**Comment by KKS161994** [comment]
Yes I would.I have cloned and compiled the project Also I have added the stetho dependency and initialised it in MainApplication . What more should I do to commit it for pull request.

**Comment by liveHarshit** [comment]
> Yes I would.I have cloned and compiled the project Also I have added the stetho dependency and initialised it in MainApplication . What more should I do to commit it for pull request.

https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

<blockquote><div><strong><a href="https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/">Open Source Developer Guide and Best Practices at FOSSASIA | blog.fossasia.org</a></strong></div><div>I would request you to please guide me as to how can I collaborate with you and also how can I contribute effectively to the organization. At times I might get</div></blockquote>

**Comment by liveHarshit** [comment]
Fixed #2371
