### ISSUE TITLE
Improving chat box UI

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#237]
**Actual Behaviour**

If there are even only six messages it covers the whole screen of chat box.
**Expected Behaviour**

As in popular message app the chat box can be made a little concise to provide more space in a single view.

- [x] Place the timestamp in par with the text. 

- [x] Make the chat bubbles flatter. Reducing the spacing between each bubble to a reasonable amount.

**Would you like to work on the issue?**

Yes

**Comment by daminisatya** [comment]
@mayank408 What sort of design are you referring to? This?

https://cloud.githubusercontent.com/assets/6227784/19443251/c78067ca-94a9-11e6-873a-7c96d952e66b.jpg

**Comment by mayank408** [comment]
@daminisatya Ya ya something of this kind so that each message take less space.

**Comment by mayank408** [comment]
@daminisatya Is it already assigned to someone or i can work on it??

**Comment by the-dagger** [comment]
@mayank408 You can go ahead and work on it.

**Comment by daminisatya** [comment]
- [ ] Place the timestamp in par with the text. 

- [ ] Make the chat bubbles flatter. Reducing the spacing between each bubble to a reasonable amount.

**Comment by the-dagger** [comment]
@daminisatya Maybe add these pointers to the issue?

**Comment by daminisatya** [comment]
@mayank408 Please provide the sample before you create a PR :) That would reduce the number of review iterations.

**Comment by mayank408** [comment]
@daminisatya @the-dagger Ya sure , once I am done I will send a screen shot .

**Comment by mayank408** [comment]
![whatsapp image 2016-10-18 at 1 25 05 am 1](https://cloud.githubusercontent.com/assets/22056321/19453233/039396a6-94d2-11e6-9879-cd42ecb66465.jpeg)
![whatsapp image 2016-10-18 at 1 25 05 am](https://cloud.githubusercontent.com/assets/22056321/19453235/049f169c-94d2-11e6-865a-beae92b22ef1.jpeg)

**Comment by the-dagger** [comment]
The top/bottom margins in chatbox can be made even smaller.

**Comment by mayank408** [comment]
@the-dagger 2dp will be right..

**Comment by mayank408** [comment]
![whatsapp image 2016-10-18 at 1 46 08 am](https://cloud.githubusercontent.com/assets/22056321/19453900/bc33b0ea-94d4-11e6-8ae7-fed9c9d4e371.jpeg)

**Comment by the-dagger** [comment]
@mayank408 1dp should be perfect I guess.
Could you try that?

**Comment by mayank408** [comment]
@the-dagger  Margins decreased to 1dp

![whatsapp image 2016-10-18 at 11 07 43 pm](https://cloud.githubusercontent.com/assets/22056321/19489185/d17f2a2a-9587-11e6-9b55-a756b31937eb.jpeg)

**Comment by YashishDua** [comment]
Is Issue closed or still open ?
If open Can I take up the issue ?

**Comment by jig08** [comment]
@mayank408 Updates pls ?

**Comment by mayank408** [comment]
@jig08 @the-dagger @daminisatya If the above chatbox layout is not satisfying , then I think we should try to make a drawable for chat bubble that is impressive and can be taken as background for messages.

**Comment by mayank408** [comment]
@the-dagger We can close this issue as it is already being worked on issue #265 .
