### ISSUE TITLE
Add show password option in Signup Activity

### ISSUE THREAD

**Issue by dipu989** [fossasia/susi_android#2391]
**Describe the feature you'd like**
Add option for show password in Confirm Password field of Signup Activity.

**Would you like to work on the issue?**
Open For All

**Comment by jatinsachdevame** [comment]
Yes, I would like to work on this issue.

**Comment by siddharth952** [comment]
Would like to work on this!

**Comment by dheerajkotwani** [comment]
@siddharth952 I had solved the issue
