### ISSUE TITLE
Issue with Email field of login screen

### ISSUE THREAD

**Issue by aakashkhatter1296** [fossasia/susi_android#240]
**Actual Behaviour**

On pressing the Enter key when email field is in focus, a new line is added and the text field extends.

**Expected Behaviour**

- [ ] The text field should not extend when Enter is pressed.
- [x] Remove hardcoded strings from activity_login.xml

**Steps to reproduce it**

1) Open Login Screen.
2) With the Email field in focus, press Enter key multiple times.

**Screenshots of the issue**

![screenshot_20161017-231129](https://cloud.githubusercontent.com/assets/10905662/19448472/9b64f92e-94bf-11e6-9b33-45c6d7e02318.jpg)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by aakashkhatter1296** [comment]
@the-dagger Also there are hard-coded strings in activity_login.xml . Should I create a new issue for that ?

**Comment by the-dagger** [comment]
@aakashkhatter1296 it would be great if you could add that as a sub issue to this issue itself.

**Comment by jig08** [comment]
Only "Remove hardcoded strings from activity_login.xml" was taken care of, re-opening this issue.

**Comment by aakashkhatter1296** [comment]
@jig08 I think both the issues have been taken care of. The issue that 'The text field should not extend when Enter is pressed' has been taken care of as well, I just tested it.

**Comment by jig08** [comment]
Yep, works fine.
