### ISSUE TITLE
Name not being displayed

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/susi_android#2404]
**Describe the bug**
On chatting with the AI bot in the app,
By sending the message as "Hi"
The reply comes as follows "Hello this is SHUBHAM BOT How may i help you?"

**Expected Behaviour**
The expected reply is :
"Hello this is SUSI.AI .How may i help you?"

**Steps to reproduce it**
Open the ai bot either in app or web integration and send a "hi" message.

**LogCat for the issue**

**Screenshots of the issue**
![Screenshot_2019-12-09-12-15-42-281_ai susi](https://user-images.githubusercontent.com/34577844/70414878-56590780-1a81-11ea-8366-8f1187b53ccd.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 5A|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**

**Comment by shashwatjolly** [comment]
@iamareebjamal This seems to be an issue for susi-server. 
The action returned by the GET request has this problematic expression. Nothing in the client is responsible.
