### ISSUE TITLE
Incorrect Display of Bot Name On typing certain Queries

### ISSUE THREAD

**Issue by aryanguls** [fossasia/susi_android#2407]
**Describe the bug**
On typing "hi" as a query in the SUSI AI bot it replies by stating that its name has been set as SHUBHAM Bot and not as SUSI AI Bot. Of course on typing hello or something it gives a different response

**Expected Behaviour**
I expected to sat that its ne=ame was SUSI or SUSI AI bot and not SHUBHAM Bot.

**Steps to reproduce it**
1)Go to the SUSI AI App.
2)Type "hi" as your query.
3)It will respond as SHUBHAM Bot.

**Screenshots of the issue**
![Screenshot_2019-12-10-17-37-54-282_com google android apps photos (1)](https://user-images.githubusercontent.com/58459496/70623894-15115500-1c45-11ea-82e7-c04b1c2f09c9.jpg)
![Screenshot_2019-12-10-17-37-49-001_com google android apps photos (1)](https://user-images.githubusercontent.com/58459496/70623920-23f80780-1c45-11ea-89fd-bdd9e1f3753e.jpg)

**Would you like to work on the issue?**
Yes, given the option i would like to work to solve this issue.

**Comment by iamareebjamal** [comment]
Duplicate
