### ISSUE TITLE
Invalid Registration

### ISSUE THREAD

**Issue by sheuabdulazeez** [fossasia/susi_android#2413]
#2413 #1766 
 My email was having invalid registration. Whenever I want to create account, it display a pop up that my email is registered and when I wanted to log in, it displayed that my email is not recognized with any account

**Comment by TheJonny** [comment]
also for me
![Screenshot_20191231-183216_SUSIAI](https://user-images.githubusercontent.com/6079163/71629230-aea4a480-2bfc-11ea-95df-2dcc9ce5fe02.jpg)

![Screenshot_20191231-183221_SUSIAI](https://user-images.githubusercontent.com/6079163/71629196-7ac97f00-2bfc-11ea-9fdf-78c2e8875a66.jpg)

is yours the same problem?
