### ISSUE TITLE
Unable to answer.

### ISSUE THREAD

**Issue by atulks26** [fossasia/susi_android#2417]
**The app stops answering and shows 'Internet Connectivity Problem' in between the conversation.**

**The app should answer correctly and in case it does not know the answer it should display a message accoridingly.**

**Ask 'SUSI, what's your age?' and after some time it will show Internet Connectivity Problem'.**

![Screenshot_2019-12-19-16-16-37-18_8f810d6b56482a9a7f5d8c4ab648ebcc](https://user-images.githubusercontent.com/58624657/71167749-1d036300-220a-11ea-9dcb-343860a7b04b.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oppo A5 2020|
|Android Version|Pie 9    |

**No, I would not like to work on the issue.**

**Comment by iamareebjamal** [comment]
Duplicate
