### ISSUE TITLE
App crashes on taking screenshot

### ISSUE THREAD

**Issue by serializer** [fossasia/susi_android#2420]
**Describe the bug**

On the ChatActivity screen, when I use 3-finger gesture to take screenshot, the app crashes.

**Expected Behaviour**

App shouldn't have crashed.

**Steps to reproduce it**

1. Go to ChatActivity
2. Use any gesture like fling.
3. App crashes after one or two times.

**LogCat for the issue**
![Screenshot (100)](https://user-images.githubusercontent.com/31654207/71308857-709ec800-2427-11ea-8ec3-faa4802c465d.png)

**Screenshots of the issue**
![ezgif-2-b1df41ba33f8](https://user-images.githubusercontent.com/31654207/71308873-8613f200-2427-11ea-9d6b-e3710261396b.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Mi Note 5 |
|Android Version| Oreo 8.1   |

**Would you like to work on the issue?**
Yes

**Comment by pallav12** [comment]
Apparently not an issue in Oppo A3s, Android Version oreo 8.1

**Comment by serializer** [comment]
@pallav12 are you using hand gestures to take a screenshot?

**Comment by pallav12** [comment]
My bad, sometimes it does crash, but most of the times it doesn't. And its hard to find pattern, but if you clear app from background then it'll never crash.

**Comment by serializer** [comment]
I have found the issue through the logcat. I can fix it but no maintainer is active I guess.

**Comment by atm1504** [comment]
@tronku if u can solve it, please do it

**Comment by serializer** [comment]
Please review the pull request.
