### ISSUE TITLE
Map feature broken

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#243]
**Actual Behaviour**

Map is not rendering both image and text are gone. click listener also not working.

**Expected Behaviour**

Map Image and text should be shown.  click listener also should be working.

**Steps to reproduce it**

ask for any place.

**Screenshots of the issue**

![image](https://cloud.githubusercontent.com/assets/8329096/19455665/8672b3f0-94db-11e6-9147-4711f3a89d7c.png)

**Would you like to work on the issue?**

yes

**Comment by daminisatya** [comment]
Very sad to know, that a bug like this got regressed.

**Comment by betterclever** [comment]
It is due to a wrong "if" condition block in line number 369 ChatFeedRecyclerAdapter.java, the map will show if user has opted for speech output.

**Comment by betterclever** [comment]
@daminisatya #245 fixes this issue too.

**Comment by amitiwary999** [comment]
I already solved this issue in my previous pr.

**Comment by gogeta95** [comment]
@amitiwary999 then why isn't it mentioned anywhere?

**Comment by amitiwary999** [comment]
@gogeta95 because when I solving issuec#225 at that time I was not aware with this issue and changed the code.when @betterclever give the reason of this issue then I came to know that I solved this issue also.
