### ISSUE TITLE
Bug in login in and signing up

### ISSUE THREAD

**Issue by muneebGH** [fossasia/susi_android#2434]
**Describe the bug**
I started the app . I never created account on it . I went to sign up . entered email . Got prompt that email already exists. Went to reset password .Reseted the password . tried to login . got prompt that email not registered .

**Expected Behaviour**

it should sign me up because I never created account

**Steps to reproduce it**
go to sign up page . enter inputs with email never registered .

**LogCat for the issue**

**Screenshots of the issue**
![1](https://user-images.githubusercontent.com/49611774/71625363-35f81500-2c09-11ea-8f3a-f523dec19434.jpeg)
![2](https://user-images.githubusercontent.com/49611774/71625367-3c868c80-2c09-11ea-8f47-6db3eec35e47.jpeg)
![3](https://user-images.githubusercontent.com/49611774/71625369-414b4080-2c09-11ea-90c1-c1975998e70e.jpeg)
![4](https://user-images.githubusercontent.com/49611774/71625375-47d9b800-2c09-11ea-94f9-834f072d02b1.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
pixel 3
|Android Version|    |
api 29

**Would you like to work on the issue?**

**Comment by atm1504** [comment]
Duplicate to #2422
