### ISSUE TITLE
Shimmer layout appears even when switching back to SkillListingFragment

### ISSUE THREAD

**Issue by shashwatjolly** [fossasia/susi_android#2438]
**Describe the bug**

When skill list is loaded for the first time, the shimmer layout works as expected. However, switching to any other screen and then coming back to the skill list causes the shimmer layout to overlay on the underlying skill list for some time, preventing user input.

**Expected Behaviour**

The skill list should stay as it is when we come back to it. Reloading of the list happen, which is not necessary in my opinion.

**Steps to reproduce it**

1. Go to Skill List
2. Go to setting or a particular skill details page
3. Go back to the Skill List

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/26327688/71644244-35d04600-2ceb-11ea-9841-f4d4aecc1d0d.png)

**Would you like to work on the issue?**
Yes, taking it up

**Comment by shashwatjolly** [comment]
@atm1504 Should the list be reloaded when coming back to this page or should we remove the reloading?

**Comment by rob729** [comment]
@atm1504  Can I work on this issue?
