### ISSUE TITLE
The app says " No internet connection" even if i have an intenet connection.

### ISSUE THREAD

**Issue by SpinningPulsar** [fossasia/susi_android#2453]
|---------------|-|
|Device         |Samsung Galaxy J7|
|Android Version |  8.1.0  |

![Screenshot_20200112-183327_SUSIAI](https://user-images.githubusercontent.com/17098604/72219295-97ee3e00-356a-11ea-996e-33a28b2340e2.jpg)
When I ask the app some questions the app says that there is no internet connection, even when there is an internet connection.

**Comment by pallav12** [comment]
I've also faced similar issue, I think(not sure) at the time you are using app, susi server is down. So not really susi_android issue, and also somewhat identical to #2429

**Comment by shashwatjolly** [comment]
Yup, most probably an issue with the server.
