### ISSUE TITLE
Sign_in bug

### ISSUE THREAD

**Issue by janWICKEDpro** [fossasia/susi_android#2454]
**Describe the bug**
When trying to sign up to susi.ai it alerts that i already have an account on their servers meanwhile i don't. When i try to login with the email they say already exists it alerts " The email you entered is not registered with us. please try again. 

**Expected Behaviour**
The sign up should create a new account for me immediately i complete it

**Screenshots of the issue**
![Screenshot_20200113-140544 1](https://user-images.githubusercontent.com/42650809/72258655-e8b77280-360e-11ea-9219-d2dac3f23551.png)

**Smartphone Info:**

device name: itel A32f
android version: 8.1

**Comment by atm1504** [comment]
Duplicate of issue #2422
