### ISSUE TITLE
Unable to sign-in or sign-up, internet connectivity problem

### ISSUE THREAD

**Issue by adithyagenie** [fossasia/susi_android#2458]
I am unable to sign-in or sign-up, shows email ID is already registered while signing up but if you click forgot password, shows that email ID is not registered. I am not unable to sign-in too. Tried to use different email address, then too didn't work. 

Shows that there is not internet in SUSI.AI skills page even though there is internet and works fine.

Please fix these issues.

**Comment by shashwatjolly** [comment]
Skills page working fine for me.
I think the server was down a while back, but it's fine right now.
