### ISSUE TITLE
Search bar for skills does not close on going back with android nav button

### ISSUE THREAD

**Issue by shashwatjolly** [fossasia/susi_android#2459]
The search bar for skills closes when we press the action bar back button or the "x" on the search bar. But it does not close when we press the android navigation back button.

**Expected Behaviour**

The search bar should behave the same as it does when the action bar back button is pressed.

**Steps to reproduce it**

1. Press the search button in the Skills page.
2. Repeatedly pressing the android back button does not cause anything. Ideally the search bar should close.

**Would you like to work on the issue?**

Yes

**Comment by rob729** [comment]
@shashwatjolly are you still working on this issue?

**Comment by shashwatjolly** [comment]
@rob729 Yes PR is already up
