### ISSUE TITLE
Issue in password field of the Login Screen

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#246]
**Actual Behaviour**

On entering a password that does not match registration criterion i.e. atleast one letter must be capital and number must be present, warning is shown in login screen too and login is prevented.

**Expected Behaviour**

As per other login interfaces, it must try to login and give failed authentication message instead of giving warning in password field.

**Steps to reproduce it**

Try to enter a wrong password in login field say: abcdef which doesn't specify registration criterion.

*LogCat for the issue**

Not Applicable.

**Screenshots of the issue**

![screenshot_20161018-104032](https://cloud.githubusercontent.com/assets/16309034/19465336/f91c5e66-9520-11e6-8588-396270ff3741.png)

**Would you like to work on the issue?**

Sure.

**Comment by mayank26saxena** [comment]
Can I take up this issue?

**Comment by betterclever** [comment]
@daminisatya @jig08 I've also opted for assignment. Please consider.

**Comment by YashishDua** [comment]
Can I take up the issue ?

**Comment by jig08** [comment]
@mayank26saxena @YashishDua 
@betterclever is already working on this, let's wait for any update from his side.
