### ISSUE TITLE
Sign in/Sign up and Forgot Password issue.

### ISSUE THREAD

**Issue by priyansh0512** [fossasia/susi_android#2461]
During Sign up, When my e-mail isn't registered with SUSI.AI anytime before it says "**E-mail address already exists** Please use the "Forgot password?" option to reset your password". Using the Forget Password option it displays "**Incorrect e-mail address** The e-mail address you entered doesn't belong to an account. Please check your e-mail and try again."
When I tried the other way round by using the Sign in option it says "**E-mail address already exists** The e-mail you entered is not registered with us. Please try again." which completely falsifies the previous message. I tried the same with other e-mail ids but the problem still persists.

**Expected Behaviour**

The app should allow me to Sign up and if in case I had already created an account, it should allow me to reset my password.

**Steps to reproduce it**

1. Download and Install the SUSI.AI Android app on your phone.
2. Open SUSI.AI app on your Android Phone.
3. Tap on "Sign up for SUSI" option.
4. Enter your e-mail address and password.
5. Tap on the "SIGN UP" option.
_A pop-up message stating "**E-mail address already exists** Please use the "Forget password?" option to reset your password" will appear._
6. Tap on "Forgot Password?" option.
_A pop-up message stating "**Incorrect e-mail address** The e-mail address you entered doesn't belong to an account. Please check your e-mail and try again." will appear._
7. Go back to the Sign in page and repeat Step 4.
_A pop-up message stating "**E-mail address already exists** The e-mail you entered is not registered with us. Please try again." will appear which proves that there's a bug in SUSI.AI app during Sign up/Sign in._

**Screenshots of the issue**

![Screenshot_20200116-234039_SUSIAI](https://user-images.githubusercontent.com/59209058/72558873-96ee4100-38c9-11ea-9671-60610815db71.jpg)
![Screenshot_20200116-234143_SUSIAI](https://user-images.githubusercontent.com/59209058/72558881-99509b00-38c9-11ea-9fc0-1c3bf574a5f2.jpg)
![Screenshot_20200116-234210_SUSIAI](https://user-images.githubusercontent.com/59209058/72558903-a1a8d600-38c9-11ea-9cab-dcea31ca4215.jpg)
![Screenshot_20200117-004409_SUSIAI](https://user-images.githubusercontent.com/59209058/72558919-a66d8a00-38c9-11ea-9ab5-5caa790fc009.jpg)
![Screenshot_20200117-004514_SUSIAI](https://user-images.githubusercontent.com/59209058/72558924-a9687a80-38c9-11ea-9588-97a01ce1ef59.jpg)
![Screenshot_20200117-013743_SUSIAI](https://user-images.githubusercontent.com/59209058/72559105-12e88900-38ca-11ea-9ed4-50901f153925.jpg)

**Smartphone Info:**

Device: Samsung Galaxy S7 Edge(SM-G935FD)
Android Version: Oreo 8.0.0

**Would you like to work on the issue?**
 No, I would not like to work on this issue.

**Comment by ankushmundhra** [comment]
I am getting the same issue. Can i work on this issue?
