### ISSUE TITLE
Incomplete Unit and UI testing

### ISSUE THREAD

**Issue by pallav12** [fossasia/susi_android#2462]
**Currently UI testing or susi covers only activity's xml and that also incomplete(only visibility of views are checked), providing minimal value to codebase. There're many important fragments(skill listing fragment) which should be tested.**

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
We want to focus on unit tests. Not UI tests. There are multiple issues open for unit tests
