### ISSUE TITLE
excessive marginTop of RecyclerView + UI enhancment

### ISSUE THREAD

**Issue by viveksb007** [fossasia/susi_android#248]
**Actual Behaviour**

excessive marginTop of RecyclerView

![1](https://cloud.githubusercontent.com/assets/12713808/19479236/62302274-9563-11e6-9fde-93d57d241d8f.png)

**Expected Behaviour**

Should be like this

![2](https://cloud.githubusercontent.com/assets/12713808/19479248/6e470e88-9563-11e6-81a6-4d55accbe313.png)

**Would you like to work on the issue?**

Yes

**Comment by mejariamol** [comment]
would be better if date-view appears over the RecycleView at the top

**Comment by viveksb007** [comment]
@mejariamol yup i guess that could be done using frame layout. will try that once

**Comment by viveksb007** [comment]
@the-dagger @daminisatya hows this?
@mejariamol were you referring to this?

![screenshot_2016-10-18-19-58-09-870_org fossasia susi ai](https://cloud.githubusercontent.com/assets/12713808/19481980/4efc71d0-956d-11e6-9eab-61140c78a069.png)
