### ISSUE TITLE
ChatMessage overlaps RecycleView

### ISSUE THREAD

**Issue by mejariamol** [fossasia/susi_android#251]
**Actual Behaviour**

Chatmessage view is overlapping recycleview at its max height.

**Expected Behaviour**

Should not overlap

**Screenshots of the issue**

![screenshot_2016-10-18-22-37-15](https://cloud.githubusercontent.com/assets/13533840/19490513/4d31ae0e-9524-11e6-905f-fb772f527cd8.png)

**Would you like to work on the issue?**

yes

**Comment by VDenis** [comment]
How to reproduce this issue?
I have this behavior **screenshot**:

<img src="https://cloud.githubusercontent.com/assets/5451716/19516779/514403ec-9606-11e6-8af2-36cd8f237aa4.png" height="600" alt="login screen screenshot"/>

**Comment by daminisatya** [comment]
In the input field give some large text. @VDenis
