### ISSUE TITLE
Add option to display multiple answer lines

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#252]
**Actual Behaviour**
Currently the app returns one aswer line for each input

**Expected Behaviour**
It should be possible that the app returns several answer lines, each within it's own box. The answer lines may also appear with a given delay

To test this, you need a response from susi_server which produces several lines. This is prepared for the test question consisting of only one word which is "multi3".
Or test with this URL http://api.asksusi.com/susi/chat.json?q=multi3

The `actions` object should then look like:

```
"actions": [
      {
        "expression": "Line 1",
        "type": "answer"
      },
      {
        "delay": 400,
        "expression": "Line 2",
        "type": "answer"
      },
      {
        "delay": 1000,
        "expression": "Line 3",
        "type": "answer"
      }
    ]
```

You can see three answers, two of them have a delay assigned. For each of those answers with an delay, there should be a pause of the delay value in milliseconds before the answer is written.

**Comment by Orbiter** [comment]
This also applies to TTS!

**Comment by betterclever** [comment]
I would like to work on this.

**Comment by samsruti** [comment]
I would like to work on this :)
