### ISSUE TITLE
Date Display Feature Broken

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#255]
**Actual Behaviour**

The display of date in the textView above the RecyclerView in ChatMessageView is completely broken. It displays the date on which app was launched rather than the date on which the conversation has happened. Basically, it is a calender not a real date display.

**Expected Behaviour**

The date TextView should display date of that conversation rather than the current date. A relevent entry for the same must be there in data model for chat message. 

**Steps to reproduce it**
- Open app and check date in TextView.
- Send some messages.
- Change date of your phone manually and return to Susi app.
- Send some more messages.
- The date remains the one that was earlier.
- Reopen the app, the date changes to current one (The one set manually in settings).

**Cause of the issue**

Line number 301 in MainActivity.java at revision 395bd879d23db5ff701e35639eaa32d2faf0c76d applies current date to the textView.

_LogCat for the issue_*

Not Required

**Screenshots of the issue**

Not Applicable.

**Would you like to work on the issue?**

Sure.

**Comment by betterclever** [comment]
@daminisatya @jig08 This is needed to be fixed for #230 since in multiple copy date should also be added.

**Comment by chiragw15** [comment]
@mariobehling can you assign this to me?

**Comment by chiragw15** [comment]
@the-dagger In this issue, should I add a "DeliveryDate" field in data model or is there any other way?

**Comment by mariobehling** [comment]
@Orbiter ?

**Comment by chiragw15** [comment]
@Orbiter @the-dagger ^

**Comment by the-dagger** [comment]
@chiragw15 Adding a date field seems like the viable option for now.
As soon a message is typed, you'll have to fetch the current date and store it to the database.

**Comment by chiragw15** [comment]
Thanks @the-dagger :+1:

**Comment by chiragw15** [comment]
@mariobehling @Orbiter @the-dagger one more thing. Currently we are using system date and time. So, if we change it in settings, the date and time in app will also change .So, should I implement something like this http://stackoverflow.com/questions/13064750/how-to-get-current-time-from-internet-in-android  to get date and time from apache or http://www.docjar.com/html/api/examples/ntp/NTPClient.java.html this from NTP or this api http://www.timeapi.org/utc/now. or from susi server or anything else?

**Comment by the-dagger** [comment]
For now, id suggest to use the system date and time only, as Android will automatically update the current date and time to the actual date and time if it has network connection (is automatic date and time is turned on in the settings ). 
If it is not turned in, then that means the user wants the system to use a custom date and time and we should respect his choice.

**Comment by chiragw15** [comment]
@the-dagger yup agreed. Nice point. :+1:

**Comment by chiragw15** [comment]
@the-dagger I have completed the work and displayed the right date. 
![screenshot_20161204-055808](https://cloud.githubusercontent.com/assets/16978820/20868657/e76cfb5e-ba86-11e6-8c65-fe2fedfd0878.png)

But there is a problem in this implementation. Suppose a case when messages of two different dates are displayed on the screen. In this implementation, the date will be displayed of the upper message.

How about making a view holder for date like below.

![screenshot_20161204-054230](https://cloud.githubusercontent.com/assets/16978820/20868664/0759ce24-ba87-11e6-816c-02ecf2fe1536.png)

![screenshot_20161204-055025](https://cloud.githubusercontent.com/assets/16978820/20868667/12f8d3ba-ba87-11e6-8608-a9447303b92c.png)

**Comment by mayank408** [comment]
@chiragw15 Any progress in this issue ... :)

**Comment by chiragw15** [comment]
@mayank408 What I did is to create a new view for date and whenever the date is changed, the view gets visible. I am also adding this date view to database but sometimes the order of two message gets reversed since we are adding objects asynchronously in database. I am trying to figure that out. If you have any other idea for implementing this or any other trick to control ordering in asynchronous operations , please do share. Meanwhile, I am implementing something else , Hope it works.

**Comment by mayank408** [comment]
@chiragw15 I got your point , to solve this issue first we have to deal with the issue regarding the order of message , I am looking into it :)
