### ISSUE TITLE
Space at end of email not trimmed automatically on login screen

### ISSUE THREAD

**Issue by charany1** [fossasia/susi_android#257]
**Actual Behaviour**

On login screen , when using keyboard like swiftkey which provides suggestions for input , when I have entered my mail id only partially in mail text box , and then press on complete mail id suggestion , swiftkey by default appends a space at end of mail id . Now , when I press on Login button , it says , invalid e-mail .

**Expected Behaviour**

We should treat mail ids with white space appended as correct rather than showing "Invalid Email."

**Steps to reproduce it**
 Just use swiftkey for entering credentials , enter mail id partially use auto-complete . 

**Would you like to work on the issue?**

Yes

**Comment by jig08** [comment]
Copy of Issue #185, closing this.
