### ISSUE TITLE
Issue with the image SUSI on the login screen

### ISSUE THREAD

**Issue by VDenis** [fossasia/susi_android#260]
**Actual Behaviour**

On login screen when type email or password keyboard is opened and image with application name SUSI gets bigger or smaller.

**Expected Behaviour**

The image should not getting bigger or smaller when type email or password.

**Steps to reproduce it**

1) Open Login Screen.
2) Remove focus from any field. Type some part email, when type some part password. Repeat jumping from email to password.

**Screenshots of the issue**

<img src="https://cloud.githubusercontent.com/assets/5451716/19515848/e2f87c64-9601-11e6-90dd-a940855bdd0e.gif" alt="login screen screenshot"/>

**Comment by daminisatya** [comment]
@VDenis I thought it was doing some responsive job.

**Comment by betterclever** [comment]
@daminisatya @VDenis I guess, it looks good as it is now. Gives a parallax effect.

**Comment by VDenis** [comment]
@daminisatya @betterclever @mariobehling Previously, i watch at this like user and it's looks sharp.
But after your explanation i understand that it's doing some responsive job and it gives a parallax effect.

Is this expected behavior?
Should i close this issue or we need to discuss or i need rename issue to make smooth transitions?
What do you think people?

**Comment by mariobehling** [comment]
@VDenis These effects are not smooth and the UI should be simple. The best design of the app is if the UI feels invisible and the "Susi" simply serves the user. So, agree with you. Let's keep it more simple. Cheers.

**Comment by chiragw15** [comment]
@VDenis @mariobehling @daminisatya For simplicity, we can just add a scroll view. Check this implementation. 
https://www.youtube.com/watch?v=LW18DevRGH8

**Comment by chiragw15** [comment]
@mariobehling @daminisatya should I send a PR for implementation mentioned in the above comment?

**Comment by mariobehling** [comment]
The UI has changed since this issue was reported. Closing it.
