### ISSUE TITLE
Issue with Alignment of SUSI Image in chat window.

### ISSUE THREAD

**Issue by YashishDua** [fossasia/susi_android#262]
**Actual Behaviour**

SUSI Image which is placed at top is not aligned in centre.

**Expected Behaviour**

It must be algined to centre properly.

**Steps to reproduce it**

Open the chat window

**Would you like to work on the issue?**
Yes

**Comment by jig08** [comment]
@YashishDua Could you post a screenshot demonstrating the same ?

**Comment by VDenis** [comment]
@YashishDua you mean this image with SUSI title at the top?

<img src="https://cloud.githubusercontent.com/assets/5451716/19539352/94ae2cec-9661-11e6-9ed1-33389f867ae3.png" height="600"></img>

**Comment by mariobehling** [comment]
Please feel free to change it. Thank you.

**Comment by YashishDua** [comment]
@VDenis Yes ! The image is not aligned properly .
@mariobehling Can I take up this issue ?

**Comment by jig08** [comment]
@mariobehling @YashishDua If we plan to mimic WhatsApp UI, The SUSI image and this bug there-on serve no purpose. 
@YashishDua I would rather suggest you to work on Issue https://github.com/fossasia/susi_android/issues/265

**Comment by mariobehling** [comment]
@YashishDua Yes, please take it up. 

@jig08 For the moment we are keeping this part and will change step by step.
