### ISSUE TITLE
Mimic chat UI interface of existing app 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#265]
A lot of ideas are getting incorporated into the app UI, but as a first step the UI should be simple and follow market leaders like Whatsapp to get people accustomed to chatting with Susi. Therefore please somehow mimic the chat UI of Whatsapp.

Implement:
- [ ] gray background
- [ ] green background for Susi chat
- [ ] white background for user
- [ ] ensure left/right chat boxes
- [ ] slightly reduce height of Susi logo

![nexus2cee_whatsapp-material-8](https://cloud.githubusercontent.com/assets/1583873/19541447/b89c8dc4-9666-11e6-8da0-7c573411382f.png)

**Comment by betterclever** [comment]
I would like to work on this.

**Comment by betterclever** [comment]
@jig08 @mariobehling What should be the PrimaryColor, same Dark Grey as being used now or some other light material color?

**Comment by jig08** [comment]
@betterclever Use the same old Dark Grey for the time being.

**Comment by betterclever** [comment]
@jig08 @mariobehling 

I personally think that Chat UI must be similar to Allo and not WhatsApp reason being WhatsApp UI is not designed to handle other data well like link preview , multiple replies in form of actionable cards, maps , charts etc which are being currently or will be used in Susi in future. 
+ less important info like timestamps can be hidden and be visible when user taps once, on any message to make more room for messages. 

Please share your worthy opinion and guide. 

![screenshot_20161020-134040](https://cloud.githubusercontent.com/assets/16309034/19551964/730c3c7c-96cb-11e6-82f4-78d4e79e690c.png)

**Comment by mariobehling** [comment]
@betterclever Thanks for your input. Let's not have a long feature discussion on this issue. Whatsapp is just an example. Yes, Google Allo is better in some respects, but also still under heavy development.

This issue is mainly about the colors and top bars. There is a list of items on the top. Other questions like link preview etc. - this is not part of this issue.

Regarding the background: Please use a light gray background like Whatsapp or Allo.

**Comment by mayank408** [comment]
@betterclever #237 you working on this as well??

**Comment by betterclever** [comment]
@mayank408 Both are related. So, I should say, yes.

**Comment by betterclever** [comment]
![screenshot_20161027-021251](https://cloud.githubusercontent.com/assets/16309034/19744600/d030e176-9beb-11e6-8b50-b743cd13d9fe.png)
@mariobehling How does it look? Sorry, for being so late in it. My health was not so well lately.

**Comment by jig08** [comment]
@betterclever Looks neat.

**Comment by mariobehling** [comment]
Good start. Please also ensure you follow the description (gray background) and keep some distance to the side of chat bubbles for example. 

Also keep the time in the chat UI. Cheers.

**Comment by mariobehling** [comment]
@betterclever Are you still working on this issue? Please let me know and I re-assign you.

**Comment by aakashkhatter1296** [comment]
@mariobehling I would like to work on this if no one else is.

**Comment by aakashkhatter1296** [comment]
@mariobehling how does this look ?

![screenshot_20161121-225227](https://cloud.githubusercontent.com/assets/10905662/20493171/b222fdca-b03d-11e6-8d5d-da506e06352e.jpg)

**Comment by mariobehling** [comment]
Please use the whatsapp background. Cheers.

**Comment by aakashkhatter1296** [comment]
@mariobehling Does this look good or I should change something ?
![screenshot_20161123-234629](https://cloud.githubusercontent.com/assets/10905662/20573759/67d5b168-b1d7-11e6-832f-d325145e7d7c.jpg)
