### ISSUE TITLE
Show "received" ticks if message has been sent 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#266]
The app might be temporarily offline and event though the user has typed a message, maybe Susi might not have received it. 

Please implement a double tick similar to Facebook indicating that the message has been sent and received.

![nexus2cee_whatsapp-material-8](https://cloud.githubusercontent.com/assets/1583873/19541562/9077c718-9667-11e6-9cad-3072979cc6f4.png)

**Comment by amitiwary999** [comment]
I would like to work on this.

**Comment by mariobehling** [comment]
Unassigning due to inactivity.

**Comment by chiragw15** [comment]
@mariobehling if no one is working on it, can you assign it to me?

**Comment by mariobehling** [comment]
Sure, thanks.

**Comment by chiragw15** [comment]
@mariobehling @jig08 @the-dagger does this look fine?

1.) When user sent message but susi didn't receive it.

![screenshot_20161122-184052 1](https://cloud.githubusercontent.com/assets/16978820/20526447/201e429c-b0ea-11e6-8466-cda424281bbd.png)
![screenshot_20161122-184052](https://cloud.githubusercontent.com/assets/16978820/20526459/2f9e087e-b0ea-11e6-8777-ab775ade6c87.png)

2.) When susi received message but didn't reply.

![screenshot_20161122-182318 1](https://cloud.githubusercontent.com/assets/16978820/20526501/5d84bf62-b0ea-11e6-8f73-6f38f0beec5b.png)
![screenshot_20161122-182318](https://cloud.githubusercontent.com/assets/16978820/20526507/683e88f2-b0ea-11e6-9300-54e2c4eb7053.png)

3.) susi replied to the mesaage.

![screenshot_20161122-182359 1](https://cloud.githubusercontent.com/assets/16978820/20526533/7bbb6b52-b0ea-11e6-8337-8d607ba86c65.png)
![screenshot_20161122-182359](https://cloud.githubusercontent.com/assets/16978820/20526541/83d656e4-b0ea-11e6-9f30-ef6a1cb1e5a3.png)

**Comment by the-dagger** [comment]
Since Susi will be replying to each and every message once it receives it,
I'd suggest implementing 1) and 2) only for now.

**Comment by chiragw15** [comment]
@the-dagger sure :+1:

**Comment by mayank408** [comment]
@the-dagger  Its resolved, so it can be closed
