### ISSUE TITLE
Issue with SnackbarBehavior

### ISSUE THREAD

**Issue by NiharG15** [fossasia/susi_android#270]
**Actual Behaviour**

When you delete a message, a snackbar pops up, which moves the rest of the UI up. When the snackbar gets dismissed, the rest of the UI doesn't come back to its original position.

**Expected Behaviour**

The UI should go back to its normal position.

**Steps to reproduce it**

1. Long press on a message
2. Select delete

**LogCat for the issue**

NA

**Screenshots of the issue**
![device-2016-10-21-111522](https://cloud.githubusercontent.com/assets/2757665/19587920/b8330cb8-977f-11e6-8b4c-8076ea755169.png)

**Would you like to work on the issue?**
Yes.

**Comment by jig08** [comment]
@NiharG15 assigned, take this up.
