### ISSUE TITLE
Issue with Chat setting background colour

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#271]
**Actual Behaviour**
Chat setting background colour is unattractive.
Please state here what is currently happening.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

*LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.
![screenshot_2016-10-21-03-13-33](https://cloud.githubusercontent.com/assets/14003244/19596110/aa9794a4-97aa-11e6-82ad-8e70b55d0df3.png)

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.
Yes

**Comment by amitiwary999** [comment]
@jig08 
![screenshot_2016-10-22-13-39-50](https://cloud.githubusercontent.com/assets/14003244/19618046/69afdae2-985d-11e6-9efd-0436c1ba953a.png)

**Comment by mariobehling** [comment]
Gray for settings is fine for the moment. Let's focus on the existing issues first. 

We need a good chat UI. All other parts will depend on the chat UI. Closing this for the moment as it is not a focus. We need to look at the start UI and chat UI first.

Thank you.
