### ISSUE TITLE
Voice of Susi offering download of file, but it should not

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#273]
**Actual Behaviour**

After activating Susi Voice output, after Susi reads out the answer, the app offers download of file.

**Expected Behaviour**

There should not be a file download option.

**Screenshots of the issue**

![screenshot_2016-10-21-22-02-21](https://cloud.githubusercontent.com/assets/1583873/19610023/9277a6e0-97da-11e6-8c89-10f2efaad9a0.png)

**Comment by amitiwary999** [comment]
I would like to work on this issue

**Comment by mariobehling** [comment]
Please do not claim numerous issues. Please solve one issue at a time and solve questions of open pull requests first. It does not make sense to claim issues "on stock".

**Comment by betterclever** [comment]
I would like to work on this.

**Comment by betterclever** [comment]
@mariobehling Please clear a doubt, user is prompted since he doesn't have English UK installed, so what should be the behaviour in such a scenario?
1. Abandon Voice Output.
2. Fallback to English US as it is installed by default in most handsets.
3. A check can be made for language at the time of enabling voice output to download language at that time.
or any other behaviour?

**Comment by mariobehling** [comment]
@betterclever 

Falling back to US English sounds like a good solution.

> A check can be made for language at the time of enabling voice output to download language at that time.

Can we do that at the installation of the app? Is it possible to download the language of the user's phone at the time of the app installation?

**Comment by betterclever** [comment]
@mariobehling As far as I know, we can do this at first run of App but not at the time of installation.

@the-dagger Is it possible to check at installation?

**Comment by mariobehling** [comment]
@betterclever Ok, great. Please proceed to whatever is possible. If it is not possible at time of installation, let's to it at first run. Thank you.

**Comment by the-dagger** [comment]
During installation isn't possible, but it is possible on the first run. 
@betterclever

**Comment by anantprsd5** [comment]
I would like to work on this issue.

**Comment by mariobehling** [comment]
Closing this issue in favor of https://github.com/fossasia/susi_android/issues/350
