### ISSUE TITLE
Offer language settings, especially for voice input/output or propose alternative solution

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#274]
**Actual Behaviour**

Currently the app is mainly tested in one language. If we define rules, the app could also be used in different languages. 

A challenge is if Susi uses text to speech. These services currently use a standard language, e.g. British English.

We need to define what language is used in the settings, but also allow users to change that setting.

**Expected Behaviour**

Enable the correct language output for speech.

**Comment by anantprsd5** [comment]
I would like to take up this issue.

**Comment by mariobehling** [comment]
Closing this issue in favor of: https://github.com/fossasia/susi_android/issues/350
