### ISSUE TITLE
Overlapping Area: Text behind input box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#275]
**Actual Behaviour**

Text or box is partly hidden behind input box.

**Expected Behaviour**

Compare to chat UI of Whatsapp and implement in similar ways.

**Screenshots of the issue**

![screenshot_2016-10-21-22-14-52](https://cloud.githubusercontent.com/assets/1583873/19610302/14d21638-97dc-11e6-8fb4-8889f69d14b2.png)

**Comment by amitiwary999** [comment]
I would like to work on this issue.

**Comment by mayank408** [comment]
@the-dagger Its already solved . So we can close this.
