### ISSUE TITLE
Enable Voice Output if user speaks to app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#276]
**Actual Behaviour**

Currently the user needs to enable voice output of Susi in the settings. Even if the user uses voice to communicate.

**Expected Behaviour**

* [x]  The output of voice should be enabled if users uses voice input.
* [x]  There should be an additional option in settings deactivate/activate Voice Output if user uses "Speech to Text", e.g. "At speech input enable speech out"
* [ ] The currently existing option "Speech Output" should be changed to "Speech Output Always On"

**Comment by mayank408** [comment]
@mariobehling  I would like to work on this
