### ISSUE TITLE
Ragarding chat bubble size.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#283]
**Actual Behaviour**

Chat bubble is taking whole size of the screen if message is large.
**Expected Behaviour**

There should be a minimum width
![whatsapp image 2016-10-22 at 5 20 20 pm](https://cloud.githubusercontent.com/assets/22056321/19619100/fd92b48c-987b-11e6-83fa-758c6c72d0e0.jpeg)

**Would you like to work on the issue?**
yes

**Comment by daminisatya** [comment]
@mayank408 Please refer #265 No duplicate issues. Please contribute there

**Comment by daminisatya** [comment]
Any suggests or want to split the issues please put it on that issue. Thank you

**Comment by mayank408** [comment]
@daminisatya ok sure.
