### ISSUE TITLE
Issue with logout

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#284]
**Actual Behaviour**

When we click on logout is does not ask for confirmation.
**Expected Behaviour**

When we click on logout it should ask for confirmation.

**Would you like to work on the issue?**
Yes ofcourse

**Comment by mariobehling** [comment]
Ok, great. Please follow services like Whatsapp and Twitter, e.g. implement a small pop up. thank you.

**Comment by mayank408** [comment]
@madhavrathi Should i need to explain you the rule . How can you send pr to an issue assigned to someone else.
@mariobehling @daminisatya @the-dagger  pls ensure that this thing dont happen in future . I have already worked on it just to waste my time.
