### ISSUE TITLE
Propose and implement bug and crash logs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#290]
We already have a number of issues when the app crashes and reports are submitted by testers. How can we automate this process, especially for versions we did not put yet on the play store?

How can we collect logs?

I found this project: https://code.google.com/archive/p/android-remote-stacktrace/

Any other suggestions? Please propose and implement a suitable solution.

**Comment by NiharG15** [comment]
@mariobehling  I've used Crashlytics (now part of fabric) before, and it works well. 
https://get.fabric.io/

**Comment by mariobehling** [comment]
@NiharG15 Sounds good. Please help to implement it.

**Comment by NiharG15** [comment]
![Crashlytics](https://cloud.githubusercontent.com/assets/2757665/19769695/1d5cbafe-9c7a-11e6-8e87-d65411609a98.png)
 
Its working well.

We need to keep the API key out of the public repo. For this purpose, we could create a strings-private.xml file and add it there. Then add the file to .gitignore to keep it out of the repo. API key will be given to contributors on request via gitter. If anybody has a better way of handling this, please let me know.

**Comment by mariobehling** [comment]
@NiharG15 Unassigning you due to inactivity. Let us know if you would like to be active and re-assigned.

**Comment by vivekkiran** [comment]
@mariobehling @Orbiter I would like to work on this issue, I will be using Firebase https://firebase.google.com/ for crash reporting along with analytics.

**Comment by the-dagger** [comment]
@mariobehling since the app is still in alpha phase, adding in crash logging makes little sense since that is helpful only when the crash happens on the user's device. 
I'd suggests to implement this feature when we are opening Susi for beta testing.

**Comment by samsruti** [comment]
@mariobehling I would agree with @the-dagger. I have implemented it so later during the beta stage I will add that into this branch :)
