### ISSUE TITLE
Collapse searchView on getting focus of ChatMessage

### ISSUE THREAD

**Issue by vikiCoder** [fossasia/susi_android#292]
Currently, the ChatMessage is being disabled on click on search button.

But I think, ChatMessage should not be disabled. And when user again click on it (ChatMessage), the searchView should collapse automatically.

I would like to work on it.

**Comment by amitiwary999** [comment]
@vikiCoder I tried to implement feature like in whatsapp but was busy so I done that for temporary.I planned for hiding edittext box when user click on serch view and as soon as user close searchview edittext box will become visible.(I already coded that part so if you not started work on it .can I take this issue.)

**Comment by vikiCoder** [comment]
Actually I have done what I said, but yours seems better...Do it

**Comment by amitiwary999** [comment]
@vikiCoder if they approved this issue then I will send a PR.

**Comment by mariobehling** [comment]
@amitiwary999 Not sure, exactly how this will look and feel, but we can try out it. Please send a PR and add a screenshot if possible. Cheers.

**Comment by amitiwary999** [comment]
@mariobehling once I write something in serachview editext box become invisible and on clicking search option from keyboard it shows required result. And after clicking close button serchview collapsed and editext box become visible.
![screenshot_2016-10-23-22-06-59](https://cloud.githubusercontent.com/assets/14003244/19627794/2e9479b6-996d-11e6-8c37-607f7f752d73.png)

![screenshot_2016-10-23-21-52-11](https://cloud.githubusercontent.com/assets/14003244/19627748/2077cb4a-996c-11e6-8725-34c2eb879838.png)
![screenshot_2016-10-23-22-02-00](https://cloud.githubusercontent.com/assets/14003244/19627758/8aaf7ce2-996c-11e6-8639-84520d92821b.png)

**Comment by mayank408** [comment]
@jig08
@amitiwary999   You have many issues assigned can I work on this.

**Comment by amitiwary999** [comment]
No, I already coded this part and will send a PR if required.(I sent screenshot for reference and if they allow then I will send PR).
If you want to work,  work on issue #278 which is assigned to you.
