### ISSUE TITLE
Automatically build an app after each PR and add it into the apk repository

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#3]
We have a number of projects, that automatically build an app after each commit. The event orga app adds an apk in the apk branch here, e.g. https://github.com/fossasia/open-event-orga-app/tree/apk.

Please follow this approach and implement an automatic build after each code merge.

**Comment by code-crusher** [comment]
@mariobehling should the generated apk file be pushed in a folder in the master branch (similar to open-event-android) or in a new branch?

**Comment by mariobehling** [comment]
@code-crusher 

I think I answered this in the issue description:

> The event orga app adds an apk in the apk branch here, e.g. https://github.com/fossasia/open-event-orga-app/tree/apk. Please follow this approach and implement an automatic build after each code merge.

So, yes into a branch "apk".

**Comment by code-crusher** [comment]
@mariobehling Thank you clarification. Will start working on it.

**Comment by shivenmian** [comment]
@mariobehling Not sure, why this is needed here. This is a normal Android app, not an app generator. Can't correlate open-event with this.

**Comment by mariobehling** [comment]
We need it for testing. So, non-developers can also test.

**Comment by jig08** [comment]
@mariobehling +1

**Comment by mariobehling** [comment]
@code-crusher @the-dagger There was an apk branch with a copy of the code from master. The goal of this issue is to have an apk only in that branch and nothing else at the moment. Please check out the example in the description (https://github.com/fossasia/open-event-orga-app/tree/apk). I deleted the apk branch as it did not fulfill the purpose.

**Comment by code-crusher** [comment]
@the-dagger can you create an `orphan` branch `apk`? :)

**Comment by the-dagger** [comment]
@code-crusher Doing it in a min

**Comment by the-dagger** [comment]
@code-crusher The branch is up.
[https://github.com/fossasia/susi_android/tree/apk](https://github.com/fossasia/susi_android/tree/apk)

**Comment by mariobehling** [comment]
Please call the apk: susi.apk

**Comment by addiittya2006** [comment]
@the-dagger Also, #77 .

**Comment by mariobehling** [comment]
What is missing to make this feature happening?

**Comment by the-dagger** [comment]
I'm testing it @mariobehling. 
Waiting for the Travis build to complete.

**Comment by the-dagger** [comment]
@mariobehling Fixed now.
@addiittya2006 Please try and run your changes once in the local fork before sending a pull request to verify that it works correctly. :slightly_smiling_face:

**Comment by mariobehling** [comment]
@the-dagger Would be great to get this feature back.

**Comment by the-dagger** [comment]
@mariobehling I'll fix this today.

**Comment by mariobehling** [comment]
@the-dagger Should we move back to travis?

**Comment by the-dagger** [comment]
@mariobehling I've fixed this in my fork with circleci.
Will send a PR with it today.

**Comment by the-dagger** [comment]
@mariobehling fixed. 
https://github.com/fossasia/susi_android/tree/apk

**Comment by mariobehling** [comment]
Awesome!
