### ISSUE TITLE
UI improvement in chat wallpaper dialog

### ISSUE THREAD

**Issue by rahulworld** [fossasia/susi_android#303]
We can add m-desgin in dialog for choose wallpaper.

![screenshot_2016-10-25-18-41-40](https://cloud.githubusercontent.com/assets/15066782/19687426/f42617b8-9ae2-11e6-8142-b6f593d63366.png)

I would like to work on this.

**Comment by jig08** [comment]
Material Design sounds good, but I don't think numbering does.

**Comment by rahulworld** [comment]
@jig08  yes only use of material design numbering wouldn't be there.

**Comment by mayank408** [comment]
@rahulworld Are you working on this or else i want to work on this..

**Comment by rahulworld** [comment]
@mayank408  yes, i am working on this.

**Comment by arp95** [comment]
Numbering doesnt look good better would be using bullet points.

**Comment by mariobehling** [comment]
There is an implementation and this issue has been inactive for some time. Closing it therefore.
