### ISSUE TITLE
Option to select all messages at once.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#307]
**Actual Behaviour**

There is no option to select all messages in the susi app.
**Expected Behaviour**
There should be a functionality to select all messages.

**Would you like to work on this?**
yes

**Comment by jig08** [comment]
Un-assigning at the moment, follow up on previously assigned issues.

**Comment by mariobehling** [comment]
This is not a focus at the moment. We need the basics to work first. This app provides a AI chatbot and we need this chatbot to work before we think about additional features. Closing it therefore. Thank you.
