### ISSUE TITLE
Option to delete chat history

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#308]
**Actual Behaviour**

There is no such option to delete chat history.

**Expected Behaviour**

There should be a dedicated option to delete chat history

Would you like to work on this?
yes

**Comment by mariobehling** [comment]
This is an additional feature. Right now we don't want to increase the complexity and add this kind of features to the app. We need the chat to work. Currently it does not.

More features mean more things to take care of. We need the basics to work flawlessly. Closing this therefore.
