### ISSUE TITLE
Show relevant error messages in chat box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#309]
This is a follow up to issue: https://github.com/fossasia/susi_android/issues/306

Currently there is a general error message if something went wrong in Susi "an error ocurred. please try again."

As a matter of fact the server seems to work perfectly fine and it is unclear what the error is. We need a simple way to understand the cause without having to browse through logs at this stage of development.

Please show real error message/reason for errors instead of "there was an error".

@mejariamol @amitiwary999 Please help if possible.

**Comment by mejariamol** [comment]
@mariobehling I ll work on dis

**Comment by amitiwary999** [comment]
@mejariamol have you started work on this?

**Comment by mejariamol** [comment]
@amitiwary999 yes
