### ISSUE TITLE
Multiple Issues with splash screen.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#31]
- [x] Splash activity extends Activity, should extend Appcompativity.
- [x] Image is loaded in XML, should be loaded with an image library to resize according to screen size.
- [x] layout can be improved by removing RelativeLayout.

@the-dagger what library should we use for image loading? Picasso or glide? i prefer glide because it handles image resizing effectively.

**Comment by the-dagger** [comment]
Yes, plus glide has better caching too, in case we implement images to be fetched from network in the future

**Comment by gogeta95** [comment]
using glide for this issue also then.
