### ISSUE TITLE
Error in chat: Invalid access token

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#311]
Follow up to https://github.com/fossasia/susi_android/issues/306#issuecomment-256540167

The chat has some errors as below:

@amitiwary999 @mariobehling 

if (!isNetworkConnected()) {
                                        recyclerAdapter.hideDots();
                                        nonDeliveredMessages.addFirst(new Pair(query, id));
                                        Snackbar snackbar = Snackbar.make(coordinatorLayout,
                                                getString(R.string.no_internet_connection), Snackbar.LENGTH_LONG);
                                        snackbar.show();
                                    } else {
                                        realm.executeTransactionAsync(new Realm.Transaction() {
                                            @Override
                                            public void execute(Realm bgRealm) {
                                                long prId = id;
                                                try {
                                                    ChatMessage chatMessage = bgRealm.where(ChatMessage.class).equalTo("id", prId).findFirst();
                                                    chatMessage.setIsDelivered(true);
                                                } catch (Exception e) {
                                                    e.printStackTrace();
                                                }
                                            }
                                        });
                                        **rvChatFeed.getRecycledViewPool().clear();
                                        recyclerAdapter.notifyItemChanged((int) id);
                                        addNewMessage(getString(R.string.error_occurred_try_again), false, false, false, null);**
                                    }
                                }

@Orbiter stated that this problem is caused by an invalid access token. Probably the token must be renewed in some way. Maybe the token is void when the susi_server restarts.

@mayank408 @amitiwary999 Question: Does the android client has still the log-in information and is able to retrieve a new access token automatically in that case? That would be the most appropriate solution for the problem.

**Comment by mayank408** [comment]
@gogeta95 what are your views..

**Comment by gogeta95** [comment]
Saving password in local storage defeats the purpose of token based authentication. The server shouldn't invalidate tokens on each restart, tokens do have an expiry date, we can set the expiry date to 1-2 months and ask user to re login if token has expired.

**Comment by mariobehling** [comment]
@gogeta95 This is not the intended solution. We do not want the user to have to login again. It is not in line with the experience in other apps.

**Comment by gogeta95** [comment]
In that case, we could implement oauth2.0 where we need to manage 2 tokens, access and refresh. However, I have never done that, so we need someone with more knowledge about this process to guide. More info is at: https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

**Comment by Orbiter** [comment]
can we use the AccountManager? https://developer.android.com/reference/android/accounts/AccountManager.html which handles the whole process, stores authentication credentials and re-establishes access tokens if they have been invalidated.

**Comment by mejariamol** [comment]
@mariobehling @Orbiter @mayank408 @gogeta95 I didn't get what invalid access token is. How the failure in SusiResponse request is related to the access token. Access token is for local use only. It doesn't have any part in server requests right. The error is due to failure in request because of Internet connectivity.

**Comment by gogeta95** [comment]
Access token is sent with every network call so that server can identify
which user sent the request.

**Comment by mejariamol** [comment]
@gogeta95 Will you please point me to the code where a token is sent with a network call. I was unable to find such thing.

**Comment by mejariamol** [comment]
@gogeta95 @mayank408 @mariobehling @Orbiter Is there any easy way to reproduce this error due to invalid access token?

**Comment by mejariamol** [comment]
@mariobehling I will work on this. Using `AccountManager` will fix the issue.

**Comment by supreme96** [comment]
@mariobehling is this issue assigned?

**Comment by mariobehling** [comment]
I think this issue was solved. Please open new issue with relevant updates if necessary.
