### ISSUE TITLE
New login feature

### ISSUE THREAD

**Issue by arp95** [fossasia/susi_android#316]
Right now we are using normal login feature, can we incorporate the fb , google login for users instead of creating another account for user ?
And if yes can i take up this issue ?

**Comment by jig08** [comment]
@mariobehling we could look into including Google Sign-In facility ...

**Comment by nukex1122** [comment]
Can I Take Up This Issue?

**Comment by arp95** [comment]
Im working on this. Will communicate when help needed.

**Comment by mariobehling** [comment]
This could be a way. The goal would be to make it easier to connect accounts. However, this is making the project more complex. For the moment we want to keep it simple and reduce the bugs.
