### ISSUE TITLE
Using Web_Search Intent(Feature)

### ISSUE THREAD

**Issue by octacode** [fossasia/susi_android#317]
**Actual Behaviour**

Each Time Susi says "I don't know" when it doesn't have the appropriate answer. 

**Expected Behaviour**

What we could do is that instead of displaying I don't know to user we could launch a web_search intent.

**Would you like to work on the issue?**
Yes, If you find this issue relevant enough, then I sure would like to work on it.

Thanks

**Comment by mariobehling** [comment]
@octacode Yes, we are also thinking about this. What are your ideas for an implementation? Would the search results be displayed within the chat, in the browser or where?

**Comment by octacode** [comment]
@mariobehling 
I am thinking of using the browser to display the result.

**Comment by octacode** [comment]
@mariobehling 
Would it be fine if you assign this issue to me. I have already started with it.

**Comment by mariobehling** [comment]
@octacode An option is also to display results in the Susi chat. We might prefer this solution. Maybe let's tray with the browser as well and check out how is the user experience.

**Comment by octacode** [comment]
Great! Let's try with browser first.

**Comment by jig08** [comment]
PR https://github.com/fossasia/susi_android/pull/324 resolves this for now.
