### ISSUE TITLE
Crash on location question using Speech

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#318]
**Actual Behaviour**

Using voice input with Susi and asking "Where is San Francisco", Susi crashes.

**Expected Behaviour**

No crash.

**Comment by octacode** [comment]
@mariobehling 
Hey! 
If it's fine. Can I work on this issue?

**Comment by mariobehling** [comment]
Yes, please. I have invited you to the org. Only members of the org can be assigned. Please accept the invitation. Cheers.

**Comment by octacode** [comment]
@mariobehling
Thanks for such generosity. I have accepted the invitation. :)
