### ISSUE TITLE
Show "wrong password" if user enters wrong password

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#319]
**Actual Behaviour**

Currently if the user enters the wrong password, there is no wrong password message.

**Expected Behaviour**

Similar behaviour to apps like the Facebook apps, that shows an error and allows the user to enter the password again.

**Comment by octacode** [comment]
@mariobehling 
How do you want the wrong password message to be displayed?
Whether it should be in form of an AlertDialog box or simply a Snackbar.
Thanks

**Comment by mariobehling** [comment]
@octacode How does the Facebook app do it? Please do it in exactly the same way. Thank you.

**Comment by octacode** [comment]
Okay! I am on it.
:)

**Comment by mayank408** [comment]
@mariobehling  This is what happens in facebook

![whatsapp image 2016-11-01 at 11 18 01 am](https://cloud.githubusercontent.com/assets/22056321/19880661/3500630a-a025-11e6-8d9d-d82915353a37.jpeg)


I would like to work on this.

**Comment by mayank408** [comment]
@mariobehling Can i work on this issue . Pls assign me..
