### ISSUE TITLE
Delete confirmation issue

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#325]
**Actual Behaviour**

Susi does not ask for confirmation of deleting messages.
**Expected Behaviour**

It should ask for confirmation before deletion like in whatsapp.

![whatsapp image 2016-11-02 at 12 27 46 pm](https://cloud.githubusercontent.com/assets/22056321/19944166/e5760c4e-a0f7-11e6-806c-04a5dd98eb0f.jpeg)

**Would you like to work on the issue?**

yes

**Comment by jig08** [comment]
@mayank408 Sure, go ahead.
