### ISSUE TITLE
Adding Border around Edit Text in Home Activity.

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#327]
**Actual Behaviour**

There is no border around edit text.
![screenshot_20161103-044851](https://cloud.githubusercontent.com/assets/16978820/19951185/4552fef8-a182-11e6-975f-37fb74ea53e3.png)

**Expected Behaviour**

Border added around edit text.
![screenshot_20161103-050431](https://cloud.githubusercontent.com/assets/16978820/19951344/77564490-a183-11e6-9715-9d206604bb08.png)

@the-dagger , If it looks fine, I'll send a PR.

**Comment by mariobehling** [comment]
Looks good. Thank you.

**Comment by mejariamol** [comment]
@chiragw15 @mariobehling Implementing material design elevation would be better. (shadows)

**Comment by chiragw15** [comment]
@mariobehling @mejariamol @the-dagger @jig08 These are some other designs:

Light Gradient with elevation(shadow)
![screenshot_20161103-160306](https://cloud.githubusercontent.com/assets/16978820/19963027/90bf9406-a1e0-11e6-91f9-781336d11563.png)


Dark Gradient without elevation(shadow)
![screenshot_20161103-160227](https://cloud.githubusercontent.com/assets/16978820/19963051/b81432dc-a1e0-11e6-87eb-d1ab1d3ce1c5.png)


Light Gradient without elevation(shadow)
![screenshot_20161103-160009](https://cloud.githubusercontent.com/assets/16978820/19963068/d11e684c-a1e0-11e6-96a0-9a6ec91794dc.png)


No Gradient, only elevation(shadow)
![screenshot_20161103-155655](https://cloud.githubusercontent.com/assets/16978820/19963104/f872b2fe-a1e0-11e6-8ad1-139062de3322.png)

**Comment by the-dagger** [comment]
Last one looks the best to me. 👍

**Comment by daminisatya** [comment]
@chiragw15 Last one.

**Comment by chiragw15** [comment]
Last one it is then :) . Sending a PR.

**Comment by mariobehling** [comment]
Please keep it simple. Simple grey line, no shadow or so, please.
