### ISSUE TITLE
After signUp the user have to login again.

### ISSUE THREAD

**Issue by octacode** [fossasia/susi_android#328]
**Actual Behavior**

After successfully signing in, The user is asked to login again. Which from my point of view is not a good practice.

**Expected Behaviour**

The user should be directly redirected to the main page without asking for logging in again.

**Would you like to work on the issue?**

If you find this enhancement worth for Susi. Then I would love to work on it.

**Comment by mariobehling** [comment]
After sign up the user should confirm the account by email and receive the info: Please go to your email to confirm the account.
