### ISSUE TITLE
Option asking user if he/she wants to launch browser.

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#338]
**Actual Behaviour**

Currently, When susi doesn't know something, it automatically launches a browser with the search query.

**Expected Behaviour**

Instead, it will be better if we display top result in chat and add an option which asks user if he/she wants to search the query on google.

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
@mariobehling @daminisatya @the-dagger @jig08 Please clearify something. If susi doesn't understand a query, should the search results be displayed in chat itself or in a separate browser? If the results need to be displayed in the chat, then there is no need for this issue else there is no need for issue #342 . Alternatively, we can implement something like this, which displays search results in chat as well as gives option to search it on separate browser.

![screenshot_20161107-013135](https://cloud.githubusercontent.com/assets/16978820/20041193/a957227e-a48b-11e6-935a-9b6402cdf6de.png)

**Comment by octacode** [comment]
Hi @chiragw15 . Please refer to #317. Thanks :)

**Comment by chiragw15** [comment]
@mariobehling should I close this issue or should I implement the above feature?

**Comment by mariobehling** [comment]
@chiragw15 Yes, the way the Assistant implements it, looks good to me. Would be great, if you could do it in the same way.

**Comment by chiragw15** [comment]
@mariobehling Sure, I'll also upload a mock-up to confirm before implementing.

**Comment by mariobehling** [comment]
@chiragw15 How is the progress? I think the launch of the web browser is not the best option for the moment. I feel it breaks the interaction with the user. Displaying the results in the chat seems to be better.

**Comment by chiragw15** [comment]
@mariobehling yes we can display the result in the chat itself but we will only be able to show the top 1-2 results. What if the user doesn't find what he is looking for in that? What we can do is to show the top result in chat itself and add an option to launch the browser if he doesn't find what he is looking for.

**Comment by mariobehling** [comment]
Yes, great. Please proceed. Cheers.

**Comment by mariobehling** [comment]
Please also have a look at this issue that is closely related: https://github.com/fossasia/susi_android/issues/150

**Comment by chiragw15** [comment]
@mariobehling I guess this issue is same as #150 . Sorry for trouble. Should I close it?

**Comment by mariobehling** [comment]
ok, closing it then. Please talk to @gogeta95 to collaborate on this issue. It seems there is little progress. Would be great if you make a PR.
