### ISSUE TITLE
Multi line query not supported

### ISSUE THREAD

**Issue by octacode** [fossasia/susi_android#340]
**Actual Behaviour**
Susi works great when we query Susi in a single line. But as the query turns into a multi-line query. No matter susi knows the answer or not Susi returns a message saying "An error occurred. please try again."

**Expected Behaviour**

If Susi knows the answer it should return an answer and if Susi doesn't knows the answer it should launch a browser search. That is Susi should work the way it works for a single line query.

**Screenshots of the issue**

![error_input](https://cloud.githubusercontent.com/assets/20819968/20037584/8f072aba-a448-11e6-8864-46b1638331ad.png)

**Would you like to work on the issue?**
Yes, I would love to. :)

**Comment by daminisatya** [comment]
Please open a PR, code looks good! 👍

**Comment by octacode** [comment]
Opened the PR #341
Thanks
@daminisatya
