### ISSUE TITLE
Chat layout does not come down when dismissing Snackbar manually

### ISSUE THREAD

**Issue by lokeshsaini94** [fossasia/susi_android#343]
**Actual Behaviour**

When there is any Snackbar and it's dismissed manually, the Whole Chat layout doesn't come back down to its original position.

**Expected Behaviour**

The whole Chat layout should come back to its original position after dismissing the Snackbar

**Steps to reproduce it**

Whenever there's any Snackbar like for network state etc. The whole Chat layout will move up to give space to the Snackbar
Swipe right to dismiss it, and Chat layout doesn't come to its original position.

**Screenshots of the issue**

http://i.imgur.com/Vuz9YAp.png

**Would you like to work on the issue?**

Yes, I would like to work on this Issue

**Comment by mariobehling** [comment]
Thanks. 

Please include screenshots directly in the github issue instead of linking to external sites in future as well. This ensures we keep all the resources in one place. Cheers.
