### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by vishwesh3** [fossasia/susi_android#345]
**Actual Behaviour**

As of now when someone opens app in landscape mode some info(forgot possword button, sign up button etc) is not visible on screen due to lack of scroll

**Expected Behaviour**

It should scroll, so user can see whole info.

**Steps to reproduce it**

Add ScrollView as parent in both **activity_login.xml** and **activity_sign_up.xml**

**Screenshots of the issue**

![susi_landscape_bug](https://cloud.githubusercontent.com/assets/18511177/20227444/4b819b12-a872-11e6-909b-8acc4d0b981b.png)
![susi_landscape_bug2](https://cloud.githubusercontent.com/assets/18511177/20227445/4b8c9724-a872-11e6-9b4c-ecde1b29c4eb.png)
![susi_landscape_bug3](https://cloud.githubusercontent.com/assets/18511177/20227513/9ebe7e58-a872-11e6-8d96-54376abc3659.png)
Aslo not able to find **Sign up** button until I press back button and hide keyboard
![susi_landscape_bug4](https://cloud.githubusercontent.com/assets/18511177/20227514/9ec883c6-a872-11e6-9f25-7a0c1190d42f.png)

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by anantprsd5** [comment]
@vishwesh3 I would like to work on this issue.

**Comment by vishwesh3** [comment]
I am waiting for @the-dagger @himanshu-soni review before I send PR.

**Comment by daminisatya** [comment]
@vishwesh3 valid issue. Please go ahead.

**Comment by vishwesh3** [comment]
created PR #346
