### ISSUE TITLE
Add open camera feature to change wallpaper

### ISSUE THREAD

**Issue by vishwesh3** [fossasia/susi_android#347]
**Actual Behaviour**
Currently user have 3 options for changing wallpaper.

**Expected Behaviour**
I would be better, if there is open camera option too. Means, if user want to change wallpaper than he can open his/her default camera and take photo (if wants to crop then crop) and apply that as wallpaper.

**Steps to reproduce it**
Add a 4th option in below screenshot.
On click of that camera will open.
If user want's to crop than he/she can crop.
Set as wallpaper.

**Screenshots of the issue**
![screenshot_20161114-200707](https://cloud.githubusercontent.com/assets/18511177/20277002/d6bf6fb6-aac4-11e6-9933-4e3adf07fa69.jpg)

**Would you like to work on the issue?**
Yes, I would like to work to implement this feature.

**Comment by mariobehling** [comment]
@vishwesh3 Hi, sorry but this is out of scope at the moment. We are still working on the basic features of this app. The user already has a cam feature on the phone. We should keep the app focus inline and get the basics work. Currently, we need more support for the server to make everything work. Cheers.
