### ISSUE TITLE
App not using standard voice and language of phone for text to speech

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#350]
**Actual Behaviour**

Currently there are some issues with the voice output e.g. it asks the user to install a voice instead of using the standard Android voice.

**Expected Behaviour**

The app should use the standard language and voice of the Android phone. It should not use its own settings and voice. Changing the standard language and voice of the phone should also change the setting in Susi. There should be a link in the settings menu of the app that directs the user to the settings of voice/language of the Android system.

**Screenshots of the issue**

At Wikihow it is shown how to change the voice/language of the system. The Susi settings should have a button that directs the user to these settings: http://www.wikihow.com/Change-the-Android-Voice

**Comment by anantprsd5** [comment]
@mariobehling Can you please assign me to this bug.

**Comment by anantprsd5** [comment]
@mariobehling I added a language button inside of Susi Settings which redirects to android TTS settings.
![susi_settings](https://cloud.githubusercontent.com/assets/20367966/20475218/9330348e-aff0-11e6-96ae-4ceb
![android_settings](https://cloud.githubusercontent.com/assets/20367966/20475242/ba0123b6-aff0-11e6-9c20-8a371040fe3c.jpg)
b05a7c7c.jpg)

Is it fine?

**Comment by anantprsd5** [comment]
@mariobehling I added a Language settings button inside of Susi settings which on being clicked redirects to the TTS android settings.

![susi_settings](https://cloud.githubusercontent.com/assets/20367966/20475278/f43e4bc6-aff0-11e6-8fba-98f8a3cad37b.jpg)

![android_settings](https://cloud.githubusercontent.com/assets/20367966/20475295/128d0892-aff1-11e6-9c4a-a6ed295deca9.jpg)

Is it fine?

**Comment by mariobehling** [comment]
@anantprsd5 
I don't know if it is fine unless you make a PR and we can try it out.

**Comment by anantprsd5** [comment]
@mariobehling PR #353 for this issue has been merged. Please close this issue.
Thanks.

**Comment by mariobehling** [comment]
Thanks!
