### ISSUE TITLE
Ensure signup process with email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#351]
**Actual Behaviour**

The account sign up process currently enables the user to register a new account, but there is no confirmation email sent or received. On the web app account signup page, it works though: http://api.asksusi.com/apps/signup/

Even though the user does not receive and confirm the email he/she is still able to sign up with the unverified email and password chosen.

**Expected Behaviour**

After the user signs up for a new account, show the login screen and a popup message "An email has been sent to you. Please confirm this account by clicking the confirmation link in the mail."
Then: Only let users use the app, who have confirmed their email.

**Comment by SuperHaker** [comment]
I would like to work on the issue.

**Comment by SuperHaker** [comment]
@mariobehling  App is already working fine with sending data to the server for verification. I was not able to login after signup. 

But the confirmation link leads to a 404 page on susi_server. So the user is not able to confirm at all.

![screenshot 16](https://cloud.githubusercontent.com/assets/16765805/20562632/9302cfd8-b1aa-11e6-9140-8244037ef33d.png)

![screenshot 17](https://cloud.githubusercontent.com/assets/16765805/20562633/9305d48a-b1aa-11e6-8626-9d5173e36512.png)

**Comment by mariobehling** [comment]
@SuperHaker Could you check, please if it is working for you now?

**Comment by SuperHaker** [comment]
@mariobehling 
I created an issue on susi_server and it is working now. This issue can be closed.

![screenshot 19](https://cloud.githubusercontent.com/assets/16765805/20642288/62d0dc86-b431-11e6-89e3-11c9f6cc52ca.png)
