### ISSUE TITLE
Susi crashes on Text to Speech Input and Speech Output

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#354]
**Actual Behaviour**

On a Samsung GT-I1919 and Android 4.4.2 the app crashes when I use text to speech and do not get an immediate answer. When restarting the app, it immediately crashes.

**Expected Behaviour**

No crashes.

**Comment by SuperHaker** [comment]
Happened on my Samsung GT-I8552 too. Cleared app data and restarted the app, and it was fixed.
Something to do with resource consumption on phone?

**Comment by vivekkiran** [comment]
I would like to work on this issue! @mariobehling

**Comment by SuperHaker** [comment]
@mariobehling This issue can be closed. :)

**Comment by mayank408** [comment]
@the-dagger Its merged can be closed now :)
