### ISSUE TITLE
Take out "launching browser" from Susi and instead trigger search through a rule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#355]
**Actual Behaviour**

There was the idea of launching a search with Susi whenever there is an answer "I dont know." 
Right now this is triggered in the mobile app. A better approach is to use a rule, that is defined in the susi server. Therefore please take the current implementation out.

**Expected Behaviour**

Susi search should be triggered by a rule instead by a "I dont know" in the app.

**Comment by anantprsd5** [comment]
@mariobehling So for present after taking this implementation out the answer which Susi should provide is "I don't know". Right?

**Comment by mariobehling** [comment]
@anantprsd5 Yes, it should just provide what comes back from the server. Thank you.

**Comment by anantprsd5** [comment]
Okay, Working on it.

**Comment by anantprsd5** [comment]
Thanks for help.

**Comment by Orbiter** [comment]
the correct behaviour for web search is now defined in https://github.com/fossasia/susi_android/issues/360
