### ISSUE TITLE
Add an emoji keyboard like popular chat apps.

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#36]
Emoji sending option can be added directly instead of using keyboard specific emoji option like in popular chat apps. Later on, susi backend api can be improved to add emoji support in the messages.

**Comment by betterclever** [comment]
@the-dagger @daminisatya  You may assign it to me if you find this feature good enough/ worth adding.

**Comment by daminisatya** [comment]
@betterclever yes, this is was in the idea stack. You can implement it. Make sure you open a relevant issue in the susi server as well.

**Comment by addiittya2006** [comment]
@daminisatya Are Rules for parsing unicode Emojis defined in Susi Server?

**Comment by daminisatya** [comment]
@addiittya2006  rules for emojis arent present. Its an open issue

**Comment by mariobehling** [comment]
@addiittya2006 Please open an issue for this in the Susi Server

**Comment by addiittya2006** [comment]
I opened an Issue for this in the server but currently I don't think support for emojis is really required as specifying datasets and rules for emojis for such a peculiar feature is a cumbersome task.

**Comment by amitiwary999** [comment]
@the-dagger @daminisatya for now close this issue because we can't work on this until this issue is resolved in the Susi Server.

**Comment by daminisatya** [comment]
Sure then please follow up with the server update . Thank you.
