### ISSUE TITLE
Show a google search result list for new answer action type "websearch"

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#360]
**Actual Behaviour**

currently there is a hard-coded rule inside the app which triggers a web search.

**Expected Behaviour**

The app shall not decide on itself to perform a web search. It must only react on the actions as given in the actions object. To perform a web search, the actions object may now contain an action with the type "websearch". In case that such an action appears, use the value "query" inside the action object to get the actual query term for the web search.

The new actions array will probably contain two actions, one with an normal answer type and another with the new websearch type. Both actions must be performed in the same order as given in the actions array

**Steps to reproduce it**

ask susi the following string: "search for linux distibutions", or open http://api.asksusi.com/susi/chat.json?timezoneOffset=-60&q=search+for+linux+distributions. You will get an result json with the following actions array:
```
"actions": [
      {
        "type": "answer",
        "expression": "Here is a web search result:"
      },
      {
        "type": "websearch",
        "query": "linux distributions"
      }
    ]
```
Use the query object to query the google search result, in this case "linux distributions".
The app shall then show two things:
- the line "Here is a web search result:" - as taken from the expression object
- the google search result in the same window

**Comment by mayank408** [comment]
I would like to work on this..

**Comment by mayank408** [comment]
@Orbiter I have changed the type from "rss" to "websearch" but the response from the server is not proper, there is no title , link , description anywhere as mentioned in issue #150 . 
Due to which the views are null and are not inflating.

![whatsapp image 2016-11-26 at 11 08 00 pm](https://cloud.githubusercontent.com/assets/22056321/20642158/aef6c822-b42d-11e6-95d0-23c7273ef35b.jpeg)

**Comment by Orbiter** [comment]
this is a misunderstanding. Just recently the android app gained the ability to search for google search results itself. That shall be triggered with the 'websearch' action. There is no rss-like data submitted in the case that 'websearch' is given as action. Instead, the app shall do the websearch itself.

In contrast to this, if 'rss' is given as action, the susi result data stucture will return title, subject and link as you expect. In that case the result rendering shall be the same as if the android app performs the web search itself.

**Comment by mayank408** [comment]
@Orbiter I got your point , just tell me one more thing that if the action is "websearch" , do we want to pass the intent to the browser or show the result in the app itself.

**Comment by mariobehling** [comment]
@mayank408 If the action is websearch, please show the result in the app for now.

**Comment by Orbiter** [comment]
in the app itself - and it should look exactly the same as showing rss lists -> use the same code!

**Comment by mayank408** [comment]
@Orbiter ok working on it.

**Comment by mayank408** [comment]
@the-dagger @Orbiter Do I need to use specific API such as google search API or directly query using https://www.google.com/serach?q=query.

**Comment by mayank408** [comment]
@the-dagger ^^

**Comment by the-dagger** [comment]
Yeah, just make a search request on google and parse the incoming html. 
There is no Google search API for this as of now,so this is the o lyrics way to do it.

**Comment by Orbiter** [comment]
I thought there could be a build-in view mechanism in android to do that. If not, use the parser.

**Comment by samsruti** [comment]
@maany Are you still working on this? I would love to take up this issue if you wish to.

**Comment by mayank408** [comment]
@samsruti Ok no problem we can work together but pls tell me how you gonna approach it because there is no API available for search and if you directly query google using https://www.google.com/search?q=search , then according to google policy we get an error asking to write a captcha as we cant use google services through an app.

**Comment by mayank408** [comment]
@chiragw15 @the-dagger @SuperHaker ^^

**Comment by the-dagger** [comment]
If querying google for answers isn't possible, I'd suggest you to have a
look at DuckDuckGo's APIs.
https://duckduckgo.com/api
They do have open sourced APIs for search and answers.

**Comment by chiragw15** [comment]
@mayank408 you can also use this one http://www.faroo.com/hp/api/api.html

**Comment by samsruti** [comment]
Yeah I agree with @the-dagger and @chiragw15, we can use Open Sourced APIs for this.
They are easy and good to use.

**Comment by betterclever** [comment]
https://github.com/fossasia/susi_server/issues/100
