### ISSUE TITLE
Color correction

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#362]
**Actual Behaviour**

1.) Link color is white. Not visible.
![screenshot_20161127-005419](https://cloud.githubusercontent.com/assets/16978820/20643935/fedba7d6-b44b-11e6-8043-f44a2e16d73e.png)

2.) Search color is very dark. Again not visible.
![screenshot_20161127-005408](https://cloud.githubusercontent.com/assets/16978820/20643937/09102646-b44c-11e6-9de6-6b9e76694b29.png)

**Expected Behaviour**

1.) Changing link color to blue similar to whatsapp.
![screenshot_20161127-033029](https://cloud.githubusercontent.com/assets/16978820/20644184/84415bcc-b452-11e6-9913-cbf7b9a48722.png)

or 

plain black.
![screenshot_20161127-011250](https://cloud.githubusercontent.com/assets/16978820/20643944/3213a37e-b44c-11e6-86d2-09f216ae88d7.png)

2.) Changing searched text color to yellow. 
![screenshot_20161127-011230](https://cloud.githubusercontent.com/assets/16978820/20643951/5931524e-b44c-11e6-9111-9ee95ca51469.png)

**Would you like to work on the issue?**
yes

**Comment by satyammittal** [comment]
i would like to work on this

**Comment by chiragw15** [comment]
@satyammittal Sorry, but I have already completed the work.
