### ISSUE TITLE
Empty Messages

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#364]
**Actual Behaviour**

User can send empty messages to susi.

**Expected Behaviour**

No empty messages should be there.

**Steps to reproduce it**

Step 1.) Go to settings,

![screenshot_20161128-044137](https://cloud.githubusercontent.com/assets/16978820/20652820/0ffd2a72-b527-11e6-96a2-483dc3dfe62b.png)

Step 2.) Disable "use mic as input" setting under mic settings.

![screenshot_20161128-044150](https://cloud.githubusercontent.com/assets/16978820/20652830/467ee98c-b527-11e6-892d-543cce249ef0.png)

Step3.) Now tap space bar and send empty messages.

![screenshot_20161128-044226](https://cloud.githubusercontent.com/assets/16978820/20652842/709fc196-b527-11e6-925b-7e92e198c2ed.png)

**Would you like to work on the issue?**
yes

**Comment by mayank408** [comment]
@chiragw15 I already rectified this issue while working on my previous pr , that's why i m sending the pull request.Thanks

**Comment by chiragw15** [comment]
@mayank408 your commit didn't solve the problem. Sending another PR.
