### ISSUE TITLE
Settings title not clear

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#365]
**Actual Behaviour**

The title of settings is not clear and complete. eg "enter as send" , "At speech input enable speech outp.."
Also, there is no need to write enabled or disabled as it is clear from the switch button.

![screenshot_20161128-044150](https://cloud.githubusercontent.com/assets/16978820/20653112/79f33ca4-b52d-11e6-89d8-861dd86b1d0a.png)

**Expected Behaviour**

We can simply remove enabled/disabled text and write a description about the setting just like normal phone settings.

![screenshot_20161128-053322](https://cloud.githubusercontent.com/assets/16978820/20653118/b298830c-b52d-11e6-8c7d-5f956ea0298f.png)

**Would you like to work on the issue?**
yes

**Comment by jig08** [comment]
@chiragw15 Any updates on this ? Are you working on this ?

**Comment by chiragw15** [comment]
@jig08 I have completed it. Wasn't able to send PR due to wifi crises. Sending it.

**Comment by jig08** [comment]
@chiragw15 yes, pls.
