### ISSUE TITLE
"Default Wallpaper" and "No Wallpaper" are same

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#366]
**Actual Behaviour**

Clicking on "No wallpaper" or "Default" sets same background image.

![screenshot_20161128-064732](https://cloud.githubusercontent.com/assets/16978820/20653698/9e04545c-b537-11e6-8d72-879db32bb9e0.png)

**Expected Behaviour**

They should be different.

**Would you like to work on the issue?**
yes

**Comment by daminisatya** [comment]
good point, please show what can the default wallpaper be

**Comment by mayank408** [comment]
@daminisatya can't we scrap the option of default wallpaper as background pretty good just like WhatsApp.

**Comment by chiragw15** [comment]
There is no need to remove the default wallpaper option. We can simply add previous default wallpaper or if not , can find another good one.
![screenshot_20161128-172919](https://cloud.githubusercontent.com/assets/16978820/20667710/b31cfe94-b590-11e6-988b-8fc7be87be1d.png)

**Comment by mariobehling** [comment]
Please do not add the previous wall paper again.

The main goal of the app is to enable people to communicate with Susi. All other features should be a simple as possible. So, if "default wall paper" can go out, then this is good.

We only need the options that really enable Susi. In my view, the question is, if we need wall papers at all. But we have it already..

The future of Susi is to make "her" invisible. We can talk to her and ask her anything and we should not even think of a UI.

**Comment by chiragw15** [comment]
@mariobehling So, I am removing the option of default wallpaper.

**Comment by chiragw15** [comment]
@the-dagger  closing it.
