### ISSUE TITLE
add timezoneOffset to susi API request

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#371]
Currently the ```http://api.asksusi.com/susi/chat.json``` api is called without a timezone information. 

**Expected Behaviour**

For time-based services, we need the local time zone of the android device. The time zone must be computed as minutes delta to the GMT norm as minutes. I.e. if your local position is five hours east of GMT, then you must compute a ```timezoneOffset=-300```.
That parameter must be appended to the susi api call. Currently a call is like:
```
http://api.asksusi.com/susi/chat.json?q=what+time+is+it
```
This must become a call like:
```
http://api.asksusi.com/susi/chat.json?timezoneOffset=-60&q=what+time+is+it
```

If your local position is west of GMT, the timezoneOffset must be a positive number. If you are in the east, the timezoneOffset must be a negative number.

**Steps to reproduce it**

Use the android device with your code an ask "what time is it". Then Susi will tell you the exact time for your local time zone

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by SuperHaker** [comment]
I would like to work on this issue
