### ISSUE TITLE
add geolocation to susi api call

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#372]
Currently the ```http://api.asksusi.com/susi/chat.json``` api is called without a location information. 

**Expected Behaviour**

For location-based services, we need the local geolocation of the android device. If the user has no GPS switched on, you can also use the fuzzy location that can be obtained in android using a network provider. The details are explained in the first answer of http://stackoverflow.com/questions/6181704/good-way-of-getting-the-users-location-in-android .. please use that method.

That longitude and latitude parameter must be appended to the susi api call. Currently a call is like:
```
http://api.asksusi.com/susi/chat.json?timezoneOffset=-60&q=where+am+I
```
This must become a call like:
```
http://api.asksusi.com/susi/chat.json?timezoneOffset=-60&longitude=8.11&latitude=55.8&q=where+am+I
```

**Steps to reproduce it**

Use the android device to ask where you are. An example output will be provided as the solution evolves.

**Comment by chiragw15** [comment]
I would like to work on this issue.

**Comment by samsruti** [comment]
I would like to work on this issue :)

**Comment by chiragw15** [comment]
@Orbiter @mariobehling @the-dagger can we implement something like this?
If the device location is not switched on, we can use device's ip address to find its location.
We can use this api http://freegeoip.net
![screenshot_20161203-044712](https://cloud.githubusercontent.com/assets/16978820/20853778/664bc69a-b914-11e6-8b86-20162d198040.png)

**Comment by the-dagger** [comment]
Sure, looks good.

**Comment by Orbiter** [comment]
freegeoip should be considered as a nice-to-have add-on. It also rises the question if we need another attribute which declares the accuracy of the location which again rises the question on how to handle that.

Therefore let's add another query attribute named 'geosource' where you can set a text, one of
- gps (for LocationManager.GPS_PROVIDER)
- network (for LocationManager.NETWORK_PROVIDER)
- ip (for geoip)

And please compute the geoip only if none of GPS_PROVIDER and NETWORK_PROVIDER is available. Please also do the call to freegeoip at most once.

**Comment by Orbiter** [comment]
To test this, I added a rule for the question "where am I".

The api call url must be
```
http://localhost:4000/susi/chat.json?timezoneOffset=-60&longitude=8.68&latitude=50.11&geosource=gps&q=where+am+I
```

And it will return an answer like:
```
"actions": [{
      "type": "answer",
      "expression": "You are here: https://www.openstreetmap.org/#map=13/50.11/8.68"
    }]
```
So you can test this directly in your android emu.

**Comment by chiragw15** [comment]
@Orbiter sure :+1: Thanks :)

**Comment by chiragw15** [comment]
@Orbiter It is working fine but it isn't showing a map. Instead giving a link to a map.
![screenshot_20161207-062843](https://cloud.githubusercontent.com/assets/16978820/20950709/53f3ffc2-bc47-11e6-9583-7be914268473.png)

**Comment by Orbiter** [comment]
That's fine, we will have another issue to handle the map in a consistent way with the question 'where is'

**Comment by Orbiter** [comment]
so just check in your code please
