### ISSUE TITLE
URLencoding for query attributes missing or failing - mathematical terms do not work

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#373]
**Actual Behaviour**

Susi is now able to compute simple mathematical terms, like ```3+5```, ```7/2```, ```9-1```, ```5*6```. You can test this successfully if you use the native query interface at http://api.asksusi.com and it also works at the web interface at http://asksusi.com

What does not work is the submission of such terms at the android client. Obviously the characters +, -, / and * are encoded in the wrong way.

**Expected Behaviour**

All terms as given above should cause that susi computes the mathematical result on the android client

**Steps to reproduce it**

Type in ```3+5```, ```7/2```, ```9-1```, ```5*6```: there are currently wrong answers (Susi tries to find answers with the help of tweets). The correct answer would be an answer line like ```3+5=8```

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by mayank408** [comment]
@Orbiter  is it all right...

![whatsapp image 2016-11-30 at 10 36 50 am 1](https://cloud.githubusercontent.com/assets/22056321/20740439/06120d5c-b6e9-11e6-9d7f-43b6545eb1f3.jpeg)

**Comment by Orbiter** [comment]
Yes, great! Did you change anything? I tested that with the latest dev release from yesterday.

**Comment by mayank408** [comment]
No , I have not changed anything , my repo is 7 commits behind master.

**Comment by Orbiter** [comment]
I have just pulled the latest commits and my tests in an emulator are the same bad ones as I had with a real device:
![susibadc](https://cloud.githubusercontent.com/assets/238730/20756233/2baf030c-b712-11e6-81e9-a9df0b992b32.PNG)
What could be the reason? Why is this working for you, but not for me?

**Comment by SuperHaker** [comment]
@Orbiter 
Try again with today's debug release. This issue is not in mine either.

**Comment by Orbiter** [comment]
Oh ok, it's actually working now! Thank you!
