### ISSUE TITLE
Messages are deleted after logout

### ISSUE THREAD

**Issue by samsruti** [fossasia/susi_android#380]
**Actual Behaviour**
Before logout
![before_logout](https://cloud.githubusercontent.com/assets/6136117/20842011/f363e4d8-b8db-11e6-992e-20dc1b97f5d0.png)

After Logout
![after_logout](https://cloud.githubusercontent.com/assets/6136117/20842021/fe041160-b8db-11e6-870b-116c760f06b5.png)

**Expected Behaviour**

The messages should remain as it is. 

**Steps to reproduce it**

1. Login in to app. Send some messages.
2. Logout then.
3. All messages are deleted.

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by amitiwary999** [comment]
@samsruti Yeah because messages are saved on  mobile using realm and it is erased when user logout.

**Comment by samsruti** [comment]
@amitiwary999 But I think this should not happen. What if a user wants the old messages after he logged out?

**Comment by amitiwary999** [comment]
@samsruti I know but for that we have to save data on a server.

**Comment by SuperHaker** [comment]
@samsruti  can we use firebase/Google drive/or just save the messages on phone storage and the next time the user logs in, it searches for a backup and if found, restores the messages, something like how whatsapp implements it?

**Comment by samsruti** [comment]
@SuperHaker Yeah we could use firebase to implement that. But what if we got a lot of user messages? It will be difficult to store the messages.

**Comment by mariobehling** [comment]
Probably we would save the data in the server. There are already ways to save items in the susi server. At the moment we need people who understand the server better and can join development there as well. Let's postpone this issue for now before we make a decision and get the app more stable.

**Comment by samsruti** [comment]
@mariobehling Yeah sure we will postpone this. I have started understanding the server. If I feel like I could handle this later, I will surely let you know. Till then we should focus to make the app more stable.
