### ISSUE TITLE
Date is always of today

### ISSUE THREAD

**Issue by vishwesh3** [fossasia/susi_android#382]
**Actual Behaviour**

In the chat activity date is always of today irrespective of the chat message date.

**Expected Behaviour**

Date should change according to the message data (floating labels) as happens in whatsapp.

**Steps to reproduce it**

Store date along with message in local database. Create a floating label (Date textview) and change it text according to message date in recyclerView. 

**Screenshots of the issue**

![susi floating date label](https://cloud.githubusercontent.com/assets/18511177/20865954/f34876c4-ba45-11e6-9efc-57fbbaf85012.jpeg)

**Would you like to work on the issue?**

Yes i would like on this issue.

**Comment by amitiwary999** [comment]
@vishwesh3 look at #255
