### ISSUE TITLE
Clear chat option in Menu Item.

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/susi_android#383]
**Actual Behaviour**

There is no option to clear the chats at once.

**Expected Behaviour**

A clear chat option should be  implemented in the MenuItem to clear all the chats.

**Steps to reproduce it**

Clear chat menu should be added in the menu item to clear all the chats.

**Screenshots of the issue**

![whatsapp image 2016-12-04 at 5 29 32 pm](https://cloud.githubusercontent.com/assets/21558765/20866001/73b57c2a-ba47-11e6-9569-9d79d4f7348e.jpeg)

**Would you like to work on the issue?**

Yes i would like to work on this.

**Comment by mayank408** [comment]
Copy of #308

**Comment by saketkumar95** [comment]
@mayank408 That issue is closed without being implemented. 
@mariobehling Can i work on this?

**Comment by mayank408** [comment]
@saketkumar95 It is closed because its not required as of now.

**Comment by saketkumar95** [comment]
@mayank408 It was not required in october. This is december now. Let @mariobehling comment on this. If it is not required , then i will close the issue. Thanks for your suggestions.

**Comment by mariobehling** [comment]
We would need to implement this in the server first and there are still issues to run the app on many devices in a stable manner. Therefore closing this as a non-priority issue. Cheers.
