### ISSUE TITLE
Improve error messages and design for sign up and wrong emails/passwords

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#384]
**Actual Behaviour**

Currently the error message when signup for an account or entering the wrong passwords are difficult to view. Please improve the process similar to Facebook and show info boxes.

* [ ]  Please add "Ok" buttons for messages as Facebook does.

* Please implement info boxes as follows:
   * [ ] "Incorrect Password 
          The password you have entered is incorrect. Please try again"
![screenshot_2016-12-05-19-41-39](https://cloud.githubusercontent.com/assets/1583873/20885815/80693464-bb25-11e6-90ae-703b75fe5642.png)

   * [ ] "Incorrect Email
          The email you entered does not belong to an account. Please check your email address and try again"
![screenshot_2016-12-05-19-54-31](https://cloud.githubusercontent.com/assets/1583873/20885829/90669406-bb25-11e6-96b2-2e5bce6784ac.png)

  * [ ] If a user tries to sign up with an existing email in the system, please display the following info in the box "This email address is already registered. Please use the forgot password option, if you do not remember your password."

  * [ ] If a user stops the sign up process, please display a box with the info "Are you sure, you want to stop the sign up process? You will not be able to use the Susi app without an account."

**Comment by samsruti** [comment]
I would like to work on this issue :)

**Comment by mayank408** [comment]
@jig08 @samsruti I have already implemented alert for already existing emails and signup , so if u like I want to work on this.

**Comment by daminisatya** [comment]
@mayank408 Conflict of work :) Try to share the work you have done and not done. So that it reduces duplicate effort.

**Comment by samsruti** [comment]
@mayank408 I already started on that. But do let me know what sections out of 5 you want to work upon?

**Comment by mayank408** [comment]
@samsruti I am working on invalid email and password.
