### ISSUE TITLE
Display message at the end of the sign up process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#386]
**Actual Behaviour**

Currently no specific message is shown.

**Expected Behaviour**

* [ ]  At the end of the sign up process display a message box "Thank you for signing up. We have sent an email to the address you provided. Please use the confirmation link to activate your account and sign in to Susi." 
* [ ] Add an "Ok" button (just like Facebook)
* [ ] After the user presses ok, redirect to login page

**Comment by amitiwary999** [comment]
I would like to work on this issue

**Comment by jig08** [comment]
@amitiwary999 Pls take one issue at a time, you can resolve the prev assigned before taking this up next.

**Comment by mayank408** [comment]
I would like to work on this.
