### ISSUE TITLE
Do not let user signup with alredy registered email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#387]
**Actual Behaviour**

Currently the mobile app let's users sign up with existing emails. However the server does not send the registration credentials, - cause the email address already exists.

**Expected Behaviour**

During sign up display message "Email address already exists. Please sign in with this email or use another email" and add an "Ok" button.

**Comment by mayank408** [comment]
I would like to work in this.

**Comment by mariobehling** [comment]
Great. You can test how this works on the web here: http://api.asksusi.com/apps/signup/
