### ISSUE TITLE
Addition of stricter unit tests.

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#39]
Current unit tests on Travis just check for successful build but does not check whether various app functionality is working correctly or not.

We may add support for checking basic app functionalities like sending messages using androidTest framework so that errors like in #34  can be avoided.

**Comment by code-crusher** [comment]
@betterclever I was also thinking of making Unit Tests from the beginning. Are you working on it or can i take this?

**Comment by betterclever** [comment]
@code-crusher I am a bit busy currently in studies. You may take it for sure.

**Comment by code-crusher** [comment]
@betterclever great, I'll do it today.

**Comment by jig08** [comment]
@code-crusher Updates on this ?

**Comment by code-crusher** [comment]
@jig08 currently many parts of the app are changing, if i write a test case it might fail on update. Will try to add a few. And it would be good if it is not assigned to anyone so that all can write test cases. :)
