### ISSUE TITLE
Add action type 'anchor' to display a single link as answer line

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#397]
**Actual Behaviour**

Currently we cannot have anchor texts for links embedded in answer texts.

**Expected Behaviour**

We want to show links with link texts differently from the link itself. To do this, a new answer action type 'anchor' is introduced. Answer actions are presented as extra object within the set of given actions.

An anchor action looks like:
```
"actions": [
      {
        "type": "anchor",
        "link": "https://www.openstreetmap.org/#map=13/52.52436820069531/13.41053001275776",
        "text": "Link to Openstreetmap: Berlin"
      }
    ]
```
and can be tested with a query "where is berlin", i.e.:
http://api.asksusi.com/susi/chat.json?timezoneOffset=-60&q=where+is+berlin

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by mayank408** [comment]
I would like to work on this.

**Comment by mayank408** [comment]
{
        "type": "answer",
        "expression": "Berlin is a place with a population of 3426354. Here is a map: https://www.openstreetmap.org/#map=13/52.52436820069531/13.41053001275776"
      },
      {
        "type": "anchor",
        "link": "https://www.openstreetmap.org/#map=13/52.52436820069531/13.41053001275776",
        "text": "Link to Openstreetmap: Berlin"
      },

**Comment by mayank408** [comment]
Just tell me how we gonna expression then , for ex if user asked "where is berlin" then susi would reply 
Berlin is a place with a population of 3426354. Here is a map: https://www.openstreetmap.org/#map=13/52.52436820069531/13.41053001275776"

https://www.openstreetmap.org/#map=13/52.52436820069531/13.41053001275776"
"Link to Openstreetmap: Berlin"

in this way??

**Comment by Orbiter** [comment]
Yes I know that looks awkward right now, but it's just an example. As soon as this works, the rule in Susi will be changed and there will be only one link as a result.

**Comment by Orbiter** [comment]
There is now also a related issue: https://github.com/fossasia/susi_android/issues/400 which will show a map according to given location informations. But it is a different aspect. Both (showing a link and showing a map) will be combined for answers to questions like "where is". So please omit any map-related things here, this is just about links. The map is handled in https://github.com/fossasia/susi_android/issues/400

**Comment by samsruti** [comment]
I would like to work on this issue

**Comment by samsruti** [comment]
@Orbiter Can you please close this issue?
