### ISSUE TITLE
Add action type 'map' to display a map within the chat

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#400]
**Actual Behaviour**

Currently there is no special handling of geolocation information from actions in susi response

**Expected Behaviour**

A new action type "map" has been introduced. If the susi server responds with a geolocation action result, the android app shall show a map for the given coordinates.
Here is an example:
```
"actions": [
      {
        "type": "map",
        "latitude": "52.52436820069531",
        "longitude": "13.41053001275776",
        "zoom": "13"
      }
    ]
```
If such an action occurs, please show a map in the response of the chat. The zoom value represents a zoom level according to openstreetmap zoom levels.

**Steps to reproduce it**

You can get such an action type if you ask susi "where is berlin" (or any other location). This would be the api call:
http://api.asksusi.com/susi/chat.json?timezoneOffset=-60&q=where+is+berlin

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by mayank408** [comment]
I would like to work on this.
