### ISSUE TITLE
Add a feature of Solid colors as background.

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/susi_android#408]
**Actual Behaviour**

In most of the messaging apps, the user gets to select the Solid colors as background color. Currently there is only option to set an image or no wallpaper

**Expected Behaviour**

There should be an option of selecting solid colors for background. Just for a demo see the screenshots.

![2c](https://cloud.githubusercontent.com/assets/21558765/21056112/3d57f114-be5a-11e6-99d9-b70d1dc4cace.jpeg)

![1c](https://cloud.githubusercontent.com/assets/21558765/21056123/486fcbd0-be5a-11e6-98ea-19d16e273c25.jpeg)

**Steps to reproduce it**

Add an option to select solid colors in background.

**Would you like to work on the issue?**

Yes i would like to work on this.

**Comment by jig08** [comment]
With respect to https://github.com/fossasia/susi_android/issues/366#issuecomment-263709314, closing this issue :) 

We are currently focussing more on the functionality aspect than UI.

**Comment by saketkumar95** [comment]
@jig08 Will like to know what more functionality we can add. I'm ready to work on it.

**Comment by jig08** [comment]
Check out the [unassigned issues issues](https://github.com/fossasia/susi_android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) and grab any :)

**Comment by saketkumar95** [comment]
They are unassigned but people already commented to work on that. I got this [#211](https://github.com/fossasia/susi_android/issues/211) issue but couldn't understand what actually is the issue? If you could then do explain me.

**Comment by jig08** [comment]
When you send a link in a message (say `message_a`) to `susi`, a link preview is displayed.

But then when you scroll up to the extent that `message_a` isn't visible on the current screen and go back again (downwards) to `message_a` again after scrolling up, the link preview is gone.


That's what Issue #211 states.

Hope I was able to put in clearer words.

**Comment by saketkumar95** [comment]
Cool. I got it now. Thanks :) and do assignee me that issue.
