### ISSUE TITLE
Disable The Ask Susi Something Bar on tapping on the search view bar.

### ISSUE THREAD

**Issue by HimanshuS01** [fossasia/susi_android#414]
**Actual Behaviour**

When we tap on the search icon in the action bar, the AskSusi Something EditText shown below along with the mic which   usually remains hidden in other chat application.

**Expected Behaviour**

So either we can hide the AskSusi Something EditText and FloatingActionButton i.e. mic or we can disable both of them. 
Thank You!

**Screenshots of the issue**
![untitled-1](https://cloud.githubusercontent.com/assets/18090596/21078992/7fc031ec-bfa9-11e6-95c8-c29204a5f9c1.png)

**Would you like to work on the issue?**
Yes.I would like to work on it.

**Comment by amitiwary999** [comment]
Already done this in #292 .I am Waiting for their reply.

**Comment by LearnerHimanshu** [comment]
Ok fine @amitiwary999 .So didn't you send the PR for the same?

**Comment by amitiwary999** [comment]
They closed this issue #292.

**Comment by LearnerHimanshu** [comment]
@mariobehling @amitiwary999  My point is different from what is mentioned in #292 
The mic is not disabled like EditText. Either both of them should be disabled or none of them or we should also hide both of them like in whatsapp. Thanks.
@mariobehling can I work on this?

**Comment by HimanshuS01** [comment]
@jig08 @the-dagger can I send PR for this if this is an intented enhancement?

**Comment by jig08** [comment]
Kindly hide the `EditText` and `Mic` on search.

**Comment by HimanshuS01** [comment]
Ok @jig08 .I will soon send  a PR.
