### ISSUE TITLE
Addition of a new action 'Call'

### ISSUE THREAD

**Issue by octacode** [fossasia/susi_android#415]
**Actual Behaviour**

For the time being. If we request Call '987653210'. Susi launches a web search intent for it.

**Expected Behaviour**

Susi will launch the dialer and set the number "9876543210" on the dialer.

**Steps**
I will use the Intent.ACTION_DIAL. So no new permission will be required.

**Would you like to work on the issue?**

Definitely, I would love to.

**Comment by mayank408** [comment]
@octacode any updates on this issue.

**Comment by octacode** [comment]
Working on it.

**Comment by mayank408** [comment]
@octacode great
