### ISSUE TITLE
On changing the screen orientation data in the search bar lost

### ISSUE THREAD

**Issue by HimanshuS01** [fossasia/susi_android#417]
**Actual Behaviour**
When we change the orientation of our device then anything we had typed in search bar gets lost.

**Expected Behaviour**

Data we typed on search bar must be preserved even on changing the screen orientation.

**Screenshots of the issue**
Before:
![3ecf2142-30cd-4097-9da2-0e01c968f2e7](https://cloud.githubusercontent.com/assets/18090596/21083289/0c63be0c-c013-11e6-9598-e41f65f97475.jpg)

After:
![59edb56e-570b-4ae9-8fbd-337c7a99eeb9](https://cloud.githubusercontent.com/assets/18090596/21083318/d2179a9c-c013-11e6-872c-5c3dfa4713bd.jpg)

**Would you like to work on the issue?**
Yeah! I would like to work on this issue.Thanks.

**Comment by LearnerHimanshu** [comment]
hey @mayank408 ,I had already solved this issue and was waiting for the @mariobehling @the-dagger approval.I will send PR once this is approved.
Thanks.

**Comment by samsruti** [comment]
@mayank408 Please let everyone know that you are working on any issue if you are not assigned to it. If nobody is assigned wait for the admin, so that they can assign. Otherwise conflict of work would happen :)

**Comment by mayank408** [comment]
@LearnerHimanshu @samsruti The issue was unassigned and required only a single line of code thats why I made the pull request because there is no point in holding such petty issues. Ya i must have informed first , sry for that part .
Thanks.

**Comment by samsruti** [comment]
@mayank408 Thanks.
