### ISSUE TITLE
Wake lock permission

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#42]
@the-dagger could you tell why there is wake lock permission declared in manifest? we can remove it if not needed.

**Comment by shivenmian** [comment]
Because the project was originally a fork of another repo. Maybe the line came from there.

**Comment by the-dagger** [comment]
I believe that is for a future use case, in which susi has to remind the user of a particular task or has to trigger a particular function at a specific time.
Although I'm not really sure if it is required as of now.
You can go ahead and remove it for now.

**Comment by gogeta95** [comment]
Okay, sending PR in a minute.
