### ISSUE TITLE
Order of messages not right

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#421]
**Actual Behaviour**

When sent two or more continuous messages, their response order is not correct.

**Expected Behaviour**

The response from susi should be in correct order.

**Steps to reproduce it**

Send two consecutive messages without waiting for susi's reply.

**Screenshots of the issue**

![screenshot_20161219-082024](https://cloud.githubusercontent.com/assets/16978820/21125887/bd82720e-c10e-11e6-8ac1-66d9dd2bc2f2.png)

**LogCat for the issue**

12-19 08:20:03.793 15122-15989/org.fossasia.susi.ai V/chirag: yo (123 ) Sent for response
12-19 08:20:04.537 15122-15988/org.fossasia.susi.ai V/chirag: added yo (123) to database
12-19 08:20:05.122 15122-16014/org.fossasia.susi.ai V/chirag: hi (124 ) Sent for response
12-19 08:20:05.125 15122-16013/org.fossasia.susi.ai V/chirag: added hi (124) to database
12-19 08:20:05.632 15122-15122/org.fossasia.susi.ai V/chirag: Got response of hi (124)
12-19 08:20:05.659 15122-16026/org.fossasia.susi.ai V/chirag: added Hi, I'm Susi(125) to database
12-19 08:20:07.166 15122-15122/org.fossasia.susi.ai V/chirag: Got response of yo (123)
12-19 08:20:07.195 15122-16053/org.fossasia.susi.ai V/chirag: added Yo this Instagram update is crazy. You can livestream!(126) to database

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
@the-dagger @Orbiter What may be the cause of this issue?

**Comment by viveksb007** [comment]
@chiragw15 its probably because of response delay from susi server. response for "hi" is fast but for "yo" it takes time relative to "hi".
you can check it here https://susi-server.herokuapp.com/  check with "hi" and "yo", you can see the delay.

**Comment by chiragw15** [comment]
@viveksb007 @samsruti @mayank408 Is it possible that we are sending one query to susi server and even before receiving response of the first query, we are sending a second query and getting its response? If it is possible, then what may be the possible solution of this problem?

**Comment by samsruti** [comment]
@chiragw15 I think yes.
It is an issue in susi_server i think.

**Comment by chiragw15** [comment]
@samsruti What is the ideal behavior then? "One api call at one time" or can we send multiple queries from a single device at a particular time?

**Comment by viveksb007** [comment]
@chiragw15 that's exacly what is happening. We can send multiple queries at a particular time.

![screenshot from 2016-12-19 22-13-45](https://cloud.githubusercontent.com/assets/12713808/21320895/9271c02c-c638-11e6-94a6-a5bbffab6c4b.png)
![screenshot from 2016-12-19 22-14-03](https://cloud.githubusercontent.com/assets/12713808/21320896/927531a8-c638-11e6-8ea3-2826c52d0f73.png)

you can see delay in response by difference in query-date and answer-date.
To solve arrangement of messages arrange by query-date, but that would add another parameter with susi reply. If you have some different approach, do tell.

**Comment by chiragw15** [comment]
Since we are maintaining a queue for susi api call, can we simply push the next query in the queue when the response of the first query is received? Will that work?

**Comment by samsruti** [comment]
@chiragw15 if we could wait for the first query to get executed, then we could solve this issue. So Yeah, Queuing would work ;)

**Comment by mayank408** [comment]
@chiragw15 @samsruti  Cant we limit only one query at a time, it will eventually solve this problem.

**Comment by octacode** [comment]
@mayank408 Yeah, I too am thinking the same. But how will we limit to only one query?

**Comment by samsruti** [comment]
@mayank408 This could make a user feels boring sometimes. Suppose I want to type 3 messages like: 
1.Hey Susi
2. Show me a nearby hospital
3. Call me an ambulance.

I can't wait for the response of that message to reply another message.
So I think we should queuing of queries would be helpful in this case.

**Comment by chiragw15** [comment]
@samsruti We are actually maintaining a queue right now and recursively poping elements (queries) of queue and sending it to susi server. But due to asynchronous operations, the order is reversed because it takes more time for susi to reply to "yo" than "hi".

**Comment by anuradhagupta345** [comment]
@the-dagger Shall I work on this?

**Comment by chiragw15** [comment]
@anuradhagupta345 go ahead :+1:

**Comment by Abhi2424shek** [comment]
I think for this, we need to open a susi response with dots after the user has clicked the send button and that's what's being done and send a string with timestamp and a hash, and susi server needs to respond with the given has back, and we change the dots in the susi response to have the updated result!

**Comment by Abhi2424shek** [comment]
@anuradhagupta345 updates would be awesome ;)

**Comment by mayank408** [comment]
@chiragw15 I think the problem is resolved now as I have tested it 3 - 4 times.

**Comment by chiragw15** [comment]
@mayank408 nope. Try with "where is Singapore" and "hi".

**Comment by dabbler011** [comment]
@chiragw15 trying similar example as you mentioned, responses of both queries comes out to be that of the first one only i.e. I tried "where is India" and "hi" and susi responses twice with location of india as you can see in screenshots.

![screenshot_2017-09-09-01-02-13](https://user-images.githubusercontent.com/24551629/30228694-713b27c0-94fc-11e7-82ff-91f1a7067ded.jpg)

![screenshot_2017-09-09-01-02-25](https://user-images.githubusercontent.com/24551629/30228701-738da2fa-94fc-11e7-9833-daefe8da0113.jpg)

![screenshot_2017-09-09-01-02-28](https://user-images.githubusercontent.com/24551629/30228703-7673e6c8-94fc-11e7-8427-9096ce859f4b.jpg)

shall I work on this?

**Comment by chiragw15** [comment]
Yaa sure. Go ahead :+1:
