### ISSUE TITLE
Addition of a RateApp feature in the settings Activity.

### ISSUE THREAD

**Issue by octacode** [fossasia/susi_android#426]
**Expected Behaviour**
As Susi is already live on PlayStore. I was thinking of adding a link in the Settings Activity.

**Would you like to work on the issue?**
Yes!

**Comment by krishnarai30** [comment]
yes

**Comment by AmoliShah** [comment]
I would like to work on this issue. @octacode

**Comment by octacode** [comment]
@AmoliShah I am already done with it. As soon as it is approved. I will send the PR.

**Comment by AmoliShah** [comment]
ok. @octacode
