### ISSUE TITLE
No Search Results Found

### ISSUE THREAD

**Issue by AmoliShah** [fossasia/susi_android#427]
**Actual Behaviour**

Whenever it answers 'I dont know how to answer this.Here is the web search result:' No search results are found.

**Expected Behaviour**

It should produce the results from Google search.

**Screenshots of the issue**

![screenshot_2016-12-21-12-17-47](https://cloud.githubusercontent.com/assets/15183634/21379962/dba6f47a-c777-11e6-80c8-d7729b5c387a.png)

**Would you like to work on the issue?**
Yes

**Comment by AmoliShah** [comment]
@the-dagger Can i start working on it?

**Comment by mayank408** [comment]
@AmoliShah @the-dagger  I am already working on implementing google search using chrome custom tabs you can check out at gitter channel as well.

**Comment by AmoliShah** [comment]
@mayank408 ok cool.
