### ISSUE TITLE
Page down Navigation Icon is visible everytime

### ISSUE THREAD

**Issue by samsruti** [fossasia/susi_android#438]
**Actual Behavior**

Page down Navigation Icon is visible even if the last message is showing. 

**Expected Behavior**

This icon should be present when you are at the top of the conversation. It should display at the end of the conversation

**Steps to reproduce it**

Navigate to the end of the conversation. That icon would still be visible.

**Screenshots of the issue**

![bug](https://cloud.githubusercontent.com/assets/6136117/21506205/47780466-cc94-11e6-967e-f9f06fed9dc1.png)

**Would you like to work on the issue?**

Yes I would like to work on this issue.

**Comment by mayank408** [comment]
@samsruti Its not showing in my mobile , its not an issue until the last merge , how its showing in yours....

**Comment by samsruti** [comment]
@mayank408 I have updating my branch and still its happening.
