### ISSUE TITLE
Adding landscape layout for signup screen

### ISSUE THREAD

**Issue by HimanshuS01** [fossasia/susi_android#445]
**Actual Behaviour**
Right now there is a scrolling behaviour in SignUp screen during landscape mode,which is generally not present in other application like in facebook.

**Steps to reproduce it**
Adding landscape layout for signup screen.

**Screenshots of the change**
![device-2016-12-30-153713](https://cloud.githubusercontent.com/assets/18090596/21563213/c7d0704a-cea5-11e6-9c23-5d8c2cc1ce81.png)

**Would you like to work on the issue?**
@daminisatya @the-dagger @jig08 If this is an intented enhancement can i send the PR for the same ?
Thanks.

**Comment by krishnarai30** [comment]
@HimanshuS01 i would like to work on this

**Comment by HimanshuS01** [comment]
Hey @krishnarai30  I have already done with this UI and just waiting for mentors approval. Once they approve this, I will send the PR. 
Thanks.

**Comment by HimanshuS01** [comment]
@the-dagger @daminisatya @jig08 can I send the PR? 
Thanks.

**Comment by HimanshuS01** [comment]
Sure @mariobehling Thank you.I am just waiting for my issue approval whether it is legitimate or not.
I will take care of that.
