### ISSUE TITLE
Wallpaper Not changing

### ISSUE THREAD

**Issue by krishnarai30** [fossasia/susi_android#446]
**Actual Behavior**

Wallpaper isn't changing.
The image to be applied changes its aspect ratio and saves as a new version of the actual image.

**Expected Behavior**

Wallpaper is changed.

**Steps to reproduce it**

Refer screenshots.

**Screenshots of the issue**

![whatsapp image 2016-12-30 at 9 54 55 pm 2](https://cloud.githubusercontent.com/assets/16545083/21568648/454193ac-cedc-11e6-8b0b-4f37168b5bef.jpeg)
![whatsapp image 2016-12-30 at 9 54 55 pm 3](https://cloud.githubusercontent.com/assets/16545083/21568645/4540d836-cedc-11e6-95fe-5087232e9933.jpeg)
![whatsapp image 2016-12-30 at 9 54 55 pm 4](https://cloud.githubusercontent.com/assets/16545083/21568646/45413164-cedc-11e6-8056-66bffae66593.jpeg)
![whatsapp image 2016-12-30 at 9 54 55 pm 5](https://cloud.githubusercontent.com/assets/16545083/21568647/45418ad8-cedc-11e6-9b9e-bf9b5c401fad.jpeg)
![whatsapp image 2016-12-30 at 9 54 55 pm 6](https://cloud.githubusercontent.com/assets/16545083/21568650/454b03f6-cedc-11e6-9c77-e2d4405d6846.jpeg)
![whatsapp image 2016-12-30 at 9 54 55 pm 7](https://cloud.githubusercontent.com/assets/16545083/21568649/4545bdba-cedc-11e6-87d1-e23aadd758d3.jpeg)
![whatsapp image 2016-12-30 at 9 54 55 pm 1](https://cloud.githubusercontent.com/assets/16545083/21568651/45706434-cedc-11e6-9be3-c73dbb0b21d2.jpeg)

**Would you like to work on the issue?**
Yes, I have started working on the issue. will send a PR after admin approval.

**Comment by chiragw15** [comment]
@krishnarai30 I think it is working fine if you complete action using galley but doesn't work for Google photos. Is it?

**Comment by HimanshuS01** [comment]
Hey @krishnarai30 what's the progress in this issue.?  :)

**Comment by krishnarai30** [comment]
@HimanshuS01 I am working on the issue and testing it on various devices will send PR within this week.

**Comment by Abhi2424shek** [comment]
@krishnarai30 updates?

**Comment by krishnarai30** [comment]
@Abhi2424shek  at ISGW Hackathon this weekend will send the PR soon.

**Comment by Abhi2424shek** [comment]
Sure take your time, i just wanted to ensure you were on it @krishnarai30

**Comment by anantprsd5** [comment]
@krishnarai30 Any updates on this?

**Comment by krishnarai30** [comment]
Sorry for the delays due to prior appointments I haven't been able to dedicate time to this problem.

**Comment by Abhi2424shek** [comment]
@krishnarai30 so if you wish we could flag this if you so that someone else gets it done as far I understand that it is what you r trying to tell with the last message, but who is a programmer who hates to code, we could wait for you so let us know your decision in poor words for we await it :)

**Comment by anantprsd5** [comment]
@krishnarai30 Please let us know if you are working on this or else I want to take this issue.
