### ISSUE TITLE
all prev web search results reflect the latest one only.

### ISSUE THREAD

**Issue by supreme96** [fossasia/susi_android#447]
**Actual Behaviour**
when made multiple queries which were responded with different web search results, all previous web search results also change to show only the latest search result. 

**Expected Behaviour**

for the multiple quries each of the response search results should show their own results.

**Steps to reproduce it**
make multiple queries which are answered by web search results
**LogCat for the issue**

"query": "delhi",
12-31 16:14:58.185 14333-14688/org.fossasia.susi.ai D/OkHttp:   "client_id": "ZW1haWxfc2FoaWx0YW5kb24xOTk2QGdtYWlsLmNvbQ==",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:   "query_date": "2016-12-31T10:44:53.926Z",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:   "answer_date": "2016-12-31T10:44:58.243Z",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:   "answer_time": 4317,
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:   "count": 1,
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:   "answers": [{
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:     "data": [
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:       {
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "0": "delhi",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "1": "delhi",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "timezoneOffset": "-330",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "latitude": "28.6216",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "longitude": "77.0946",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "answer": "I don't know how to answer this. Here is a web search result:",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "query": "kolkata"
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:       },
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:       {
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "answer": "I don't know how to answer this. Here is a web search result:",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "query": "mysore"
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:       },
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:       {
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "answer": "I don't know how to answer this. Here is a web search result:",
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "query": "delhi"
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:       },
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:       {
12-31 16:14:58.186 14333-14688/org.fossasia.susi.ai D/OkHttp:         "answer": "I don't know how to answer this. Here is a web search result:",
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:         "query": "delhi"
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:       },
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:       {
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:         "answer": "you gotta check yo girls temperature fellas..or i will",
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:         "query": "temperature"
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:       }
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:     ],
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:     "metadata": {"count": 5},
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:     "actions": [
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:       {
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:         "type": "answer",
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:         "expression": "I don't know how to answer this. Here is a web search result:"
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:       },
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:       {
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:         "type": "websearch",
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:         "query": "delhi"
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:       }
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:     ]
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:   }],
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:   "session": {"identity": {
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:     "anonymous": false
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp:   }}
12-31 16:14:58.187 14333-14688/org.fossasia.susi.ai D/OkHttp: }
12-31 16:14:58.188 14333-14688/org.fossasia.susi.ai D/OkHttp: <-- END HTTP (1393-byte body)
12-31 16:14:58.205 14333-14333/org.fossasia.susi.ai D/org.fossasia.susi.ai.activities.MainActivity: []
12-31 16:14:58.210 14333-14333/org.fossasia.susi.ai D/org.fossasia.susi.ai.activities.MainActivity: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
12-31 16:14:58.308 14333-14333/org.fossasia.susi.ai V/org.fossasia.susi.ai.activities.MainActivity: updated successfully!

**Screenshots of the issue**

![screenshot_20161231-140854](https://cloud.githubusercontent.com/assets/15019358/21577123/96661cf0-cf75-11e6-98b3-243321f365fc.png)
![screenshot_20161231-161838](https://cloud.githubusercontent.com/assets/15019358/21577124/96680902-cf75-11e6-9edd-e20c9c9f93eb.png)

**Would you like to work on the issue?**

yes

**Comment by mayank408** [comment]
@supreme96 This issue is copy of #211 , in both we have to save it in database and I am working on it.
Please find other issue or take any unassigned issue . Cheers :)

**Comment by supreme96** [comment]
ok .
