### ISSUE TITLE
Apk does not install

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#448]
**Actual Behaviour**

Latest apk does not install on my phone.

**Steps to reproduce it**

After an unusual long installation time I get the dialog message "not installed"

**Comment by samsruti** [comment]
Which version of OS and phone are you using?

**Comment by HimanshuS01** [comment]
Yeah.  There is a problem occurring in installing the apk and yes! It is also taking so much time to install

**Comment by samsruti** [comment]
Can you please check by uninstalling the previous version of the app and install the latest one?

**Comment by Orbiter** [comment]
I uninstalled the older version first. After that the installation of the most recent version failed fast. Then I rebooted the device and installation took long but still failed.

**Comment by samsruti** [comment]
Can you please help us by showing the logs? 
Thanks :)

**Comment by mayank408** [comment]
@HimanshuS01 I am not facing any problem in installing the new apk.

**Comment by chiragw15** [comment]
@Orbiter @HimanshuS01 Are you guys getting something like this? 
![screenshot_20170101-135724](https://cloud.githubusercontent.com/assets/16978820/21580623/40e67dcc-d02b-11e6-9e86-de4d1c22b0b4.png)

I too got this when I downloaded the apk from link in the below picture but worked fine when I ran the project from android studio.
![susi](https://cloud.githubusercontent.com/assets/16978820/21580627/9712e4c4-d02b-11e6-86a4-adfaf268f412.png)

**Comment by mayank408** [comment]
@chiragw15  Yup , I am also facing the issue when downloading through the given link..

**Comment by Orbiter** [comment]
@chiragw15 exactly (well, I have the german message "nicht installiert" which means the same)

**Comment by samsruti** [comment]
I didn't face anything like this.

**Comment by samsruti** [comment]
@the-dagger Can you please re-run the apk-gen.sh :) ?

**Comment by mayank408** [comment]
ebug{
 +            minifyEnabled false
 +        }
 +    }
 +
 +    splits {
 +        abi {
 +            enable true
 +            reset()
 +            include 'x86', 'armeabi-v7a', 'mips', 'arm64-v8a', 'x86_64'
 +            universalApk false
 +        }
 +    }
 +
 +    project.ext.versionCodes = [ 'armeabi-v7a': 1, 'arm64-v8a': 2, 'mips': 3, 'x86': 4, 'x86_64': 5]
 +
 +    android.applicationVariants.all { variant ->
 +        // assign different version code for each output
 +        variant.outputs.each { output ->
 +            output.versionCodeOverride =
 +                    project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) * 1000000 + android.defaultConfig.versionCode
 +        }

**Comment by mayank408** [comment]
@samsruti @Orbiter @the-dagger @chiragw15 This is what I found is causing the error.I think we should not split the apk as done here . I will send the pr if it worked. Thanks:)

**Comment by samsruti** [comment]
mayank408 thanks :)
Let's all try to fix this issue :)
