### ISSUE TITLE
The Ask Susi Something bar doesn't working after closing search bar using back button

### ISSUE THREAD

**Issue by Rajat2712** [fossasia/susi_android#454]
**Actual Behaviour**

When we close the search bar using the back button the ask susi something bar stop responding we have to reopen the app in order to work

**Expected Behaviour**

So after closing the search bar ask susi something bar should work.
![screenshot_2017-01-03-01-41-48](https://cloud.githubusercontent.com/assets/23000971/21595852/9960289e-d158-11e6-9126-881ecb26010b.jpg)

**Would you like to work on the issue?**

 I have a fix for this. Can I work on this. :-)

**Comment by HimanshuS01** [comment]
hey @Rajat2712 I have already solved this issue in #414 and already sent the PR.Now the AskSusi bar is working fine after closing the search bar using back button.Kindly close this issue.
Thanks :)

**Comment by Rajat2712** [comment]
hey @HimanshuS01  I think this issue is different from issue #414  as you had worked on the visibility of the AskSusi bar that it is it will become visible but still it will not work.
