### ISSUE TITLE
Compile only a binary for the external Library

### ISSUE THREAD

**Issue by addiittya2006** [fossasia/susi_android#46]
I think we should only compile the binary for the View Library until we rewrite, which is available [here](https://github.com/himanshu-soni/ChatMessageView#installation).
Project management and gradle compilation is faster after proguard and easier maintenance.

**Comment by addiittya2006** [comment]
@daminisatya Assign me if deemed right.

**Comment by daminisatya** [comment]
@addiittya2006 feel free to take up open issues and you can assign it yourself
