### ISSUE TITLE
Share App feature

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/susi_android#463]
**Actual Behaviour**

Currently there is no option to share app.

**Expected Behaviour**

The users will be able to share app with others.

**Steps to reproduce it**

It should be implemented in the settings activity.

**Would you like to work on the issue?**

Yes, I would like to work on this feature.

**Comment by rohanagarwal94** [comment]
@jig08 @mariobehling any update regarding this?

**Comment by mananwason** [comment]
@rohanagarwal94 Please go ahead with this.
