### ISSUE TITLE
Add Brand Splash Screen

### ISSUE THREAD

**Issue by bxute** [fossasia/susi_android#465]
**Actual Behavior**

Usually App takes some time to load, user is presented with blank screen.
User is confused about apps behavior.
All Google products load with their version of splash screens.
https://material.io/guidelines/patterns/launch-screens.html

**Expected Behavior**

App should present some splash screen

**Steps to reproduce it**

App needs splash screen, i.e. using Theme it can be achieved.

**Would you like to work on the issue?**

Yes i want to enhance it.

**Comment by jig08** [comment]
Closing wrt Issue https://github.com/fossasia/susi_android/issues/385
