### ISSUE TITLE
Adding play music feature in the app

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/susi_android#468]
**Actual Behaviour**

we can't play music on our mobile through susi app.

**Expected Behaviour**

 Just like google allo, we can add this feature to make the app much more user friendly.

**Would you like to work on the issue?**

Yes i would like to work on this.

@jig08 @mariobehling Can i send the PR?

**Comment by jig08** [comment]
@saketkumar95 Go ahead.

**Comment by saketkumar95** [comment]
@jig08 I was thinking of adding many more features like opening social media apps like facebook,  twitter and many others . opening gmail app for sending mails.
What are your suggestions?

**Comment by jig08** [comment]
Open an issue for each feature separately, we can then carry on a discussion for each categorically. 

Also, for playing music, kindly define your implementation strategy in detail, thanks.

**Comment by mayank408** [comment]
@saketkumar95 don't rush it . Take issue one by one and solve it . And pls tell how you gonna implement playing music through the app like you want the user to play music stored on the device or from the internet like youtube..?

**Comment by saketkumar95** [comment]
@jig08 i was thinking of playing music video from youtube in the app itself using youtube api.

**Comment by Abhi2424shek** [comment]
The server would require a tweak!

**Comment by mayank408** [comment]
@saketkumar95 updates..

**Comment by saketkumar95** [comment]
@mayank408  Have patience. I'm working on it, Having some issues in Youtube API. Will complete this soon. :)

**Comment by mayank408** [comment]
@saketkumar95 Great ....

**Comment by mayank408** [comment]
@saketkumar95  @daminisatya I am working on playing youtube videos on the app and you work on playing music , this way the issue can be resolved in quick time. :)

**Comment by saketkumar95** [comment]
@mayank408  I almost completed both the work.  Will submit yhe PR in 2-3 days.. :)

**Comment by mayank408** [comment]
@saketkumar95 I have already solved this issue and sending a pr , its about half a month , there is no point in holding back the issue with yourself. You can work on the music one . Cheers :)
And I have implemented it as you suggested that you are facing problem regarding youtube api. If we will work together issues can be solved in less time . Thats what the beauty of open source is . Thanks :)
