### ISSUE TITLE
Switch between hide and view password in LoginActivity and SignupActivity

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/susi_android#469]
**Actual Behaviour**

Currently there is no option to view the password whenever it is entered.

**Expected Behaviour**

There should be an option to view the password which is entered.

**Would you like to work on the issue?**

Yes i would like to work on it.

**Comment by jig08** [comment]
Kindly take up one issue at a time. Resolve the previous one assigned to you before we can assign you the next. Cheers !

**Comment by amitiwary999** [comment]
I would like to work on this issue.

**Comment by saketkumar95** [comment]
@jig08 I've completed this issue. Waiting for your reply.   And working on my previous assigned issue. Can i send the PR for this?

**Comment by jig08** [comment]
@saketkumar95 In that case, open the issue when you are done with your previous one :) Project contributors and maintainers are not working full-time on these, they have other commitments as well. Hope you understand.
