### ISSUE TITLE
Dots are showing before the message is sent.

### ISSUE THREAD

**Issue by shubhamvashisht** [fossasia/susi_android#471]
**Actual Behaviour**
the dots are showing before the message is sent.
![screenshot_20170115-004410](https://cloud.githubusercontent.com/assets/16692282/22097909/97fd52b2-de49-11e6-9c8c-c957867ccd24.png)

**Expected Behaviour**
The dots should shown after the message is delivered. As in any other IM apps. say ALLO.
and dots should get hide after reply.

**Steps to reproduce it**
@the-dagger is this a valid issue?

**Would you like to work on the issue?**
If its really an issue.

**Comment by the-dagger** [comment]
Ok, makes sense.
Please go ahead and work on this if you'd like to

**Comment by shubhamvashisht** [comment]
alright. Working on it.
