### ISSUE TITLE
An option to delete all chat history

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#473]
**Actual Behaviour**

As of now there is no option to delete whole chat history.

**Expected Behaviour**

There should be an option just like other apps to delete chat history.

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
@mayank408 pls work on then :)

**Comment by saketkumar95** [comment]
Copy of https://github.com/fossasia/susi_android/issues/383
