### ISSUE TITLE
"internet connectivity problem!" error occurring very frequently.

### ISSUE THREAD

**Issue by shubhamvashisht** [fossasia/susi_android#477]
**Actual Behaviour**

"internet connectivity problem!" error occurring very frequently. i tested this for hours, From App and from browser by hitting the url for get request.
:::::::::::::Results:::::::::::::::::
::::::From APP:::::::
Total messages sent: 30
Message resulted in Failure(when onFailure() is called) :13
::::::From Browser:::::
Total message sent(hit the get url same as for messages from app):30
Message resulted in failure(ERROR CODE:503): 1
503 is for when server cant handle HTTP request due to overload.
**Expected Behaviour**

**LogCat for the issue**

![internetcon](https://cloud.githubusercontent.com/assets/16692282/22175403/ead6efe4-e019-11e6-8bb9-9578127a2de3.PNG)

**Would you like to work on the issue?**

HELP me to find whats the issue.

**Comment by Abhi2424shek** [comment]
It's the internet connection issue can you double check your connectivity

**Comment by shubhamvashisht** [comment]
@Abhi2424shek  quite sure that its not a connectivity issue. browser and phone was connected to same network all the time.

**Comment by Abhi2424shek** [comment]
Then it maybe a server issue as there's a request timeout to the three shake TCP handshake!

**Comment by shubhamvashisht** [comment]
may be, its happening more frequently when request is from APP  than from when its from browser.

**Comment by mayank408** [comment]
The problem is not occurring now.
