### ISSUE TITLE
Sometimes a webview response is causing the force close.

### ISSUE THREAD

**Issue by shubhamvashisht** [fossasia/susi_android#478]
**Actual Behaviour**
Sometimes a webview response is causing the force close.
This is only happening when response is a web result.
**Expected Behaviour**
Should not happen :P
**LogCat for the issue**

![error one](https://cloud.githubusercontent.com/assets/16692282/22175452/d8e6222c-e01a-11e6-84c3-188b7bf6e490.PNG)
![screenshot_20170121-211117](https://cloud.githubusercontent.com/assets/16692282/22175652/5cf7ccb0-e01f-11e6-96e3-c686797a9cd2.png)

**Would you like to work on the issue?**
    Yes am looking into it.

**Comment by mayank408** [comment]
Issue resolved.
