### ISSUE TITLE
EditTextBox on Enter key text sending

### ISSUE THREAD

**Issue by sagarchoudhary96** [fossasia/susi_android#48]
when we press enter key, it goes to second line. we can make it that on pressing enter msg get sent

**Comment by daminisatya** [comment]
+1

**Comment by the-dagger** [comment]
@sagarchoudhary96 Sounds good, do you want to work on this?

**Comment by sagarchoudhary96** [comment]
yeah sure .. i would love to work on it :)

**Comment by sagarchoudhary96** [comment]
@the-dagger  okay i will see to it too

**Comment by amitiwary999** [comment]
But My work is different.User may write multiline text without pressing enter key and it will hide large portion of UI.

**Comment by the-dagger** [comment]
@amitiwary999 Yeah saw it just now.
Will reopen your issue

**Comment by gogeta95** [comment]
How about we make it like WhatsApp?
Limit of  4 lines max and "enter is send" is user preference?

**Comment by gogeta95** [comment]
This solves both #48 and #49.

**Comment by addiittya2006** [comment]
#52 A preference toggle must be added in settings to use 'Enter as Send' as most queries to Susi are short.

**Comment by amitiwary999** [comment]
@sagarchoudhary96  if you are working on it then try to solve issue #49  also . Otherwise I will try to solve both issue.

**Comment by sagarchoudhary96** [comment]
@amitiwary999 i'll see to it

**Comment by amitiwary999** [comment]
@sagarchoudhary96 are you working on it. @the-dagger I would  like to work on this. At last you decide whose code you want to pull.

**Comment by sagarchoudhary96** [comment]
@amitiwary999 I have completed it .. i will update pull request as soon i reach home :)

**Comment by sagarchoudhary96** [comment]
For issue 49 as written that User may write multiline text without pressing enter key and it will hide large portion of UI. If enter key as send preference is enabled then the text will be a single line only and if it is disable than it will go to multiline and since it is chatbot what i think is no user will be ever asking questions more tan 2-3 lines at max.  if question is more than 7-8 lines then only it will cover a large portion of ui which i don't think will be a case ...

**Comment by amitiwary999** [comment]
If you know  human being then you know that they can ask anything.

**Comment by sagarchoudhary96** [comment]
@daminisatya can we know close this issue :)
