### ISSUE TITLE
Displaying Multiple Results in web search.

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#483]
**Actual Behaviour**

Currently, app displays only a single result in web search using DuckDuckGo API .

**Expected Behaviour**

The app should display multiple search results and user should be able to open relevant webpage by his choice. I suggest using free FAROO api for it.
http://www.faroo.com/hp/api/api.html

**Would you like to work on the issue?**

Yes.

**Comment by chiragw15** [comment]
@betterclever I have registered for api key of FAROO. Will get it in 24 hours. If the search results are fine using FAROO, we can replace DuckDuckGo with FAROO and implement multiple results something like this. What say?
![screenshot_20170508-103342](https://cloud.githubusercontent.com/assets/16978820/25790920/5ff0e014-33da-11e7-8c17-0b813adbe447.png)

**Comment by mayank408** [comment]
same as #647
