### ISSUE TITLE
Using Cardviews instead of current ChatMessageViews

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#484]
**Actual Behaviour**

Currently ChatMessageViews provided by ChatMessageView library are being used throughout the app.
This makes implementation of some other views difficult like after multiple websearch results, results displayed would look better in a scrollable view containing cards.

**Expected Behaviour**

I would highly suggest use of CardViews throughout the app since it makes it look modern, compact and helps making further views easy and uniform. 

**Screenshots of the Initial Card Implementation**

![screenshot_1482062777](https://cloud.githubusercontent.com/assets/16309034/22329021/5d3b6596-e3e5-11e6-87a0-2a1f489f548a.png)

**Would you like to work on the issue?**

Yes

**Comment by Abhi2424shek** [comment]
Looks cool, we could make a bit of tweaks

**Comment by betterclever** [comment]
@Abhi2424shek This is just a crude implementation. I done it a long time back. I will add a refined version here.

**Comment by Abhi2424shek** [comment]
Sure

**Comment by Abhi2424shek** [comment]
Updates @betterclever

**Comment by mayank408** [comment]
@Abhi2424shek don't keep on commenting updates all the time , it does not look good , everyone is working with its own pace..

**Comment by Abhi2424shek** [comment]
I just wanted to followup as it's been 6 days and know that he's still in it, no hard feeling :) @mayank408 just checking that he's still working, it happens in the community where people abandon their work after claiming it, so I was just asking whether he was in touch with it, people have priorities in life :)

**Comment by betterclever** [comment]
I'm still in it.
