### ISSUE TITLE
Allow user to send the mail from the susi app itself.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#485]
**Actual Behaviour**

As in present user cannot send the mail from susi.

**Expected Behaviour**

Like google allo , the user must be provided with the feature to send the mail.
 
**Would you like to work on the issue?**

Yes

**Comment by Abhi2424shek** [comment]
This must be implemented on the susi server first.

**Comment by mayank408** [comment]
@Abhi2424shek No need I just have to pass the intent from the app itself from the suitable query .

**Comment by Abhi2424shek** [comment]
But, setting up an email client on server would just improve the app's perfomanc3

**Comment by mayank408** [comment]
@Abhi2424shek I have discussed it with the @the-dagger , what we are trying to achieve is that to intent the gmail when the user queries "send a mail" and will ask for the email , there is no need for email client server for this.

**Comment by betterclever** [comment]
@Abhi2424shek It is not related to server at all. We just need to send intent for mailing. How is it even related to App Performance? Please elaborate. I would suggest you to always discuss in Gitter first before commenting here. Thanks.

**Comment by Abhi2424shek** [comment]
Sure then!
