### ISSUE TITLE
If user write multiple line message then edittext cover the large portion of UI

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#49]
If user line message with multiple line then edittext box will cover the large portion of UI.

**Comment by sagarchoudhary96** [comment]
yaa that's why i want to make it single line.... :)

**Comment by the-dagger** [comment]
Similar issue is already opened in #48

**Comment by sagarchoudhary96** [comment]
i have fixed this one too .. just sending the pull request
