### ISSUE TITLE
Location from GPS doesn't work 

### ISSUE THREAD

**Issue by dilpreet96** [fossasia/susi_android#491]
**Actual Behaviour**

LocationHelper.canGetLocation() returns false in case of GPS turned off and no prompt is displayed to user to turn on GPS.

**Expected Behaviour**

If GPS is turned off ,it should ask user to turn on GPS (everytime or for the first time) in order to fetch location.

**Would you like to work on the issue?**

Yes ,I would like to work on this.

**Comment by Abhi2424shek** [comment]
Sure, but there is a way you could flag it on and off, can you go for something like that, i mean, if it is turned off, give a pop-up to turn it on, then as a responsive mobile app turn it off(this would also need user's permission). @dilpreet96 :)

**Comment by dilpreet96** [comment]
<img src="http://i.makeagif.com/media/1-29-2017/KcyOu8.gif"/>

If GPS is off user is prompted to turn it on as suggested by you , Should I send a PR ? @Abhi2424shek

**Comment by Abhi2424shek** [comment]
Could we utilize location only when needed and stop wasting the user's battery.

**Comment by dilpreet96** [comment]
Yes I have already implemented this, it will stop using gps as soon as it fetches the location and hence stops wasting user's battery. Should i send a quick PR @Abhi2424shek ? :)

**Comment by Abhi2424shek** [comment]
No need to hurry up, take your time but wht happens if the user is moving? @dilpreet96

**Comment by dilpreet96** [comment]
We can implement locationManager.requestLocationUpdates which could help us retrieve user location after a certain interval of time using gps efficiently . Should I implement this also and send a PR ? @Abhi2424shek

**Comment by chiragw15** [comment]
@dilpreet96 @Abhi2424shek That was deliberately done. What I did was : I firstly found location of user using his ip address (which is not that accurate) and assigned the value to two variables, latitude and longitude. Then I found location of user through Network Provider (more accurate than previous method) and updated the variables with new values. Then I checked if the GPS of user is on , I found out location using GPS (most accurate) and updated the variables.  You can checkout this issue #372

**Comment by mayank408** [comment]
@dilpreet96 @Abhi2424shek.   @chiragw15 Is right , what we want is to obtain user location from the gps and if it is not on then we would take location from network services.

**Comment by Abhi2424shek** [comment]
So this one is no longer relevant and could be closed.
