### ISSUE TITLE
Now we can open/launch other apps from susi

### ISSUE THREAD

**Issue by shubhamvashisht** [fossasia/susi_android#495]
**Expected Behaviour**

Other apps can be launched from susi by command/message open+APP NAME
![issue](https://cloud.githubusercontent.com/assets/16692282/22477443/1b97c910-e80c-11e6-9ca5-82fbbaa177f6.gif)

**Would you like to work on the issue?**
Yes, done it.

**Comment by Abhi2424shek** [comment]
Try to add a space between launch and app name and try to make case ignorerant

**Comment by shubhamvashisht** [comment]
@Abhi2424shek  Above requirements Done.

**Comment by shubhamvashisht** [comment]
@daminisatya  Mam, Please review.

**Comment by jig08** [comment]
@shubhamvashisht Send a PR to `fossasia/susi_android` following the naming guidelines pls.

**Comment by mayank408** [comment]
Not required for now
