### ISSUE TITLE
Autocomplete email text input

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/susi_android#496]
**Actual Behaviour**

The user has to each and every time enter the whole email address to login.

**Expected Behaviour**

The user would be able to select his email from autocomplete dropdown if he has successfully logged in earlier in the app.

**Would you like to work on the issue?**

Yes, I would like to solve this issue.

**Comment by Abhi2424shek** [comment]
Go on but be sure to encrypt it.
