### ISSUE TITLE
Not giving proper Respone

### ISSUE THREAD

**Issue by vibhav16** [fossasia/susi_android#502]
**Actual Behaviour**

Susi is not showing results for many questions like - if i want to search for hollywood films ,it is not giving any response ... 

**Expected Behaviour**

should give response for most of the queries and allow the user to send sms and email from susi.

**Screenshots of the issue**

![screenshot_2017-02-05-12-29-28-517_org fossasia susi ai 1](https://cloud.githubusercontent.com/assets/14825091/22624343/5b35d102-eb9f-11e6-9423-4bd7108d3398.png)

**Would you like to work on the issue?**

Yes.

**Comment by Abhi2424shek** [comment]
@vibhav16 please modify the issue template according to the given instructions in it pls.

**Comment by Abhi2424shek** [comment]
Well this has to worked on the susi server first IMO

**Comment by mayank408** [comment]
@vibhav16 It is to be done in the susi server and not in the app.

@jig08 @the-dagger Kindly close this issue.

**Comment by rishsethia** [comment]
Isn't "No Result Found " in the web search a bug ? I think it should atleast display the result of the web search properly in the app itself even if it is unable to answer a query from server ! And I would like to solve this issue !

**Comment by rishsethia** [comment]
@jig08 @mariobehling @the-dagger What do you guys say ?

**Comment by Abhi2424shek** [comment]
Well this is to be solved in the server
