### ISSUE TITLE
Add 'Clear Chat ' option in Settings 

### ISSUE THREAD

**Issue by vibhav16** [fossasia/susi_android#506]
**Actual Behaviour**

Clear chat option is not available in settings 

**Expected Behaviour**

Add clear chat . This will help user to delete all his chats in one go , otherwise user has to select every chat one by one and then delete .

**Steps to reproduce it**

Update the settings menu!!!

**Would you like to work on the issue?**

Yes Sure..

**Comment by mayank408** [comment]
@vibhav16 Not required as of now , it was raised already and closed.

**Comment by vibhav16** [comment]
alright mayank got it
