### ISSUE TITLE
Toast displayed multiple times

### ISSUE THREAD

**Issue by Jonsnow21** [fossasia/susi_android#507]
**Actual Behaviour**

![](http://im2.ezgif.com/tmp/ezgif.com-0c63e00d31.gif)

"press again to exit" toast is displayed again after exiting the app.

**Expected Behaviour**

Toast should not be displayed the second time.

**Steps to reproduce it**

- open app
- press back 
- press back again

**Would you like to work on the issue?**

Yes

**Comment by the-dagger** [comment]
Looks good, please send a fix if you want :slightly_smiling_face:

**Comment by Abhi2424shek** [comment]
@Jonsnow21 go on :) -- as a fix add something like a counter which counts the number of times the back button has been pressed. The counter should reset after every 3secs or so.

**Comment by Abhi2424shek** [comment]
Nice I guess the counter was already there.
