### ISSUE TITLE
Picking up the next query for search

### ISSUE THREAD

**Issue by abhinay01** [fossasia/susi_android#509]
**Actual Behaviour**

current question web search result is empty and as soon as user ask the next question susi displays the result for the next question 

**Expected Behaviour**

susi should display the web search result for the question asked

**Steps to reproduce it**

open susi and ask question which let her search the web for the result.
The result textview will be empty until user ask another question.
Then the textview is filled with the web search answer of the next question.

**Screenshots of the issue**

![whatsapp image 2017-02-08 at 01 54 20](https://cloud.githubusercontent.com/assets/17912074/22709975/aefbb712-eda1-11e6-8dbc-4a964cd02a50.jpeg)
first screenshot is of samsung galaxy E5 running on android5.1.1
![whatsapp image 2017-02-08 at 01 54 26](https://cloud.githubusercontent.com/assets/17912074/22710015/cb55ab2a-eda1-11e6-8141-300297653de8.jpeg)
second screenshot is of yu yureka plus running android 7.1 and cyanogenMod 14.1

**Would you like to work on the issue?**

yes

**Comment by mayank408** [comment]
@abhinay01 We are already saving it into the database , and I am facing such an issue , pls update your fork to the latest commit.

**Comment by mayank408** [comment]
@abhinay01 Your fork is 65 commits behind :| . I Don't understand what you are trying to do.
Please update before making an issue.

**Comment by abhinay01** [comment]
I am sorry for the mistake, i'll surely take care from the next time.
