### ISSUE TITLE
reduce the build time

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_android#510]
**Actual Behaviour**

build time on my machine is 1 mins 11secs

**Expected Behaviour**

after modifying the gradle files, build time reduced to 23 secs and 458 msecs

**Steps to reproduce it**

modifying the gradle.properties reduced the build time. 

**Would you like to work on the issue?**

yes

**Comment by Abhi2424shek** [comment]
@DavidLochan sure go on give us your PR :)

**Comment by DravitLochan** [comment]
incoming...

**Comment by DravitLochan** [comment]
who gives the final approval and merge?

**Comment by jig08** [comment]
@DravitLochan All the active maintainers of the project review the PR before merging them. Follow up with comments on the corresponding PR pls.

**Comment by DravitLochan** [comment]
ok.

**Comment by DravitLochan** [comment]
is it done now?
