### ISSUE TITLE
Output of text to speech delayed (very slow)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#512]
Speech to text is fast, but text to speech is slow. Text to voice has 15-20 seconds delay of answers. The server response is quick. So this is not a server issue. Please check what is the reason for the delay and help to fix it.

**Comment by Orbiter** [comment]
This bug prevents that we can make a demo movie which we need to get a larger audience.

**Comment by rohanagarwal94** [comment]
@mariobehling just tested the application on the issue. Discovered the delay is just the first time a user resumes/opens the app. Trying to figure out why is it happening the first time. Assign me please.

**Comment by rohanagarwal94** [comment]
@mariobehling the problem is with google's text-to-speech only. see [this](http://stackoverflow.com/questions/34884961/text-to-speech-initialization-delay). Should we use some other service like pico TTS?

**Comment by Orbiter** [comment]
Google tts has the best quality, so let's try to work around the problem: can we initiate the tts in advance once at application start in the background and then never again?

**Comment by DravitLochan** [comment]
@Orbiter  +1. 
I realized that the response is delayed only for the first time after the launch of the application. In the subsequent request for tts, it was giving promptly.
