### ISSUE TITLE
Font size in settings

### ISSUE THREAD

**Issue by vibhav16** [fossasia/susi_android#516]
**Actual Behaviour**

No font size activity present.

**Expected Behaviour**

User should be able to select font size.
**Steps to reproduce it**

Add font size preference in settings.

**Would you like to work on the issue?**
Yes

**Comment by vibhav16** [comment]
Shall i put card of font size in settings?☺

**Comment by Abhi2424shek** [comment]
Yes you may please @vibhav16 do so :)

**Comment by mayank408** [comment]
@vibhav16 I don't understand what's the need of selecting font size in the setting from an app, when the setting in the phone provides the same functionality. Please find the relevant issues only.

**Comment by mayank408** [comment]
@the-dagger @jig08 Kindly close this issue.
