### ISSUE TITLE
Add option to choose Susi AI server URL to settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#520]
Currently a lot of development is going on. The outcome of the server changes cannot be easily tested and developers need to set up the complete stack to do this. Also, user possibly want to change their server in the future.

Therefore please implement an option in the setting to choose the Susi AI server. Offer the option to choose a) Susi AI standard server and b) Enter URL for other Server.

Please ensure, the calls of the API are abstracted and use the URL specified in the settings.

**Comment by chiragw15** [comment]
@mariobehling What if the URL mentioned by the user provides response in different way as expected? The format of the response may not be same as the susi standard server.

**Comment by mayank408** [comment]
@mariobehling As susi server does not supports images and emojis , so we have to make the app compatible to support them , so that if the user enters some different URL we can handle all its cases.

**Comment by Abhi2424shek** [comment]
@chiragw15 simple we check for the essential things needed in a reply and if they are not present  the output will be something like unknown response from the server or undefined response etc.

**Comment by chiragw15** [comment]
@Abhi2424shek Also, we can write something in settings (where user enters URL of other server) like "Please follow the similar structure http://api.asksusi.com/susi/chat.json?timezoneOffset=-330&q=hello ).

**Comment by Abhi2424shek** [comment]
Sure

**Comment by chiragw15** [comment]
@Abhi2424shek I would like to work on this one.

**Comment by Abhi2424shek** [comment]
Well go on. Give it a try, and also give suggestions for valid fields

**Comment by chiragw15** [comment]
@Abhi2424shek Also, Are all the rules of susi api calls and response defined somewhere. If yes, Can you provide me with the link?

**Comment by Orbiter** [comment]
Don't bother with the response format, it will be the same. This is I.e. to test a intranet susi_server, not a completely different chat service.

**Comment by betterclever** [comment]
I would like to work on this.

**Comment by chiragw15** [comment]
@mariobehling @Orbiter Will the user be using his own server for login and sign up also? If yes, then shouldn't we also ask for the his server url just after the app is installed apart from asking in the settings?

**Comment by betterclever** [comment]
@chiragw15 Are you still working on this? I wish to work on this.

**Comment by chiragw15** [comment]
@betterclever I have implemented this. But I don't know if this is the intended solution. I asked this in the above comment but didn't get any response. @the-dagger @mariobehling @Orbiter Can anyone please confirm if it.

![screenshot_20170303-224607](https://cloud.githubusercontent.com/assets/16978820/23561273/93023296-0063-11e7-97bd-6ec5efe0a715.png)

**Comment by betterclever** [comment]
@chiragw15 I guess this is required solution, additionally we can put an option in settings to change server in which in turn, you may ask user to sign out first to change server and take him to this screen. 
@mariobehling Can you confirm this approach?

**Comment by chiragw15** [comment]
@betterclever Done exactly the same :D
