### ISSUE TITLE
Changing the chat ui

### ISSUE THREAD

**Issue by arp95** [fossasia/susi_android#521]
I suggest a change in the chat ui as follows:

![16763684_10210476235816652_428135706_o](https://cloud.githubusercontent.com/assets/8268392/22884264/0c81fbe0-f21a-11e6-8ca0-dfddfe494718.png)

Here the edit text for writing a message and the audio button are separated instead of the audio button coming under the edit text field.

@the-dagger @jig08 please review this.

**Comment by jig08** [comment]
@arp95 Sure, it looks similar to Whatsapp's UI now. Send a PR ....
