### ISSUE TITLE
mark messages as important

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_android#522]
**Actual Behaviour**
As of now, a message can not be marked as important. Quite simple and straight. I had asked susi a question some time back. Now if I want to read the reply, either I ask susi again or scroll through the whole list of questions and answers to find it. 

**Expected Behaviour**
If we provide a feature to mark messages important, it will allow user to simply open the important one's and read through them.  This will allow the user to read the message even if there is no internet (solution to re-ask the question). In the absence of internet, this feature will be a bliss. 

**Steps to reproduce it**
Store the messages marked as important in the in-app database. 

**Would you like to work on the issue?**
Yes

**Comment by DravitLochan** [comment]
1. show an option to mark as important onLongClick of a message.
2. when selected, give a toast message marked as important.
   in the background, store the message and its response in database.
3. add an option in overflow menu to open important messages.
4. list the messages from database.

is this workflow ok?

**Comment by jig08** [comment]
@DravitLochan Sounds good.

**Comment by DravitLochan** [comment]
I am using SQLite

**Comment by mayank408** [comment]
@DravitLochan Use Realm instead as we are already using it and it is more secure and reliable than SQLite.

**Comment by DravitLochan** [comment]
copy that!

**Comment by betterclever** [comment]
@DravitLochan @mayank408 A better approach would be to add a starred field just like whatsapp in current model. When user clicks on important messages, filter can be applied.

**Comment by DravitLochan** [comment]
Progress so far: on selecting one or more messages, * button comes along with delete, copy and share. On hitting *, selected messages are marked important (another attribute of isImportant has been added). Now I was thinking for  opening an activity which contains all the messages marked important. if some one has better solution, please tell.

**Comment by DravitLochan** [comment]
may I close it?

**Comment by Abhi2424shek** [comment]
Next time reference the issue solved in the commit message @DravitLochan. Close this one pls.
