### ISSUE TITLE
Problem with EditText field in chat Activity

### ISSUE THREAD

**Issue by arp95** [fossasia/susi_android#527]
When we enter text beyond one line in the edit text field it continues in the same line. Its better to enter the text beyond a single line to another line as seen in Whatsapp. 
@jig08 please review this.

**Comment by jig08** [comment]
@arp95 Could you add relevant screenshots as well ?

**Comment by arp95** [comment]
@jig08 
![16763640_10210484047251933_286412836_o](https://cloud.githubusercontent.com/assets/8268392/22931231/e6e2b7c8-f2e9-11e6-8af9-5655d5dd2c8a.png)

As you can see the text i keep on entering is going on a single line. What i want is the text to move to the next line automatically after reaching the end as seen in Whatsapp UI.
Working on this right now.

**Comment by arp95** [comment]
@jig08 please see the pr for changes.

**Comment by betterclever** [comment]
Solved in #503
