### ISSUE TITLE
Adding the option to customize theme of the application from overflow menu

### ISSUE THREAD

**Issue by nikhilbalyan** [fossasia/susi_android#530]
**Actual Behaviour**

Only one of the theme is available.

**Expected Behaviour**

Option should be available to change the theme of the layout.

**Steps to reproduce it**

we can deploy it in the  overflow menu as select theme like in many applications.

**LogCat for the issue**

Provide logs for the crash here.

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

I would love to work on the issue by changing the themes of the toolbar as the user want.

**Comment by betterclever** [comment]
@nikhilbalyan Edit the template according to issue and mention required points. It is a good practice.

**Comment by nikhilbalyan** [comment]
@betterclever i would love to work on this issue :smile:

**Comment by mayank408** [comment]
Not required for now.
