### ISSUE TITLE
Small issue in Chat Activity

### ISSUE THREAD

**Issue by arp95** [fossasia/susi_android#533]
When we enter text in multiple lines in the edit text field in the chat activity we get the message as one liner in our messages like this:

![16777110_10210493290283003_48589909_o](https://cloud.githubusercontent.com/assets/8268392/22985060/49404280-f3cd-11e6-9a38-4db3f785cda8.png)

I want something like this:

![16763838_10210493320043747_1005002941_o](https://cloud.githubusercontent.com/assets/8268392/22985195/bfe90818-f3cd-11e6-82ac-f33fc40c2ba8.png)

The response of susi is not getting affected as i am using the trimmed message for that but storing the actual string in the database as entered by the user.

@jig08 should i send a pr regarding the same?

**Comment by Abhi2424shek** [comment]
@arp95 your apps seems outdated pls update it then reference.

**Comment by arp95** [comment]
@Abhi2424shek sorry for that.

Here are the updated screenshots.

Without change:

![16804740_10210501826656407_1522058241_o](https://cloud.githubusercontent.com/assets/8268392/23014897/d89b08f0-f456-11e6-9698-a93a966360ca.png)

With change:

![16776328_10210501826536404_1415249538_o](https://cloud.githubusercontent.com/assets/8268392/23014909/e2446a4a-f456-11e6-85eb-80c541727443.png)

@the-dagger @jig08 please review this.

**Comment by Abhi2424shek** [comment]
Well I can't really figure out exactly what you mean it would be better if you could be more precisive.

**Comment by arp95** [comment]
@Abhi2424shek what i am referring to is that when user enters the text in multiple lines it get displayed in the same line itself in the message which should not be the case as you can see in the second screenshot.
Hope you get what im referring to.

**Comment by Abhi2424shek** [comment]
Pr please :)
