### ISSUE TITLE
Unable to place calls with both firstname and sirname

### ISSUE THREAD

**Issue by rishsethia** [fossasia/susi_android#538]
**Actual Behaviour**

When we try to place the call of a contact name which contains a space , susi is not able to recoginize what to do 
![img-20170217-wa0000](https://cloud.githubusercontent.com/assets/11053890/23068769/f538315a-f54a-11e6-9084-9f9d73596a0c.jpg)

Yes I would like to solve this issue ! Should I go ahead? Please review @the-dagger @jig08 !

**Comment by mayank408** [comment]
@rishsethia Don't open two different issues for the same bug.

**Comment by rishsethia** [comment]
@mayank408  Hi, It's not the same bug ! This one is related to query parsing and other one is related to the response of the app to any call query, in general . I opened 2 different issues to keep things modular!

**Comment by mayank408** [comment]
Not required for now.
