### ISSUE TITLE
Calling Functionality Needs to be Improved

### ISSUE THREAD

**Issue by rishsethia** [fossasia/susi_android#539]
**Actual Behaviour**
When triggering calling functionality from susi , it just opens up the dialer app.
**Expected Behaviour**
It should go to the particular contact searched for/directly try to place the call
**Would you like to work on the issue?**
Yes.

Waiting for approval to start working on this !
@jig08 @the-dagger

**Comment by jig08** [comment]
@rishsethia yes pls.

**Comment by the-dagger** [comment]
@rishsethia <https://github.com/rishsethia> wouldn't that require adding
calling permission to susi, which I don't think is a good idea.
Thougn we can handle this in API 22+ with dynamic permissions but for API
below that would still be a problem.
Let's keep the calling functionality as it is for now.

**Comment by rishsethia** [comment]
@the-dagger ,

Yeah I also thought that . So , instead of calling directly , it will open the specified contact directly , instead of just launching the dialer app . So user is just one touch away from calling , instead of completely searching contacts again calling.

**Comment by the-dagger** [comment]
Ok, that makes sense. :+1:

**Comment by mayank408** [comment]
Not required for now.
