### ISSUE TITLE
Adding an option to clear chat window from overflow menu.

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/susi_android#543]
**Actual Behaviour**

Currently, there is no option to delete chat history. If user wants to delete all them then either he has to delete them one by one or on logout the chat history gets deleted.

**Expected Behaviour**

Instead of clearing out chat history on logout we can add an option Clear Chat in the menu which can provide ease to the user for deleting the chat and we can preserve the chat history even after the logout.

![videotogif_2017 02 18_15 59 33](https://cloud.githubusercontent.com/assets/12701036/23092632/54c9be2c-f5f5-11e6-9529-e0990fe0885f.gif)

**Steps to reproduce it**

After logging out and again logging in the chat history is deleted.
 
**Would you like to work on the issue?**

Yes!

@jig08 @the-dagger Can I send the PR for the same?

**Comment by anantprsd5** [comment]
@harshitagupta30 I think this is not required as of now because the issue was raised twice and was closed. Refer #506

**Comment by harshitagupta30** [comment]
@anantprsd5 Thanks for letting know!

**Comment by harshitagupta30** [comment]
@Abhi2424shek @jig08 Just wanted to know why we are deleting the chat history on logout?
