### ISSUE TITLE
Adding scroll view in the message text box for multi line messages.  

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/susi_android#544]
**Actual Behaviour**

Currently, if a message contains multiple lines then there is no way a user can predict how long is the message.

**Expected Behaviour**

Just like other chat applications, we can add scroll view in the message box which can help the user to view how long the typed message is.

**Screenshots of the issue**

**Actual Behaviour**
![screenshot_20170218-163431](https://cloud.githubusercontent.com/assets/12701036/23092805/f1671704-f5f8-11e6-8fe1-27043d989903.jpg)

**Expected Behaviour**
![videotogif_2017 02 18_16 37 17](https://cloud.githubusercontent.com/assets/12701036/23092806/f6b33fda-f5f8-11e6-8f0e-cac7fe770093.gif)

**Would you like to work on the issue?**
Yes.

@jig08 @the-dagger @Abhi2424shek Can I send the PR for the issue?

**Comment by Abhi2424shek** [comment]
Yes sure seems valid :)
