### ISSUE TITLE
Everything in the app is hardcoded

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#546]
**Actual Behaviour**

@mariobehling @Orbiter @jig08 @the-dagger @daminisatya Everything in the app is hardcoded. Every feature that susi has, is hardcoded and works on the app level only. No query is sent to server for the response. I know susi ai is not that advanced to handle difficult queries but writing code like
this is not the solution. This is not how an AI bot works.
```
if( query.contains("call") ){
    //call
} else if (query.contains("play") {
   //play video
} else if (query.contains("send message") {
   //open message app 
}
```
**Examples of the above**

1.) **Playing a video** : Anything you write after play is searched on youtube and the top video is displayed. It doesn't matter what you write. Write "play with me" , it will search "with me" on youtube and play the top video.

![screenshot_20170219-000006](https://cloud.githubusercontent.com/assets/16978820/23097105/6efe076a-f651-11e6-8db1-0870f9f31672.png)
 
2.) **Sending a message** : Just write "send message to -----" the "----" will be replaced with recipient's name. Example write "message mom asking for money". 

![screenshot_20170219-022226](https://cloud.githubusercontent.com/assets/16978820/23097129/65b58d76-f652-11e6-9aaa-a023fc613411.png)

This is what susi does. It makes "mom asking for money" as recipient and an empty message.

![screenshot_20170219-022246](https://cloud.githubusercontent.com/assets/16978820/23097139/bcb1e49e-f652-11e6-89dc-d715b95787b3.png)

What google assistant does:

![screenshot_20170219-023734](https://cloud.githubusercontent.com/assets/16978820/23097172/7cdd9088-f653-11e6-8a6e-1f45fc0ccb58.png)

3.) **Setting an alarm** : query "set alarm" works and "set a alarm", "set a alarm for 6 am" or "wake me up at 6 am" doesn't work. 

![screenshot_20170218-235731](https://cloud.githubusercontent.com/assets/16978820/23097077/c3ebc042-f650-11e6-84fe-90fe903142ee.png)

Similar issues arises for setting reminder, making call and sending emails.
I am not saying that these things don't work but this is not the solution to the problem. This is just a way around and fine for temporary use but if we see the future of susi, work like these may not be intended. 

**Expected Behaviour**

**Rules about these should be written in the susi server and after that these should be implemented according to the response of the server.**

**Comment by mayank408** [comment]
@chiragw15 I agree with you but we know that the susi server is still incapable of handling complex queries so this is the best we can do till the server site gets updated. All these features are working fine and responsive as well, if they are queried within the prescribed way. We will update this as the server gets updated.

**Comment by Abhi2424shek** [comment]
Well I raised this earlier, we could have basic rules for the above, there are lots more than those mentioned in the issue that are hardcoded, I should gradually do this one by one, we would need the server to handle them first, removing them without the server support wont be good, so let's first add support in the server.

**Comment by chiragw15** [comment]
@mayank408 I don't see a point in writing thousands of lines of code if we know we have to remove it in the future. As you said. 
>if they are queried within the prescribed way.

The problem is that there is no prescribed way to query to a bot. That's why it is a bot. How will the user know what's the prescribed way? The better way was to create issues in susi server repo and adding rules there instead of adding them directly to android app. Adding 1 feature directly to the server would have been much better rather than hardcoding say 10 feature in the app. 

Now the point is, since these features already added are not working correctly, should we create issues to fix them or should we leave them as it is?

**Comment by the-dagger** [comment]
@chiragw15 My suggestion would be to create a new issue on susi server
regarding this and halt adding new features to the Android Client as of
now.​
Since it doesn't make any sense to have new features if we need to remove
later anyways.

I hope that clears up the confusion.
