### ISSUE TITLE
Option to resend messages should be there

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/susi_android#547]
**Actual Behaviour**
There is no option to resend the messages as of now.

**Expected Behaviour**
When the user long presses any message there should be an option to resend the messages as there are many questions like "What's the temperature today" and so on which the user wants to know on a daily basis so having a resend button will make things easier. 

**Would you like to work on this issue**
Yes

**Comment by anantprsd5** [comment]
@the-dagger @jig08 @daminisatya Please approve the issue so that I can proceed.

**Comment by betterclever** [comment]
@anantprsd5 I don't think it is required, We can rather have suggestions based on his interests in a lower pane. This approach to long press and resend doesn't make sense.

**Comment by anantprsd5** [comment]
@betterclever I feel that the resend button is useful in a chat application as we don't have to type the whole set of common messages again and again and this thing can be accomplished easily and to make suggestions based on interests is more complex and will take time. I need more opinions on it. @Abhi2424shek @mayank408 What do you think about this?

**Comment by betterclever** [comment]
@anantprsd5 As we came to conclusions in a discussion about features in app earlier too, we should implement features based on utility and not complexity.  Adding not/less useful features is not what should be practiced as a long term goal.
 @the-dagger Opinions on this?

**Comment by Abhi2424shek** [comment]
@anantprsd5 we should not waste resources for easy things which would be replaced in the future.
