### ISSUE TITLE
App invite via Facebook

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/susi_android#550]
**Actual Behaviour**

Only sharing of app is being implemented.

**Expected Behaviour**

App invite through facebook notification feature.

**Screenshots of the issue**

![appinvite](https://cloud.githubusercontent.com/assets/13241256/23142200/b436bdc8-f7e0-11e6-9075-e8146a1b226c.png)

**Would you like to work on the issue?**

Yes, in fact I already implemented this in the open-event-android.

**Comment by Abhi2424shek** [comment]
Sure that would be cool

**Comment by chiragw15** [comment]
Currently this is out of scope. (mentioned by Mario in PR too). Thus closing.
