### ISSUE TITLE
Shall we have espresso as testing framework

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/susi_android#551]
The Espresso testing framework is an instrumentation-based API and works with the AndroidJUnitRunner test runner.

**Actual Behaviour**
The tests aren't based on espresso

**Expected Behaviour**
The tests should be based on espresso.

**Would you like to work on the issue?**
No, I can't code on my PC this month.

**More information about espresso and settings g it up**
https://developer.android.com/training/testing/ui-testing/espresso-testing.html#setup
https://google.github.io/android-testing-support-library/docs/espresso/

**Should we have a discussion**
Yes pls, this is a big project and I would love opinions.

**My Opinion**
We should have espresso it will accelerate the tests a lot and provide for better test cases.

**Comment by Abhi2424shek** [comment]
@the-dagger whts your opinion?

**Comment by chiragw15** [comment]
@Abhi2424shek Don't we already use espresso?

**Comment by chiragw15** [comment]
We already have espresso for testing. Closing it. Re open if I am wrong.
