### ISSUE TITLE
Predefined question formater for asking question susi  

### ISSUE THREAD

**Issue by rahulworld** [fossasia/susi_android#554]
**Actual Behaviour**
there is no question format for asking.
Please state here what is currently happening.
![16910624_813375112134104_1906750939_o](https://cloud.githubusercontent.com/assets/15066782/23269101/77fc1416-fa15-11e6-8063-b2ddb02263b5.png)

**Expected Behaviour**
so for good result we add some predefined question format.

**Steps to reproduce it**
adding a question format template.

**Would you like to work on the issue?**
yes, i would like.
Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by Abhi2424shek** [comment]
Susi server is the place you should go for this. Further susi server interprets the questions in two senses.

**Comment by rahulworld** [comment]
@Abhi2424shek  I want add template in gui in which the question template having some question formate so input take from question template. should i go for susi server according to you.

**Comment by Abhi2424shek** [comment]
Well we don't want to make the app hardcoded it should just be a beautiful interface for the susi server.

**Comment by mayank408** [comment]
Server issue.
