### ISSUE TITLE
Providing start/end attributes for each left/right ones

### ISSUE THREAD

**Issue by arp95** [fossasia/susi_android#558]
**Actual Behaviour**

Currently in some layout files only left/right attributes for each views are present.

**Expected Behaviour**

To support right to left languages each left/right attribute should have its start/end counterpart.

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Comment by betterclever** [comment]
@arp95 Is it needed? Susi currently supports only English so enabling that won't help much.

**Comment by mayank408** [comment]
Not needed for now.
