### ISSUE TITLE
Removing Lint issues in project 

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/susi_android#559]
**Actual Behaviour**

Currently, on running lint in the project it raises multiple potential issues which need to be solved.

**Expected Behaviour**

They must be resolved.

**Would you like to work on the issue?**
Yes

@jig08 @the-dagger @Abhi2424shek  Can I resolve them? :)

**Comment by Abhi2424shek** [comment]
Yep @harshitagupta can we have a linting test also?

**Comment by mayank408** [comment]
Already done
