### ISSUE TITLE
New Application Icon

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#560]
Please exchange the application Icon, image is attached

![susi_icon_2017](https://cloud.githubusercontent.com/assets/238730/23824832/617c9010-067e-11e7-8caf-88dc81000008.png)

**Comment by mayank408** [comment]
@Orbiter I want to work on this

**Comment by Orbiter** [comment]
Great! Please!

**Comment by Orbiter** [comment]
https://github.com/fossasia/susi_android/commit/7559b427b3105f17afe5fcdc092dad74f88bee91
