### ISSUE TITLE
Sort Sponsors according to sponsorship level.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#561]
Sponsors are currently not sorted to their level. Please ensure the sponsors are listed according to the order. In the server app it is sorted according to numbers, e.g. 5 is higher than -2. So the sponsor is on top. If two sponsors have the number 5 there are both in the same category.

**Comment by Jonsnow21** [comment]
I would like to work on this

**Comment by mariobehling** [comment]
Yes, posted it too late at night, when I was sleepy already. Please follow up here: https://github.com/fossasia/open-event-android/issues/1280
