### ISSUE TITLE
Create a screencast in high resolution with questions/text listed in issue

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#564]
We would like to have a screencast with the questions/text listed below to showcase Susi. Please make the screencast in high resolution.

- who are you
- are you alive
- what is summer
- what is love
- ask urbandictionary for love
- where is singapore
- set home to singapore
- get home
- ask me anything
- Michael
- what is my name
- do you like me
- forget my name
- what did I say lately
- compute 50 * 7
- what is 99 divided by 9
- what time is it
- How many mentions are on reddit about fossasia
- What are the reddit articles about fossasia
- who tweeted recently about fossasia
- do you have access to a previous configuration?
- erase latest interaction
- Analysis
- cognition only please
- carry on
- Oh freddled gruntbuggly
- Where do you see yourself in five years?
- Are you planning on having children?
- where are you
- Do you have a mind?
- what is the meaning of life and everything
- how big is the universe
- how many people live on earth
- Explain pi
- how cold is it on mars

**Comment by chiragw15** [comment]
@mariobehling is this resolution fine? https://youtu.be/Oppy6X2iTXc . It's a demo. If this quality seems fine, I'll make a complete one.

**Comment by daminisatya** [comment]
@chiragw15 looks good!

**Comment by chiragw15** [comment]
https://drive.google.com/file/d/0B6IO4qTKhVUCVmtvdUZpMzg2b00/view?usp=drivesdk

**Comment by jig08** [comment]
@chiragw15 Nice work !

**Comment by Abhi2424shek** [comment]
Since @chiragw15 made it, can we close this?
