### ISSUE TITLE
Respond to a query as soon as connected to internet

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_android#565]
**Actual Behaviour**

If a user fires a query but is not connected to internet, They get the answer only when they open the app and the query gets fired on the server from the undeliveredMessage list. 

**Expected Behaviour**

Similar to other apps, Susi should be able to generate a notification with a response to the questions in the undeliveredMessage list.

**Steps to reproduce it**
Start a service which generates the notification as soon as it gets connected to the internet and answer the queries. 

**Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.**
yes!

**Comment by DravitLochan** [comment]
@jig08 if you could review and merge my early pr #522

**Comment by Abhi2424shek** [comment]
Sure pls make a PR

**Comment by Abhi2424shek** [comment]
Hi @DravitLochan any updates?

**Comment by DravitLochan** [comment]
Just need some time. I had some branch issues earlier. right now looking at the services. Will update soon :)

**Comment by DravitLochan** [comment]
On getting connected to internet, BroadcastReceiver is not fired. Otherwise, everything is set to roll. Someone else has the same scenario? @Abhi2424shek

**Comment by srv-twry** [comment]
@chiragw15 @DravitLochan  Can i take it ?

**Comment by batbrain7** [comment]
this works
