### ISSUE TITLE
Compare Mycroft with SUSI AI and evaluate skills import options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#566]
Mycroft (https://mycroft.ai) is doing a great job to tell people about the project. Lots of people know it. Please compare it with SUSI AI and Mycroft. There are a number of skills (https://github.com/MycroftAI/mycroft-skills). Can we import them to SUSI? This issue is related to both the Android client and the SUSI server.

**Comment by Abhi2424shek** [comment]
We would need to port them one by one. I like their readme file which specifies the things which are needed to be done.
