### ISSUE TITLE
Send ISO 639-1 of configured language to the server for queries

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#575]
**Actual Behaviour**

When calling the `/susi/chat.json` api of susi_server, no language information is transmitted

**Expected Behaviour**

The configured language (not the country code) shall be send to the server.

Please add a query attribute `language` and fill it with the currently configured language using the ISO 639-1 standard (a lowercase two-letter code), see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by mayank408** [comment]
I would like to work on this.
