### ISSUE TITLE
Login buggy and does not work - invalid password

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi_android#578]
I tried to sign up for the Android app. Lots of issues:
1. Signup link brings me to a JSON file.
2. Does not fetch email from the phone.
3. I get an email that I signed up for loklak. I signed up for SUSI AI!
4. Password does not work - cannot login.
5. Reset password still not working.

Result -> I cannot login.

Such a pity. I am sad.

**Comment by mayank408** [comment]
Server Issue , Hence closing.
