### ISSUE TITLE
Removing Change Password Activity

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#580]
**Actual Behaviour**

Currently there is an activity called change password activity which asks users for token id and new password if user forgets the password. 

![screenshot_20170416-145441](https://cloud.githubusercontent.com/assets/16978820/25070179/061cb90e-22b5-11e7-9a80-5f814b1b62cf.png)

**Expected Behaviour**

In reference to this https://github.com/fossasia/susi_server/issues/108 . Since we are sending an email with link to change password, there is no need of the change password activity anymore. We can replace it with a dialog box displaying something like "Link to change password has been sent to your email id. Follow the link to change password and login again". 
**Would you like to work on the issue?**
yes

**Comment by mayank408** [comment]
@chiragw15 I would like to work on this if you are working on other issues.

**Comment by chiragw15** [comment]
@mayank408 yeah sure, go ahead :+1:

**Comment by mayank408** [comment]
@chiragw15 👍
