### ISSUE TITLE
Use api.susi.ai instead of asksusi.com domain and provide UI to change server manually

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#583]
The current version of the app uses asksusi.com. Please use api.susi.ai instead. Asksusi.com will be faded out.

In the login screen add an option to manually change the susi server.

**Comment by Abhi2424shek** [comment]
The login screen has been provided the functionality in #572

**Comment by mayank408** [comment]
@mariobehling We can select the server the server from the app itself after merging #572.
I will change the url to updated one 👍
