### ISSUE TITLE
Web search not working

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#590]
**Actual Behaviour**

Curently web search is not working. Though the server is giving correct response, it is not displayed correctly in app.

**Expected Behaviour**

It should work as both susi server and duckduckgo api is giving correct response.

**Steps to reproduce it**

enter query "search for dog"
http://api.asksusi.com/susi/chat.json?timezoneOffset=-330&q=search+for+dog
^correct response.

http://api.duckduckgo.com/?format=json&pretty=1&q=dog
^duckduckgo api correct response

![screenshot_20170508-082955](https://cloud.githubusercontent.com/assets/16978820/25788741/0626177c-33c9-11e7-9b17-f2436cef66c5.png)
^still no response

**Would you like to work on the issue?**
yes

**Comment by betterclever** [comment]
I guess while improving this, we can have a look at FAROO, it is a free api
for Search. It provides multiple results, as opposed to single result by
DuckDuckGo.

@chiragw15 what do you think?

**Comment by chiragw15** [comment]
@betterclever I haven't really tried FAROO. As far as DuckDuckGo is concerned, it do provide related topics in json response. But they all are weird and doesn't make sense. I'll register for API key of FAROO and will try and let know. If the results are fine, we can surely shift to faroo.

**Comment by mayank408** [comment]
@chiragw15 It will be again hardcoded and will work only when the search object is preceded by "search for" . I don't think it will work if the user queries "I want to know about something".

**Comment by betterclever** [comment]
@mayank408, it is not like that. Web search is triggered in the case when
action returned from server asks to perform websearch. The query is being
sent to server and response is being evaluated on client, this is exactly
how Orbiter asked it should be. Follow up #100 on susi_server repo for more
info.

**Comment by chiragw15** [comment]
@mayank408 You are misinterpreting the issue. I am not implementing anything here. http://api.asksusi.com/susi/chat.json?timezoneOffset=-330&q=search+for+dog This is a response of a query from server.

**Comment by mayank408** [comment]
@betterclever Yes you got me wrong, I am saying that when I query "I want to know about something". The server is not returning a websearch for only the object but instead it search for the whole phrase.Due to which the DuckDuckGo Api shows no result found.


![whatsapp image 2017-05-08 at 10 02 03 am](https://cloud.githubusercontent.com/assets/22056321/25790345/799e2738-33d5-11e7-8f0c-27f12452a02b.jpeg)

**Comment by mayank408** [comment]
See above Singapore can be easily found , whereas when we write "i want to know about Singapore" , It doesn't search for singapore instead the whole phrase which is ofcourse not found .

**Comment by chiragw15** [comment]
@mayank408 Yup because this is not implemented on the server. You need to understand the meaning of hardcoding here. If are replying to a query in the app itself without sending the query to server or without using the response of server. It is hardcoding. In this case, we are sending query to server and displaying what the result is coming in. Since it is not implemented on server, it is not working. At later point of point it will be implemented on server and it will work fine.

**Comment by mayank408** [comment]
@chiragw15 yes right and I know what hardcoded is, and there are many features in the app that can need to replaced, once they get added to the server.

**Comment by chiragw15** [comment]
Yes, that's what I am saying for a long time. All the hardcoded features of the app will be replaced by the server ones. The app should not process user query **at all**. It should directly send it to server. What it should do is to act according to the response of server and display the result.

**Comment by amitiwary999** [comment]
@chiragw15 You are right we need to replace all the hardcoded features.

**Comment by mayank408** [comment]
@amitiwary999 We cant do it know and the server still lacks them.

**Comment by chiragw15** [comment]
Yes, slowly and steadily. Implementing each feature on server. :+1:
