### ISSUE TITLE
Incorrect response to 'Hii'

### ISSUE THREAD

**Issue by jyoth1raditya** [fossasia/susi_android#593]
**Actual Behaviour**

Its web searching on Duck Go GO

**Expected Behaviour**

Just reply back with Hello

![screenshot_20170508-151213](https://cloud.githubusercontent.com/assets/24853337/25800411/e0866cc2-3406-11e7-9779-13bcbbdc0188.png)

**Comment by chiragw15** [comment]
@jyoth1raditya please open this issue in susi_server repo and close this one. It needs to be corrected there. Thanks.

**Comment by mayank408** [comment]
It is a server issue. Hence closing
