### ISSUE TITLE
Addressing of Fact based queries 

### ISSUE THREAD

**Issue by jyoth1raditya** [fossasia/susi_android#594]
@mariobehling @Orbiter , Please help us how to address this issue. 

![screenshot_20170508-160426 1](https://cloud.githubusercontent.com/assets/24853337/25801511/87ee5958-340b-11e7-8839-882c69cb78b9.png)
![screenshot_20170508-160223 1](https://cloud.githubusercontent.com/assets/24853337/25801510/87ed716e-340b-11e7-8c15-9a43e810e2f8.png)

**Comment by chiragw15** [comment]
As mentioned in #593 , This too.

**Comment by chiragw15** [comment]
You can use wolfram alpha api to create a skill for fact based queries. eg. https://api.wolframalpha.com/v1/result?i=distance+between+earth+and+sun&appid=XL374T-P3L4UJ53R6 . But since it is not an open source project and query limit is 2000 per month, I don't know if @mariobehling will allow it?
