### ISSUE TITLE
Updating docs

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#600]
Following changes in readme file:

1. Adding preview at Appetize.io and adding its badge.
2. Changing Mailing List to https://groups.google.com/forum/#!forum/susiai  here https://github.com/fossasia/susi_android#communication .
3. Removing note from branch policy since we have a development branch now.
4. Changing badge link of circle ci from https://circleci.com/gh/fossasia/susi_android.svg?style=svg  to   https://circleci.com/gh/fossasia/susi_android.svg?style=svg&branch=development .
5. Adding Screenshots of app.
6. Adding libraries and apis used.
7. Adding apk branch in branch policy.

@mayank408 @DravitLochan @amitiwary999 What else?

**Comment by DravitLochan** [comment]
I'll advice not to add the APIs as in the end they are going to be implemented on the server. Rest looks good
