### ISSUE TITLE
Features/Skills in android app as of now

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#601]
**Features/Skills present in android app :**

1. Reply user with text message. (response type : answer)
2. Displaying a map in message. (response type : map)
3. Displaying a websearch result in message. (response type : websearch)
4. Displaying a Pie chart (Though this has never been tested) 
5. Displaying mutiple search results. (response type : rss)  

**Features/Skills/action type present in server but not in android app :** 

1. Display table of result (response type : table)

**Features/Skills/action type not present in server but can be useful in android app : (Should be implemented in server first and then in app)**

1. Calling a person.
2. Setting Alarm
3. Setting a reminder.
4. Playing a youtube video.
5. Send Message to someone.
6. Send Email to someone.
7. Google searching a query.

@mayank408 @amitiwary999 Please comment if I missed something.

**Comment by amitiwary999** [comment]
@chiragw15 multible websearch result is also included in displaying a websearch result in text message?

**Comment by chiragw15** [comment]
@mariobehling @amitiwary999 @mayank408 How about we make separate a branch of app which will contain only skills that use server response?

**Comment by mayank408** [comment]
So now all the hardcoded features are removed. closing this

**Comment by chiragw15** [comment]
@mayank408 @amitiwary999 please see the updated issue. Thanks.

**Comment by mariobehling** [comment]
@chiragw15 Please open an issue for each skill in the skill data repository. So these skills can be implemented and thought-through.

**Comment by amitiwary999** [comment]
@mariobehling for websearch and play video we can use the same api in susi skill which we used in android app but in case of set alarm, send email type query we send plain text response? @chiragw15 what you think? I will open corresponding issues in susi skill.

**Comment by chiragw15** [comment]
Opened corresponding issues in skill_data_repo where they belong. Need to implement those skills and after implementation of each skill, create new issue in this repo and work.
