### ISSUE TITLE
Improving layout of websearch holder

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#609]
**Actual Behaviour**

![screenshot_20170512-064900](https://cloud.githubusercontent.com/assets/16978820/25980713/25739442-36ee-11e7-939f-47dee5e5960a.png)

1. text alignment is wrong.
2. White space if image url is empty in json.

**Expected Behaviour**

1. Aligning text to left.
2. If image url from json response is null, remove the extra white space at the left.

**Would you like to work on the issue?**
yes

**Comment by mayank408** [comment]
Done
