### ISSUE TITLE
Increase speed of app wherever possible

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#613]
**Actual Behaviour**

The response of app is slower even if the response from server is fast? I don't know the reason yet. Maybe poor implementation or a need of better algorithm. Need to figure it out. 

**Expected Behaviour**

If the response from server is fast, the response from app should be fast too.

**Mini-Project**
Increase the speed of app wherever possible.

@amitiwary999 If you find any poor implementation in app which can be improved, comment on this issue.

**Comment by amitiwary999** [comment]
@mariobehling  We can use google cloud speech api. It return text result in real time just like google assistant. @chiragw15 I am trying to implement it in a sample app by following there docs it will be better if you also look into it.

**Comment by mariobehling** [comment]
@amitiwary999 Please open a dedicated issue.

**Comment by amitiwary999** [comment]
@chiragw15 your implementation looks good . I am opening a issue for it you can make a pull request. I too trying to find some other way to make susi faster.

**Comment by amitiwary999** [comment]
@chiragw15 currently some function like calling someone,sending email, setting alarm etc. which not depend on susi response are kept under susi response in mainactivity.  If we are planing to keep these functions hardcode then we should keep these functions outside of it.If you agree then I will open a issue. @mariobehling @Orbiter needed your suggestion.

**Comment by chiragw15** [comment]
@mariobehling I have removed all harcoded features. They were interfering with actual susi response. Also, it makes the app a little faster, efficient and reduces app size. The code is in my fork https://github.com/chiragw15/susi_android/tree/removehard . To test it here is an [apk](https://drive.google.com/file/d/0B6IO4qTKhVUCRHJDYzEydElSamc/view?usp=sharing). If you feel it has increased the speed of the app, I'll create a PR.

**Comment by mayank408** [comment]
Merged

**Comment by chiragw15** [comment]
@mayank408 This issue is a parent issue. We have to continuously check for implementation and better techniques for increasing speed of app. Only a part of it is solved.

**Comment by arundhati24** [comment]
The app has a new UI flow now. The skills loaded very slowly due to a number of API calls at almost the same time. The skills load faster now as the API calls are now being made optimally. Hence, closing this issue.
