### ISSUE TITLE
Make speech to text faster in susi android

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#616]
**Actual Behaviour**

Currently when user finished speech input after that it is converted to text.

**Expected Behaviour**

As soon as user start speaking it should converted to text like google assistant.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

me and @chiragw15 are working together on it.

**Comment by chiragw15** [comment]
@amitiwary999 fixed. Issue can be closed.
