### ISSUE TITLE
Make text to speech better

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#621]
**Actual Behaviour**

Currently text to speech is slower and hence some text missed sometimes.

**Expected Behaviour**

Text to speech should match with text.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment]
@amitiwary999 I don't think any text is missed. Can you give an example of that. For my mobile text to speech is working absolutely fine. There is no case when text is not converted to speech. @mayank408 @betterclever can you please check it on your devices?

**Comment by amitiwary999** [comment]
@chiragw15 It is not happening always. Sometimes like for first time when we ask something to susi. I think at the time of reply initializing tts engine takes sometimes.

**Comment by amitiwary999** [comment]
I checked it again now it is working well.I will try to update if I find exact reason.
