### ISSUE TITLE
Keep some features separate from susi response

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#623]
**Actual Behaviour**

Some features like setting alarm that not depend on susi response are coded inside susi response.

**Expected Behaviour**

Keep these features outside of susi response.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment]
removed hardcoded action types.
