### ISSUE TITLE
Memory leak in getVideos

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#625]
**Actual Behaviour**

There is a memory leak in GetVideos.java 

![screenshot_20170519-103126](https://cloud.githubusercontent.com/assets/16978820/26234438/3917fd64-3c82-11e7-94d8-6a135e86bcb5.png)

**Expected Behaviour**

Removing leak for better performance.

**Would you like to work on the issue?**
yes

**Comment by chiragw15** [comment]
@mayank408 Can you help me in this?

**Comment by mayank408** [comment]
@chiragw15 I have tested it in my environment, it is showing varied results from 21 to 28kb.
Is this actually a memory leak or just the memory required for the task because its too small , i am looking into this.

**Comment by iamareebjamal** [comment]
Memory Leaks are rarely leaking the same amount of memory. You may be storing the context in some static variable and not clearing it

**Comment by iamareebjamal** [comment]
```
private MyPlayerStateChangeListener playerStateChangeListener;
private MyPlaybackEventListener playbackEventListener;
```

Remove these listeners in `onDestroy()`

**Comment by iamareebjamal** [comment]
And BTW, why registering listeners when not using them?

**Comment by chiragw15** [comment]
@iamareebjamal I have already removed these listeners because they weren't being used but there is still a memory leak. Don't know why.

**Comment by iamareebjamal** [comment]
You can expand the sections in leakcanary to see which section of your code is being retained in memory

**Comment by mayank408** [comment]
So this feature is removed, hence closing it.
