### ISSUE TITLE
Make login/Signup experience smoother

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_android#627]
**Actual Behaviour**
The current Login/Signup/Password needs improvement to make signup process easier.

**Expected Behaviour**
Registration/Password Recovery should be made easy to provide a user-friendly experience.

Provide the ways to make signup experience smoother.

**Comment by saurabhjn76** [comment]
- **Auto Complete Suggestion in Email Address** - Just by entering first few letters of the email address, a user would be able complete the email.

- **Integration of FB/Google for authentication** - This will make signup process easy and also the information shared through these accounts would be accessible by Susi AI.

**Comment by mayank408** [comment]
Autocomplete done. Fb signup will be discussed in future.
