### ISSUE TITLE
Implement image support

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#63]
Currently contrary to the web client on asksusi.com questions about maps do not generate a map image. Please implement support for map images and other images.

If any relevant output is needed from the server, please open issues in the susi server project.

**Comment by daminisatya** [comment]
For the susi web client, the maps are displayed with the help of leaflet. Hope it can be used here.

**Comment by gogeta95** [comment]
I'd like to work on this, will be using http://staticmap.openstreetmap.de/ to generate images from response, no need to add changes to server.

**Comment by daminisatya** [comment]
Yes looks good to me. Please go ahead.

**Comment by gogeta95** [comment]
@orbiter, can we add a type parameter in response which tells us whether a given response is  text/map/image? It'll also help later if we want to add more types of messages.

**Comment by gogeta95** [comment]
I have a question, shall we just add an image in case of map or make it clickable too?
click map -> open location in browser/google maps?

**Comment by gogeta95** [comment]
any updates?

**Comment by mariobehling** [comment]
@gogeta95 Yes, add an image of the map location and open it in browser/maps.

**Comment by gogeta95** [comment]
how is this for maps? let me know any improvement before making a PR.
![image](https://cloud.githubusercontent.com/assets/8329096/19201071/b8ea0e68-8ce9-11e6-8e25-6c8c705086b9.png)

**Comment by betterclever** [comment]
https://github.com/fossasia/susi_server/issues/100
