### ISSUE TITLE
Memory Leak in Location Helper

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#635]
**Actual Behaviour**

There is a memory leak in location helper.

**Expected Behaviour**

There should be no memory leak in the app.

**Steps to reproduce it**

Be sure your location is ON . Then start the app and query "where am I" and then close the app. You will see memory leak.

**Screenshots of the issue**

![screenshot_20170527-144157](https://cloud.githubusercontent.com/assets/16978820/26522032/0779ec4c-4315-11e7-84dc-6e9cc3298bba.png)

**Would you like to work on the issue?**
yes

**Comment by chiragw15** [comment]
@iamareebjamal I used `locationManager.removeUpdates(this);` in the onStop() method but it didn't fix the issue. I googled it and found that is an issue in google maps sdk as mentioned in this [PR](https://github.com/mcharmas/Android-ReactiveLocation/pull/142). There is a work around using weak reference [here](https://github.com/googlesamples/android-play-location/issues/26#issuecomment-248101802). Need help in implementing it.

**Comment by iamareebjamal** [comment]
Sure, first create a topic branch in your fork and I can help with that.

**Comment by chiragw15** [comment]
@iamareebjamal https://github.com/chiragw15/susi_android/tree/locationLeak this the branch

**Comment by iamareebjamal** [comment]
Hey, I have commented on your commit in the branch. Please take a look if issue is not solved yet
