### ISSUE TITLE
Removing dialog box asking user to retrieve old messages

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#637]
**Actual Behaviour**

There is a dialog box which asks user if he wants to retrieve old messages

**Expected Behaviour**

As mentioned here https://github.com/fossasia/susi_android/pull/634#issuecomment-304710323, removing the dialog box asking user to retrieve old messages and loading previous messages automatically.

**Would you like to work on the issue?**
@mayank408 's working

**Comment by mayank408** [comment]
@chiragw15 Can I work on this.

**Comment by chiragw15** [comment]
Sure, go ahead :+1:
