### ISSUE TITLE
Retrieving old messages not shown correctly  in case of websearch

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#639]
**Actual Behaviour**

Retrieving old messages is not shown correctly.

**Expected Behaviour**

Retrieved messages should be shown correctly.

**Steps to reproduce it**

Start chat with susi which also include websearch. Now logout and again login. you can see websearch is shown according to latest websearch.

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-05-30-02-45-13](https://cloud.githubusercontent.com/assets/14003244/26562359/4fc2b0ea-44e3-11e7-9163-a801ff682d7f.png)
![screenshot_2017-05-30-02-45-46](https://cloud.githubusercontent.com/assets/14003244/26562360/4fc7a4ec-44e3-11e7-9be9-c2d339a89e91.png)

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment]
This line `webquery = MainActivity.webSearch;` [here](https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java#L486) is causing trouble. If the webSearch string is changed too fast i.e before loading of view, the results will be displayed of the last query. Change the implementation of websearch.
