### ISSUE TITLE
Improving overall implementation of websearch

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#647]
**Actual Behaviour**

The current websearch only displays one search result that too is not that informative.

**Expected Behaviour**

- [x] Add horizontal list of results.
- [x] Improve layout (issue #609)
- [x] Improve implementation

**Comment by mayank408** [comment]
@chiragw15 Which Api are we trying to use for this.

**Comment by chiragw15** [comment]
Right now we'll be using DuckDuckGo only. I registered for faroo api key but they never send me. If we can find any better api, we'll shift to it. Meanwhile you register for faroo api key as well.
