### ISSUE TITLE
Test and add support for Snowboy Hotword Detection

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#648]
**Actual Behaviour**

Currently we have a PR open for hotword detection #615 which uses CMU's Pocketsphinx for hotword detection. 

**Expected Behaviour**

Snowboy (https://snowboy.kitt.ai/) is a DNN- based hotword detection library for various platforms. It can be utilized to improve Hotword Detection a lot. Test and implement hotword detection using snowboy.

We can compare result from snowboy and Pocketsphinx and pick the better one.

**Comment by amitiwary999** [comment]
Snowboy is free or paid library? It is free for personal use right?

**Comment by chiragw15** [comment]
Everything discussed on SUSI IOS gitter chat. https://gitter.im/fossasia/susi_iOS

**Comment by jyoth1raditya** [comment]
@chiragw15 , I am working on it from couple of days.
Will send PR today.

**Comment by chiragw15** [comment]
@jyoth1raditya did you solve the issue you were facing?
