### ISSUE TITLE
Issue with alignment of layout in display of maps.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#651]
**Actual Behaviour**

The layout is not uniform.

**Expected Behaviour**

The layout must be uniform.

**Screenshots of the issue**

![screenshot_1496417839](https://cloud.githubusercontent.com/assets/22056321/26733179/a6004886-47d7-11e7-8233-60070a145ab2.png)

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
Map is now a separate message.(After #681) Thus no need for it now.
