### ISSUE TITLE
Reduce complexity of ChatFeedRecyclerAdapter

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#654]
**Actual Behaviour**

The whole Adapter is of ~1200 lines. It is difficult to analyse and many completely different things are happening in the same class. Bugs are hard to track in such big objects and issues difficult to solve

**Expected Behaviour**

Class should be reduced to at max 500 lines. This can be easily done as the binding of viewholders is being done in the class itself and can be delegated to corresponding viewholders which are not more that 25-30 lines. 

This pattern if delegating binding to viewholders also make them self contained and not needing to expose their views outside their lifecycle, reducing the chances of memory leaks

**Would you like to work on the issue?**

No

**Comment by iamareebjamal** [comment]
Some tips while refactoring or mini issues will be to also remove changelisteners from realm on destruction of views. I have seen that you close realm but this will be more foolproof

**Comment by amitiwary999** [comment]
I will work on it.
