### ISSUE TITLE
Correctly format HTML escape characters from response

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#656]
**Actual Behaviour**

Currently, the response shows HTML escaped characters as is without formatting them to normal text

**Expected Behaviour**

Correct formatting must be done before showing the results.

**Steps to reproduce it**

Run any query with return response containing escape characters

**Screenshots of the issue**

![device-2017-06-03-220117](https://cloud.githubusercontent.com/assets/3874064/26755338/a80a2634-48a8-11e7-8a88-7d5c564a3834.png)

**Would you like to work on the issue?**

No

**Comment by Muks14x** [comment]
I'd like to work on this issue. I added a html escape sequence filter before adding the messages to the database. Should I do it before/after this or is this okay? I tested the app with some responses with escape sequences, and it seems to be working fine.

**Comment by chiragw15** [comment]
@Muks14x Sure, go ahead. Add filtered message to database.
