### ISSUE TITLE
Is there any sample query that provides "diagram" type response

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susi_android#666]
Is there any sample query that provides "diagram" type response ?

**Comment by chiragw15** [comment]
@isuruAb There is no action type "diagram" as far as I know. {answer, table, piechart, rss, self, websearch, anchor, map;} These are the action types I found in server code. Still you can confirm it from Orbiter about this.

**Comment by isuruAb** [comment]
@chiragw15  yes i asked it was not woking at the moment .thank you for your response 👍
