### ISSUE TITLE
Use thumbnail image to show images of video played so that user can play it later also.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#669]
**Actual Behaviour**

Currently on play video command YouTube video start playing but susi response side shows hardcoded answer playing video.

**Expected Behaviour**

Instead of showing hardcoded response we can show thumbnail of that YouTube video.

**Steps to reproduce it**

Query play some video.

**LogCat for the issue**

**Screenshot/-s of the issue**

**Would you like to work on the issue?**
yes

**Comment by mayank408** [comment]
@amitiwary999 We are getting away with hardcoded features at this time. So there is no need for implementing this for now.
What do you think @chirag15

**Comment by betterclever** [comment]
Yes, Issue not needed. Closing for now.
