### ISSUE TITLE
Remove hardcoded action types not supported on server yet.

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_android#670]
**Actual Behaviour**

It seems many action types are supported by the client which are not yet supported on the server. Instead, create issues on server for supporting the same.

**Expected Behaviour**

All functionality and action types should be fetched from the server instead of hard coding them

**Steps to reproduce it**

`Play {any song}`

Check: https://github.com/fossasia/susi_iOS/pull/91 for more information.

**Comment by mayank408** [comment]
It is already discussed in #601, we will be replacing it as the server gets the ability to perform the task.

**Comment by chiragw15** [comment]
@mayank408 we are removing them now and creating issues on server to implement them on it. Now is the time. We can't wait for someone else to implement it.

**Comment by chiragw15** [comment]
Already removed them https://github.com/fossasia/susi_android/issues/613#issuecomment-303088758 . Will resolve the merge conflicts and send a PR.
