### ISSUE TITLE
Add "anchor" action type

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#676]
**Actual Behaviour**

Anchor action type is not implemented yet.

**Expected Behaviour**

Need to add anchor action type to support links along with texts.

**Comment by amitiwary999** [comment]
@chiragw15 Can I work on this?

**Comment by chiragw15** [comment]
Sure. Just add the code in parseSusiResponse method.

**Comment by amitiwary999** [comment]
@chiragw15 only parseSusiResponse? or I have to viewholders and chatfeedrecycleradapter too?

**Comment by chiragw15** [comment]
I guess there won't be a need of new view holders. Simply do `answer="<a href=\"http:/the_link_in_the_anchor_action_type.com\">Text_in_anser_action_type</a>"` and add line `textview.setMovementMethod(LinkMovementMethod.getInstance());` and it should work.

**Comment by amitiwary999** [comment]
I think anchor action type use along with answer action type so `answer = answer + answer as you suggest` or `answer = "<a href ...`?

**Comment by chiragw15** [comment]
Second one `answer="<a href=\"http:/the_link_in_the_anchor_action_type.com\">Text_in_anchor_action_type</a>"` and add line `textview.setMovementMethod(LinkMovementMethod.getInstance());`

**Comment by amitiwary999** [comment]
@chiragw15 which one is correct? ` boolean isAnchor = susiResponse.getAnswers().get(0).getActions().get(0).getType().equals("anchor");
            if(isAnchor)
            answer = "<a href = "  +  susiResponse.getAnswers().get(0).getActions().get(0).getAnchorLink() + ">" + susiResponse.getAnswers().get(0).getActions().get(0).getAnchorText() + "</a>";`
or
` boolean isAnchor = susiResponse.getAnswers().get(0).getActions().get(1).getType().equals("anchor");
            if(isAnchor)
            answer = "<a href = "  +  susiResponse.getAnswers().get(0).getActions().get(1).getAnchorLink() + ">" + susiResponse.getAnswers().get(0).getActions().get(1).getAnchorText() + "</a>";`

there is a anchor link in map type response too

**Comment by chiragw15** [comment]
use i instead of 0 or 1. See PR #681 for reference.

**Comment by amitiwary999** [comment]
So I change it here or I will solve this issue after your pr merged?

**Comment by chiragw15** [comment]
Just change it, solve the issue and send a PR. It can be merged after the other one gets mergerd
