### ISSUE TITLE
Decrease parameters in addNewMessage() and updateDatabase() method

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#680]
**Actual Behaviour**

Right now there are 8 parameters in [addNewMessage](https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java#L1075) method and 14 parameters in [updateDatabase](https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java#L1094) method.

**Expected Behaviour**

Decrease the number of parameters by using classes.

**Comment by amitiwary999** [comment]
@chiragw15 we can make a class where we can save all the boolean values?

**Comment by chiragw15** [comment]
addNewMessage method removed and updateDatabase method now has 8 parameters. I think its fine for now.
