### ISSUE TITLE
Reduce Codacy issues wherever possible

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#682]
**Actual Behaviour**

There are 48 potential issues [here](https://www.codacy.com/app/harshithdwivedi/susi_android/dashboard)

**Expected Behaviour**

Try fixing as much as possible.

**Comment by amitiwary999** [comment]
@chiragw15 can I work on this issue.

**Comment by chiragw15** [comment]
Don't ask. If you see unassigned issue, assign it to yourself or comment "I am working on this" and start working.

**Comment by chiragw15** [comment]
@amitiwary999 Though you PR improved implementation of dialog boxes. It hasn't reduced codacy issues much. Let me know if you want to work on this.

**Comment by amitiwary999** [comment]
@chiragw15 when I started working on this issue that time you were working on mainactivity that's why I left mainactivity part. Yes I would like to work on this.

**Comment by chiragw15** [comment]
No problem. Send a PR now. :+1:
