### ISSUE TITLE
Update "rss" action type

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#685]
**Expected Behaviour**

Recently rss action type is updated in susi_server. So we have to implement it in client side.

**Would you like to work on the issue?**

yes

**Comment by mayank408** [comment]
i@amitiwary999 @chiragw15 I want to work on this as my issue related to map UI got resolved .

**Comment by chiragw15** [comment]
@amitiwary999 @mayank408 rss action type is already implemented and working. Just check if it needs some tweaks or changes according to the new response. And improve performance.
![screenshot_20170609-045716](https://user-images.githubusercontent.com/16978820/26954909-c8b61e70-4cd0-11e7-8be3-478d3ad5fb27.png)
