### ISSUE TITLE
The voice recording button.

### ISSUE THREAD

**Issue by AkashIsCoding** [fossasia/susi_android#687]
**Actual Behaviour**

You press and you say your note. You cannot record or dump your note on the go.

**Expected Behaviour**

It will record only record when the record button is clicked, like what we have in Whatsapp, and dragging the button towards the left should dump the message.

**Would you like to work on the issue?**
Yes

**Comment by betterclever** [comment]
Please try to understand , this is not a instant messaging application. 
You are not trying to voice record a voice message and send but interact by voice using STT. A user won't wish to keep the Mic button pressed. The described behavior is not needed at all imo. 
If you wish to idealize something, idealize Google Assistant, not Whatsapp.

@chiragw15 What do you think?

**Comment by chiragw15** [comment]
@AkashIsCoding Some points here: 
1. There is a dump option on the left size, the 'X' icon . So, when you click on mic button, and say something, you can cancel that by clicking on cross (X) button. You can dump on the go. No problem with that imo.
2. That button is for speech input and not recording voice. and sending like whatsapp. Why would a personal assistant even need to record a voice?
3. The main aim of that button is for the users who wish to interact with susi through speech and not text. So, pressing the mic button while speaking is not a good option. The feature is similar to any other personal assistant like google assistant. 

I hope, I am understanding the issue right.

**Comment by mayank408** [comment]
@AkashIsCoding There is no need for this, we are not recording the voice or the query.

**Comment by chiragw15** [comment]
@AkashIsCoding Are we interpreting the issue right? If no, can you explain it a bit? If yes, then this is not required and should be closed.

**Comment by mayank408** [comment]
It is not required for now.
