### ISSUE TITLE
Issue with rss action type

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#691]
**Actual Behaviour**

On marking the rss query answer as important the fields become empty.
**Expected Behaviour**

The fields shoud not become empty.

**Steps to reproduce it**

Mark any rss type query answer important.

**Screenshots of the issue**

![screenshot_1497046780](https://user-images.githubusercontent.com/22056321/26998006-70f2f0c0-4d87-11e7-932a-54c798df1b7b.png)

**Comment by rrishabhj** [comment]
I want to solve this issue.

**Comment by mayank408** [comment]
Sry, It was deleted by mistake.

**Comment by chiragw15** [comment]
@rrishabhj go ahead and send a PR.

**Comment by chiragw15** [comment]
Removed marking important feature. No need for it now.
