### ISSUE TITLE
Issue with retrieved messages.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#698]
**Actual Behaviour**

Messages are retrieved everytime when date of phone is changed.

**Expected Behaviour**

Messages should be retrieved only a single time .

**Steps to reproduce it**

change the date of the app.

**Would you like to work on the issue?**
yes

**Comment by chiragw15** [comment]
@mayank408 I am not able to reproduce it. Can you provide exact steps to be followed?

**Comment by amitiwary999** [comment]
@mayank408 I too not able to reproduce it. Can you please provide full steps to reproduce it.

**Comment by chashmeetsingh** [comment]
@mayank408 can you explain a bit more please? Why are you deleting all the messages in the DB in the PR?

**Comment by mayank408** [comment]
@chashmeetsingh  There is time limit of access token. After that time limit the token is expired and user is logged out. So, this process we are not deleting all messages. We do delete messages when user clicks on log out option but we do not delete it when we automatically logs user out
