### ISSUE TITLE
Setting the app on appetize.io for easy testing.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#702]
**Actual Behaviour**

Apk is not added to the pull request.

**Expected Behaviour**

Apk must be added after the pull request for easy testing.

**Comment by mayank408** [comment]
@betterclever Pls add your comments

**Comment by betterclever** [comment]
Okay. This can be done in the following way.
- After APK build is complete and upload-apk.sh is executing, verify if it is a pull request or regular commit (like merge commit). An 'if' check is there already.
- For PR, upload APK to transfer.sh service using, their curl command. See more here https://transfer.sh/
- Use circle-github-bot (https://github.com/themadcreator/circle-github-bot), to post comment back to Pull Request.

**Comment by chiragw15** [comment]
No one actually is going to download apk from the PR and then transfer it to mobile and install. Therefore it is useless to do it for every PR. It will be better if we somehow can display preview on appetize.io or similar service.

**Comment by betterclever** [comment]
@chiragw15 Appetize.io has only 100 minutes viewership in free tier + slightly sluggish experience. Also, to experience some features like Hotword Detection, you need to check on an actual device. Thus, it might be helpful for non Android Developers to test PRs quickly without needing to pull from PR and set it on on their devices.

**Comment by chiragw15** [comment]
IMO there is no need of automatically adding apk file to every PR. It is just wastage to add apk for a 1-2 line PR. For larger PR, developer should add apk in PR manually. @mayank408 if you find any way to automate preview on appetize.io or any other similar platform, proceed with it else close this.
