### ISSUE TITLE
LongclickListener not working.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#703]
**Actual Behaviour**

LongClickListener is not working for search result.

**Expected Behaviour**

LongClickListener should work for search result.

**Would you like to work on the issue?**
Yes

**Comment by chiragw15** [comment]
Yes, I deliberately left this earlier. This needs to be thought through. You have created the issue now, so let's discuss this. We need to modify click listeners for websearch, maps and RSS. When we long click any message, there are three possible options : copy that message, share that message and delete that message. So, if the action type is map or websearch , we don't need first 2 options. So, we can simply remove them when action type other than answer and anchor is selected and just keep only delete option. This is inspired from Google assistant. @mayank408 @amitiwary999 views?

**Comment by mayank408** [comment]
@chiragw15 Yes , I totally agree with you. Lets do this way only 👍

**Comment by amitiwary999** [comment]
@chiragw15 :+1:

**Comment by mayank408** [comment]
@chiragw15 I am working on it.
