### ISSUE TITLE
Bug: Date is displayed after each message

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#712]
**Actual Behaviour**

Date is displayed after every message.

**Expected Behaviour**

No need of displaying date after each message. 

**Screenshots of the issue**

![screenshot_20170616-164012](https://user-images.githubusercontent.com/16978820/27224473-f716f130-52b2-11e7-8a1e-f5d344d4c137.png)

**Would you like to work on the issue?**
yes

**Comment by mayank408** [comment]
Merged hence closing.
