### ISSUE TITLE
Issue with retrieving old messages

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#716]
**Actual Behaviour**

If user logout and then login and during login if internet connection lost then user can not retrieve old messages.

**Expected Behaviour**

User should be able to retrieve old messages.

**Steps to reproduce it**

Logout and again login. During login disconnect your net connection.

**LogCat for the issue**

**Screenshots of the issue**
This is my messages before logout

![screenshot_2017-06-16-19-34-53](https://user-images.githubusercontent.com/14003244/27230176-ff320012-52cb-11e7-9fad-90be16d65c9f.png)

After login when net connection is lost
![screenshot_2017-06-16-19-35-22](https://user-images.githubusercontent.com/14003244/27230211-1e1b9eca-52cc-11e7-99d3-a64facd24cdb.png)

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
@amitiwary999 I don't know how this is even an issue. First, the messages are retrieved as soon as user logs in, that means after maybe 1-2 seconds. I don't know, how can user have internet connection when he logs in and after 2 secs his internet connection disconnects. Secondly, How will you even solve this?

**Comment by chiragw15** [comment]
Not needed.
