### ISSUE TITLE
Remove Important message activity

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#717]
**Actual Behaviour**

There is a feature in app to mark messages as important, it does not involve server and stores important messages locally.

**Expected Behaviour**

As stated by Mario, since the server doesn't support it, we need to remove it.

**Would you like to work on the issue?**
yes

**Comment by amitiwary999** [comment]
I want to work on this issue.

**Comment by chiragw15** [comment]
@amitiwary999 please complete your old issues first and then start working on it.

**Comment by amitiwary999** [comment]
@mayank408 I was working on this issue. I already mention this.

**Comment by mayank408** [comment]
as @chiragw15 mentioned I thought you were working on old issues. Also, it was unassigned so I assigned it to myself as I don;t have any other issue to work. Please assign it to yourself first if you want to work on it. Thanks

**Comment by amitiwary999** [comment]
But you didn't ask me. I already started working on this issue. Even I mention it in chat that there is some issue with important message. I asked 2 days before for that. So I already planned for it.

**Comment by mayank408** [comment]
Why would I ask you it was unassigned so I assigned it to me, you could also do so. How would the co-dev know that you "already planned it". Pls work cooperatively.

**Comment by betterclever** [comment]
@amitiwary999 As @chiragw15 said, you had some pending issues. But that aside, your PR seems to not have removed all traces of ImportantMessages. Only 7 changed files in comparison to 19 in PR by @mayank408 . If you started working on this early, you should take care that issue gets resolved fully.

**Comment by amitiwary999** [comment]
@mayank408 Currently I have no right for this that's why I can't assign issues to my self. I only comment that I want to work on this issue. I already mention that.

**Comment by mayank408** [comment]
@amitiwary999 But even after your comment @chiragw15  mentioned that you have to do old issues first and after which there was no response from your side. Well lets be more clear in future as we are all working together. Thanks

**Comment by amitiwary999** [comment]
No problem. Currently I have no right so if I mention that I want to work on this issue atleast ask me once. I can't assign issue to myself.

**Comment by mayank408** [comment]
@amitiwary999 Ya sure will ask you and assign you at the same time if you wants to work on an issue. Cheers 👍
