### ISSUE TITLE
Map does not showing the right location 

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#72]
on asking where is india ,Its showing the location of indija...

![whatsapp image 2016-10-01 at 6 16 34 pm](https://cloud.githubusercontent.com/assets/22056321/19014174/480cfa7e-8803-11e6-9f98-f0501c646ce6.jpeg)

![whatsapp image 2016-10-01 at 6 16 34 pm 1](https://cloud.githubusercontent.com/assets/22056321/19014173/47e8f0e8-8803-11e6-82ee-7868647aabb0.jpeg)

**Comment by daminisatya** [comment]
@mayank408 we are not sure whether it is issue with the open street map interpretation or with the response from susi server. 
Can you please investigate in this. ☺

**Comment by amitiwary999** [comment]
I think it is issue with open street map interpretation

**Comment by amitiwary999** [comment]
On asking about other country like where is America or China it replies you can ask me anything not that

**Comment by mayank408** [comment]
@daminisatya @amitiwary999 The issue is with open street interpretation as it only recognize India that too not correctly while it does not show any result for other countries..

**Comment by daminisatya** [comment]
Ok, So the issue is in wrong repo, please open the same in susi server.

**Comment by daminisatya** [comment]
The response coming from the server uses the open street maps for the map links. So we can think of another alternative. Please follow up with this issue in susi server
