### ISSUE TITLE
Issue with date of retrieved old messages

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#723]
**Actual Behaviour**

Currently date of all retrieved message is same which is date of last message.

**Expected Behaviour

Retrieved message should be shown according to it's date.

**Steps to reproduce it**

Logout and login. See the date of retrieved message. It is same for all. But in response date is different.

**LogCat for the issue**

**Screenshots of the issue**
.

**Would you like to work on the issue?**

Yes.

**Comment by chiragw15** [comment]
@amitiwary999 #712 is same. The reason why there is date after every message because date of all retrieved messages are same. So, I just changed that and it is solved. Sending a PR in some time. Cheers.

**Comment by chiragw15** [comment]
Okay sorry, Didn't see you already sent a PR. Cool.

**Comment by mayank408** [comment]
same as #712. Hence closing

**Comment by amitiwary999** [comment]
@mayank408 It is not same as #712 . #712 is for current chat messages and this issue is related to retrieved old messages after user login again. Please open it.

**Comment by mayank408** [comment]
@amitiwary999 @chiragw15 Pls be more clear. As @chiragw15 said #712 is same as it. I am opening it.

**Comment by chiragw15** [comment]
@amitiwary999 The reason why issue #712 was occurring was that the retrieved message had same date which is this issue. So, the reason of issue #712 is this issue. Thats why I said it is same as #712.

**Comment by mayank408** [comment]
Fixing all date and time related bugs PR #728 is merged. Hence closing.
