### ISSUE TITLE
Using speech to text to take the input 

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#73]
how it would be to use speech to text input in the app..
i would like to work on that....

**Comment by daminisatya** [comment]
Its a good enhacement, please provide us with info on how you are planing to implement it.

**Comment by mayank408** [comment]
Speech to text is implemented ..
its working fine without any crashes or lag..
![whatsapp image 2016-10-01 at 8 25 40 pm 1](https://cloud.githubusercontent.com/assets/22056321/19014845/72d40e98-8815-11e6-9452-d0f2270d4efb.jpeg)
![whatsapp image 2016-10-01 at 8 25 40 pm](https://cloud.githubusercontent.com/assets/22056321/19014846/72db5586-8815-11e6-9ad5-c21cb90966eb.jpeg)

**Comment by mayank408** [comment]
@daminisatya  Should i give a pull request or any improvement is required like a single button for both and other transition effects..

**Comment by daminisatya** [comment]
@mayank408  it looks good to me. Please create a pull request! 👍

**Comment by mayank408** [comment]
#76 updated speech to text input..

**Comment by mayank408** [comment]
new pull request #83 has been created.. resolving all the conflicts.
