### ISSUE TITLE
Removing msg with link function

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#731]
**Actual Behaviour**

Currently, we are showing link preview if the query contains a link. This is not related to the server anyway.

**Expected Behaviour**

As it is not related to server we should remove this as stated by @mariobehling. 

**Screenshots of the issue**

![screenshot_1497784517](https://user-images.githubusercontent.com/22056321/27260285-f35fa73c-5445-11e7-83c6-7075f6d7f6fc.png)

As you can see query and its response have no connection as server is not playing any role here.

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
IMO, no need of removing link preview. It depends on client how it has to display the response from server. Just update the code such that if link preview callback does not yield anything, then hide link preview.

**Comment by mayank408** [comment]
@chiragw15 yup okk fine 👍
