### ISSUE TITLE
Create javadocs.

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#749]
- [x] Add Javadoc comments in code like this 
```
/**
 * Validates a chess move.
 *
 * Use {@link #doMove(int theFromFile, int theFromRank, int theToFile, int theToRank)} to move a piece.
 *
 * @param theFromFile file from which a piece is being moved
 * @param theFromRank rank from which a piece is being moved
 * @param theToFile   file to which a piece is being moved
 * @param theToRank   rank to which a piece is being moved
 * @return            true if the move is valid, otherwise false
 */
boolean isValidMove(int theFromFile, int theFromRank, int theToFile, int theToRank) {
    // ...body
}
```
- [ ] Now configure Circle CI script to generate javadocs after each successful build and commit the generated files to the `gh-pages` branch. I found this loklak blog which maybe helpful. http://blog.loklak.net/under-the-hood-javadocs/ .

**Comment by the-dagger** [comment]
Sounds good. 👍

**Comment by chiragw15** [comment]
@the-dagger The first part of issue is done. How should we proceed with the second part? As you mentioned [here](https://github.com/fossasia/susi_android/pull/739#discussion_r123311684) that hosting is not needed, should we leave the second part for now?

**Comment by the-dagger** [comment]
Yeah, hosting isn't really needed right now imo.
This issue can be closed. 👍
