### ISSUE TITLE
Each time when app start it shows the first ever chat between AI and user

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#75]
Each time when user Start app by default app always show first ever message between SUSI_AI and user

**Comment by amitiwary999** [comment]
I would like to work on it.

**Comment by jig08** [comment]
@amitiwary999 Please be clear on what the issue is and what do you suggest as a fix.
Thanks !

**Comment by amitiwary999** [comment]
@jig08 
This is the first chat between me and AI when I install app
![screenshot_2016-10-02-08-10-55](https://cloud.githubusercontent.com/assets/14003244/19018267/75da167e-8878-11e6-9074-d85986836e41.png)

**Comment by amitiwary999** [comment]
and this is the last chat 
![screenshot_2016-10-02-08-11-06](https://cloud.githubusercontent.com/assets/14003244/19018277/b5721e12-8878-11e6-8040-5c77e653b072.png)

**Comment by amitiwary999** [comment]
but whenever I open app it always show me the first ever chat between me and AI 
![screenshot_2016-10-02-08-10-55](https://cloud.githubusercontent.com/assets/14003244/19018287/ecdcc00a-8878-11e6-958c-284fb122f0bf.png)

**Comment by amitiwary999** [comment]
But it should show last chat between me and AI i.e this pic.
![screenshot_2016-10-02-08-11-06](https://cloud.githubusercontent.com/assets/14003244/19018292/059a6e12-8879-11e6-932f-90f55c6a2edc.png)

**Comment by daminisatya** [comment]
@amitiwary999 good catch. Please go ahead and fix it
