### ISSUE TITLE
Showing image in the response to queries.

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#762]
**Actual Behaviour**

We are not showing images even when there is image URL present in the response from the server.

**Expected Behaviour**

Just like IOS and Web Clients we should show the image in the answer if image URL is present in the response.

**Screenshots of the issue**

![screen shot 2017-06-22 at 3 18 57 pm](https://user-images.githubusercontent.com/22056321/27428449-ae687042-575f-11e7-9018-16cb5df97056.png)

**Would you like to work on the issue?**

Yes, already working on this.

**Comment by chiragw15** [comment]
Server does not support it. It is under development. Continue with this once it is complete on server.

**Comment by batbrain7** [comment]
@chiragw15 we have to do it in this way only bcoz web app does it in the same way
