### ISSUE TITLE
Issue with preview in map action type reply

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#764]
**Actual Behaviour**

answer has link but app not showing preview 

**Expected Behaviour**

If answer has link then app should show preview.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-06-22-20-39-13](https://user-images.githubusercontent.com/14003244/27441468-476a0df2-578b-11e7-9db2-6428911b2947.png)

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
This is a general link preview bug and not specific to map action type.
