### ISSUE TITLE
Store User settings on server

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#766]
Store the user settings on the server and push and pull from the server accordingly to maintain the app state.

Refer fossasia/susi_server#306 for endpoints to push data to server

Listing Settings :
http://api.susi.ai/aaa/listUserSettings.json?access_token=ACCESS_TOKEN

Adding Settings :
http://api.susi.ai/aaa/changeUserSettings.json?key=theme&value=THEME&access_token=ACCESS_TOKEN

**Comment by mayank408** [comment]
http://api.susi.ai/aaa/changeUserSettings.json?key=theme&value=THEME&access_token=ACCESS_TOKEN

The link is not working.

**Comment by mayank408** [comment]
Which theme are we gonna store in the server?

**Comment by chiragw15** [comment]
Where is the mention of theme in the issue? I have specifically mentioned `user settings`. If you are talking about theme in the link, that is just an example. Another example can be http://api.susi.ai/aaa/changeUserSettings.json?key=voice_input&value=true&access_token=ACCESS_TOKEN

**Comment by mayank408** [comment]
yes , I was talking about the use cases.

**Comment by chiragw15** [comment]
All the settings like voice_input , voice_output, voice_output_on_voice_input will be stored on server. Apart from that, in future if we also have different themes : light and dark like http://chat.susi.ai/, those will also be stored on server.
