### ISSUE TITLE
UI issue with websearch and rss action type.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#768]
**Actual Behaviour**

There is a nonuniform margin right margin.

**Expected Behaviour**

Margin should be same everywhere.

**Steps to reproduce it**
Try to query websearch and rss action type reply continuously you will find that margin increasing continuously.

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-06-23-11-50-05](https://user-images.githubusercontent.com/14003244/27469063-25c9f6b4-580b-11e7-9169-7841d77c73c8.png)

![screenshot_2017-06-23-08-57-22](https://user-images.githubusercontent.com/14003244/27469069-35800f08-580b-11e7-8cad-c6819524aece.png)
![screenshot_2017-06-23-08-51-58](https://user-images.githubusercontent.com/14003244/27469105-592b426a-580b-11e7-8cd7-f253baf840a3.png)

**Would you like to work on the issue?**

Yes.

**Comment by amitiwary999** [comment]
@mayank408 can you check this. I think you solved this issue in your previous pr but issue is not solved it looks more weird now.

**Comment by mayank408** [comment]
@amitiwary999 The reason was that itemDecorator was called everytime when the recycleview is updated.
Now I have added the ItemDecorator on onCreateViewHolder instead of onBindViewHolder as it is being called only a single time. This solves the issue.
Thanks for pointing out.

**Comment by amitiwary999** [comment]
But why did you send PR for this. I was working on this. Please close your
pr. I already gave you many chances. Please cooperate and close your pr

**Comment by mayank408** [comment]
@amitiwary999 For your kind information you asked me to check the issue that why I send the Pr and please don't behave childish like "Close the Pr". And above all this issue was related to the previos issue I was solving.

**Comment by amitiwary999** [comment]
Yeah but I asked to check it is happening on your device or not. I am not
behaving like childish. When I mentioned that yes I want to work on this
issue then you must ask me first. Please cooperate and don't waste my time.
I am working on this issue.
