### ISSUE TITLE
Deactivate debugging in sample app in apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#77]
Deactivate debugging in sample app in apk branch.

See more info here: http://developer.android.com/tools/device.html

**Comment by addiittya2006** [comment]
We are building and uploading app-debug.apk to the orphan branch through travis. Actually, debugging must not be disabled for the debug buildVariant. Debugging is disabled by default for the release Variant, So what can be done is Build a release apk through Travis, then that apk can't be debugged.

Rather another great option would be to do an Alpha tag Github release after successful builds and Milestone releases manually.

**Comment by mariobehling** [comment]
> So what can be done is Build a release apk through Travis, then that apk can't be debugged.

Yes, please do. We need a sample apk without debugging
