### ISSUE TITLE
Handle new action type : playaudio

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_android#778]
In reference to [issue 187](https://github.com/fossasia/susi_skill_data/issues/187), Please follow up with a discussion on how would  you handle the response coming from the server.

**Comment by chiragw15** [comment]
This can be done by two ways : 
1. Send a link to youtube video along with action type = "play". This is how google assistant do it.
2. We store an audio file in locally and play it when action type is "play" and you will also need to send name of audio file to be played in the response.

**Comment by chiragw15** [comment]
Not implemented on server. Reopen when implemented on server.
