### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by Arshilgenius** [fossasia/susi_android#784]
**Actual Behaviour**

Currently the Button Corners  in forgot password activity and Sign up Activity are not rounded

**Expected Behaviour**

Make the Button Corners rounded
**Steps to reproduce it**

 Just open  the App and move to sign up and Forgot Password Page
**LogCat for the issue**

**Screenshots of the issue**

![whatsapp image 2017-07-02 at 11 07 44 pm](https://user-images.githubusercontent.com/21264401/27772271-5d5f4dea-5f7c-11e7-9ef1-dfd9591a18b5.jpeg)
![2](https://user-images.githubusercontent.com/21264401/27772273-60473b26-5f7c-11e7-9b10-28f72de249b6.jpeg)

**Would you like to work on the issue?**
 
Yes

**Comment by chiragw15** [comment]
@Arshilgenius Go ahead. Make sure you change it in landscape mode too. :+1:
