### ISSUE TITLE
New Feature : Displaying Skill Pane in Clients in Grid form

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#785]
Generally, when a user first install a Personal Assistant app, he/she doesn't know what to ask the client and what all skill does it have,

To tackle this, Cortana has a very nice and elegant solution. Displaying the main skills in client as a grid form.

<p align="center">
    <img src="https://user-images.githubusercontent.com/16978820/27773389-2a767146-5f96-11e7-8d71-34adf5c4f57b.png" height = "480" width="270"> 
    <img src="https://user-images.githubusercontent.com/16978820/27773458-b51a0546-5f97-11e7-9e47-c76f063fa607.png" height = "480" width="270"> 
  </p>

Susi already has skills for news, weather, location, joke etc whereas many new skills are like alarm and play audio are almost implemented. So, how about we display the main susi skills in clients itself. This can be implemented in all clients.
Clicking on these skills will send the Server, query for that skill and after getting response, it will be displayed same way as we are displaying now.
 
@mariobehling @the-dagger 
@uday96 @rishiraj824 @madhavrathi @isuruAb 
@chashmeetsingh 
@mayank408 @amitiwary999
Views on this?

**Comment by chashmeetsingh** [comment]
Yup, 👍  even Google Assistant shows its capabilities.

**Comment by rishiraj824** [comment]
@chiragw15 Yes we can add this in web too.

**Comment by the-dagger** [comment]
@chiragw15 Sounds like a plan.
A good way to implement this is allowing some hardcoded actions in the app which can be clicked in order to receive details about that call.

In order to do this, we can use something similar to what WhatsApp does on clicking the "Attach" button in the editText area of a chat screen.

On the first launch, we can prompt the user to click that button and present him/her with some actions which susi can perform.

**Comment by chiragw15** [comment]
Yes, that is how I was thinking too. The implementation will be exact same as in "cortana on android" i.e clicking on skill will send susi query related to skill and work accordingly. :+1:

**Comment by mariobehling** [comment]
@chiragw15 How does Google show the skills? How can we avoid that the button takes up space on the start screen? 

Instead of starting this with a button, can we have a skill "Show me what you can do"?

**Comment by chiragw15** [comment]
@mariobehling google displays skills in two ways:
1. First is the skill listing that we already have at susi-skill-cms. They list out all skills category wise. 
![screenshot_20170719-124708](https://user-images.githubusercontent.com/16978820/28360993-d26d60b6-6c94-11e7-944e-04b89c0ff2fa.png)
2, Second is as you said, "What can you do" gives a list and it is displayed with horizontal scrolling.
![screenshot_20170719-124734](https://user-images.githubusercontent.com/16978820/28361125-55a06a00-6c95-11e7-835d-44cd2ac4feaa.png)

**Comment by Orbiter** [comment]
Looks good, skill list should come from the server as json response. In the future that list should be generated using learning from most frequent skills but for the first step and tests it's ok to make this hardcoded but hardcoded on server-side

**Comment by harshvardhan-takawale** [comment]
Hi, I am new to open source development and would like to work on this issue, is it still up for grabs? What all needs to be done?

**Comment by chiragw15** [comment]
@harshvardhan-takawale pick any other issue. It is already implemented now in the form of skill listing. Closing it.
