### ISSUE TITLE
Shift to MVP Design Pattern

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#786]
The code in the app is already getting pretty messy even though there is not much features implemented. In the future when there will be a lot of action types from server, it will be very difficult to manage code base. This also makes testing of the app extremely difficult and causes various crashes and memory leaks here and there. 

Suggestion -> Using MVP design pattern with dagger 2 injection
 
@iamareebjamal 's blog http://blog.fossasia.org/the-joy-of-testing-with-mvp/ explains very nicely how MVP design pattern works and how to test the app. Also, this https://stackoverflow.com/questions/40766185/advantage-of-mvp-in-android stackoverflow answer lists advantages of using MVP design pattern. 

Since, the codebase is small right now and will get huge with the development of more and more skills on server, it may be a wise decision to shift to MVP architecture.

@mariobehling @the-dagger @mayank408 @amitiwary999 @betterclever views on this?

**Comment by amitiwary999** [comment]
@chiragw15 Yes using MVP architecture is good. I have tried mvp architecture.

**Comment by mayank408** [comment]
@chiragw15 @betterclever I too have been the supporter of MVP design pattern but there few things to keep in mind:-

1. It's quite confusing to understand so for new developers contributing to the code base will find it very difficult to start with.

2. After converting into MVP the codebase will become quite large as compared to the present scenario.

**Comment by chiragw15** [comment]
@mayank408 We can't compromise with the performance of the app just because it is a little difficult to understand. Just a normal 1 day study is enough to get started with MVP. And as far as codebase is concerned we'll follow different packages style. Each feature/activity will have a different package containing everything related to it. If code is organized, it does not matter how large it is.

**Comment by mayank408** [comment]
I think @the-dagger Will be better to answer this question.

**Comment by iamareebjamal** [comment]
You can look at MVVM using new Architecture components as it is a little easier, and solves problems like reactivity and orientation changes easily

**Comment by mayank408** [comment]
@iamareebjamal Yes MVVP seems better than MVP as its is relatively new but I am not sure whether there are enough resources available for it to get started with.

**Comment by iamareebjamal** [comment]
There are several code labs for Architecture Components, several articles on medium and hours of talks from Google I/O on YouTube, and it's easy to convert from any design pattern

**Comment by the-dagger** [comment]
@chiragw15 @mayank408 We should definitely shift to MVP asap, that will make managing the code a lot easier.
I don't really find MVVM that appealing in terms of code readability so let's skip that.

Regarding dagger/dagger2 it has a steeper learning curve as compared to MVP, so let's not implement it right away.

**Comment by mayank408** [comment]
@the-dagger Yes sure its good to start with MVP first. 👍
