### ISSUE TITLE
Shift to Kotlin

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#787]
If we plan to go with the MVP design pattern mentioned in #786 , we might need to implement many new classes. So, if we are writing them again, why don't we write them in Kotlin. There is no doubt that Kotlin is better than java with less amount of code for same thing, free from null pointer exception, its interoperability with java, etc. (More information : https://code.tutsplus.com/articles/java-vs-kotlin-should-you-be-using-kotlin-for-android-development--cms-27846 )

It is also now officially supported by google now.

The best part is we don't need to change complete code to kotlin at once. Kotlin and Java works together in same app and user will not even find a difference. So, we can slowly shift to kotlin changing components one at a time and keeping the app always running. 

@mariobehling @the-dagger @mayank408 @amitiwary999 @betterclever views?

**Comment by betterclever** [comment]
Indeed @chiragw15 , kotlin will be a good switch for the app. Code will become much concise. As you mentioned already, best part is that we can shift in phases. I have made an app entirely in Kotlin and I will definitely recommend it.

**Comment by the-dagger** [comment]
Using kotlin sounds good.
Start off by using it in small places and increasing it gradually.
Automatica java to kotlin conversion is available in the canary built, but you can use the kotlin plugin for the stable Studio version.
