### ISSUE TITLE
Changing theme is not working properly

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#792]
**Actual Behaviour**

Theme not changed in mainactivity even when it is changed in setting.

**Expected Behaviour**

Theme should be changed.

**Steps to reproduce it**

Change theme in setting and then press back arrow. Mainactivity will open but theme remain same.

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-07-04-20-52-48](https://user-images.githubusercontent.com/14003244/27836136-cd20d40c-60fb-11e7-8e1f-e6561efb6be7.png)

**Would you like to work on the issue?**

Yes

**Comment by amitiwary999** [comment]
App is not working properly in my device. I will reopen it if I face this issue again.

**Comment by mayank408** [comment]
@amitiwary999 Its working fine on my phone.

**Comment by mayank408** [comment]
![screenshot_1499187739](https://user-images.githubusercontent.com/22056321/27838489-a8bdfeac-6108-11e7-8772-aa0fc069096e.png)

**Comment by amitiwary999** [comment]
@mayank408 change theme in setting and then press back arrow. MainActivity will open but theme remain same.
