### ISSUE TITLE
App is crashing after logging in

### ISSUE THREAD

**Issue by Arshilgenius** [fossasia/susi_android#798]
**Actual Behaviour**
After logging out and then again logging in
and entering my email and password the App is crashing.

**Expected Behaviour**

The  App should not crash after logging in

**Steps to reproduce it**

Logout and then again Login.

**LogCat for the issue**

07-05 23:22:24.775 14348-14523/? E/GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
07-05 23:22:24.986 14348-14348/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.fossasia.susi.ai, PID: 14348
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                       at java.io.StringReader.<init>(StringReader.java:50)
                                                       at android.text.HtmlToSpannedConverter.convert(Html.java:758)
                                                       at android.text.Html.fromHtml(Html.java:245)
                                                       at android.text.Html.fromHtml(Html.java:188)
                               
**Screenshots of the issue**

![screenshot_1499279391](https://user-images.githubusercontent.com/21264401/27879080-19f6d776-61de-11e7-83c8-9e8ce73cacc1.png)

**Would you like to work on the issue?**

Yes

** Google Play Services are already  installed still i am facing this issue. **

I think it's a server error.

**Comment by chiragw15** [comment]
@Arshilgenius This is the issue `java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference` Can you provide complete logs?

**Comment by Arshilgenius** [comment]
![screen shot 2017-07-06 at 1 55 08 pm](https://user-images.githubusercontent.com/21264401/27902311-e768eaa4-6252-11e7-9d6f-a7413f3ce0f6.png)

**Comment by chiragw15** [comment]
Okay. This is because of this `holder.titleTextView.setText(Html.fromHtml(datum.getTitle()));` line (line 57 SearchResultAdapter). Here datum.getTitle() is null and we are using HTML.fromHTML on null object generating null pointer exception. Add null check above this to solve it.

**Comment by chiragw15** [comment]
@Arshilgenius why did you close this?

**Comment by Arshilgenius** [comment]
@chiragw15  should i change and send a PR?

**Comment by chiragw15** [comment]
Yes. That's why I told  you `Add null check above this to solve it.`. Go ahead and send a PR.
