### ISSUE TITLE
Shift Main Activity to Kotlin with MVP Design

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#799]
Shift Main Activity to Kotlin and MVP design Pattern

Parent issues : #787 #786

**Comment by mayank408** [comment]
Line no: 983 PrefManager.putBoolean(Constant.MIC_INPUT, checkMicInput() && PrefManager.getBoolean(Constant.MIC_INPUT, false));

**Comment by mayank408** [comment]
Add INSTANCE after MediaUtil and DateHelper class like MediaUtil.INSTANCE.isAvailableForVoiceInput(MainActivity.this);
