### ISSUE TITLE
Use Mockito as Mocking Framework for App Testing

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#803]
Mockito is a mocking framework, JAVA-based library that is used for effective unit testing of JAVA applications. Mockito is used to mock interfaces so that a dummy functionality can be added to a mock interface that can be used in unit testing.

http://site.mockito.org/

Use Mockito to mock interface and test the app.

**Comment by codedsun** [comment]
@chiragw15 Can I work on this issue?

**Comment by arundhati24** [comment]
@chiragw15 I am working on this. :)

**Comment by iamareebjamal** [comment]
@arundhati24 Is your PR linked to this issue? As I saw another PR handling this

**Comment by arundhati24** [comment]
@iamareebjamal I have just opened the issues for writing unit tests. @batbrain7 has started working on unit tests for login feature. He has used Mockito. So I think you might have come across that [PR](https://github.com/fossasia/susi_android/pull/1251).
