### ISSUE TITLE
Write good Unit Tests to Test the working of the app

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#804]
Write good quality unit tests to test the working of each component of the app. After Shifting to MVP, the testing will be a lot easier. So, write tests for everything. Make sub issues for tests related to particular issues like Login tests etc.

**Comment by codedsun** [comment]
@chiragw15 Can I work on this issue?

**Comment by Bhavnaharitsa** [comment]
@batbrain7 @iamareebjamal 

Can I work on this ?
