### ISSUE TITLE
Remove change server option in Login Mode

### ISSUE THREAD

**Issue by mayank408** [fossasia/susi_android#828]
As @mariobehling said we should get away with the change server option as it is of no use in Login mode

**Would you like to work on the issue?**

Yes, working on this.

**Comment by chiragw15** [comment]
@mayank408 Option to disable hotword detection is already implemented https://github.com/fossasia/susi_android/pull/805

**Comment by amitiwary999** [comment]
@mayank408 are you working on this issue?

**Comment by mayank408** [comment]
Yes @amitiwary999 i have almost completed it
