### ISSUE TITLE
HTML tags are not parsed in susi android

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_android#834]
**Actual Behaviour**

Currently, HTML tags are not getting parsed  in susi
![image](https://user-images.githubusercontent.com/9781788/28128757-797f1b70-674e-11e7-9938-514fafbaefea.png)

**Expected Behaviour**
Like web client HTML should be parsed
![image](https://user-images.githubusercontent.com/9781788/28128941-0773ff40-674f-11e7-90e3-1b9591724fe0.png)

**Would you like to work on the issue?**

@chiragw15 @mayank408 @amitiwary999 Please help in fixing it

**Comment by amitiwary999** [comment]
I will fix it.

**Comment by amitiwary999** [comment]
@saurabhjn76 I tried but response is different. Can you tell me how you get that response?

![screenshot_2017-07-12-23-01-37](https://user-images.githubusercontent.com/14003244/28131000-2749bbfa-6756-11e7-88d8-ced93c7a220c.png)

**Comment by chiragw15** [comment]
https://github.com/fossasia/susi_server/pull/367 PR is still open. Pull the code and run on local host

**Comment by saurabhjn76** [comment]
@amitiwary999 It was from my local server, Please refer to https://github.com/fossasia/susi_server/pull/367 for changes. Thanks

**Comment by amitiwary999** [comment]
Okay
