### ISSUE TITLE
Add crash reports

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#843]
There are crash reporting tools. Please propose and add a tool, e.g. chrashalytics.

**Comment by mayank408** [comment]
@mariobehling After going through some of the tools from this link linhttp://leaks.wanari.com/2016/05/26/crash-report-tools-android-developers/

We can either use firebase or Crashlytics, both are equally powerful and efficient 
But as we don't use Firebase for any of other features in the app, I think Crashlytics should be obvious choice for this.

Will be looking forward to implement it

**Comment by mayank408** [comment]
@mariobehling It requires an account for an API key, should I supposed to give my own account or any other account?

**Comment by niranjan94** [comment]
@mariobehling a better option would be (keeping all fossasia projects in mind) is to have a self-hosted [Sentry](https://sentry.io/welcome/) for fossasia. Maybe at `sentry.fossasia.com` which could be used for all fossasia projects. Very similar to how we do for eventyay ([sentry.eventyay.com](https://sentry.eventyay.com)).

**Comment by niranjan94** [comment]
This gives us complete control/freedom to since we're not actually tied into any third-party service (Sentry runs completely on-premise and doesn't call home for any feature)

**Comment by mariobehling** [comment]
@niranjan94 For FOSSASIA services, I would not want to depend on a free tier of a could provider. Can we host Sentry on a VPN? E.g. is this on sufficient? https://www.hetzner.com/virtual-server/cx10

**Comment by niranjan94** [comment]
Yes @mariobehling.. That vps is sufficient
