### ISSUE TITLE
Option to set different languages

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_android#845]
currently the android client sends the client language to the susi_server within the `language` attribute. I believe that this is taken from the default settings of android.

For testing, we need an option to overwrite the default setting with a given language.

Please add such a setting with the options:
* default language
* en
* de
* es
* fr
* it

**Comment by mayank408** [comment]
Yes sure I will be working on this

**Comment by amitiwary999** [comment]
I will work on it.

**Comment by chiragw15** [comment]
@Orbiter wrote in the channel the following. Please implement as required:

> Language detection is now in place. Susi will try to answer in the language that is submitted with the language attribute in the api query. That means this value must be set properly in all clients. Can please someone take care that this works properly? you can test if the language is set correctly with the susi chat phrase „my language“.
The skill selection for given languages will not restrict to the language but it will make the given language the main ranking criteria. So if your own language is not available, it will then prefer english next. There are exceptions like: if your language is finnish, it will prefer swedish as alternative language (they ususaly speak swedish). We can make such exceptions for any language. For not it works with english.
