### ISSUE TITLE
Use moshi to automap JSON to Kotlin class to reduce boiler plate code

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#848]
Use Moshi convertor factory for auto-mapping https://github.com/square/moshi. By this way, we can reduce 
```
class LocationResponse {

    @SerializedName("ip")
    var ip: String? = null

    @SerializedName("hostname")
    var hostname: String? = null

    @SerializedName("city")
    var city: String? = null

    @SerializedName("region")
    var region: String? = null

    @SerializedName("country")
    var country: String? = null

    @SerializedName("loc")
    var loc: String? = null

    @SerializedName("org")
    var org: String? = null

    @SerializedName("postal")
    var postal: String? = null
}
```
to
```
class LocationResponse (
    var ip: String?,
    var hostname: String?,
    var city: String?,
    var region: String?,
    var country: String?,
    var loc: String?,
    var org: String?,
    var postal: String?
)
```
By this way, we can even fit every susi response in single file, making overall 3 files i.e for susi response, for websearch and for location. See this tutorial for example. https://android.jlelse.eu/keddit-part-6-api-retrofit-kotlin-d309074af0 and this code https://github.com/juanchosaravia/KedditBySteps/commit/8295dfa18896a3ac18757e4c026fa1e7d5ec1600#diff-f419ad5f6c76e2617a08405003a66c76

**Comment by mayank408** [comment]
@chiragw15 I will be working on this.

**Comment by S2606** [comment]
@mayank408 Are you working on this?? or can I?

**Comment by chiragw15** [comment]
@S2606 please proceed. Cheers. :+1:
