### ISSUE TITLE
Make Speech input full Screen 

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#856]
Follow Siri and Cortana and implement a full-screen Speech input feature.  
![1](https://files.gitter.im/fossasia/susi_android/MnWd/index11.jpeg)
![2](https://files.gitter.im/fossasia/susi_android/WTpU/IMG_41F2667EE1DF-1.jpeg)

**Comment by amitiwary999** [comment]
@chiragw15 can you test this [apk](https://drive.google.com/open?id=0B8gIkH5cqXi3Mk9TbnJIdFpuN28)?
