### ISSUE TITLE
Implement let's train SUSI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#861]
Google has an option to train the voice. In the SUSI Android settings implement a screen to train "Hi SUSI" similarly to Google and connect this feature with the Snowboy training service.

![screenshot_2017-07-18-23-04-44](https://user-images.githubusercontent.com/1583873/28340695-fabf5bde-6c10-11e7-82e5-939802e3317e.png)

![screenshot_2017-07-18-23-04-37](https://user-images.githubusercontent.com/1583873/28340701-0102e0a6-6c11-11e7-93e4-2eb71678d240.png)

**Comment by chiragw15** [comment]
@mariobehling same as #806
