### ISSUE TITLE
Make a design prototype following Google Assistant

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#862]
The UI of the app needs to be improved. For that, as suggested by @mariobehling we should follow Google Assistant closely. So, make a design prototype following them closely and share here for further discussion.

**Comment by chiragw15** [comment]
@amitiwary999 Please follow this design. Thanks. 
![1](https://files.gitter.im/fossasia/susi_android/vH4C/Screenshot_20170721-164630.png)

**Comment by amitiwary999** [comment]
@chiragw15 only for chat bubble layout?

**Comment by chiragw15** [comment]
No, Completely. Follow the UI changes here https://github.com/fossasia/susi_android/compare/development...chiragw15:newdesign2?expand=1 . 
1. Shift Login/Logout, Share and Change Background to Settings.
2. Remove Search. Not needed. This feature is more related to messenger application and not Personal Assistants. 
3. Either Remove Copy and Sharing of messages or implement it the way google assistant implements delete and edit query feature. By the second way we can add delete functionality in future easily.

**Comment by mayank408** [comment]
@chiragw15 Don't do all this in a single issue, make separate issues one by one and solve them. It will make the development fast and it will easy for reviewing.

**Comment by chiragw15** [comment]
Instead of focussing more on features from chat/messenger applications, we should focus more on features from Personal Assistant applications which include. nice animations for voice input (maybe full screen), ways to showcase skills, implementing training of hotword detection, etc

**Comment by chiragw15** [comment]
@mayank408 Yes, obviously. I am just mentioning what all we can do. When implementing, make sub issues.
