### ISSUE TITLE
chat background image

### ISSUE THREAD

**Issue by rahulworld** [fossasia/susi_android#87]
like whats app and hike messenger

**Comment by jig08** [comment]
@rahulworld Be specific in detailing about the issue or feature suggestion and its implementation. 

If you mean that a user can change the Chat background accordingly to his/her needs either from a given set or from the gallery, it seems to be a good feature ! Go ahead.

**Comment by rahulworld** [comment]
yes

**Comment by the-dagger** [comment]
@rahulworld Are you working on this?

**Comment by rahulworld** [comment]
yes, i am.

**Comment by rahulworld** [comment]
@jig08 i have done chat background activity using galley, no wall paper, default.
default image
![screenshot_2016-10-08-15-05-15](https://cloud.githubusercontent.com/assets/15066782/19212197/4f6f17ae-8d6a-11e6-96f6-d521781809bd.png)
select
![screenshot_2016-10-08-15-05-36](https://cloud.githubusercontent.com/assets/15066782/19212203/75a0b5fe-8d6a-11e6-866e-a7f8ca00a777.png)

no wall paper
![screenshot_2016-10-08-15-07-00](https://cloud.githubusercontent.com/assets/15066782/19212227/bdb3f644-8d6a-11e6-8889-e8f485c84cb7.png)

**Comment by rahulworld** [comment]
@jig08  there is any changes so i do .

**Comment by daminisatya** [comment]
Looks great

**Comment by rahulworld** [comment]
@daminisatya  what shoud i do now or any changes.

**Comment by jig08** [comment]
@rahulworld Good. 
Send a `Pull request` with your changes with the commit name following the pattern `Fixes #<issue number> <commit message>`.

**Comment by daminisatya** [comment]
Yes as @jig08 said go ahead and create the pull request. But please follow the coding practices, which you can see in the readme

**Comment by gogeta95** [comment]
@rahulworld, by screenshots, doesn't look like you've updated your project.. please update your project before submitting PR.
