### ISSUE TITLE
Change Layout of Action Bar (Sub-issue of issue #857)

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#873]
1. Remove Action bar and search feature as it is of no use in a personal assistant app. This feature is more inclined towards a chat/messenger application and not Personal Assistant. Remove action bar to increase space. Instead introduce a FAB with settings icon. Clicking on which opens settings activity ( If possible, use slide animation to open settings)

Reference: ![1](https://files.gitter.im/fossasia/susi_android/vH4C/Screenshot_20170721-164630.png)

2. Instead of adding multi select and displaying share and copy icon on actionbar, display it as a dialog box. See this for reference: 
![screenshot_20170729-054142](https://user-images.githubusercontent.com/16978820/28740419-1c81e26e-7422-11e7-9382-489b08cf65f1.png)

**Comment by chashmeetsingh** [comment]
Are we removing change wallpaper settings as well here? @chiragw15

**Comment by chiragw15** [comment]
Yes, wallpaper and login/logout will go in settings.
