### ISSUE TITLE
Save settings for Anonymous user

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#891]
**Actual Behaviour**

Settings are not saved for the anonymous user. 

**Expected Behaviour**

Settings should be saved for anonymous user.

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
@amitiwary999 
>Settings are not saved for the anonymous user.

Here do you mean "It is not saved on server"?

**Comment by amitiwary999** [comment]
No. I mean if any user logged in and change settings and then log out, settings will remain same for the anonymous user. Either we can reset settings to the default value each time when user logs out or we can store settings for anonymous locally.

**Comment by chiragw15** [comment]
No, save settings only for one session only. For logged in user, when he logs in, fetch from server and set settings. And when he logs out, set to default. For anonymous user, keep settings only for that time when user is anonymous. That means whenever he logs in, the settings should come from server and when he logs out, it should be set to default again. So, basically, think of it as settings for account and not for mobile. That means only settings will remain stored only for one session, be it logged in session or be it anonymous session. Whenever user changes account or logs out. Just set to default and then start recording (saving) settings for next session.
