### ISSUE TITLE
Update answer action type to retrieve and show images send from the server.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#893]
**Actual Behaviour**

For the query like 'search for  ' server send images along with expression but it is not used in the app.

**Expected Behaviour**

Image should be shown in the app.

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
@amitiwary999 any example query?

**Comment by amitiwary999** [comment]
@chiragw15 search for god

{
  "query": "Search for god",
  "count": 1,
  "client_id": "aG9zdF80My4yMzkuODIuODk=",
  "query_date": "2017-08-15T10:02:16.929Z",
  "answers": [{
    "data": [
      {
        "Result": "<a href=\"https://duckduckgo.com/God\">God<\/a> In monotheism, God is conceived of as the Supreme Being and principal object of faith. The...",
        "Icon": {
          "URL": "https://duckduckgo.com/i/f27c2543.jpg",
          "Height": "",
          "Width": ""
        },
        "FirstURL": "https://duckduckgo.com/God",
        "Text": "God In monotheism, God is conceived of as the Supreme Being and principal object of faith. The...",
        "k0": "Result",
        "v0": "<a href=\"https://duckduckgo.com/God\">God<\/a> In monotheism, God is conceived of as the Supreme Being and principal object of faith. The...",
        "k1": "Icon",
        "v1": {
          "URL": "https://duckduckgo.com/i/f27c2543.jpg",
          "Height": "",
          "Width": ""
        },
        "k2": "FirstURL",
        "v2": "https://duckduckgo.com/God",
        "k3": "Text",
        "v3": "God In monotheism, God is conceived of as the Supreme Being and principal object of faith. The...",
        "mapsize": 4,
        "0": "search for god",
        "1": "god",
        "token_original": "search",
        "token_canonical": "search",
        "token_categorized": "search",
        "timezoneOffset": "-330",
        "language": "en",
        "answer": "I found this on the web:",
        "skill_link": "https://github.com/fossasia/susi_server/blob/development/conf/susi/en_0090_fail.json",
        "query": "dog",
        "skill": "/susi_server/conf/susi/en_0090_fail.json",
        "_answer": "Vanessa Kensington"

Check ICON

**Comment by chiragw15** [comment]
@amitiwary999 How are you planning to update it? The response gives action type answer which means display only the the answer given in the response and do nothing else. Have you planned the UI and the flow for it? Remember, "no hardcoding"

**Comment by chiragw15** [comment]
Needs to be implemented in the server first. Closing for now.
