### ISSUE TITLE
Add intro screens

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#894]
Add intro screens when an app is installed for the first time. They will include:
1. Displaying Skills.
2. Quick Info about Speech input/output.
3. Hotword and Hotword Training.
4. Login/Signup

**Comment by Arshilgenius** [comment]
@chiragw15  I want to work on this. can i ?

**Comment by chiragw15** [comment]
@Arshilgenius work with @mishraanmol on this and divide the work. You may divide two screens each.

**Comment by Arshilgenius** [comment]
@chiragw15  okay, thanks a lot 👍

**Comment by mishraanmol** [comment]
@chiragw15 Ok

**Comment by Arshilgenius** [comment]
Is this design good? It's from my previous app, and can i add code in java or convert it into kotlin?

![1](https://user-images.githubusercontent.com/21264401/29332950-83aa56a0-821f-11e7-9717-5a0a1e3e3bec.jpeg)

**Comment by chiragw15** [comment]
@Arshilgenius These look better to me 
<img src="https://user-images.githubusercontent.com/16978820/29339344-72f09c76-8237-11e7-9081-5a5a22f388e1.png" height = "480" width="270">
.
<img src="https://user-images.githubusercontent.com/16978820/29339347-73070312-8237-11e7-86b1-745b2b380c9c.png" height = "480" width="270">
.
<img src="https://user-images.githubusercontent.com/16978820/29339346-72f40f46-8237-11e7-9bfe-cb0245efe46f.png" height = "480" width="270">
.
<img src="https://user-images.githubusercontent.com/16978820/29339348-730b4c10-8237-11e7-8687-0e02a863fa79.png" height = "480" width="270">

**Comment by Arshilgenius** [comment]
How does this look? Sorry for being late.. 

![login](https://user-images.githubusercontent.com/21264401/29495034-47b5439a-85d4-11e7-887a-bf2f8363bfec.jpeg width="300" height="500")

**Comment by chiragw15** [comment]
1. Make it full screen.
2. The line below cuts the mobile frame. Instead, shift the mobile frame a little above.

**Comment by Arshilgenius** [comment]
Full screen like this?

<img src=https://user-images.githubusercontent.com/21264401/29495112-bea2e6a0-85d5-11e7-8e0c-bda4b4d317ec.jpeg width="300" height="500">

**Comment by chiragw15** [comment]
No. Reduce the size of mobile frame and remove status bar like the screenshots I added in my above comment.

**Comment by Arshilgenius** [comment]
How is this now?

<img src=https://user-images.githubusercontent.com/21264401/29495420-7799966c-85dc-11e7-8bd2-28e867253fdc.jpeg width="300" height="500">

**Comment by chiragw15** [comment]
In this <img src=https://user-images.githubusercontent.com/21264401/29495057-9f57bc0e-85d4-11e7-97b1-2f3b953ef689.jpeg width="300" height="500"> 
reduce size of mobile frame like this
<img src=https://user-images.githubusercontent.com/21264401/29495420-7799966c-85dc-11e7-8bd2-28e867253fdc.jpeg width="300" height="500">
and keep "Login written on the top". 

2. Change the color of the circle indicators like this <img src="https://user-images.githubusercontent.com/16978820/29339344-72f09c76-8237-11e7-9081-5a5a22f388e1.png" height = "480" width="270">

3. And remove status bar like this <img src="https://user-images.githubusercontent.com/16978820/29339344-72f09c76-8237-11e7-9081-5a5a22f388e1.png" height = "480" width="270">

**Comment by Arshilgenius** [comment]
@chiragw15  How is this now? 

<img src=https://user-images.githubusercontent.com/21264401/29517054-d626060c-8690-11e7-886f-6f50589f88b5.jpeg width="300" height="500">

**Comment by Arshilgenius** [comment]
How is this now? I am really sorry i thought you meant something else by status bar.

<img src=https://user-images.githubusercontent.com/21264401/29523722-8cc3b5fc-86ab-11e7-989b-68f59569e08a.jpeg width="300" height="500">

 *OR*
<img src=https://user-images.githubusercontent.com/21264401/29523753-a46cdea4-86ab-11e7-9f00-e1cf90e45c11.jpeg width="300" height="500">

**Comment by chiragw15** [comment]
Second one with white circle indicators instead of red. Also, add a line describing the screenshot/feature under the mobile frame.

**Comment by Arshilgenius** [comment]
@chiragw15  : Can you tell me which all screens should i add and what should be the describing line for each screens ( i am not that good in english ) and what more needs to be done in this layout?

<img src=https://user-images.githubusercontent.com/21264401/29564268-b0f7e4f8-875e-11e7-8f2c-c1dd38395090.jpeg width="300" height="500">

**Comment by chiragw15** [comment]
In the above screenshot, just decrease the size of the the line written below the mobile frame and replace it with "Login into SUSI AI using your account for better customization. If you don't have an account, just click on the sign up option and create one. Or else you can simply skip the whole process and jump into the chat interface".

2. Add another screen about main chat interface defining how to interact with SUSI. Write "Interact with SUSI AI by just entering the query in the given input box and SUSI will response to your queries. Click on the microphone button to give voice input to SUSI"

3. Third would be about skill Listing. Add screenshot for it. Write "SUSI AI has many skills. Browse through all the skills and try your favorite one on the chat interface".

Leave the fourth one. It will be on hotword detection. I'll add that later.

**Comment by Arshilgenius** [comment]
@chiragw15  What else needs to be done?

<img src=https://user-images.githubusercontent.com/21264401/29667536-62380530-88fa-11e7-8b6e-813711fbc02f.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29667544-674e4f20-88fa-11e7-8a27-3818ee56de04.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29667547-6a95a0de-88fa-11e7-8fb6-eb5e5b5e4196.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29667550-6d35e394-88fa-11e7-88c1-f38ae052d745.jpegwidth="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29667641-c5473740-88fa-11e7-9ddf-c947596229f0.jpeg width="300" height="500">

**Comment by chiragw15** [comment]
1. In second screen, change title "Interface" to "Chat Interface".
2. Change the screenshot in second screen similar the one used in third screen which has some messages in it. Also, update the code and use new screenshots. The settings icon in the FAB is replaced. 
3. For the screenshot in third screen, use  
<img src="https://user-images.githubusercontent.com/16978820/29496658-caaddb3e-85f4-11e7-888e-cd8889af367d.png" height = "480" width="270">
4. For the 4th screen, remove Hotword Detection for now. Will add that later. For now make it "Chat Settings"
and use screenshot of settings fragment. For description, use: "You can personalize you experience with Chat Settings. You can select language of interaction, change password, switch on/off voice input and output etc"

**Comment by chashmeetsingh** [comment]
@chiragw15 IMO such long descriptions shouldn't be present in the intro screens.

**Comment by Arshilgenius** [comment]
@chiragw15  @chashmeetsingh  what else needs to be done?

<img src=https://user-images.githubusercontent.com/21264401/29716053-7d0fe99a-89c7-11e7-9567-22e4f18d5c1d.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29716055-81d6fb9e-89c7-11e7-9a15-cb8a8c5d793b.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29716059-85ad6564-89c7-11e7-911b-77413e903007.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29716062-88668a24-89c7-11e7-8482-92077eece139.jpeg width="300" height="500">

**Comment by chiragw15** [comment]
Looks good to me. @chashmeetsingh Your views?

**Comment by chashmeetsingh** [comment]
I suppose the descriptions can be shorter like for the `skill listing` it can simply be `Browse and try your favorite skill` or maybe something similar. What do you think @chiragw15 ?
Design wise it looks good.

**Comment by chashmeetsingh** [comment]
I suppose the descriptions can be shorter like for the `skill listing` it can simply be `Browse and try your favorite skill` or maybe something similar. What do you think @chiragw15 ?
Design wise it looks good.

**Comment by chiragw15** [comment]
Okay. Concise the description a bit. Maybe: 
Login :
Login into the app using SUSI AI account or else signup to create new account or just skip login. 
Chat interface : 
Interact with SUSI AI asking queries. Use microphone button for give voice interaction.
Skill listing :
Browse and try your favorite SUSI AI Skill
Chat settings:
Personalize your chat settings for better experience.

**Comment by Arshilgenius** [comment]
@chiragw15 @chashmeetsingh : How does  it look now?

<img src=https://user-images.githubusercontent.com/21264401/29740259-201067c0-8a70-11e7-9375-ab4a9abc262d.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29740260-253282ce-8a70-11e7-962d-76567e775ce4.jpeg width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29740290-b260c5d4-8a70-11e7-8f54-264c2b884c34.jpeg  width="300" height="500">
<img src=https://user-images.githubusercontent.com/21264401/29740261-29c1c2e6-8a70-11e7-82ce-fbeb0c0203ac.jpeg width="300" height="500">

**Comment by chashmeetsingh** [comment]
Looks good to me, just remove the `!` from `Login!`.

**Comment by chiragw15** [comment]
@Arshilgenius Good work. Please send a PR. Thanks.
