### ISSUE TITLE
Add splash screen

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#895]
Add this splash screen in the app. No need of Copyright message at bottom.
![1](https://user-images.githubusercontent.com/16130948/29251250-598d4b86-806f-11e7-8288-404e6e5a1825.png)

**Comment by S2606** [comment]
@chiragw15 Are you working on this or can I??

**Comment by chashmeetsingh** [comment]
@S2606 you can take this up as it is not assigned to anyone yet. Just mention that you are working on it.

**Comment by mishraanmol** [comment]
I'm working on it @chashmeetsingh , If you would like to.

**Comment by S2606** [comment]
I m working on it @mishraanmol . :)

**Comment by mishraanmol** [comment]
Ok @S2606 .

**Comment by chiragw15** [comment]
@S2606 You can work on this. @mishraanmol You can work on this #894 , if you want.

**Comment by mishraanmol** [comment]
@chiragw15 I would love to work on #894 ,Can I?

**Comment by S2606** [comment]
@chiragw15 while building the app on android studio, I am facing this issue

`Error:Execution failed for task ':app:preDebugAndroidTestBuild'.> Conflict with dependency 'com.squareup.okhttp3:okhttp' in project ':app'. Resolved versions for app (3.3.1) and test app (3.3.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.`

Can you please help me with this?

**Comment by chiragw15** [comment]
Did you change anything in build.gradle file? This should work if you haven't changed anything. Try building again. Make sure you have updated code and haven't edited the build.gradle file. If it still exists, try changing the version [here](https://github.com/fossasia/susi_android/blob/development/app/build.gradle#L77) to 3.3.0 and see if it works.

**Comment by mariobehling** [comment]
Why do we need a splash screen? We got rid of it before. How can we rather make the app start faster and avoid a splash screen. People should see the login screen right away or their chat UI if they are already logged in.
