### ISSUE TITLE
Add "About Section"

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#898]
Add a about section section adding following information.
1. About SUSI
2. Adding github link of this repo for reporting bug.
3. Add link to skill cms (http://skills.susi.ai/) for editing and creating skills.
4. Add licence information.

eg. 
<img src="https://user-images.githubusercontent.com/16978820/29319305-36e2fd78-81f1-11e7-9289-1fe4b8788390.png" height = "480" width="270">

**Comment by hardik124** [comment]
@chiragw15, Can I work on this issue?

**Comment by chiragw15** [comment]
@hardik124 Once #899 is completed and merged, you can start working on it.

**Comment by hardik124** [comment]
@chiragw15  Sure. Thanks.

**Comment by chiragw15** [comment]
@hardik124 Please proceed with it. I have added a TODO here https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt#L87 . Add code for about here. 
<img src="https://user-images.githubusercontent.com/16978820/29496659-cab91076-85f4-11e7-82d6-1f34889fb3a1.png" height = "480" width="270">

**Comment by hardik124** [comment]
@chiragw15 A dialog? Do u think an activity will be better? We can put links etc?
Also what should be the content?

PS : 
I apologise for being late , i got sick.

**Comment by chiragw15** [comment]
@hardik124 Don't add activity. Instead add fragment. Though, only a dialog would suffice our need but check if it doesn't look nice, add fragment instead. Add following information.
1. About SUSI AI
>[Susi AI](http://susi.ai/) is an intelligent Open Source personal assistant. It is capable of chat and voice interaction by using APIs to perform actions such as music playback, making to-do lists, setting alarms, streaming podcasts, playing audiobooks, and providing weather, traffic, and other real time information. Additional functionalities can be added as console services using external APIs. Susi AI is able to answer questions and depending on the context will ask for additional information in order to perform the desired outcome. The core of the assistant is the Susi AI server that holds the "intelligence" and "personality" of Susi AI.

2. Contributors link 
>This app is developed by the [SUSI.AI Android App](https://github.com/fossasia/susi_android) [contributors](https://github.com/fossasia/susi_android/graphs/contributors).

3. Link to susi_skill_cms in order to create and edit SUSI skills.
>SUSI is having many skills. You can look at the collection of skills at skills.susi.ai. SUSI Skill development is easy and fun. You can edit existing skills or even create your own. 

4. Link to this repo for reporting issues related to the app.
>Please report all the issues in [Github Repository Issue Tracker](https://github.com/fossasia/susi_android/issues).

5. Licence information
>This project is currently licensed under the Apache License Version 2.0. A copy of [LICENSE.md](https://github.com/fossasia/susi_android/blob/master/LICENSE)

**Comment by Prashant-Chaurasia** [comment]
@chiragw15 , Can I work on this issue?

**Comment by chiragw15** [comment]
@hardik124 are you working on this?

**Comment by hardik124** [comment]
yes, there seem to be a problem with my laptop , i will comeplete it ASAP

**Comment by hardik124** [comment]
@chiragw15  the app is crashing, I am unable to test it.

**Comment by chashmeetsingh** [comment]
@hardik124 please create an issue for the same and if you want, you can start working on the fix for that and continue the about section after that.

**Comment by hardik124** [comment]
@Prashant-Chaurasia  You can take up this issue, I am working on the crash right now and  I can't do this unless I solve that.

**Comment by Prashant-Chaurasia** [comment]
Should I work on this issue @chiragw15  ?

**Comment by chiragw15** [comment]
Sure, go ahead. I have added comments and TODOs. Remove them and add code there.

**Comment by kislaysr** [comment]
@Prashant-Chaurasia  are you working on this issue?

**Comment by S2606** [comment]
@kislaysr  i think so you can go ahead. What fo you say it @chiragw15 ??

**Comment by Prashant-Chaurasia** [comment]
@kislaysr I am new to kotlin, so I am learning it.
