### ISSUE TITLE
Display "Unable to send message" or similar on unavailability of internet. 

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_android#9]
The App currently displays "no value for answers" on unavailability of internet, an appropriate error message must be displayed instead.

**Comment by jig08** [comment]
@betterclever Thanks for the suggestion. Are you working on this ?

**Comment by betterclever** [comment]
@jig08 Yes.

**Comment by betterclever** [comment]
Solved in #14, hence closing.
