### ISSUE TITLE
Settings UI should be improved to material design.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_android#91]
currently, the settings page is using old stock settings UI according to platform, we can update it to follow material design using support libs.

current on Kitkat:
![image](https://cloud.githubusercontent.com/assets/8329096/19089557/6be097e8-8a98-11e6-86ed-b41aa2ddc070.png)

new UI:
![image](https://cloud.githubusercontent.com/assets/8329096/19089501/296c4452-8a98-11e6-835c-3399aa67db43.png)

**Comment by gogeta95** [comment]
I'll work on it. please assign, thanks.

**Comment by jig08** [comment]
@gogeta95 Go ahead.
