### ISSUE TITLE
Circle CI build stuck

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#919]
In the recent PRs, the Circle CI build is stuck at " Waiting for status to be reported". And other checks are also not running. 
 
Find possible issue and try to fix it so that PRs can be merged.

@Arshilgenius @S2606 @hardik124 guys please see if you can fix this.

**Comment by Arshilgenius** [comment]
![screen shot 2017-09-08 at 8 22 34 pm](https://user-images.githubusercontent.com/21264401/30217362-8664328c-94d3-11e7-8c18-b8ad52a93d3b.png)
@chiragw15  is it because of this?

**Comment by chiragw15** [comment]
Hmm. May be. Let's wait for the fix for sometime.

**Comment by chiragw15** [comment]
It is still stuck. Isn't the issue fixed yet? @Arshilgenius

**Comment by Arshilgenius** [comment]
![screen shot 2017-09-10 at 2 11 18 pm](https://user-images.githubusercontent.com/21264401/30247424-ffeb3966-9631-11e7-9110-3a7a25bb0008.png)

I don't know why it's still stuck if they are saying that no incidents of outrage were reported.

**Comment by S2606** [comment]
@chiragw15 from what i had found out we need to unfollow and then refollow it on circle ci

**Comment by chiragw15** [comment]
Reported issue https://discuss.circleci.com/t/status-on-pr-not-updating-shows-waiting-for-status-to-be-reported/16416

**Comment by chiragw15** [comment]
Issue fixed. Closing.
