### ISSUE TITLE
SUSI.AI crashes on activation of Voice Input

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#921]
When hitting the voice button SUSI.AI crashes.
 Trying on a Galaxy S4 Mini GT-1919 with Android 4.4.2

**Comment by hardik124** [comment]
@mariobehling , I would like to work on this 
Since i dont have that phone, could you provide stacktrace:?

**Comment by atm1504** [comment]
@mariobehling @iamareebjamal please close this issue. This issue no longer exists
