### ISSUE TITLE
Failing Circle CI build

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#928]
The Circle CI build is failing. The reason is 
https://github.com/fossasia/susi_android/blob/development/app/src/androidTest/java/org/fossasia/susi/ai/TestChatActivity.java#L90

This UI test will fail because the search feature does not exit anymore. But due to same id of views, it was passing somehow in some builds.

**Comment by isaeef** [comment]
is it still open or it is passing all the cl builds ???

**Comment by chiragw15** [comment]
#929 fixes this issue. @isaeef please find some other open issue to work on.
