### ISSUE TITLE
New app icon and splash

### ISSUE THREAD

**Issue by code-crusher** [fossasia/susi_android#93]

**Comment by code-crusher** [comment]
@the-dagger @daminisatya i would like to implement this :)

**Comment by daminisatya** [comment]
+1

**Comment by jig08** [comment]
@code-crusher Thanks. Kindly design a mock-up and put it up for review as well.

**Comment by daminisatya** [comment]
But you cant change the app icon AFAIK.

**Comment by code-crusher** [comment]
@jig08 sure i'll put up the mockups first. 
@daminisatya i'll put up the mockup if everyone likes then we can change that too.

**Comment by daminisatya** [comment]
@code-crusher Sure. :) @Orbiter Designed the artwork for Susi. So let's loop him too!

**Comment by mariobehling** [comment]
Great you are working on the design! Thank you.

About the splash screen: If we can keep the app starting fast we can start it without splash screen.

**Comment by code-crusher** [comment]
@mariobehling we should remove splash screen, as of now we are not doing any background task on it.

**Comment by code-crusher** [comment]
@daminisatya can you tell me what is the font for SUSI logo?

**Comment by daminisatya** [comment]
@code-crusher no clue, cause @orbiter designed the art work for susi. @orbiter we need your help over here :)

**Comment by lokeshsaini94** [comment]
@code-crusher Are you working on the icon and splash screen? If not then, I'd like to work on it.

**Comment by jig08** [comment]
@code-crusher Did you follow the `SUSI Artwork` discussion on Gitter ? It might come in handy for re-designing .

**Comment by code-crusher** [comment]
@jig08 i had no idea about it. Will finish it asap. Thanks for the update.

**Comment by jig08** [comment]
@code-crusher Yes pls. Thanks.

**Comment by code-crusher** [comment]
@daminisatya @the-dagger @jig08 please review the icon so that i can move forward.

> _**Note:** leaving splash as it will be removed_

![susi_icon](https://cloud.githubusercontent.com/assets/6625740/19243131/efa5c1a8-8f33-11e6-8d90-423fe3a6d8aa.png)

**Comment by the-dagger** [comment]
Looks good :+1:
