### ISSUE TITLE
Use https instead of http

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#931]
We are moving all SUSI components and the API server to https. Please implement the API calls through https.

**Comment by chiragw15** [comment]
Change here https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/rest/clients/BaseUrl.java#L17-L19

**Comment by codedsun** [comment]
Can I work on this issue?

**Comment by chiragw15** [comment]
Sure. Go ahead :+1:

**Comment by codedsun** [comment]
@chiragw15 Done :) Guide me for the PR.I am newbie to Open Source.

**Comment by stellargo** [comment]
@codedsun 
Make your changes to a branch other than the master.
In your comment write Fixes: and insert URL of this issue
then push the branch to your forked repo
After which you can use github to create a PR :)
