### ISSUE TITLE
App goes in recent after we perform a lot of tasks with the app at a faster rate , but doesn't crashes

### ISSUE THREAD

**Issue by Anshpuri** [fossasia/susi_android#935]
**Actual Behaviour**

Please state here what is currently happening.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by akashagra** [comment]
@Anshpuri  this is probably when you use Susi Skills? Right
If thats so i have referenced it in #926 and also resolved it and sent a pull request

**Comment by chiragw15** [comment]
@Anshpuri please edit the issue according to the given format. See other issues for reference.

**Comment by chiragw15** [comment]
@Anshpuri see if you still face this issue.

**Comment by chiragw15** [comment]
Fixed in #926 . Not facing this issue. @Anshpuri Reopen if you still face this issue.
