### ISSUE TITLE
Update roadmap in documentation

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#936]
Update roadmap in the documentation. 
https://github.com/fossasia/susi_android#roadmap

There are 4 features out of which 3 are already implemented:
* Hotword Detection training
* Full Screen Voice interaction
* Feedback for skills.
* Displaying SUSI skills

Change it to:
* Hotword Detection training
* ~~Full Screen Voice interaction~~
* ~~Feedback for skills.~~
* ~~Displaying SUSI skills~~

**Comment by chiragw15** [comment]
Sure :+1:

**Comment by chiragw15** [comment]
@vaibhavsingh97 Same goes for you https://github.com/fossasia/susi_android/issues/940#issuecomment-330155423

**Comment by vaibhavsingh97** [comment]
@chiragw15 Sure! I will work on another issue 😄
