### ISSUE TITLE
Add screenshots in documentation 

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#937]
Add screenshots regarding 
1. Full speech voice input
2. Skill List
3. Skill Detail

<img src = "https://user-images.githubusercontent.com/14003244/29521703-3bebfb3c-86a4-11e7-834d-4b6eafa8b128.png" height="480" width="270">
.
<img src="https://user-images.githubusercontent.com/16978820/29992762-f72aaeb4-8fc0-11e7-915a-75e0235aa377.png" height = "480" width="270">
.
<img src="https://user-images.githubusercontent.com/16978820/29496658-caaddb3e-85f4-11e7-888e-cd8889af367d.png" height = "480" width="270">

**Comment by Kartik2016** [comment]
Can i work on this ?

**Comment by chiragw15** [comment]
Sure. Go ahead :+1:
