### ISSUE TITLE
Update Link Preview library 

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#938]
Update Link Preview library [here](https://github.com/fossasia/susi_android/blob/development/app/build.gradle#L82) with new version which is 2.0.0 (reference https://github.com/LeonardoCardoso/Android-Link-Preview#gradle)

**Comment by yyxtreme** [comment]
Can I work on this one?

**Comment by atultherajput** [comment]
@chiragw15 I would love to work on this issue.

**Comment by chiragw15** [comment]
@yyxtreme @atultherajput guys, please pick some other issue. This is already fixed.
