### ISSUE TITLE
Remove YouTubeAndroidPlayerApi.jar from libs

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#939]
We once used Youtube lib to play videos but we don't need it right now and can be removed. 
Just remove [this](https://github.com/fossasia/susi_android/blob/development/app/libs/YouTubeAndroidPlayerApi.jar) from `libs` folder.

**Comment by vaibhavsingh97** [comment]
Can i work on this issue?

**Comment by chiragw15** [comment]
Sure. Go ahead. :+1:
