### ISSUE TITLE
Add Names of Libraries used in docs

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#940]
Add following library information in docs here https://github.com/fossasia/susi_android#libraries-used-and-their-documentation.
* Gericop/Android-Support-Preference-V7-Fix ([docs](https://github.com/Gericop/Android-Support-Preference-V7-Fix))
* Snowboy Hotword Detection ([docs](http://docs.kitt.ai/snowboy/))
* zagum/SpeechRecognitionView ([docs](https://github.com/zagum/SpeechRecognitionView))

**Comment by Kartik2016** [comment]
I would like to take up this issue. Please assign it to me.Thanks.

**Comment by chiragw15** [comment]
@Kartik2016 Please work on one beginner issue only. You are already working on #937 .These issue are just for understanding the work flow. Let someone else work on this. There are other open issues in the repo. Pick some other issue please.

**Comment by Kartik2016** [comment]
Yes sure. Thank you :-)

**Comment by aayush4vedi** [comment]
Hi, I'd like to work on the issue if no one is doing so.

**Comment by chiragw15** [comment]
@aayush4vedi go ahead please.
