### ISSUE TITLE
Leak Activity leaked 15 KB

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#946]
![screenshot_2017-09-18-12-17-38](https://user-images.githubusercontent.com/1583873/30543069-feea9a42-9c81-11e7-9f8e-c805c16d9ccf.png)

**Comment by hardik124** [comment]
@mariobehling  Can i  work on this issue?

**Comment by akashagra** [comment]
@mariobehling Can i work on this issue?

**Comment by chiragw15** [comment]
Is this even an issue of the app? It is most probably a bug in leak canary as far as I think because there is no such activity as DisplayLeakActivity in SUSI Android App. @hardik124 @akashagra What do you guys think?

**Comment by hardik124** [comment]
Actually there was a leak on chatActivity.

**Comment by chiragw15** [comment]
Actual issue #996 This is issue with leak canary. Closing.
