### ISSUE TITLE
Add support for Pie charts in Susi Response

### ISSUE THREAD

**Issue by daminisatya** [fossasia/susi_android#95]
Susi server is well ahead giving response in various forms, one such visualization is pie charts. The app must provide support to process the pie data and shoot out a pie chart as a result. Susi server tells you what kind of data its going to give. 
Susi webclient uses high charts to display the pie charts

**Comment by iit2014086** [comment]
i would like to work on this using AndroidMPChart....but could you give me an example like for what kind of message will i get pie as a type in response :p ...i am getting "i dont know" for everything..

**Comment by jig08** [comment]
As far as I remember, for queries like `Who will win the 2020 presidential election` we had a pie-chart response between Trump and Hillary...

**Comment by iit2014086** [comment]
@jig08  tried this just now...it again gives "i dont know" once can you check?

**Comment by mariobehling** [comment]
@Orbiter adding you here in case you have feedback.

**Comment by daminisatya** [comment]
@iit2014086 In case of a piechart, here's the sample response. 

```
{
  "session": {"identity": {
    "type": "host",
    "name": "10.67.93.57",
    "anonymous": true
  }},
  "count": 1,
  "answers": [{
    "metadata": {
      "hits": 21,
      "offset": 0,
      "count": 2
    },
    "data": [
      {
        "percent": 50,
        "president": "hillary2016"
      },
      {
        "percent": 50,
        "president": "trump2016"
      }
    ],
    "actions": [
      {
        "expression": "I believe the next president will be hillary2016 with a likelihood of 50.0 percent but I a not sure.",
        "type": "answer"
      },
      {
        "total": 100,
        "unit": "%",
        "type": "piechart",
        "value": "percent",
        "key": "country"
      }
    ]
  }]
}
```

For the sample query 
```Who will win the 2016 presidential elections```

**Comment by daminisatya** [comment]
You have make us of the ```data``` and process it into a piechart. I have implemented it using highcharts for displaying piechart.

**Comment by iit2014086** [comment]
@daminisatya i have a doubt regarding this... in the data there are two attributes percent and president...but for other types of query which are not about presidential elections how can i know what president attribute will be replaced with...

**Comment by daminisatya** [comment]
@iit2014086 As of now there is only one rule on piechart response. 
Please refer this issue. 
https://github.com/fossasia/asksusi_com/issues/15

**Comment by iit2014086** [comment]
@daminisatya i am not getting the expected response for the query.... i attached a screen shot of the response i am receiving... once can you check this...even on asksusi.com.... susi replies "i dont know" and doesnt show a pie chart.
![screenshot 47](https://cloud.githubusercontent.com/assets/12937069/19277814/b0cd255a-8ff8-11e6-9dd1-8ca927031889.png)

**Comment by iit2014086** [comment]
This is how the pie chart looks like....is this chart ok??...i am not getting required response from server...so for previewing the chart i used hardcoded values..
![device-2016-10-12-035607](https://cloud.githubusercontent.com/assets/12937069/19290978/09427924-9030-11e6-9026-c0c11b83462f.png)

**Comment by daminisatya** [comment]
@iit2014086 the chart looks cool. Then log a bug in susi_server regarding this.

**Comment by betterclever** [comment]
https://github.com/fossasia/susi_server/issues/100
