### ISSUE TITLE
Unresolved Reference kotlinx and Updated Gradle

### ISSUE THREAD

**Issue by yashLadha** [fossasia/susi_android#956]
**Actual Behaviour**

Android Studio shows unresolved reference for kotlinx.

**Expected Behaviour**

There should be no warning for kotlin support in android studio.

**Steps to reproduce it**

Build the cloned repo

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
@yashLadha Are you still facing this issue? Because I am not getting any warnings as such. Do check again.

**Comment by yashLadha** [comment]
Nopes. Closing this issue
