### ISSUE TITLE
Use the standard text to speech engine and settings of Android phone

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#958]
Currently text to speech on the phone uses a default engine instead of the "default of the actual phone". Furthermore the language choice does not seem to have any effect anyways.

Expected: 
1. Use the phone text to speech engine.
2. Changing the text to speech language in the settings should direct to the text to speech settings of the phone. Don't use a different configuration of SUSI.AI and the Android system itself.

**Comment by akashagra** [comment]
I would like to work on it

**Comment by chiragw15** [comment]
@mariobehling The language selected from the language setting in the settings is passed as a parameter in the api call. eg. https://api.susi.ai/susi/chat.json?timezoneOffset=-330&longitude=84.85147599&latitude=25.54135048&geosource=gps&language=en&q=hi . In this language is set as `"en"` . Now, in the json response there is an attribute of language 
```
  "answer_date": "2017-09-24T10:34:10.613Z",
  "answer_time": 5,
  "language": "en",
```
The language provided from this is then used for Text to speech. We don't want user to set langage of TTS separately. There is a primary language of interaction of user. The TTS will be set according to it.

**Comment by batbrain7** [comment]
@iamareebjamal please close this issue
