### ISSUE TITLE
Susi skill groups with no skills have no message

### ISSUE THREAD

**Issue by Muks14x** [fossasia/susi_android#968]
**Actual Behaviour**

The skill listing page displays skill groups that are empty, with no message.

**Expected Behaviour**

It should either not list the skill group or display that there are no skills found, like the [skills.susi.ai](https://skills.susi.ai) website does.

**Steps to reproduce it**

Open the SUSI.AI Skills page

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/11333048/30782824-ed176f28-a156-11e7-95df-e8e6845a5088.png" width="300"> <img src="https://user-images.githubusercontent.com/11333048/30782826-f29f5c4e-a156-11e7-9154-21c17355816f.png" width="300">
Here, Lifestyle, Health & Fitness, and Social don't have any skills.

**Would you like to work on the issue?**
Yes

**Comment by Muks14x** [comment]
Is there a better way to do this, or should I go ahead and send in a pull request?

**Comment by chiragw15** [comment]
@Muks14x Hide the groups with no skills
