### ISSUE TITLE
Wrong link in About Us Page

### ISSUE THREAD

**Issue by Arshilgenius** [fossasia/susi_android#971]
**Actual Behaviour**

The Link opens the stackOverflow website.

**Expected Behaviour**

The link should open SUSI.AI

**Steps to reproduce it**

Open the About Us Page and click on SUSI AI 

**Screenshots of the issue**

<img src=https://user-images.githubusercontent.com/21264401/30786064-b6bfddd4-a18d-11e7-9f36-a8a4f86d7984.jpeg width="300" height="500">

<img src=https://user-images.githubusercontent.com/21264401/30786070-bc9caf98-a18d-11e7-9116-510c31a51231.jpeg width="300" height="500">

**Would you like to work on the issue?**

Yes

**Comment by collinx** [comment]
@Arshilgenius go ahead and change the link.
