### ISSUE TITLE
App crashing after login

### ISSUE THREAD

**Issue by Arshilgenius** [fossasia/susi_android#972]
**Actual Behaviour**

The app crashes as soon as i login.

**Expected Behaviour**

The App should not crash

**Steps to reproduce it**

Login with email and password

**LogCat for the issue**

![screen shot 2017-09-25 at 1 28 50 am](https://user-images.githubusercontent.com/21264401/30786275-eeea0920-a190-11e7-996d-b7a1f7de8c27.png)

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
Same as #961
