### ISSUE TITLE
Add information about versionCode update before merge in ReadMe

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/susi_android#980]
Update ReadMe for future devs notifying on changing the versionCode before merging development branch into master

Excerpt from https://github.com/fossasia/open-event-orga-app

## Publishing

Each push to master branch automatically publishes the application to Play Store as an Alpha Release. Thus, on each merge into master, the `versionCode` and `versionName` **MUST** be changed accordingly in `app/build.gradle`  
- `versionCode` : Integer : To be monotonically incremented with each merge. Failure to do so will lead to publishing error, and thus is a crucial step before any merge
- `versionName` : String : User visible version of the app. To be changed following [symantic versioning](http://semver.org/)

Modify accordingly

**Comment by sachincool** [comment]
i would like to work on this issue  as my first Contribution to this organization.

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by sachincool** [comment]
should i make the PR into master or development ?

**Comment by chiragw15** [comment]
@sachincool development

**Comment by anandwana001** [comment]
I had found some typo in README.md and would like to fix them as my first contribution to fossasia. 
fix: Typo in README.md #1017 
@chiragw15 Could you help me in this contribution
