### ISSUE TITLE
Some skills have broken image links

### ISSUE THREAD

**Issue by Muks14x** [fossasia/susi_android#981]
**Actual Behaviour**

Some images for susi skills have broken links. 
For example, [this](https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/Business%20and%20Finance/en/images/currency_exchange.png) link is being fetched, but it has moved [here](https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/Business%20and%20Finance/en/images/currency_exchange.png/currency_exchange.png).
This is true for most of the images that aren't being rendered. This is also because there isn't a check for invalid image urls.

**Expected Behaviour**

Display the actual images themselves, with their new urls. Or display the placeholder image instead for these skills, in case of error in loading the image url.

**Steps to reproduce it**

Open the skills list page. The utilities section for example, currently has no images rendered

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/11333048/30815951-45fe260a-a232-11e7-9c9e-19e78c0a069e.png" width="250"> <img src="https://user-images.githubusercontent.com/11333048/30815954-48496d5c-a232-11e7-8d61-567083108ec1.png" width="250">

**Would you like to work on the issue?**

Yes

**Comment by Muks14x** [comment]
Currently, all this does is display the placeholder image in case of broken links. How should the actual links be fixed - is it a problem with the Api?

**Comment by chiragw15** [comment]
@Muks14x Here https://github.com/fossasia/susi_skill_data/tree/master/models/general/Business%20and%20Finance/en/images the image currency_exchange.png is in another folder which is incorrect. All the images should be in a images folder like every other groups. Please open an issue in Skill_data repo and fix this. Also for group Utilities, no images are present. Would be nice if you could add them. Once those images are added. This issue will be fixed automatically.

**Comment by chiragw15** [comment]
Also, do one thing more, add a place holder image in case image is not rendered. Just add name of the skill. See how it is done on skill.susi.ai

**Comment by Muks14x** [comment]
Sent a pull request in susi_skill_data, with the appropriate changes [here](https://github.com/fossasia/susi_skill_data/pull/303). Also, the commit made earlier(above) should display the placeholder image in case there is an error in loading/rendering the image, which it does now. 

<img src="https://user-images.githubusercontent.com/11333048/30827682-962ce46a-a258-11e7-8df8-4907bba3801e.png" width="250">   <img src="https://user-images.githubusercontent.com/11333048/30827683-964ad808-a258-11e7-93f2-81b5387c6f9f.png" width="250">
