### ISSUE TITLE
SUSI_Skills activity looks cluttered on emulator

### ISSUE THREAD

**Issue by yashLadha** [fossasia/susi_android#986]
**Actual Behaviour**

Some cards hide in the layout.

**Expected Behaviour**

Each card should cover the space and does not hide in the layout.

**Steps to reproduce it**

Go to susi skills activity in nexus 5 emulator

**Screenshots of the issue**

![screenshot_1506390662](https://user-images.githubusercontent.com/18033231/30838919-14680b24-a28c-11e7-9dfd-4b38ea5765f9.png)

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
>Some cards hide in the layout.

Where? If you are talking about the cards on the right in above image which are not completely visible, they are fine. That's a horizontal recycler view. Scroll horizontally and you will see complete list.

**Comment by yashLadha** [comment]
But it will look more meaningful if we stretch te card according to the screen sizes

**Comment by chiragw15** [comment]
Generally it is advised to indicate content overflow by cutting off grid tiles according to material design guidelines. If you align and stretch the tile to fit screen. It will not clearly indicate that there are more tiles on scrolling. Ref https://material.io/guidelines/components/grid-lists.html#grid-lists-behavior

**Comment by yashLadha** [comment]
Sure, Thanks for this :+1:
