### ISSUE TITLE
making button corners rounded and adding thumbs up/down image in  susi skills activity

### ISSUE THREAD

**Issue by Arshilgenius** [fossasia/susi_android#992]
**Actual Behaviour**

The button try it has rectangular edges which is not recommended for a good ui, also there is no image for rating positive and negative.

**Expected Behaviour**

The buttons should be rounded and there should be an image on the left of positive and negative rating 

**Screenshots of the issue**

<img src=https://user-images.githubusercontent.com/21264401/30874337-9efaa4aa-a30d-11e7-8a70-e317756590ce.jpeg  width="300" height="500">

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment]
@Arshilgenius status?

**Comment by Arshilgenius** [comment]
@chiragw15  almost done.
