### ISSUE TITLE
Date would look good  in dd-mm-yyyy format

### ISSUE THREAD

**Issue by akashagra** [fossasia/susi_android#994]
![6aa4609a-da17-4c20-b5c8-9fd13c1eb936](https://user-images.githubusercontent.com/25381904/30929991-e3209920-a3dd-11e7-81cd-1fa8c12ed4bf.jpg)
 
I would like to work on this issue

**Comment by chiragw15** [comment]
change it here https://skills.susi.ai/Productivity/calendar/edit/en

**Comment by akashagra** [comment]
Done

**Comment by akashagra** [comment]
Do i also need a pull request for the same?
@chiragw15

**Comment by chiragw15** [comment]
@akashagra Changing there should fix this but I don't think you changed there. You just changed the expected result which is just an example indication user will get result something like this. You need to change the actual result which comes from 
```
!console:It's $object$ $1$
{
"url":"http://calapi.inadiutorium.cz/api/v0/en/calendars/default/$1$",
"path":"$.date"
}
eol
```

**Comment by akashagra** [comment]
@chiragw15  I am sorry but i dont know how to change this .Please either guide me or ask someone else to do this

**Comment by chiragw15** [comment]
@akashagra The response of query comes from the api mentioned here `"url":"http://calapi.inadiutorium.cz/api/v0/en/calendars/default/$1$",` . You will be needing to read documentation of that API to change date format.

**Comment by sridharjajoo** [comment]
@chiragw15 I would like to take up this issue. Could you guide me a little as I am quite new to this project?

**Comment by jay006** [comment]
@sridharjajoo  Is the date issue is solved?

**Comment by brijeshshah13** [comment]
@chiragw15 I tried to mutate the format of the date using `!javascript:`, although I was unsuccessful. Any help on how to mutate the object using javascript would be appreciated.

**Comment by jay006** [comment]
@chiragw15  why don't we just manipulate date format which is received .

**Comment by chiragw15** [comment]
@jay006 how would you do that? How would you check if the message you received is a date. The indication should come from server.

**Comment by batbrain7** [comment]
```

  "query": "date tomorrow",
  "count": 1,
  "client_id": "aG9zdF8xNjIuMTU4LjE1OC4zNV81OWMzNzMxZQ==",
  "query_date": "2018-06-03T17:12:09.618Z",
  "answers": Array[1][
    {
      "data": Array[3][
        {
          "0": "date tomorrow",
          "1": "tomorrow",
          "object": "2018-06-04",
          "token_original": "date",
          "token_canonical": "date",
          "token_categorized": "date",
          "timezoneOffset": "-330",
```

@chiragw15 if we check for the key "token_original" we can manipulate this in the android app only
