### ISSUE TITLE
Bug in handling back button press from About and Settings fragments

### ISSUE THREAD

**Issue by Muks14x** [fossasia/susi_android#995]
**Actual Behaviour**

When the back button is pressed from the About and Settings fragment **after being launched from SkillDetails fragment**, causes the title to change to "SUSI.AI Skills", with the same fragment being displayed.

**Expected Behaviour**

The back button should close the current fragment and show the previous fragment on the stack.

**Steps to reproduce it**

Open the skill details activity for some skill (eg, Cooking Guide). Now, open the About or settings page. On pressing back once, the title changes to "SUSI.AI Skills", without the fragment closing.

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/11333048/30930276-e158da52-a3de-11e7-8a17-d8964e28de54.png" width="250">  <img src="https://user-images.githubusercontent.com/11333048/30930284-e681c764-a3de-11e7-9eef-3fc4fa5b8854.png" width="250">

**Would you like to work on the issue?**

Yes, I would.

**Comment by collinx** [comment]
@Muks14x yup, this bug is there in the code. Go ahead and work on it. 😄
