### ISSUE TITLE
Chat Activity Leaked 5.7 KB

### ISSUE THREAD

**Issue by akashagra** [fossasia/susi_android#996]
![whatsapp image 2017-09-27 at 11 56 58 pm 1](https://user-images.githubusercontent.com/25381904/30930968-f343b88e-a3e0-11e7-97b2-ea2e142ced8c.jpeg)

**Comment by sachincool** [comment]
I think @chiragw15 would be the best to answer this . his blog on [Leak canary](https://blog.fossasia.org/detecting-and-fixing-memory-leaks-in-susi-android-app/) was awsome :smiley:

**Comment by chiragw15** [comment]
@akashagra can you please give steps to reproduce this?

**Comment by akashagra** [comment]
@chiragw15 
Did some tasks related to skills ? Then i closed the app 
In the notification drawer got a notification that chat activity leaked 5.7 kb which kept on increasing

**Comment by chiragw15** [comment]
@akashagra I am not sure but I think this leak is due to link preview library we are using. This issue was there in previous version of library, don't know if it still exists in new version.
