### ISSUE TITLE
Bug while apk signing

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#999]
While signing the app in the apk-gen.sh script, it gives error `Output file 'susi-release-signed.apk' exists` i.e the app is signed successfully but the generated apk already exists. To fix this, we can delete the earlier existing apk and then sign the new apk. ref https://circleci.com/gh/fossasia/susi_android/2095

@iamareebjamal @mariobehling The app is signing successfully now. We just need to fix this and then merging dev to master should upload the app.

**Comment by mariobehling** [comment]
Ok, please go ahead.
